// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  fraudScore,
  fraudScoreWithFee,
  clampFraudScore,
  factorFromBps,
} = require("./fraudScore");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes fraudScore for a ach payments row 1", "base", 107, 24, 172.85],
  ["applies the fraudScore fee path for a visa payments row 2", "fee", 184, 1, 260.88, 11],
  ["clamps fraudScore for a amex payments row 3", "clamp", 328.75, 327, 328.75, 331],
  ["computes fraudScore for a apple payments row 4", "base", 46, 18, 75.54],
  ["applies the fraudScore fee path for a store payments row 5", "fee", 103, 0, 146.93, 5],
  ["clamps fraudScore for a klarna payments row 6", "clamp", 229.68, 230, 230, 234],
  ["computes fraudScore for a paypal payments row 7", "base", 221, 13, 325.24],
  ["applies the fraudScore fee path for a wallet payments row 8", "fee", 42, 19, 74, 4],
  ["clamps fraudScore for a ach payments row 9", "clamp", 139.68, 136, 139.68, 140],
  ["computes fraudScore for a visa payments row 10", "base", 160, 7, 227.8],
  ["applies the fraudScore fee path for a visa payments row 11", "fee", 184, 11, 279.28, 11],
  ["clamps fraudScore for a ach payments row 12", "clamp", 177.28, 172, 176, 176],
  ["computes fraudScore for a apple payments row 13", "base", 62, 24, 103.1],
  ["applies the fraudScore fee path for a amex payments row 14", "fee", 241, 18, 374.09, 8],
  ["clamps fraudScore for a klarna payments row 15", "clamp", 261.4, 262, 262, 266],
  ["computes fraudScore for a store payments row 16", "base", 103, 10, 152.23],
  ["applies the fraudScore fee path for a wallet payments row 17", "fee", 42, 4, 67.7, 4],
  ["clamps fraudScore for a paypal payments row 18", "clamp", 348.34, 345, 348.34, 349],
  ["computes fraudScore for a visa payments row 19", "base", 160, 17, 243.8],
  ["applies the fraudScore fee path for a ach payments row 20", "fee", 99, 11, 148.58, 1],
  ["clamps fraudScore for a ach payments row 21", "clamp", 111.85, 109, 111.85, 113],
  ["computes fraudScore for a visa payments row 22", "base", 128, 5, 181.08],
  ["applies the fraudScore fee path for a amex payments row 23", "fee", 185, 12, 283.55, 12],
  ["clamps fraudScore for a apple payments row 24", "clamp", 372.54, 372, 372.54, 376],
  ["computes fraudScore for a store payments row 25", "base", 63, 0, 89.53],
  ["applies the fraudScore fee path for a klarna payments row 26", "fee", 124, 6, 187.88, 11],
  ["clamps fraudScore for a paypal payments row 27", "clamp", 270.64, 266, 270, 270],
  ["computes fraudScore for a wallet payments row 28", "base", 242, 19, 370],
  ["applies the fraudScore fee path for a ach payments row 29", "fee", 75, 22, 128.75, 7],
  ["clamps fraudScore for a visa payments row 30", "clamp", 187.24, 187, 187.24, 191],
  ["computes fraudScore for a wallet payments row 31", "base", 218, 15, 325.28],
  ["applies the fraudScore fee path for a paypal payments row 32", "fee", 157, 9, 240.8, 14],
  ["clamps fraudScore for a klarna payments row 33", "clamp", 139, 138, 139, 142],
  ["computes fraudScore for a store payments row 34", "base", 39, 21, 66.28],
  ["applies the fraudScore fee path for a apple payments row 35", "fee", 222, 14, 332.9, 4],
  ["clamps fraudScore for a amex payments row 36", "clamp", 231.79, 229, 231.79, 233],
  ["computes fraudScore for a visa payments row 37", "base", 104, 1, 144.28],
  ["applies the fraudScore fee path for a ach payments row 38", "fee", 43, 20, 76.93, 5],
  ["clamps fraudScore for a wallet payments row 39", "clamp", 317.8, 316, 317.8, 320],
  ["computes fraudScore for a paypal payments row 40", "base", 149, 11, 218.58],
  ["applies the fraudScore fee path for a paypal payments row 41", "fee", 101, 3, 145.34, 3],
  ["clamps fraudScore for a wallet payments row 42", "clamp", 233.8, 232, 233.8, 236],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(fraudScore(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(fraudScoreWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampFraudScore(a, b, extra)).toBe(expected);
    }
  });
}
