// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  installment,
  installmentWithFee,
  clampInstallment,
  factorFromBps,
} = require("./installment");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes installment for a klarna payments row 1", "base", 164, 21, 204.72],
  ["applies the installment fee path for a store payments row 2", "fee", 103, 15, 128.51, 5],
  ["clamps installment for a wallet payments row 3", "clamp", 48.62, 48, 48.62, 52],
  ["computes installment for a paypal payments row 4", "base", 221, 3, 235.05],
  ["applies the installment fee path for a visa payments row 5", "fee", 168, 20, 217.96, 10],
  ["clamps installment for a ach payments row 6", "clamp", 129.12, 125, 129, 129],
  ["computes installment for a apple payments row 7", "base", 46, 8, 53.6],
  ["applies the installment fee path for a amex payments row 8", "fee", 225, 2, 244, 7],
  ["clamps installment for a klarna payments row 9", "clamp", 199, 196, 199, 200],
  ["computes installment for a store payments row 10", "base", 95, 17, 116.05],
  ["applies the installment fee path for a paypal payments row 11", "fee", 21, 23, 42.25, 13],
  ["clamps installment for a wallet payments row 12", "clamp", 89.92, 88, 89.92, 92],
  ["computes installment for a store payments row 13", "base", 143, 10, 163.16],
  ["applies the installment fee path for a klarna payments row 14", "fee", 204, 16, 244.72, 1],
  ["clamps installment for a amex payments row 15", "clamp", 33, 32, 33, 36],
  ["computes installment for a apple payments row 16", "base", 86, 3, 93.3],
  ["applies the installment fee path for a ach payments row 17", "fee", 147, 9, 170.17, 4],
  ["clamps installment for a visa payments row 18", "clamp", 244.36, 244, 244.36, 248],
  ["computes installment for a paypal payments row 19", "base", 29, 21, 38.67],
  ["applies the installment fee path for a wallet payments row 20", "fee", 90, 2, 103.6, 7],
  ["clamps installment for a apple payments row 21", "clamp", 19.12, 16, 19.12, 20],
  ["computes installment for a amex payments row 22", "base", 193, 0, 199.86],
  ["applies the installment fee path for a visa payments row 23", "fee", 136, 18, 174.2, 8],
  ["clamps installment for a ach payments row 24", "clamp", 91.5, 87, 91, 91],
  ["computes installment for a wallet payments row 25", "base", 10, 7, 13.9],
  ["applies the installment fee path for a paypal payments row 26", "fee", 189, 1, 198.67, 1],
  ["clamps installment for a klarna payments row 27", "clamp", 159.72, 161, 161, 165],
  ["computes installment for a store payments row 28", "base", 71, 13, 84.65],
  ["applies the installment fee path for a apple payments row 29", "fee", 246, 8, 286.6, 13],
  ["clamps installment for a amex payments row 30", "clamp", 192.4, 193, 193, 197],
  ["computes installment for a store payments row 31", "base", 103, 15, 123.51],
  ["applies the installment fee path for a klarna payments row 32", "fee", 164, 21, 210.72, 6],
  ["clamps installment for a paypal payments row 33", "clamp", 238.05, 233, 237, 237],
  ["computes installment for a wallet payments row 34", "base", 42, 9, 49.62],
  ["applies the installment fee path for a ach payments row 35", "fee", 107, 14, 136.12, 9],
  ["clamps installment for a visa payments row 36", "clamp", 210.96, 206, 210, 210],
  ["computes installment for a amex payments row 37", "base", 225, 2, 237],
  ["applies the installment fee path for a apple payments row 38", "fee", 46, 8, 61.6, 8],
  ["clamps installment for a store payments row 39", "clamp", 114.05, 114, 114.05, 118],
  ["computes installment for a klarna payments row 40", "base", 156, 23, 198],
  ["applies the installment fee path for a visa payments row 41", "fee", 200, 17, 253, 12],
  ["clamps installment for a ach payments row 42", "clamp", 162.07, 158, 162, 162],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(installment(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(installmentWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampInstallment(a, b, extra)).toBe(expected);
    }
  });
}
