// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 101;

function paymentReceipt(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function paymentReceiptWithFee(amount, factor, fee) {
  return paymentReceipt(amount, factor) + fee;
}

function clampPaymentReceipt(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  paymentReceipt,
  paymentReceiptWithFee,
  clampPaymentReceipt,
  factorFromBps,
};
