// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  paymentMethod,
  paymentMethodWithFee,
  clampPaymentMethod,
  factorFromBps,
} = require("./paymentMethod");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes paymentMethod for a visa payments row 1", "base", 128, 10, 155.48],
  ["applies the paymentMethod fee path for a ach payments row 2", "fee", 67, 4, 94.7, 14],
  ["clamps paymentMethod for a apple payments row 3", "clamp", 327.34, 322, 326, 326],
  ["computes paymentMethod for a amex payments row 4", "base", 185, 17, 234.55],
  ["applies the paymentMethod fee path for a klarna payments row 5", "fee", 124, 11, 163.08, 11],
  ["clamps paymentMethod for a store payments row 6", "clamp", 73.93, 75, 75, 79],
  ["computes paymentMethod for a wallet payments row 7", "base", 242, 24, 321.6],
  ["applies the paymentMethod fee path for a paypal payments row 8", "fee", 181, 18, 239.44, 8],
  ["clamps paymentMethod for a visa payments row 9", "clamp", 164.04, 160, 164, 164],
  ["computes paymentMethod for a ach payments row 10", "base", 75, 2, 88],
  ["applies the paymentMethod fee path for a amex payments row 11", "fee", 153, 15, 202.13, 10],
  ["clamps paymentMethod for a apple payments row 12", "clamp", 277.78, 277, 277.78, 281],
  ["computes paymentMethod for a ach payments row 13", "base", 35, 2, 44.8],
  ["applies the paymentMethod fee path for a visa payments row 14", "fee", 96, 8, 129.44, 13],
  ["clamps paymentMethod for a paypal payments row 15", "clamp", 191.78, 187, 191, 191],
  ["computes paymentMethod for a wallet payments row 16", "base", 210, 22, 275.8],
  ["applies the paymentMethod fee path for a store payments row 17", "fee", 31, 3, 48.79, 8],
  ["clamps paymentMethod for a klarna payments row 18", "clamp", 114.8, 111, 114.8, 115],
  ["computes paymentMethod for a amex payments row 19", "base", 161, 13, 198.59],
  ["applies the paymentMethod fee path for a apple payments row 20", "fee", 222, 19, 288.5, 4],
  ["clamps paymentMethod for a wallet payments row 21", "clamp", 122.68, 119, 122.68, 123],
  ["computes paymentMethod for a paypal payments row 22", "base", 37, 4, 47.7],
  ["applies the paymentMethod fee path for a klarna payments row 23", "fee", 220, 22, 290.6, 2],
  ["clamps paymentMethod for a store payments row 24", "clamp", 197.98, 199, 199, 203],
  ["computes paymentMethod for a apple payments row 25", "base", 102, 9, 124.3],
  ["applies the paymentMethod fee path for a amex payments row 26", "fee", 41, 3, 54.69, 3],
  ["clamps paymentMethod for a visa payments row 27", "clamp", 291.48, 289, 291.48, 293],
  ["computes paymentMethod for a ach payments row 28", "base", 163, 15, 204.23],
  ["applies the paymentMethod fee path for a wallet payments row 29", "fee", 106, 8, 135.84, 8],
  ["clamps paymentMethod for a paypal payments row 30", "clamp", 57.6, 54, 57.6, 58],
  ["computes paymentMethod for a ach payments row 31", "base", 219, 11, 263.23],
  ["applies the paymentMethod fee path for a visa payments row 32", "fee", 40, 17, 58.2, 2],
  ["clamps paymentMethod for a amex payments row 33", "clamp", 131.1, 131, 131.1, 135],
  ["computes paymentMethod for a apple payments row 34", "base", 158, 5, 182.38],
  ["applies the paymentMethod fee path for a store payments row 35", "fee", 215, 12, 272.7, 12],
  ["clamps paymentMethod for a klarna payments row 36", "clamp", 54.64, 50, 54, 54],
  ["computes paymentMethod for a paypal payments row 37", "base", 93, 0, 105.58],
  ["applies the paymentMethod fee path for a wallet payments row 38", "fee", 154, 6, 190.48, 11],
  ["clamps paymentMethod for a ach payments row 39", "clamp", 258.09, 256, 258.09, 260],
  ["computes paymentMethod for a visa payments row 40", "base", 32, 19, 47],
  ["applies the paymentMethod fee path for a klarna payments row 41", "fee", 68, 20, 92.68, 0],
  ["clamps paymentMethod for a store payments row 42", "clamp", 302.4, 301, 302.4, 305],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(paymentMethod(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(paymentMethodWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPaymentMethod(a, b, extra)).toBe(expected);
    }
  });
}
