// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 106;

function paymentMethod(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function paymentMethodWithFee(amount, factor, fee) {
  return paymentMethod(amount, factor) + fee;
}

function clampPaymentMethod(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  paymentMethod,
  paymentMethodWithFee,
  clampPaymentMethod,
  factorFromBps,
};
