// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  paymentWebhook,
  paymentWebhookWithFee,
  clampPaymentWebhook,
  factorFromBps,
} = require("./paymentWebhook");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes paymentWebhook for a apple payments row 1", "base", 150, 7, 179.5],
  ["applies the paymentWebhook fee path for a amex payments row 2", "fee", 89, 1, 110.01, 6],
  ["clamps paymentWebhook for a visa payments row 3", "clamp", 47.64, 46, 47.64, 50],
  ["computes paymentWebhook for a ach payments row 4", "base", 211, 13, 262.31],
  ["applies the paymentWebhook fee path for a wallet payments row 5", "fee", 146, 8, 179.36, 3],
  ["clamps paymentWebhook for a paypal payments row 6", "clamp", 100.5, 99, 100.5, 103],
  ["computes paymentWebhook for a klarna payments row 7", "base", 28, 20, 42.84],
  ["applies the paymentWebhook fee path for a store payments row 8", "fee", 207, 14, 263.54, 4],
  ["clamps paymentWebhook for a apple payments row 9", "clamp", 183.54, 184, 184, 188],
  ["computes paymentWebhook for a amex payments row 10", "base", 97, 24, 135.04],
  ["applies the paymentWebhook fee path for a ach payments row 11", "fee", 139, 16, 190.36, 11],
  ["clamps paymentWebhook for a visa payments row 12", "clamp", 270, 265, 269, 269],
  ["computes paymentWebhook for a amex payments row 13", "base", 17, 4, 26.04],
  ["applies the paymentWebhook fee path for a apple payments row 14", "fee", 78, 10, 109.04, 10],
  ["clamps paymentWebhook for a store payments row 15", "clamp", 175.75, 174, 175.75, 178],
  ["computes paymentWebhook for a klarna payments row 16", "base", 196, 23, 263.76],
  ["applies the paymentWebhook fee path for a paypal payments row 17", "fee", 13, 5, 26.69, 5],
  ["clamps paymentWebhook for a wallet payments row 18", "clamp", 93.06, 93, 93.06, 97],
  ["computes paymentWebhook for a ach payments row 19", "base", 131, 18, 172.06],
  ["applies the paymentWebhook fee path for a visa payments row 20", "fee", 192, 24, 264.44, 4],
  ["clamps paymentWebhook for a visa payments row 21", "clamp", 262.84, 261, 262.84, 265],
  ["computes paymentWebhook for a ach payments row 22", "base", 147, 9, 178.99],
  ["applies the paymentWebhook fee path for a apple payments row 23", "fee", 86, 3, 105.46, 3],
  ["clamps paymentWebhook for a amex payments row 24", "clamp", 40.5, 38, 40.5, 42],
  ["computes paymentWebhook for a klarna payments row 25", "base", 204, 16, 259.96],
  ["applies the paymentWebhook fee path for a store payments row 26", "fee", 143, 10, 175.74, 0],
  ["clamps paymentWebhook for a wallet payments row 27", "clamp", 100.84, 97, 100.84, 101],
  ["computes paymentWebhook for a paypal payments row 28", "base", 21, 23, 34.51],
  ["applies the paymentWebhook fee path for a visa payments row 29", "fee", 216, 13, 281.36, 13],
  ["clamps paymentWebhook for a ach payments row 30", "clamp", 185.25, 183, 185.25, 187],
  ["computes paymentWebhook for a amex payments row 31", "base", 153, 10, 187.54],
  ["applies the paymentWebhook fee path for a apple payments row 32", "fee", 214, 16, 283.36, 11],
  ["clamps paymentWebhook for a ach payments row 33", "clamp", 54.5, 51, 54.5, 55],
  ["computes paymentWebhook for a visa payments row 34", "base", 96, 3, 113.56],
  ["applies the paymentWebhook fee path for a paypal payments row 35", "fee", 149, 11, 190.31, 6],
  ["clamps paymentWebhook for a wallet payments row 36", "clamp", 268.5, 268, 268.5, 272],
  ["computes paymentWebhook for a store payments row 37", "base", 31, 23, 47.61],
  ["applies the paymentWebhook fee path for a klarna payments row 38", "fee", 92, 4, 119.04, 9],
  ["clamps paymentWebhook for a amex payments row 39", "clamp", 202.24, 203, 203, 207],
  ["computes paymentWebhook for a apple payments row 40", "base", 238, 10, 287.84],
  ["applies the paymentWebhook fee path for a apple payments row 41", "fee", 22, 4, 45.64, 14],
  ["clamps paymentWebhook for a amex payments row 42", "clamp", 272.31, 268, 272, 272],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(paymentWebhook(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(paymentWebhookWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPaymentWebhook(a, b, extra)).toBe(expected);
    }
  });
}
