// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 112;

function paymentCurrency(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function paymentCurrencyWithFee(amount, factor, fee) {
  return paymentCurrency(amount, factor) + fee;
}

function clampPaymentCurrency(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  paymentCurrency,
  paymentCurrencyWithFee,
  clampPaymentCurrency,
  factorFromBps,
};
