// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  paymentRetry,
  paymentRetryWithFee,
  clampPaymentRetry,
  factorFromBps,
} = require("./paymentRetry");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes paymentRetry for a ach payments row 1", "base", 227, 24, 354.85],
  ["applies the paymentRetry fee path for a visa payments row 2", "fee", 48, 5, 78.28, 10],
  ["clamps paymentRetry for a amex payments row 3", "clamp", 155.15, 151, 155, 155],
  ["computes paymentRetry for a apple payments row 4", "base", 166, 18, 250.34],
  ["applies the paymentRetry fee path for a store payments row 5", "fee", 223, 0, 300.13, 5],
  ["clamps paymentRetry for a klarna payments row 6", "clamp", 63.28, 61, 63.28, 65],
  ["computes paymentRetry for a paypal payments row 7", "base", 101, 13, 148.44],
  ["applies the paymentRetry fee path for a wallet payments row 8", "fee", 162, 19, 250, 4],
  ["clamps paymentRetry for a ach payments row 9", "clamp", 363.55, 361, 363.55, 365],
  ["computes paymentRetry for a visa payments row 10", "base", 56, 3, 78.04],
  ["applies the paymentRetry fee path for a visa payments row 11", "fee", 240, 12, 353.2, 7],
  ["clamps paymentRetry for a ach payments row 12", "clamp", 248.23, 246, 248.23, 250],
  ["computes paymentRetry for a apple payments row 13", "base", 118, 0, 157.58],
  ["applies the paymentRetry fee path for a amex payments row 14", "fee", 57, 19, 92.5, 4],
  ["clamps paymentRetry for a klarna payments row 15", "clamp", 343.84, 341, 343.84, 345],
  ["computes paymentRetry for a store payments row 16", "base", 175, 7, 244.5],
  ["applies the paymentRetry fee path for a wallet payments row 17", "fee", 114, 1, 154.48, 1],
  ["clamps paymentRetry for a paypal payments row 18", "clamp", 85.03, 81, 85, 85],
  ["computes paymentRetry for a visa payments row 19", "base", 8, 10, 14.28],
  ["applies the paymentRetry fee path for a ach payments row 20", "fee", 187, 4, 269.45, 14],
  ["clamps paymentRetry for a ach payments row 21", "clamp", 231.4, 230, 231.4, 234],
  ["computes paymentRetry for a visa payments row 22", "base", 216, 23, 335.64],
  ["applies the paymentRetry fee path for a amex payments row 23", "fee", 33, 5, 57.88, 10],
  ["clamps paymentRetry for a apple payments row 24", "clamp", 133.48, 134, 134, 138],
  ["computes paymentRetry for a store payments row 25", "base", 151, 18, 227.99],
  ["applies the paymentRetry fee path for a klarna payments row 26", "fee", 212, 24, 340.6, 9],
  ["clamps paymentRetry for a paypal payments row 27", "clamp", 43.73, 41, 43.73, 45],
  ["computes paymentRetry for a wallet payments row 28", "base", 90, 12, 131.7],
  ["applies the paymentRetry fee path for a ach payments row 29", "fee", 147, 19, 227.5, 4],
  ["clamps paymentRetry for a visa payments row 30", "clamp", 274.48, 273, 274.48, 277],
  ["computes paymentRetry for a wallet payments row 31", "base", 34, 16, 52.98],
  ["applies the paymentRetry fee path for a paypal payments row 32", "fee", 213, 10, 313.33, 10],
  ["clamps paymentRetry for a klarna payments row 33", "clamp", 215.04, 210, 214, 214],
  ["computes paymentRetry for a store payments row 34", "base", 95, 22, 148.35],
  ["applies the paymentRetry fee path for a apple payments row 35", "fee", 38, 15, 58.48, 0],
  ["clamps paymentRetry for a amex payments row 36", "clamp", 304.8, 305, 305, 309],
  ["computes paymentRetry for a visa payments row 37", "base", 160, 2, 215.8],
  ["applies the paymentRetry fee path for a ach payments row 38", "fee", 99, 21, 154.48, 1],
  ["clamps paymentRetry for a wallet payments row 39", "clamp", 64.9, 62, 64.9, 66],
  ["computes paymentRetry for a paypal payments row 40", "base", 221, 8, 310.19],
  ["applies the paymentRetry fee path for a paypal payments row 41", "fee", 205, 17, 308.4, 2],
  ["clamps paymentRetry for a wallet payments row 42", "clamp", 45.04, 41, 45, 45],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(paymentRetry(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(paymentRetryWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPaymentRetry(a, b, extra)).toBe(expected);
    }
  });
}
