// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 133;

function paymentAuth(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function paymentAuthWithFee(amount, factor, fee) {
  return paymentAuth(amount, factor) + fee;
}

function clampPaymentAuth(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  paymentAuth,
  paymentAuthWithFee,
  clampPaymentAuth,
  factorFromBps,
};
