// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  paymentReceipt,
  paymentReceiptWithFee,
  clampPaymentReceipt,
  factorFromBps,
} = require("./paymentReceipt");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes paymentReceipt for a amex payments row 1", "base", 185, 17, 221.3],
  ["applies the paymentReceipt fee path for a apple payments row 2", "fee", 246, 23, 321.04, 13],
  ["clamps paymentReceipt for a ach payments row 3", "clamp", 75.35, 71, 75, 75],
  ["computes paymentReceipt for a visa payments row 4", "base", 128, 10, 145.08],
  ["applies the paymentReceipt fee path for a paypal payments row 5", "fee", 181, 18, 226.39, 8],
  ["clamps paymentReceipt for a wallet payments row 6", "clamp", 304.5, 304, 304.5, 308],
  ["computes paymentReceipt for a store payments row 7", "base", 63, 5, 69.78],
  ["applies the paymentReceipt fee path for a klarna payments row 8", "fee", 124, 11, 152.88, 11],
  ["clamps paymentReceipt for a amex payments row 9", "clamp", 226.88, 225, 226.88, 229],
  ["computes paymentReceipt for a apple payments row 10", "base", 14, 21, 20.08],
  ["applies the paymentReceipt fee path for a wallet payments row 11", "fee", 50, 2, 66.5, 12],
  ["clamps paymentReceipt for a paypal payments row 12", "clamp", 281.38, 280, 281.38, 284],
  ["computes paymentReceipt for a klarna payments row 13", "base", 172, 14, 200.8],
  ["applies the paymentReceipt fee path for a store payments row 14", "fee", 111, 8, 136.99, 13],
  ["clamps paymentReceipt for a apple payments row 15", "clamp", 60.08, 56, 60, 60],
  ["computes paymentReceipt for a amex payments row 16", "base", 233, 20, 284.93],
  ["applies the paymentReceipt fee path for a visa payments row 17", "fee", 176, 13, 206.64, 3],
  ["clamps paymentReceipt for a ach payments row 18", "clamp", 124.2, 125, 125, 129],
  ["computes paymentReceipt for a wallet payments row 19", "base", 58, 0, 61.58],
  ["applies the paymentReceipt fee path for a paypal payments row 20", "fee", 237, 19, 291.4, 4],
  ["clamps paymentReceipt for a amex payments row 21", "clamp", 244.19, 240, 244, 244],
  ["computes paymentReceipt for a apple payments row 22", "base", 22, 24, 30.5],
  ["applies the paymentReceipt fee path for a ach payments row 23", "fee", 83, 5, 90.98, 0],
  ["clamps paymentReceipt for a visa payments row 24", "clamp", 165.28, 162, 165.28, 166],
  ["computes paymentReceipt for a paypal payments row 25", "base", 197, 19, 239.4],
  ["applies the paymentReceipt fee path for a wallet payments row 26", "fee", 18, 0, 31.18, 10],
  ["clamps paymentReceipt for a store payments row 27", "clamp", 85.53, 86, 86, 90],
  ["computes paymentReceipt for a klarna payments row 28", "base", 140, 12, 161.2],
  ["applies the paymentReceipt fee path for a amex payments row 29", "fee", 209, 16, 253.53, 6],
  ["clamps paymentReceipt for a apple payments row 30", "clamp", 38.9, 38, 38.9, 42],
  ["computes paymentReceipt for a visa payments row 31", "base", 112, 9, 126.2],
  ["applies the paymentReceipt fee path for a ach payments row 32", "fee", 51, 3, 69.03999999999999, 13],
  ["clamps paymentReceipt for a apple payments row 33", "clamp", 284.9, 284, 284.9, 288],
  ["computes paymentReceipt for a amex payments row 34", "base", 169, 16, 200.73],
  ["applies the paymentReceipt fee path for a klarna payments row 35", "fee", 108, 10, 132.88, 10],
  ["clamps paymentReceipt for a store payments row 36", "clamp", 52.35, 50, 52.35, 54],
  ["computes paymentReceipt for a wallet payments row 37", "base", 226, 23, 283.24],
  ["applies the paymentReceipt fee path for a paypal payments row 38", "fee", 165, 17, 204.7, 7],
  ["clamps paymentReceipt for a visa payments row 39", "clamp", 130.6, 131, 131, 135],
  ["computes paymentReceipt for a ach payments row 40", "base", 59, 1, 63.18],
  ["applies the paymentReceipt fee path for a store payments row 41", "fee", 15, 7, 26.2, 7],
  ["clamps paymentReceipt for a klarna payments row 42", "clamp", 90.64, 88, 90.64, 92],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(paymentReceipt(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(paymentReceiptWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPaymentReceipt(a, b, extra)).toBe(expected);
    }
  });
}
