// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 127;

function payoutSplit(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function payoutSplitWithFee(amount, factor, fee) {
  return payoutSplit(amount, factor) + fee;
}

function clampPayoutSplit(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  payoutSplit,
  payoutSplitWithFee,
  clampPayoutSplit,
  factorFromBps,
};
