// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 121;

function refundCapture(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function refundCaptureWithFee(amount, factor, fee) {
  return refundCapture(amount, factor) + fee;
}

function clampRefundCapture(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  refundCapture,
  refundCaptureWithFee,
  clampRefundCapture,
  factorFromBps,
};
