// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 136;

function tokenVault(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function tokenVaultWithFee(amount, factor, fee) {
  return tokenVault(amount, factor) + fee;
}

function clampTokenVault(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  tokenVault,
  tokenVaultWithFee,
  clampTokenVault,
  factorFromBps,
};
