// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  walletPay,
  walletPayWithFee,
  clampWalletPay,
  factorFromBps,
} = require("./walletPay");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes walletPay for a apple payments row 1", "base", 166, 8, 207.84],
  ["applies the walletPay fee path for a amex payments row 2", "fee", 105, 2, 132.9, 7],
  ["clamps walletPay for a visa payments row 3", "clamp", 69.28, 65, 69, 69],
  ["computes walletPay for a ach payments row 4", "base", 227, 14, 297.1],
  ["applies the walletPay fee path for a wallet payments row 5", "fee", 162, 9, 208.5, 4],
  ["clamps walletPay for a paypal payments row 6", "clamp", 124.19, 120, 124, 124],
  ["computes walletPay for a klarna payments row 7", "base", 44, 21, 62.28],
  ["applies the walletPay fee path for a store payments row 8", "fee", 223, 15, 299.13, 5],
  ["clamps walletPay for a apple payments row 9", "clamp", 214.28, 212, 214.28, 216],
  ["computes walletPay for a amex payments row 10", "base", 113, 0, 133.08],
  ["applies the walletPay fee path for a ach payments row 11", "fee", 59, 1, 77.03, 6],
  ["clamps walletPay for a visa payments row 12", "clamp", 150.6, 148, 150.6, 152],
  ["computes walletPay for a amex payments row 13", "base", 177, 14, 232.1],
  ["applies the walletPay fee path for a apple payments row 14", "fee", 238, 20, 330.68, 5],
  ["clamps walletPay for a store payments row 15", "clamp", 64.9, 65, 65, 69],
  ["computes walletPay for a klarna payments row 16", "base", 116, 8, 145.84],
  ["applies the walletPay fee path for a paypal payments row 17", "fee", 173, 15, 228.63, 0],
  ["clamps walletPay for a wallet payments row 18", "clamp", 325.58, 321, 325, 325],
  ["computes walletPay for a ach payments row 19", "base", 51, 3, 62.69],
  ["applies the walletPay fee path for a visa payments row 20", "fee", 112, 9, 156, 14],
  ["clamps walletPay for a visa payments row 21", "clamp", 201.28, 197, 201, 201],
  ["computes walletPay for a ach payments row 22", "base", 83, 15, 110.73],
  ["applies the walletPay fee path for a apple payments row 23", "fee", 22, 9, 43.5, 14],
  ["clamps walletPay for a amex payments row 24", "clamp", 244.19, 239, 243, 243],
  ["computes walletPay for a klarna payments row 25", "base", 140, 22, 195.2],
  ["applies the walletPay fee path for a store payments row 26", "fee", 79, 16, 117.28, 11],
  ["clamps walletPay for a wallet payments row 27", "clamp", 21.68, 23, 23, 27],
  ["computes walletPay for a paypal payments row 28", "base", 197, 4, 238.4],
  ["applies the walletPay fee path for a visa payments row 29", "fee", 152, 19, 216.2, 9],
  ["clamps walletPay for a ach payments row 30", "clamp", 121.39, 117, 121, 121],
  ["computes walletPay for a amex payments row 31", "base", 233, 5, 283.93],
  ["applies the walletPay fee path for a apple payments row 32", "fee", 54, 11, 71.58, 1],
  ["clamps walletPay for a ach payments row 33", "clamp", 152.95, 153, 153, 157],
  ["computes walletPay for a visa payments row 34", "base", 176, 23, 246.64],
  ["applies the walletPay fee path for a paypal payments row 35", "fee", 229, 6, 292.38, 11],
  ["clamps walletPay for a wallet payments row 36", "clamp", 68, 64, 68, 68],
  ["computes walletPay for a store payments row 37", "base", 111, 18, 150.74],
  ["applies the walletPay fee path for a klarna payments row 38", "fee", 172, 24, 256.8, 14],
  ["clamps walletPay for a amex payments row 39", "clamp", 291.79, 287, 291, 291],
  ["computes walletPay for a apple payments row 40", "base", 62, 9, 79.5],
  ["applies the walletPay fee path for a apple payments row 41", "fee", 198, 10, 261.48, 10],
  ["clamps walletPay for a amex payments row 42", "clamp", 163.4, 164, 164, 168],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(walletPay(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(walletPayWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampWalletPay(a, b, extra)).toBe(expected);
    }
  });
}
