// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  cycleSlot,
  cycleSlotWithFee,
  clampCycleSlot,
  factorFromBps,
} = require("./cycleSlot");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes cycleSlot for a b2 warehouse row 1", "base", 25, 17, 31.5],
  ["applies the cycleSlot fee path for a returns warehouse row 2", "fee", 86, 23, 111.64, 3],
  ["clamps cycleSlot for a dock warehouse row 3", "clamp", 158.35, 154, 158, 158],
  ["computes cycleSlot for a a1 warehouse row 4", "base", 208, 10, 232.88],
  ["applies the cycleSlot fee path for a bulk warehouse row 5", "fee", 21, 18, 39.989999999999995, 13],
  ["clamps cycleSlot for a c3 warehouse row 6", "clamp", 103.5, 103, 103.5, 107],
  ["computes cycleSlot for a hazmat warehouse row 7", "base", 143, 5, 153.58],
  ["applies the cycleSlot fee path for a cold warehouse row 8", "fee", 204, 11, 231.48, 1],
  ["clamps cycleSlot for a b2 warehouse row 9", "clamp", 40.28, 38, 40.28, 42],
  ["computes cycleSlot for a returns warehouse row 10", "base", 94, 21, 116.68],
  ["applies the cycleSlot fee path for a c3 warehouse row 11", "fee", 98, 5, 105.88, 0],
  ["clamps cycleSlot for a bulk warehouse row 12", "clamp", 50.25, 46, 50, 50],
  ["computes cycleSlot for a cold warehouse row 13", "base", 220, 17, 261.6],
  ["applies the cycleSlot fee path for a hazmat warehouse row 14", "fee", 159, 11, 181.08, 1],
  ["clamps cycleSlot for a returns warehouse row 15", "clamp", 107.1, 107, 107.1, 111],
  ["computes cycleSlot for a b2 warehouse row 16", "base", 41, 23, 52.84],
  ["applies the cycleSlot fee path for a a1 warehouse row 17", "fee", 224, 16, 270.08, 6],
  ["clamps cycleSlot for a dock warehouse row 18", "clamp", 182.93, 181, 182.93, 185],
  ["computes cycleSlot for a c3 warehouse row 19", "base", 106, 3, 112.24],
  ["applies the cycleSlot fee path for a bulk warehouse row 20", "fee", 45, 22, 64.35, 7],
  ["clamps cycleSlot for a b2 warehouse row 21", "clamp", 161.55, 158, 161.55, 162],
  ["computes cycleSlot for a returns warehouse row 22", "base", 198, 20, 241.58],
  ["applies the cycleSlot fee path for a dock warehouse row 23", "fee", 19, 1, 32.379999999999995, 11],
  ["clamps cycleSlot for a a1 warehouse row 24", "clamp", 89.4, 86, 89.4, 90],
  ["computes cycleSlot for a bulk warehouse row 25", "base", 133, 15, 156.28],
  ["applies the cycleSlot fee path for a c3 warehouse row 26", "fee", 194, 21, 244.68, 6],
  ["clamps cycleSlot for a hazmat warehouse row 27", "clamp", 15.45, 15, 15.45, 19],
  ["computes cycleSlot for a cold warehouse row 28", "base", 76, 8, 84.84],
  ["applies the cycleSlot fee path for a b2 warehouse row 29", "fee", 145, 12, 167.85, 2],
  ["clamps cycleSlot for a returns warehouse row 30", "clamp", 246.14, 245, 246.14, 249],
  ["computes cycleSlot for a a1 warehouse row 31", "base", 48, 5, 52.88],
  ["applies the cycleSlot fee path for a dock warehouse row 32", "fee", 227, 24, 294.75, 9],
  ["clamps cycleSlot for a returns warehouse row 33", "clamp", 198.54, 198, 198.54, 202],
  ["computes cycleSlot for a b2 warehouse row 34", "base", 105, 12, 120.65],
  ["applies the cycleSlot fee path for a cold warehouse row 35", "fee", 44, 6, 55.08, 6],
  ["clamps cycleSlot for a hazmat warehouse row 36", "clamp", 227.23, 225, 227.23, 229],
  ["computes cycleSlot for a c3 warehouse row 37", "base", 162, 19, 196.4],
  ["applies the cycleSlot fee path for a bulk warehouse row 38", "fee", 101, 13, 120.14, 3],
  ["clamps cycleSlot for a a1 warehouse row 39", "clamp", 58.24, 58, 58.24, 62],
  ["computes cycleSlot for a dock warehouse row 40", "base", 235, 22, 291.05],
  ["applies the cycleSlot fee path for a hazmat warehouse row 41", "fee", 191, 3, 203.64, 3],
  ["clamps cycleSlot for a cold warehouse row 42", "clamp", 16.2, 13, 16.2, 17],
  ["computes cycleSlot for a bulk warehouse row 43", "base", 69, 16, 82.73],
  ["applies the cycleSlot fee path for a c3 warehouse row 44", "fee", 130, 22, 163.9, 2],
  ["clamps cycleSlot for a dock warehouse row 45", "clamp", 202.85, 201, 202.85, 205],
  ["computes cycleSlot for a a1 warehouse row 46", "base", 16, 8, 19.44],
  ["applies the cycleSlot fee path for a b2 warehouse row 47", "fee", 73, 15, 91.68, 5],
  ["clamps cycleSlot for a returns warehouse row 48", "clamp", 163.48, 163, 163.48, 167],
  ["computes cycleSlot for a hazmat warehouse row 49", "base", 199, 1, 204.98],
  ["applies the cycleSlot fee path for a cold warehouse row 50", "fee", 20, 7, 35.6, 12],
  ["clamps cycleSlot for a returns warehouse row 51", "clamp", 124.4, 122, 124.4, 126],
  ["computes cycleSlot for a b2 warehouse row 52", "base", 41, 13, 48.74],
  ["applies the cycleSlot fee path for a a1 warehouse row 53", "fee", 224, 6, 247.68, 6],
  ["clamps cycleSlot for a dock warehouse row 54", "clamp", 168.63, 165, 168.63, 169],
  ["computes cycleSlot for a c3 warehouse row 55", "base", 98, 20, 120.58],
  ["applies the cycleSlot fee path for a bulk warehouse row 56", "fee", 37, 14, 58.55, 14],
  ["clamps cycleSlot for a cold warehouse row 57", "clamp", 242.6, 238, 242, 242],
  ["computes cycleSlot for a hazmat warehouse row 58", "base", 159, 1, 164.18],
  ["applies the cycleSlot fee path for a returns warehouse row 59", "fee", 110, 17, 143.8, 12],
  ["clamps cycleSlot for a b2 warehouse row 60", "clamp", 56.88, 55, 56.88, 59],
  ["computes cycleSlot for a bulk warehouse row 61", "base", 13, 10, 16.43],
  ["applies the cycleSlot fee path for a c3 warehouse row 62", "fee", 74, 16, 94.58, 6],
  ["clamps cycleSlot for a hazmat warehouse row 63", "clamp", 166.05, 166, 166.05, 170],
  ["computes cycleSlot for a cold warehouse row 64", "base", 196, 3, 205.84],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(cycleSlot(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(cycleSlotWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCycleSlot(a, b, extra)).toBe(expected);
    }
  });
}
