// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  dockDoor,
  dockDoorWithFee,
  clampDockDoor,
  factorFromBps,
} = require("./dockDoor");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes dockDoor for a cold warehouse row 1", "base", 164, 1, 201.16],
  ["applies the dockDoor fee path for a hazmat warehouse row 2", "fee", 103, 20, 153.14, 5],
  ["clamps dockDoor for a c3 warehouse row 3", "clamp", 60.44, 59, 60.44, 63],
  ["computes dockDoor for a bulk warehouse row 4", "base", 221, 8, 284.46],
  ["applies the dockDoor fee path for a a1 warehouse row 5", "fee", 168, 0, 214.24, 10],
  ["clamps dockDoor for a dock warehouse row 6", "clamp", 154.59, 151, 154.59, 155],
  ["computes dockDoor for a returns warehouse row 7", "base", 46, 13, 66.26],
  ["applies the dockDoor fee path for a b2 warehouse row 8", "fee", 225, 7, 294.25, 7],
  ["clamps dockDoor for a cold warehouse row 9", "clamp", 195.76, 193, 195.76, 197],
  ["computes dockDoor for a hazmat warehouse row 10", "base", 95, 22, 139],
  ["applies the dockDoor fee path for a bulk warehouse row 11", "fee", 149, 6, 196.76, 6],
  ["clamps dockDoor for a c3 warehouse row 12", "clamp", 281, 277, 281, 281],
  ["computes dockDoor for a hazmat warehouse row 13", "base", 31, 18, 48.16],
  ["applies the dockDoor fee path for a cold warehouse row 14", "fee", 92, 24, 145.64, 9],
  ["clamps dockDoor for a b2 warehouse row 15", "clamp", 195.19, 192, 195.19, 196],
  ["computes dockDoor for a returns warehouse row 16", "base", 214, 11, 282.06],
  ["applies the dockDoor fee path for a dock warehouse row 17", "fee", 35, 17, 65.25, 12],
  ["clamps dockDoor for a a1 warehouse row 18", "clamp", 141.36, 139, 141.36, 143],
  ["computes dockDoor for a bulk warehouse row 19", "base", 157, 4, 197.54],
  ["applies the dockDoor fee path for a c3 warehouse row 20", "fee", 218, 10, 285.04, 0],
  ["clamps dockDoor for a returns warehouse row 21", "clamp", 196.44, 191, 195, 195],
  ["computes dockDoor for a b2 warehouse row 22", "base", 81, 8, 108.06],
  ["applies the dockDoor fee path for a a1 warehouse row 23", "fee", 24, 1, 35.56, 1],
  ["clamps dockDoor for a dock warehouse row 24", "clamp", 284.14, 284, 284.14, 288],
  ["computes dockDoor for a c3 warehouse row 25", "base", 138, 15, 189.54],
  ["applies the dockDoor fee path for a bulk warehouse row 26", "fee", 77, 9, 112.79, 9],
  ["clamps dockDoor for a cold warehouse row 27", "clamp", 29, 28, 29, 32],
  ["computes dockDoor for a hazmat warehouse row 28", "base", 199, 21, 282.61],
  ["applies the dockDoor fee path for a returns warehouse row 29", "fee", 134, 16, 191.56, 6],
  ["clamps dockDoor for a b2 warehouse row 30", "clamp", 98.44, 97, 98.44, 101],
  ["computes dockDoor for a hazmat warehouse row 31", "base", 231, 23, 331.71],
  ["applies the dockDoor fee path for a cold warehouse row 32", "fee", 52, 4, 83.44, 14],
  ["clamps dockDoor for a bulk warehouse row 33", "clamp", 144.61, 145, 145, 149],
  ["computes dockDoor for a c3 warehouse row 34", "base", 170, 17, 235.5],
  ["applies the dockDoor fee path for a dock warehouse row 35", "fee", 235, 22, 337, 2],
  ["clamps dockDoor for a a1 warehouse row 36", "clamp", 71.76, 72, 72, 76],
  ["computes dockDoor for a b2 warehouse row 37", "base", 113, 10, 150.64],
  ["applies the dockDoor fee path for a returns warehouse row 38", "fee", 174, 16, 240.16, 1],
  ["clamps dockDoor for a hazmat warehouse row 39", "clamp", 269.14, 267, 269.14, 271],
  ["computes dockDoor for a cold warehouse row 40", "base", 44, 6, 60.56],
  ["applies the dockDoor fee path for a a1 warehouse row 41", "fee", 88, 0, 114.84, 5],
  ["clamps dockDoor for a dock warehouse row 42", "clamp", 39.99, 41, 41, 45],
  ["computes dockDoor for a returns warehouse row 43", "base", 206, 13, 275.86],
  ["applies the dockDoor fee path for a b2 warehouse row 44", "fee", 145, 7, 189.25, 2],
  ["clamps dockDoor for a cold warehouse row 45", "clamp", 103.96, 104, 104, 108],
  ["computes dockDoor for a hazmat warehouse row 46", "base", 23, 20, 37.74],
  ["applies the dockDoor fee path for a c3 warehouse row 47", "fee", 202, 14, 286.64, 14],
  ["clamps dockDoor for a bulk warehouse row 48", "clamp", 182.66, 182, 182.66, 186],
  ["computes dockDoor for a a1 warehouse row 49", "base", 80, 2, 102],
  ["applies the dockDoor fee path for a dock warehouse row 50", "fee", 19, 21, 43.41, 11],
  ["clamps dockDoor for a b2 warehouse row 51", "clamp", 228.79, 229, 229, 233],
  ["computes dockDoor for a returns warehouse row 52", "base", 238, 15, 322.54],
  ["applies the dockDoor fee path for a dock warehouse row 53", "fee", 59, 21, 94.01, 6],
  ["clamps dockDoor for a a1 warehouse row 54", "clamp", 147, 148, 148, 152],
  ["computes dockDoor for a bulk warehouse row 55", "base", 173, 10, 227.44],
  ["applies the dockDoor fee path for a c3 warehouse row 56", "fee", 234, 16, 320.56, 1],
  ["clamps dockDoor for a hazmat warehouse row 57", "clamp", 84, 81, 84, 85],
  ["computes dockDoor for a cold warehouse row 58", "base", 116, 3, 146.36],
  ["applies the dockDoor fee path for a b2 warehouse row 59", "fee", 169, 11, 235.01, 11],
  ["clamps dockDoor for a returns warehouse row 60", "clamp", 314.5, 315, 315, 319],
  ["computes dockDoor for a c3 warehouse row 61", "base", 26, 18, 41.36],
  ["applies the dockDoor fee path for a bulk warehouse row 62", "fee", 205, 12, 274.5, 2],
  ["clamps dockDoor for a cold warehouse row 63", "clamp", 189.04, 186, 189.04, 190],
  ["computes dockDoor for a hazmat warehouse row 64", "base", 87, 24, 129.54],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(dockDoor(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(dockDoorWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampDockDoor(a, b, extra)).toBe(expected);
    }
  });
}
