// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 118;

function dockDoor(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function dockDoorWithFee(amount, factor, fee) {
  return dockDoor(amount, factor) + fee;
}

function clampDockDoor(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  dockDoor,
  dockDoorWithFee,
  clampDockDoor,
  factorFromBps,
};
