// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 139;

function freezeHold(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function freezeHoldWithFee(amount, factor, fee) {
  return freezeHold(amount, factor) + fee;
}

function clampFreezeHold(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  freezeHold,
  freezeHoldWithFee,
  clampFreezeHold,
  factorFromBps,
};
