// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 119;

function hazardFlag(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function hazardFlagWithFee(amount, factor, fee) {
  return hazardFlag(amount, factor) + fee;
}

function clampHazardFlag(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  hazardFlag,
  hazardFlagWithFee,
  clampHazardFlag,
  factorFromBps,
};
