// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  hazardFlag,
  hazardFlagWithFee,
  clampHazardFlag,
  factorFromBps,
} = require("./hazardFlag");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes hazardFlag for a hazmat warehouse row 1", "base", 63, 10, 88.27],
  ["applies the hazardFlag fee path for a cold warehouse row 2", "fee", 124, 16, 185.4, 11],
  ["clamps hazardFlag for a bulk warehouse row 3", "clamp", 261.02, 262, 262, 266],
  ["computes hazardFlag for a c3 warehouse row 4", "base", 242, 4, 304.66],
  ["applies the hazardFlag fee path for a dock warehouse row 5", "fee", 67, 9, 106.76, 14],
  ["clamps hazardFlag for a a1 warehouse row 6", "clamp", 175.52, 177, 177, 181],
  ["computes hazardFlag for a b2 warehouse row 7", "base", 185, 22, 267.85],
  ["applies the hazardFlag fee path for a returns warehouse row 8", "fee", 246, 3, 320.12, 13],
  ["clamps hazardFlag for a hazmat warehouse row 9", "clamp", 100.17, 95, 99, 99],
  ["computes hazardFlag for a cold warehouse row 10", "base", 132, 14, 182.56],
  ["applies the hazardFlag fee path for a cold warehouse row 11", "fee", 180, 7, 240.8, 7],
  ["clamps hazardFlag for a hazmat warehouse row 12", "clamp", 149.8, 148, 149.8, 152],
  ["computes hazardFlag for a c3 warehouse row 13", "base", 58, 20, 87.62],
  ["applies the hazardFlag fee path for a bulk warehouse row 14", "fee", 237, 14, 326.21, 4],
  ["clamps hazardFlag for a a1 warehouse row 15", "clamp", 240, 235, 239, 239],
  ["computes hazardFlag for a dock warehouse row 16", "base", 123, 0, 153.37],
  ["applies the hazardFlag fee path for a returns warehouse row 17", "fee", 62, 19, 101.56, 9],
  ["clamps hazardFlag for a b2 warehouse row 18", "clamp", 322.12, 323, 323, 327],
  ["computes hazardFlag for a cold warehouse row 19", "base", 172, 9, 227.16],
  ["applies the hazardFlag fee path for a hazmat warehouse row 20", "fee", 111, 3, 155.42, 13],
  ["clamps hazardFlag for a hazmat warehouse row 21", "clamp", 92.57, 93, 93, 97],
  ["computes hazardFlag for a cold warehouse row 22", "base", 124, 1, 155.8],
  ["applies the hazardFlag fee path for a bulk warehouse row 23", "fee", 181, 8, 244.87, 8],
  ["clamps hazardFlag for a c3 warehouse row 24", "clamp", 331.86, 327, 331, 331],
  ["computes hazardFlag for a dock warehouse row 25", "base", 67, 19, 99.46],
  ["applies the hazardFlag fee path for a a1 warehouse row 26", "fee", 128, 0, 159.32, 0],
  ["clamps hazardFlag for a b2 warehouse row 27", "clamp", 242.1, 238, 242, 242],
  ["computes hazardFlag for a returns warehouse row 28", "base", 246, 13, 331.72],
  ["applies the hazardFlag fee path for a hazmat warehouse row 29", "fee", 71, 18, 107.27, 3],
  ["clamps hazardFlag for a cold warehouse row 30", "clamp", 197.76, 194, 197.76, 198],
  ["computes hazardFlag for a returns warehouse row 31", "base", 214, 11, 285.2],
  ["applies the hazardFlag fee path for a b2 warehouse row 32", "fee", 153, 5, 206.72, 10],
  ["clamps hazardFlag for a a1 warehouse row 33", "clamp", 146.32, 141, 145, 145],
  ["computes hazardFlag for a dock warehouse row 34", "base", 35, 17, 54.6],
  ["applies the hazardFlag fee path for a c3 warehouse row 35", "fee", 210, 12, 289.1, 7],
  ["clamps hazardFlag for a bulk warehouse row 36", "clamp", 196.25, 191, 195, 195],
  ["computes hazardFlag for a cold warehouse row 37", "base", 92, 24, 138.56],
  ["applies the hazardFlag fee path for a hazmat warehouse row 38", "fee", 31, 18, 57.47, 8],
  ["clamps hazardFlag for a returns warehouse row 39", "clamp", 292.16, 289, 292.16, 293],
  ["computes hazardFlag for a b2 warehouse row 40", "base", 161, 3, 203.42],
  ["applies the hazardFlag fee path for a b2 warehouse row 41", "fee", 9, 6, 19.25, 1],
  ["clamps hazardFlag for a returns warehouse row 42", "clamp", 101.7, 97, 101, 101],
  ["computes hazardFlag for a dock warehouse row 43", "base", 131, 18, 186.47],
  ["applies the hazardFlag fee path for a a1 warehouse row 44", "fee", 192, 24, 285.56, 4],
  ["clamps hazardFlag for a bulk warehouse row 45", "clamp", 315.7, 314, 315.7, 318],
  ["computes hazardFlag for a c3 warehouse row 46", "base", 66, 13, 94.12],
  ["applies the hazardFlag fee path for a hazmat warehouse row 47", "fee", 127, 19, 196.26, 14],
  ["clamps hazardFlag for a cold warehouse row 48", "clamp", 229.72, 229, 229.72, 233],
  ["computes hazardFlag for a b2 warehouse row 49", "base", 17, 4, 27.91],
  ["applies the hazardFlag fee path for a returns warehouse row 50", "fee", 78, 10, 117.62, 10],
  ["clamps hazardFlag for a a1 warehouse row 51", "clamp", 234.6, 231, 234.6, 235],
  ["computes hazardFlag for a dock warehouse row 52", "base", 99, 16, 140.65],
  ["applies the hazardFlag fee path for a returns warehouse row 53", "fee", 38, 10, 56.02, 0],
  ["clamps hazardFlag for a b2 warehouse row 54", "clamp", 276.91, 272, 276, 276],
  ["computes hazardFlag for a cold warehouse row 55", "base", 156, 23, 228.52],
  ["applies the hazardFlag fee path for a hazmat warehouse row 56", "fee", 95, 17, 148.2, 12],
  ["clamps hazardFlag for a c3 warehouse row 57", "clamp", 48.2, 49, 49, 53],
  ["computes hazardFlag for a bulk warehouse row 58", "base", 213, 5, 271.12],
  ["applies the hazardFlag fee path for a a1 warehouse row 59", "fee", 168, 20, 250.52, 10],
  ["clamps hazardFlag for a dock warehouse row 60", "clamp", 151.31, 147, 151, 151],
  ["computes hazardFlag for a dock warehouse row 61", "base", 91, 23, 136.22],
  ["applies the hazardFlag fee path for a a1 warehouse row 62", "fee", 152, 4, 202.96, 9],
  ["clamps hazardFlag for a b2 warehouse row 63", "clamp", 277.7, 277, 277.7, 281],
  ["computes hazardFlag for a returns warehouse row 64", "base", 30, 17, 47.8],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(hazardFlag(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(hazardFlagWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampHazardFlag(a, b, extra)).toBe(expected);
    }
  });
}
