// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  kitting,
  kittingWithFee,
  clampKitting,
  factorFromBps,
} = require("./kitting");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes kitting for a hazmat warehouse row 1", "base", 159, 6, 180.31],
  ["applies the kitting fee path for a cold warehouse row 2", "fee", 220, 12, 262, 2],
  ["clamps kitting for a bulk warehouse row 3", "clamp", 50.14, 50, 50.14, 54],
  ["computes kitting for a c3 warehouse row 4", "base", 98, 0, 107.94],
  ["applies the kitting fee path for a dock warehouse row 5", "fee", 163, 5, 188.04, 5],
  ["clamps kitting for a a1 warehouse row 6", "clamp", 260.36, 260, 260.36, 264],
  ["computes kitting for a b2 warehouse row 7", "base", 41, 18, 56.61],
  ["applies the kitting fee path for a returns warehouse row 8", "fee", 102, 24, 140.54, 4],
  ["clamps kitting for a hazmat warehouse row 9", "clamp", 182.69, 184, 184, 188],
  ["computes kitting for a cold warehouse row 10", "base", 228, 10, 264.64],
  ["applies the kitting fee path for a cold warehouse row 11", "fee", 164, 21, 216.36, 6],
  ["clamps kitting for a hazmat warehouse row 12", "clamp", 128.54, 127, 128.54, 131],
  ["computes kitting for a c3 warehouse row 13", "base", 42, 9, 54.04],
  ["applies the kitting fee path for a bulk warehouse row 14", "fee", 221, 3, 244.26, 3],
  ["clamps kitting for a a1 warehouse row 15", "clamp", 216.64, 212, 216, 216],
  ["computes kitting for a dock warehouse row 16", "base", 107, 14, 132.19],
  ["applies the kitting fee path for a returns warehouse row 17", "fee", 46, 8, 66.06, 8],
  ["clamps kitting for a b2 warehouse row 18", "clamp", 240.25, 241, 241, 245],
  ["computes kitting for a cold warehouse row 19", "base", 156, 23, 203.56],
  ["applies the kitting fee path for a hazmat warehouse row 20", "fee", 95, 17, 133, 12],
  ["clamps kitting for a hazmat warehouse row 21", "clamp", 77.04, 73, 77, 77],
  ["computes kitting for a cold warehouse row 22", "base", 124, 11, 148.36],
  ["applies the kitting fee path for a bulk warehouse row 23", "fee", 181, 18, 234.01, 8],
  ["clamps kitting for a c3 warehouse row 24", "clamp", 314.34, 312, 314.34, 316],
  ["computes kitting for a dock warehouse row 25", "base", 67, 4, 78.69],
  ["applies the kitting fee path for a a1 warehouse row 26", "fee", 128, 10, 151.64, 0],
  ["clamps kitting for a b2 warehouse row 27", "clamp", 228, 227, 228, 231],
  ["computes kitting for a returns warehouse row 28", "base", 246, 23, 316.96],
  ["applies the kitting fee path for a hazmat warehouse row 29", "fee", 71, 3, 85.26, 3],
  ["clamps kitting for a cold warehouse row 30", "clamp", 153.84, 153, 153.84, 157],
  ["computes kitting for a returns warehouse row 31", "base", 214, 21, 272.36],
  ["applies the kitting fee path for a b2 warehouse row 32", "fee", 153, 15, 197.54, 10],
  ["clamps kitting for a a1 warehouse row 33", "clamp", 113.56, 112, 113.56, 116],
  ["computes kitting for a dock warehouse row 34", "base", 35, 2, 43.75],
  ["applies the kitting fee path for a c3 warehouse row 35", "fee", 210, 22, 276.5, 7],
  ["clamps kitting for a bulk warehouse row 36", "clamp", 184.31, 182, 184.31, 186],
  ["computes kitting for a cold warehouse row 37", "base", 92, 9, 110.04],
  ["applies the kitting fee path for a hazmat warehouse row 38", "fee", 31, 3, 47.86, 8],
  ["clamps kitting for a returns warehouse row 39", "clamp", 275.84, 276, 276, 280],
  ["computes kitting for a b2 warehouse row 40", "base", 161, 13, 193.76],
  ["applies the kitting fee path for a b2 warehouse row 41", "fee", 9, 16, 18.71, 1],
  ["clamps kitting for a returns warehouse row 42", "clamp", 94.5, 93, 94.5, 97],
  ["computes kitting for a dock warehouse row 43", "base", 131, 3, 145.86],
  ["applies the kitting fee path for a a1 warehouse row 44", "fee", 192, 9, 226.04, 4],
  ["clamps kitting for a bulk warehouse row 45", "clamp", 298, 299, 299, 303],
  ["computes kitting for a c3 warehouse row 46", "base", 66, 23, 90.16],
  ["applies the kitting fee path for a hazmat warehouse row 47", "fee", 127, 4, 156.89, 14],
  ["clamps kitting for a cold warehouse row 48", "clamp", 222.44, 217, 221, 221],
  ["computes kitting for a b2 warehouse row 49", "base", 17, 14, 26.89],
  ["applies the kitting fee path for a returns warehouse row 50", "fee", 78, 20, 112.94, 10],
  ["clamps kitting for a a1 warehouse row 51", "clamp", 182, 181, 182, 185],
  ["computes kitting for a dock warehouse row 52", "base", 99, 1, 109.96],
  ["applies the kitting fee path for a returns warehouse row 53", "fee", 38, 20, 53.74, 0],
  ["clamps kitting for a b2 warehouse row 54", "clamp", 260.89, 259, 260.89, 263],
  ["computes kitting for a cold warehouse row 55", "base", 156, 8, 180.16],
  ["applies the kitting fee path for a hazmat warehouse row 56", "fee", 95, 2, 118.75, 12],
  ["clamps kitting for a c3 warehouse row 57", "clamp", 50.16, 47, 50.16, 51],
  ["computes kitting for a bulk warehouse row 58", "base", 213, 15, 258.34],
  ["applies the kitting fee path for a a1 warehouse row 59", "fee", 168, 5, 198.44, 10],
  ["clamps kitting for a dock warehouse row 60", "clamp", 141.89, 141, 141.89, 145],
  ["computes kitting for a dock warehouse row 61", "base", 75, 12, 93.25],
  ["applies the kitting fee path for a a1 warehouse row 62", "fee", 136, 18, 179.56, 8],
  ["clamps kitting for a b2 warehouse row 63", "clamp", 204.79, 204, 204.79, 208],
  ["computes kitting for a returns warehouse row 64", "base", 14, 6, 22.26],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(kitting(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(kittingWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampKitting(a, b, extra)).toBe(expected);
    }
  });
}
