// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 103;

function kitting(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function kittingWithFee(amount, factor, fee) {
  return kitting(amount, factor) + fee;
}

function clampKitting(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  kitting,
  kittingWithFee,
  clampKitting,
  factorFromBps,
};
