// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  laborTask,
  laborTaskWithFee,
  clampLaborTask,
  factorFromBps,
} = require("./laborTask");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes laborTask for a c3 warehouse row 1", "base", 18, 15, 23.86],
  ["applies the laborTask fee path for a bulk warehouse row 2", "fee", 197, 9, 248.37, 9],
  ["clamps laborTask for a cold warehouse row 3", "clamp", 163.6, 159, 163, 163],
  ["computes laborTask for a hazmat warehouse row 4", "base", 79, 21, 106.07],
  ["applies the laborTask fee path for a returns warehouse row 5", "fee", 22, 14, 42.72, 14],
  ["clamps laborTask for a b2 warehouse row 6", "clamp", 240.2, 240, 240.2, 244],
  ["computes laborTask for a a1 warehouse row 7", "base", 144, 1, 163.72],
  ["applies the laborTask fee path for a dock warehouse row 8", "fee", 83, 20, 110.56, 0],
  ["clamps laborTask for a c3 warehouse row 9", "clamp", 34.5, 32, 34.5, 36],
  ["computes laborTask for a bulk warehouse row 10", "base", 205, 7, 244.95],
  ["applies the laborTask fee path for a hazmat warehouse row 11", "fee", 79, 21, 117.07, 11],
  ["clamps laborTask for a cold warehouse row 12", "clamp", 163.6, 159, 163, 163],
  ["computes laborTask for a bulk warehouse row 13", "base", 197, 9, 239.37],
  ["applies the laborTask fee path for a c3 warehouse row 14", "fee", 18, 15, 33.86, 10],
  ["clamps laborTask for a dock warehouse row 15", "clamp", 112.56, 109, 112.56, 113],
  ["computes laborTask for a a1 warehouse row 16", "base", 144, 1, 163.72],
  ["applies the laborTask fee path for a b2 warehouse row 17", "fee", 201, 8, 255.2, 13],
  ["clamps laborTask for a returns warehouse row 18", "clamp", 28.72, 27, 28.72, 31],
  ["computes laborTask for a hazmat warehouse row 19", "base", 87, 19, 114.97],
  ["applies the laborTask fee path for a cold warehouse row 20", "fee", 148, 0, 171.76, 5],
  ["clamps laborTask for a cold warehouse row 21", "clamp", 225.2, 222, 225.2, 226],
  ["computes laborTask for a hazmat warehouse row 22", "base", 119, 6, 141.42],
  ["applies the laborTask fee path for a c3 warehouse row 23", "fee", 58, 0, 70.96, 5],
  ["clamps laborTask for a bulk warehouse row 24", "clamp", 313.47, 309, 313, 313],
  ["computes laborTask for a a1 warehouse row 25", "base", 184, 11, 227.32],
  ["applies the laborTask fee path for a dock warehouse row 26", "fee", 123, 5, 154.91, 10],
  ["clamps laborTask for a returns warehouse row 27", "clamp", 83.32, 83, 83.32, 87],
  ["computes laborTask for a b2 warehouse row 28", "base", 241, 18, 314.3],
  ["applies the laborTask fee path for a cold warehouse row 29", "fee", 172, 14, 231.72, 14],
  ["clamps laborTask for a hazmat warehouse row 30", "clamp", 131.2, 132, 132, 136],
  ["computes laborTask for a bulk warehouse row 31", "base", 141, 3, 163.15],
  ["applies the laborTask fee path for a c3 warehouse row 32", "fee", 202, 9, 259.41999999999996, 14],
  ["clamps laborTask for a hazmat warehouse row 33", "clamp", 30.21, 28, 30.21, 32],
  ["computes laborTask for a cold warehouse row 34", "base", 84, 21, 112.72],
  ["applies the laborTask fee path for a b2 warehouse row 35", "fee", 145, 2, 168.3, 2],
  ["clamps laborTask for a returns warehouse row 36", "clamp", 247.2, 246, 247.2, 250],
  ["computes laborTask for a dock warehouse row 37", "base", 27, 14, 35.02],
  ["applies the laborTask fee path for a a1 warehouse row 38", "fee", 88, 20, 122.16, 5],
  ["clamps laborTask for a bulk warehouse row 39", "clamp", 157.61, 155, 157.61, 159],
  ["computes laborTask for a c3 warehouse row 40", "base", 194, 11, 239.62],
  ["applies the laborTask fee path for a c3 warehouse row 41", "fee", 210, 2, 247.4, 7],
  ["clamps laborTask for a bulk warehouse row 42", "clamp", 199.17, 197, 199.17, 201],
  ["computes laborTask for a cold warehouse row 43", "base", 92, 14, 116.92],
  ["applies the laborTask fee path for a hazmat warehouse row 44", "fee", 31, 8, 46.2, 8],
  ["clamps laborTask for a returns warehouse row 45", "clamp", 245.82, 241, 245, 245],
  ["computes laborTask for a b2 warehouse row 46", "base", 153, 20, 202.96],
  ["applies the laborTask fee path for a a1 warehouse row 47", "fee", 96, 13, 134, 13],
  ["clamps laborTask for a dock warehouse row 48", "clamp", 40.65, 41, 41, 45],
  ["computes laborTask for a c3 warehouse row 49", "base", 218, 0, 245.16],
  ["applies the laborTask fee path for a bulk warehouse row 50", "fee", 157, 19, 220.67, 14],
  ["clamps laborTask for a dock warehouse row 51", "clamp", 107.65, 104, 107.65, 108],
  ["computes laborTask for a a1 warehouse row 52", "base", 152, 9, 184.92],
  ["applies the laborTask fee path for a b2 warehouse row 53", "fee", 209, 16, 274.52, 6],
  ["clamps laborTask for a returns warehouse row 54", "clamp", 41.2, 39, 41.2, 43],
  ["computes laborTask for a hazmat warehouse row 55", "base", 87, 4, 101.92],
  ["applies the laborTask fee path for a cold warehouse row 56", "fee", 148, 10, 186.56, 5],
  ["clamps laborTask for a bulk warehouse row 57", "clamp", 262.45, 263, 263, 267],
  ["computes laborTask for a c3 warehouse row 58", "base", 26, 23, 36.1],
  ["applies the laborTask fee path for a dock warehouse row 59", "fee", 83, 5, 98.11, 0],
  ["clamps laborTask for a a1 warehouse row 60", "clamp", 180.12, 176, 180, 180],
  ["computes laborTask for a a1 warehouse row 61", "base", 176, 23, 238.6],
  ["applies the laborTask fee path for a dock warehouse row 62", "fee", 115, 17, 151.35, 2],
  ["clamps laborTask for a returns warehouse row 63", "clamp", 68.42, 65, 68.42, 69],
  ["computes laborTask for a b2 warehouse row 64", "base", 233, 5, 273.61],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(laborTask(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(laborTaskWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampLaborTask(a, b, extra)).toBe(expected);
    }
  });
}
