// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 100;

function packStation(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function packStationWithFee(amount, factor, fee) {
  return packStation(amount, factor) + fee;
}

function clampPackStation(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  packStation,
  packStationWithFee,
  clampPackStation,
  factorFromBps,
};
