// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  packVerify,
  packVerifyWithFee,
  clampPackVerify,
  factorFromBps,
} = require("./packVerify");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes packVerify for a b2 warehouse row 1", "base", 73, 5, 109.74],
  ["applies the packVerify fee path for a returns warehouse row 2", "fee", 134, 11, 207.96, 6],
  ["clamps packVerify for a dock warehouse row 3", "clamp", 303.5, 300, 303.5, 304],
  ["computes packVerify for a a1 warehouse row 4", "base", 16, 23, 33.96],
  ["applies the packVerify fee path for a bulk warehouse row 5", "fee", 69, 6, 105.91, 1],
  ["clamps packVerify for a c3 warehouse row 6", "clamp", 196.5, 196, 196.5, 200],
  ["computes packVerify for a hazmat warehouse row 7", "base", 191, 18, 297.41],
  ["applies the packVerify fee path for a cold warehouse row 8", "fee", 12, 24, 31.84, 4],
  ["clamps packVerify for a b2 warehouse row 9", "clamp", 119.16, 117, 119.16, 121],
  ["computes packVerify for a returns warehouse row 10", "base", 142, 9, 210.64],
  ["applies the packVerify fee path for a c3 warehouse row 11", "fee", 210, 17, 331, 7],
  ["clamps packVerify for a bulk warehouse row 12", "clamp", 222.56, 222, 222.56, 226],
  ["computes packVerify for a cold warehouse row 13", "base", 92, 4, 135.04],
  ["applies the packVerify fee path for a hazmat warehouse row 14", "fee", 31, 23, 65.36, 8],
  ["clamps packVerify for a returns warehouse row 15", "clamp", 329.86, 326, 329.86, 330],
  ["computes packVerify for a b2 warehouse row 16", "base", 153, 10, 227.79],
  ["applies the packVerify fee path for a a1 warehouse row 17", "fee", 96, 3, 152.56, 13],
  ["clamps packVerify for a dock warehouse row 18", "clamp", 60.25, 61, 61, 65],
  ["computes packVerify for a c3 warehouse row 19", "base", 218, 15, 331.64],
  ["applies the packVerify fee path for a bulk warehouse row 20", "fee", 157, 9, 245.94, 14],
  ["clamps packVerify for a b2 warehouse row 21", "clamp", 181.61, 178, 181.61, 182],
  ["computes packVerify for a returns warehouse row 22", "base", 182, 14, 276.54],
  ["applies the packVerify fee path for a dock warehouse row 23", "fee", 243, 20, 390.79, 10],
  ["clamps packVerify for a a1 warehouse row 24", "clamp", 95.76, 93, 95.76, 97],
  ["computes packVerify for a bulk warehouse row 25", "base", 117, 9, 175.14],
  ["applies the packVerify fee path for a c3 warehouse row 26", "fee", 178, 15, 277.44, 5],
  ["clamps packVerify for a hazmat warehouse row 27", "clamp", 375.06, 375, 375.06, 379],
  ["computes packVerify for a cold warehouse row 28", "base", 60, 2, 90],
  ["applies the packVerify fee path for a b2 warehouse row 29", "fee", 129, 6, 189.31, 1],
  ["clamps packVerify for a returns warehouse row 30", "clamp", 283.5, 283, 283.5, 287],
  ["computes packVerify for a a1 warehouse row 31", "base", 176, 13, 265.96],
  ["applies the packVerify fee path for a dock warehouse row 32", "fee", 115, 7, 172, 2],
  ["clamps packVerify for a returns warehouse row 33", "clamp", 81.36, 79, 81.36, 83],
  ["computes packVerify for a b2 warehouse row 34", "base", 233, 20, 365.49],
  ["applies the packVerify fee path for a cold warehouse row 35", "fee", 172, 14, 275.84, 14],
  ["clamps packVerify for a hazmat warehouse row 36", "clamp", 166.51, 164, 166.51, 168],
  ["computes packVerify for a c3 warehouse row 37", "base", 50, 2, 76.5],
  ["applies the packVerify fee path for a bulk warehouse row 38", "fee", 229, 21, 372.66, 11],
  ["clamps packVerify for a a1 warehouse row 39", "clamp", 272.96, 272, 272.96, 276],
  ["computes packVerify for a dock warehouse row 40", "base", 123, 5, 178.74],
  ["applies the packVerify fee path for a hazmat warehouse row 41", "fee", 79, 11, 133.76, 11],
  ["clamps packVerify for a cold warehouse row 42", "clamp", 221, 217, 221, 221],
  ["computes packVerify for a bulk warehouse row 43", "base", 197, 24, 318.29],
  ["applies the packVerify fee path for a c3 warehouse row 44", "fee", 18, 5, 43.84, 10],
  ["clamps packVerify for a dock warehouse row 45", "clamp", 128.69, 126, 128.69, 130],
  ["computes packVerify for a a1 warehouse row 46", "base", 144, 16, 223.56],
  ["applies the packVerify fee path for a b2 warehouse row 47", "fee", 201, 23, 335.56, 13],
  ["clamps packVerify for a returns warehouse row 48", "clamp", 38.14, 37, 38.14, 41],
  ["computes packVerify for a hazmat warehouse row 49", "base", 87, 9, 132.54],
  ["applies the packVerify fee path for a cold warehouse row 50", "fee", 148, 15, 233.04, 5],
  ["clamps packVerify for a returns warehouse row 51", "clamp", 320.5, 318, 320.5, 322],
  ["computes packVerify for a b2 warehouse row 52", "base", 169, 21, 269.26],
  ["applies the packVerify fee path for a a1 warehouse row 53", "fee", 112, 14, 187.64, 14],
  ["clamps packVerify for a dock warehouse row 54", "clamp", 83.91, 79, 83, 83],
  ["computes packVerify for a c3 warehouse row 55", "base", 226, 3, 316.36],
  ["applies the packVerify fee path for a bulk warehouse row 56", "fee", 165, 22, 271.75, 7],
  ["clamps packVerify for a cold warehouse row 57", "clamp", 165.84, 167, 167, 171],
  ["computes packVerify for a hazmat warehouse row 58", "base", 47, 9, 75.74],
  ["applies the packVerify fee path for a returns warehouse row 59", "fee", 238, 0, 330.54, 5],
  ["clamps packVerify for a b2 warehouse row 60", "clamp", 279.04, 276, 279.04, 280],
  ["computes packVerify for a bulk warehouse row 61", "base", 141, 18, 221.91],
  ["applies the packVerify fee path for a c3 warehouse row 62", "fee", 202, 24, 340.14, 14],
  ["clamps packVerify for a hazmat warehouse row 63", "clamp", 39.74, 39, 39.74, 43],
  ["computes packVerify for a cold warehouse row 64", "base", 84, 11, 129.96],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(packVerify(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(packVerifyWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPackVerify(a, b, extra)).toBe(expected);
    }
  });
}
