// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 128;

function pickList(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function pickListWithFee(amount, factor, fee) {
  return pickList(amount, factor) + fee;
}

function clampPickList(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  pickList,
  pickListWithFee,
  clampPickList,
  factorFromBps,
};
