// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  replenish,
  replenishWithFee,
  clampReplenish,
  factorFromBps,
} = require("./replenish");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes replenish for a bulk warehouse row 1", "base", 213, 20, 291.29],
  ["applies the replenish fee path for a c3 warehouse row 2", "fee", 34, 1, 57.76, 11],
  ["clamps replenish for a hazmat warehouse row 3", "clamp", 121, 120, 121, 124],
  ["computes replenish for a cold warehouse row 4", "base", 156, 13, 204.56],
  ["applies the replenish fee path for a b2 warehouse row 5", "fee", 217, 19, 308.44, 14],
  ["clamps replenish for a returns warehouse row 6", "clamp", 48.94, 49, 49, 53],
  ["computes replenish for a dock warehouse row 7", "base", 99, 6, 125.81],
  ["applies the replenish fee path for a a1 warehouse row 8", "fee", 160, 12, 210, 2],
  ["clamps replenish for a bulk warehouse row 9", "clamp", 294.51, 296, 296, 300],
  ["computes replenish for a c3 warehouse row 10", "base", 42, 24, 65.54],
  ["applies the replenish fee path for a returns warehouse row 11", "fee", 70, 12, 97.5, 2],
  ["clamps replenish for a b2 warehouse row 12", "clamp", 17.71, 17, 17.71, 21],
  ["computes replenish for a a1 warehouse row 13", "base", 192, 24, 271.04],
  ["applies the replenish fee path for a dock warehouse row 14", "fee", 131, 18, 182.61, 3],
  ["clamps replenish for a c3 warehouse row 15", "clamp", 91.16, 89, 91.16, 93],
  ["computes replenish for a bulk warehouse row 16", "base", 245, 7, 302],
  ["applies the replenish fee path for a cold warehouse row 17", "fee", 188, 0, 220.44, 0],
  ["clamps replenish for a hazmat warehouse row 18", "clamp", 177.64, 174, 177.64, 178],
  ["computes replenish for a returns warehouse row 19", "base", 78, 10, 103.94],
  ["applies the replenish fee path for a b2 warehouse row 20", "fee", 17, 4, 36.89, 9],
  ["clamps replenish for a bulk warehouse row 21", "clamp", 173.5, 169, 173, 173],
  ["computes replenish for a c3 warehouse row 22", "base", 186, 23, 260.96],
  ["applies the replenish fee path for a hazmat warehouse row 23", "fee", 247, 4, 310.99, 14],
  ["clamps replenish for a cold warehouse row 24", "clamp", 93.64, 90, 93.64, 94],
  ["computes replenish for a b2 warehouse row 25", "base", 129, 16, 174.41],
  ["applies the replenish fee path for a returns warehouse row 26", "fee", 190, 22, 266.5, 2],
  ["clamps replenish for a dock warehouse row 27", "clamp", 21.76, 19, 21.76, 23],
  ["computes replenish for a a1 warehouse row 28", "base", 72, 9, 95.84],
  ["applies the replenish fee path for a bulk warehouse row 29", "fee", 117, 19, 166.44, 4],
  ["clamps replenish for a c3 warehouse row 30", "clamp", 212.14, 207, 211, 211],
  ["computes replenish for a cold warehouse row 31", "base", 36, 8, 51.56],
  ["applies the replenish fee path for a hazmat warehouse row 32", "fee", 215, 2, 267.25, 12],
  ["clamps replenish for a c3 warehouse row 33", "clamp", 214.36, 212, 214.36, 216],
  ["computes replenish for a bulk warehouse row 34", "base", 93, 15, 127.04],
  ["applies the replenish fee path for a a1 warehouse row 35", "fee", 40, 7, 58, 2],
  ["clamps replenish for a dock warehouse row 36", "clamp", 260.66, 256, 260, 260],
  ["computes replenish for a returns warehouse row 37", "base", 158, 20, 218.14],
  ["applies the replenish fee path for a b2 warehouse row 38", "fee", 97, 14, 145.19, 14],
  ["clamps replenish for a cold warehouse row 39", "clamp", 44.44, 40, 44, 44],
  ["computes replenish for a hazmat warehouse row 40", "base", 207, 4, 250.19],
  ["applies the replenish fee path for a dock warehouse row 41", "fee", 187, 24, 278.19, 14],
  ["clamps replenish for a a1 warehouse row 42", "clamp", 17.44, 15, 17.44, 19],
  ["computes replenish for a b2 warehouse row 43", "base", 65, 12, 89.25],
  ["applies the replenish fee path for a returns warehouse row 44", "fee", 126, 18, 186.06, 13],
  ["clamps replenish for a hazmat warehouse row 45", "clamp", 211.79, 213, 213, 217],
  ["computes replenish for a cold warehouse row 46", "base", 244, 6, 298.36],
  ["applies the replenish fee path for a bulk warehouse row 47", "fee", 61, 13, 92.86, 8],
  ["clamps replenish for a c3 warehouse row 48", "clamp", 171.04, 167, 171, 171],
  ["computes replenish for a dock warehouse row 49", "base", 179, 1, 212.06],
  ["applies the replenish fee path for a a1 warehouse row 50", "fee", 240, 7, 303, 7],
  ["clamps replenish for a c3 warehouse row 51", "clamp", 260.26, 256, 260, 260],
  ["computes replenish for a bulk warehouse row 52", "base", 133, 10, 171.59],
  ["applies the replenish fee path for a cold warehouse row 53", "fee", 76, 3, 104.16, 8],
  ["clamps replenish for a hazmat warehouse row 54", "clamp", 25.25, 26, 26, 30],
  ["computes replenish for a returns warehouse row 55", "base", 198, 15, 261.44],
  ["applies the replenish fee path for a b2 warehouse row 56", "fee", 137, 9, 184.14, 9],
  ["clamps replenish for a a1 warehouse row 57", "clamp", 100, 98, 100, 102],
  ["computes replenish for a dock warehouse row 58", "base", 19, 21, 33.46],
  ["applies the replenish fee path for a c3 warehouse row 59", "fee", 202, 14, 278.54, 14],
  ["clamps replenish for a bulk warehouse row 60", "clamp", 180.61, 177, 180.61, 181],
  ["computes replenish for a b2 warehouse row 61", "base", 105, 7, 134],
  ["applies the replenish fee path for a returns warehouse row 62", "fee", 166, 13, 225.16, 8],
  ["clamps replenish for a dock warehouse row 63", "clamp", 307.64, 306, 307.64, 310],
  ["computes replenish for a a1 warehouse row 64", "base", 48, 0, 62.24],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(replenish(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(replenishWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampReplenish(a, b, extra)).toBe(expected);
    }
  });
}
