// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 8;
const FACTOR_BASE = 101;

function returnsBin(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function returnsBinWithFee(amount, factor, fee) {
  return returnsBin(amount, factor) + fee;
}

function clampReturnsBin(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  returnsBin,
  returnsBinWithFee,
  clampReturnsBin,
  factorFromBps,
};
