// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 126;

function toteAssign(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function toteAssignWithFee(amount, factor, fee) {
  return toteAssign(amount, factor) + fee;
}

function clampToteAssign(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  toteAssign,
  toteAssignWithFee,
  clampToteAssign,
  factorFromBps,
};
