// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  toteAssign,
  toteAssignWithFee,
  clampToteAssign,
  factorFromBps,
} = require("./toteAssign");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes toteAssign for a cold warehouse row 1", "base", 156, 13, 223.84],
  ["applies the toteAssign fee path for a hazmat warehouse row 2", "fee", 95, 7, 145.35, 12],
  ["clamps toteAssign for a c3 warehouse row 3", "clamp", 47.18, 48, 48, 52],
  ["computes toteAssign for a bulk warehouse row 4", "base", 213, 20, 317.98],
  ["applies the toteAssign fee path for a a1 warehouse row 5", "fee", 160, 12, 229.8, 2],
  ["clamps toteAssign for a dock warehouse row 6", "clamp", 137.68, 136, 137.68, 140],
  ["computes toteAssign for a returns warehouse row 7", "base", 38, 0, 54.88],
  ["applies the toteAssign fee path for a b2 warehouse row 8", "fee", 217, 19, 335.65, 14],
  ["clamps toteAssign for a cold warehouse row 9", "clamp", 234.68, 230, 234, 234],
  ["computes toteAssign for a hazmat warehouse row 10", "base", 103, 5, 141.93],
  ["applies the toteAssign fee path for a bulk warehouse row 11", "fee", 29, 1, 49.83, 6],
  ["clamps toteAssign for a c3 warehouse row 12", "clamp", 125.7, 125, 125.7, 129],
  ["computes toteAssign for a hazmat warehouse row 13", "base", 151, 13, 216.89],
  ["applies the toteAssign fee path for a cold warehouse row 14", "fee", 212, 19, 323.4, 9],
  ["clamps toteAssign for a b2 warehouse row 15", "clamp", 46.58, 47, 47, 51],
  ["computes toteAssign for a returns warehouse row 16", "base", 94, 6, 131.08],
  ["applies the toteAssign fee path for a dock warehouse row 17", "fee", 155, 12, 232.9, 12],
  ["clamps toteAssign for a a1 warehouse row 18", "clamp", 315.04, 316, 316, 320],
  ["computes toteAssign for a bulk warehouse row 19", "base", 21, 3, 34.09],
  ["applies the toteAssign fee path for a c3 warehouse row 20", "fee", 82, 9, 131.7, 14],
  ["clamps toteAssign for a returns warehouse row 21", "clamp", 170.48, 165, 169, 169],
  ["computes toteAssign for a b2 warehouse row 22", "base", 57, 4, 81.1],
  ["applies the toteAssign fee path for a a1 warehouse row 23", "fee", 240, 22, 369.2, 7],
  ["clamps toteAssign for a dock warehouse row 24", "clamp", 259.18, 259, 259.18, 263],
  ["computes toteAssign for a c3 warehouse row 25", "base", 114, 11, 163.18],
  ["applies the toteAssign fee path for a bulk warehouse row 26", "fee", 53, 5, 76.43, 0],
  ["clamps toteAssign for a cold warehouse row 27", "clamp", 357.64, 357, 357.64, 361],
  ["computes toteAssign for a hazmat warehouse row 28", "base", 175, 17, 257.25],
  ["applies the toteAssign fee path for a returns warehouse row 29", "fee", 126, 8, 188.84, 13],
  ["clamps toteAssign for a b2 warehouse row 30", "clamp", 93.2, 88, 92, 92],
  ["computes toteAssign for a hazmat warehouse row 31", "base", 79, 1, 107.33],
  ["applies the toteAssign fee path for a cold warehouse row 32", "fee", 140, 7, 205.2, 12],
  ["clamps toteAssign for a bulk warehouse row 33", "clamp", 283.8, 281, 283.8, 285],
  ["computes toteAssign for a c3 warehouse row 34", "base", 18, 20, 33.28],
  ["applies the toteAssign fee path for a dock warehouse row 35", "fee", 83, 0, 111.58, 0],
  ["clamps toteAssign for a a1 warehouse row 36", "clamp", 198.08, 195, 198.08, 199],
  ["computes toteAssign for a b2 warehouse row 37", "base", 201, 13, 286.39],
  ["applies the toteAssign fee path for a returns warehouse row 38", "fee", 22, 19, 52.9, 14],
  ["clamps toteAssign for a hazmat warehouse row 39", "clamp", 137.5, 136, 137.5, 140],
  ["computes toteAssign for a cold warehouse row 40", "base", 148, 5, 200.88],
  ["applies the toteAssign fee path for a a1 warehouse row 41", "fee", 176, 3, 237.04, 3],
  ["clamps toteAssign for a dock warehouse row 42", "clamp", 177.2, 175, 177.2, 179],
  ["computes toteAssign for a returns warehouse row 43", "base", 54, 16, 83.68],
  ["applies the toteAssign fee path for a b2 warehouse row 44", "fee", 233, 10, 323.88, 0],
  ["clamps toteAssign for a cold warehouse row 45", "clamp", 231.6, 229, 231.6, 233],
  ["computes toteAssign for a hazmat warehouse row 46", "base", 111, 23, 172.39],
  ["applies the toteAssign fee path for a c3 warehouse row 47", "fee", 50, 17, 90.5, 12],
  ["clamps toteAssign for a bulk warehouse row 48", "clamp", 322.73, 319, 322.73, 323],
  ["computes toteAssign for a a1 warehouse row 49", "base", 184, 1, 240.68],
  ["applies the toteAssign fee path for a dock warehouse row 50", "fee", 123, 20, 196.58, 10],
  ["clamps toteAssign for a b2 warehouse row 51", "clamp", 42.5, 40, 42.5, 44],
  ["computes toteAssign for a returns warehouse row 52", "base", 86, 18, 130.84],
  ["applies the toteAssign fee path for a dock warehouse row 53", "fee", 147, 24, 231.5, 4],
  ["clamps toteAssign for a a1 warehouse row 54", "clamp", 279.48, 277, 279.48, 281],
  ["computes toteAssign for a bulk warehouse row 55", "base", 21, 13, 36.19],
  ["applies the toteAssign fee path for a c3 warehouse row 56", "fee", 82, 19, 139.9, 14],
  ["clamps toteAssign for a hazmat warehouse row 57", "clamp", 184.18, 185, 185, 189],
  ["computes toteAssign for a cold warehouse row 58", "base", 204, 6, 276.28],
  ["applies the toteAssign fee path for a b2 warehouse row 59", "fee", 33, 10, 61.88, 10],
  ["clamps toteAssign for a returns warehouse row 60", "clamp", 138.48, 138, 138.48, 142],
  ["computes toteAssign for a c3 warehouse row 61", "base", 114, 21, 174.58],
  ["applies the toteAssign fee path for a bulk warehouse row 62", "fee", 53, 15, 81.73, 0],
  ["clamps toteAssign for a cold warehouse row 63", "clamp", 320.24, 321, 321, 325],
  ["computes toteAssign for a hazmat warehouse row 64", "base", 175, 2, 231],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(toteAssign(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(toteAssignWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampToteAssign(a, b, extra)).toBe(expected);
    }
  });
}
