// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  warehouseMap,
  warehouseMapWithFee,
  clampWarehouseMap,
  factorFromBps,
} = require("./warehouseMap");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes warehouseMap for a a1 warehouse row 1", "base", 224, 16, 311.12],
  ["applies the warehouseMap fee path for a dock warehouse row 2", "fee", 163, 10, 222.16, 5],
  ["clamps warehouseMap for a returns warehouse row 3", "clamp", 128.52, 129, 129, 133],
  ["computes warehouseMap for a b2 warehouse row 4", "base", 41, 23, 61.45],
  ["applies the warehouseMap fee path for a cold warehouse row 5", "fee", 220, 17, 309.8, 2],
  ["clamps warehouseMap for a hazmat warehouse row 6", "clamp", 212.47, 211, 212.47, 215],
  ["computes warehouseMap for a c3 warehouse row 7", "base", 98, 5, 126.46],
  ["applies the warehouseMap fee path for a bulk warehouse row 8", "fee", 37, 24, 70.02000000000001, 14],
  ["clamps warehouseMap for a a1 warehouse row 9", "clamp", 314.52, 316, 316, 320],
  ["computes warehouseMap for a dock warehouse row 10", "base", 171, 8, 224.3],
  ["applies the warehouseMap fee path for a b2 warehouse row 11", "fee", 201, 8, 276.3, 13],
  ["clamps warehouseMap for a returns warehouse row 12", "clamp", 31.92, 30, 31.92, 34],
  ["computes warehouseMap for a dock warehouse row 13", "base", 83, 20, 119.86],
  ["applies the warehouseMap fee path for a a1 warehouse row 14", "fee", 144, 1, 180.12, 1],
  ["clamps warehouseMap for a bulk warehouse row 15", "clamp", 257.07, 258, 258, 262],
  ["computes warehouseMap for a c3 warehouse row 16", "base", 18, 15, 26.66],
  ["applies the warehouseMap fee path for a hazmat warehouse row 17", "fee", 79, 21, 125.97, 11],
  ["clamps warehouseMap for a cold warehouse row 18", "clamp", 178.6, 174, 178, 178],
  ["computes warehouseMap for a b2 warehouse row 19", "base", 209, 6, 269.52],
  ["applies the warehouseMap fee path for a returns warehouse row 20", "fee", 30, 12, 49.2, 7],
  ["clamps warehouseMap for a c3 warehouse row 21", "clamp", 68.5, 70, 70, 74],
  ["computes warehouseMap for a bulk warehouse row 22", "base", 229, 11, 306.57],
  ["applies the warehouseMap fee path for a cold warehouse row 23", "fee", 172, 4, 232.72, 14],
  ["clamps warehouseMap for a hazmat warehouse row 24", "clamp", 161.95, 161, 161.95, 165],
  ["computes warehouseMap for a returns warehouse row 25", "base", 54, 16, 76.52],
  ["applies the warehouseMap fee path for a b2 warehouse row 26", "fee", 233, 10, 309.56, 0],
  ["clamps warehouseMap for a a1 warehouse row 27", "clamp", 224, 220, 224, 224],
  ["computes warehouseMap for a dock warehouse row 28", "base", 115, 22, 167.6],
  ["applies the warehouseMap fee path for a c3 warehouse row 29", "fee", 58, 15, 86.46, 5],
  ["clamps warehouseMap for a bulk warehouse row 30", "clamp", 309.47, 310, 310, 314],
  ["computes warehouseMap for a dock warehouse row 31", "base", 171, 18, 241.4],
  ["applies the warehouseMap fee path for a a1 warehouse row 32", "fee", 232, 24, 354.72, 14],
  ["clamps warehouseMap for a b2 warehouse row 33", "clamp", 64.72, 63, 64.72, 67],
  ["computes warehouseMap for a returns warehouse row 34", "base", 110, 12, 149.4],
  ["applies the warehouseMap fee path for a hazmat warehouse row 35", "fee", 167, 19, 246.47, 9],
  ["clamps warehouseMap for a cold warehouse row 36", "clamp", 278.16, 278, 278.16, 282],
  ["computes warehouseMap for a bulk warehouse row 37", "base", 45, 7, 60.05],
  ["applies the warehouseMap fee path for a c3 warehouse row 38", "fee", 106, 13, 153.1, 8],
  ["clamps warehouseMap for a dock warehouse row 39", "clamp", 235.46, 231, 235, 235],
  ["computes warehouseMap for a a1 warehouse row 40", "base", 224, 1, 277.52],
  ["applies the warehouseMap fee path for a cold warehouse row 41", "fee", 132, 9, 178.92, 4],
  ["clamps warehouseMap for a hazmat warehouse row 42", "clamp", 87.75, 89, 89, 93],
  ["computes warehouseMap for a c3 warehouse row 43", "base", 10, 22, 16.4],
  ["applies the warehouseMap fee path for a bulk warehouse row 44", "fee", 189, 16, 263.82, 1],
  ["clamps warehouseMap for a a1 warehouse row 45", "clamp", 178.8, 177, 178.8, 181],
  ["computes warehouseMap for a dock warehouse row 46", "base", 75, 2, 95],
  ["applies the warehouseMap fee path for a returns warehouse row 47", "fee", 14, 21, 28.02, 6],
  ["clamps warehouseMap for a b2 warehouse row 48", "clamp", 267.41, 264, 267.41, 268],
  ["computes warehouseMap for a cold warehouse row 49", "base", 124, 11, 166.92],
  ["applies the warehouseMap fee path for a hazmat warehouse row 50", "fee", 63, 5, 92.01, 10],
  ["clamps warehouseMap for a bulk warehouse row 51", "clamp", 309.4, 309, 309.4, 313],
  ["computes warehouseMap for a c3 warehouse row 52", "base", 42, 24, 63.32],
  ["applies the warehouseMap fee path for a hazmat warehouse row 53", "fee", 103, 5, 137.81, 5],
  ["clamps warehouseMap for a cold warehouse row 54", "clamp", 217.12, 218, 218, 222],
  ["computes warehouseMap for a b2 warehouse row 55", "base", 225, 17, 314.75],
  ["applies the warehouseMap fee path for a returns warehouse row 56", "fee", 46, 23, 76.7, 8],
  ["clamps warehouseMap for a dock warehouse row 57", "clamp", 139.82, 135, 139, 139],
  ["computes warehouseMap for a a1 warehouse row 58", "base", 168, 10, 223.76],
  ["applies the warehouseMap fee path for a bulk warehouse row 59", "fee", 213, 20, 314.46, 10],
  ["clamps warehouseMap for a c3 warehouse row 60", "clamp", 41.82, 42, 42, 46],
  ["computes warehouseMap for a returns warehouse row 61", "base", 70, 2, 88.8],
  ["applies the warehouseMap fee path for a b2 warehouse row 62", "fee", 9, 21, 15.87, 1],
  ["clamps warehouseMap for a a1 warehouse row 63", "clamp", 264.12, 261, 264.12, 265],
  ["computes warehouseMap for a dock warehouse row 64", "base", 131, 8, 172.3],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(warehouseMap(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(warehouseMapWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampWarehouseMap(a, b, extra)).toBe(expected);
    }
  });
}
