// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  wavePick,
  wavePickWithFee,
  clampWavePick,
  factorFromBps,
} = require("./wavePick");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes wavePick for a b2 warehouse row 1", "base", 185, 2, 211.35],
  ["applies the wavePick fee path for a returns warehouse row 2", "fee", 246, 8, 306.82, 13],
  ["clamps wavePick for a dock warehouse row 3", "clamp", 88.41, 86, 88.41, 90],
  ["computes wavePick for a a1 warehouse row 4", "base", 128, 20, 171.12],
  ["applies the wavePick fee path for a bulk warehouse row 5", "fee", 181, 3, 216.72, 8],
  ["clamps wavePick for a c3 warehouse row 6", "clamp", 288.56, 290, 290, 294],
  ["computes wavePick for a hazmat warehouse row 7", "base", 63, 15, 84.12],
  ["applies the wavePick fee path for a cold warehouse row 8", "fee", 124, 21, 178.2, 11],
  ["clamps wavePick for a b2 warehouse row 9", "clamp", 214.37, 214, 214.37, 218],
  ["computes wavePick for a returns warehouse row 10", "base", 14, 6, 22.1],
  ["applies the wavePick fee path for a c3 warehouse row 11", "fee", 146, 23, 201.72, 3],
  ["clamps wavePick for a bulk warehouse row 12", "clamp", 116.1, 111, 115, 115],
  ["computes wavePick for a cold warehouse row 13", "base", 28, 10, 39.32],
  ["applies the wavePick fee path for a hazmat warehouse row 14", "fee", 207, 4, 243.91, 4],
  ["clamps wavePick for a returns warehouse row 15", "clamp", 201.5, 201, 201.5, 205],
  ["computes wavePick for a b2 warehouse row 16", "base", 89, 16, 117.25],
  ["applies the wavePick fee path for a a1 warehouse row 17", "fee", 32, 9, 52.76, 9],
  ["clamps wavePick for a dock warehouse row 18", "clamp", 243.32, 240, 243.32, 244],
  ["computes wavePick for a c3 warehouse row 19", "base", 154, 21, 206.2],
  ["applies the wavePick fee path for a bulk warehouse row 20", "fee", 93, 15, 131.32, 10],
  ["clamps wavePick for a b2 warehouse row 21", "clamp", 223.6, 219, 223, 223],
  ["computes wavePick for a returns warehouse row 22", "base", 246, 13, 306.12],
  ["applies the wavePick fee path for a dock warehouse row 23", "fee", 67, 19, 105.76, 14],
  ["clamps wavePick for a a1 warehouse row 24", "clamp", 147.52, 144, 147.52, 148],
  ["computes wavePick for a bulk warehouse row 25", "base", 181, 8, 217.77],
  ["applies the wavePick fee path for a c3 warehouse row 26", "fee", 242, 14, 312.66, 9],
  ["clamps wavePick for a hazmat warehouse row 27", "clamp", 86.27, 85, 86.27, 89],
  ["computes wavePick for a cold warehouse row 28", "base", 124, 1, 142.4],
  ["applies the wavePick fee path for a b2 warehouse row 29", "fee", 193, 5, 231.02, 5],
  ["clamps wavePick for a returns warehouse row 30", "clamp", 22.8, 21, 22.8, 25],
  ["computes wavePick for a a1 warehouse row 31", "base", 96, 23, 132.72],
  ["applies the wavePick fee path for a dock warehouse row 32", "fee", 35, 17, 62.1, 12],
  ["clamps wavePick for a returns warehouse row 33", "clamp", 262.8, 261, 262.8, 265],
  ["computes wavePick for a b2 warehouse row 34", "base", 153, 5, 180.42],
  ["applies the wavePick fee path for a cold warehouse row 35", "fee", 92, 24, 137.36, 9],
  ["clamps wavePick for a hazmat warehouse row 36", "clamp", 46.37, 43, 46.37, 47],
  ["computes wavePick for a c3 warehouse row 37", "base", 210, 12, 260.1],
  ["applies the wavePick fee path for a bulk warehouse row 38", "fee", 149, 6, 183.35, 6],
  ["clamps wavePick for a a1 warehouse row 39", "clamp", 140.2, 139, 140.2, 143],
  ["computes wavePick for a dock warehouse row 40", "base", 43, 15, 59.32],
  ["applies the wavePick fee path for a hazmat warehouse row 41", "fee", 239, 21, 322.7, 6],
  ["clamps wavePick for a cold warehouse row 42", "clamp", 74.6, 71, 74.6, 75],
  ["computes wavePick for a bulk warehouse row 43", "base", 117, 9, 144.06],
  ["applies the wavePick fee path for a c3 warehouse row 44", "fee", 178, 15, 231.72, 5],
  ["clamps wavePick for a dock warehouse row 45", "clamp", 320.47, 317, 320.47, 321],
  ["computes wavePick for a a1 warehouse row 46", "base", 64, 1, 76.4],
  ["applies the wavePick fee path for a b2 warehouse row 47", "fee", 121, 8, 155.57, 8],
  ["clamps wavePick for a returns warehouse row 48", "clamp", 228.86, 228, 228.86, 232],
  ["computes wavePick for a hazmat warehouse row 49", "base", 247, 19, 322.16],
  ["applies the wavePick fee path for a cold warehouse row 50", "fee", 68, 0, 80.12, 0],
  ["clamps wavePick for a returns warehouse row 51", "clamp", 188.5, 186, 188.5, 190],
  ["computes wavePick for a b2 warehouse row 52", "base", 89, 6, 108.35],
  ["applies the wavePick fee path for a a1 warehouse row 53", "fee", 32, 24, 57.56, 9],
  ["clamps wavePick for a dock warehouse row 54", "clamp", 276.97, 272, 276, 276],
  ["computes wavePick for a c3 warehouse row 55", "base", 146, 13, 184.12],
  ["applies the wavePick fee path for a bulk warehouse row 56", "fee", 85, 7, 106.6, 2],
  ["clamps wavePick for a cold warehouse row 57", "clamp", 33.52, 35, 35, 39],
  ["computes wavePick for a hazmat warehouse row 58", "base", 207, 19, 270.96],
  ["applies the wavePick fee path for a returns warehouse row 59", "fee", 158, 10, 194.02, 0],
  ["clamps wavePick for a b2 warehouse row 60", "clamp", 116.61, 114, 116.61, 118],
  ["computes wavePick for a bulk warehouse row 61", "base", 61, 3, 74.32],
  ["applies the wavePick fee path for a c3 warehouse row 62", "fee", 122, 9, 158.96, 9],
  ["clamps wavePick for a hazmat warehouse row 63", "clamp", 231.92, 231, 231.92, 235],
  ["computes wavePick for a cold warehouse row 64", "base", 244, 21, 323.2],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(wavePick(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(wavePickWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampWavePick(a, b, extra)).toBe(expected);
    }
  });
}
