// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  affinityScore,
  affinityScoreWithFee,
  clampAffinityScore,
  factorFromBps,
} = require("./affinityScore");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes affinityScore for a home recommendations row 1", "base", 160, 7, 238],
  ["applies the affinityScore fee path for a pdp recommendations row 2", "fee", 99, 1, 144.61, 1],
  ["clamps affinityScore for a sms recommendations row 3", "clamp", 64.04, 64, 64.04, 68],
  ["computes affinityScore for a email recommendations row 4", "base", 217, 14, 335.84],
  ["applies the affinityScore fee path for a search recommendations row 5", "fee", 156, 8, 246.76, 13],
  ["clamps affinityScore for a loyalty recommendations row 6", "clamp", 138, 137, 138, 141],
  ["computes affinityScore for a cart recommendations row 7", "base", 34, 21, 60.06],
  ["applies the affinityScore fee path for a app recommendations row 8", "fee", 213, 15, 341.89, 10],
  ["clamps affinityScore for a home recommendations row 9", "clamp", 243.24, 244, 244, 248],
  ["computes affinityScore for a pdp recommendations row 10", "base", 107, 24, 179.34],
  ["applies the affinityScore fee path for a email recommendations row 11", "fee", 41, 3, 66.81, 3],
  ["clamps affinityScore for a sms recommendations row 12", "clamp", 158.94, 154, 158, 158],
  ["computes affinityScore for a pdp recommendations row 13", "base", 163, 15, 255.39],
  ["applies the affinityScore fee path for a home recommendations row 14", "fee", 224, 21, 368.16, 6],
  ["clamps affinityScore for a app recommendations row 15", "clamp", 58.54, 57, 58.54, 61],
  ["computes affinityScore for a cart recommendations row 16", "base", 98, 10, 151.04],
  ["applies the affinityScore fee path for a loyalty recommendations row 17", "fee", 159, 16, 251.86, 1],
  ["clamps affinityScore for a search recommendations row 18", "clamp", 357, 356, 357, 360],
  ["computes affinityScore for a email recommendations row 19", "base", 49, 1, 74.11],
  ["applies the affinityScore fee path for a sms recommendations row 20", "fee", 110, 7, 177.5, 12],
  ["clamps affinityScore for a cart recommendations row 21", "clamp", 201, 199, 201, 203],
  ["computes affinityScore for a app recommendations row 22", "base", 69, 6, 105.36],
  ["applies the affinityScore fee path for a search recommendations row 23", "fee", 12, 24, 29.44, 4],
  ["clamps affinityScore for a loyalty recommendations row 24", "clamp", 305.96, 302, 305.96, 306],
  ["computes affinityScore for a sms recommendations row 25", "base", 134, 11, 205.66],
  ["applies the affinityScore fee path for a email recommendations row 26", "fee", 73, 5, 115.39, 5],
  ["clamps affinityScore for a home recommendations row 27", "clamp", 29.76, 30, 30, 34],
  ["computes affinityScore for a pdp recommendations row 28", "base", 195, 17, 308.25],
  ["applies the affinityScore fee path for a cart recommendations row 29", "fee", 138, 10, 220.24, 10],
  ["clamps affinityScore for a app recommendations row 30", "clamp", 115.34, 113, 115.34, 117],
  ["computes affinityScore for a pdp recommendations row 31", "base", 107, 24, 179.34],
  ["applies the affinityScore fee path for a home recommendations row 32", "fee", 168, 5, 256.24, 10],
  ["clamps affinityScore for a email recommendations row 33", "clamp", 345.5, 342, 345.5, 346],
  ["computes affinityScore for a sms recommendations row 34", "base", 46, 18, 77.76],
  ["applies the affinityScore fee path for a loyalty recommendations row 35", "fee", 103, 0, 153.14, 5],
  ["clamps affinityScore for a search recommendations row 36", "clamp", 242.16, 240, 242.16, 244],
  ["computes affinityScore for a app recommendations row 37", "base", 221, 13, 339.71],
  ["applies the affinityScore fee path for a cart recommendations row 38", "fee", 42, 19, 75.94, 4],
  ["clamps affinityScore for a pdp recommendations row 39", "clamp", 140.61, 142, 142, 146],
  ["computes affinityScore for a home recommendations row 40", "base", 160, 7, 238],
  ["applies the affinityScore fee path for a search recommendations row 41", "fee", 196, 8, 300.16, 8],
  ["clamps affinityScore for a loyalty recommendations row 42", "clamp", 198, 193, 197, 197],
  ["computes affinityScore for a cart recommendations row 43", "base", 74, 21, 123.66],
  ["applies the affinityScore fee path for a app recommendations row 44", "fee", 13, 15, 30.89, 5],
  ["clamps affinityScore for a home recommendations row 45", "clamp", 295, 294, 295, 298],
  ["computes affinityScore for a pdp recommendations row 46", "base", 139, 1, 199.21],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(affinityScore(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(affinityScoreWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampAffinityScore(a, b, extra)).toBe(expected);
    }
  });
}
