// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 138;

function affinityScore(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function affinityScoreWithFee(amount, factor, fee) {
  return affinityScore(amount, factor) + fee;
}

function clampAffinityScore(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  affinityScore,
  affinityScoreWithFee,
  clampAffinityScore,
  factorFromBps,
};
