// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 109;

function boughtTogether(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function boughtTogetherWithFee(amount, factor, fee) {
  return boughtTogether(amount, factor) + fee;
}

function clampBoughtTogether(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  boughtTogether,
  boughtTogetherWithFee,
  clampBoughtTogether,
  factorFromBps,
};
