// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  boughtTogether,
  boughtTogetherWithFee,
  clampBoughtTogether,
  factorFromBps,
} = require("./boughtTogether");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes boughtTogether for a email recommendations row 1", "base", 201, 8, 238.17],
  ["applies the boughtTogether fee path for a sms recommendations row 2", "fee", 22, 14, 44.06, 14],
  ["clamps boughtTogether for a pdp recommendations row 3", "clamp", 107.07, 108, 108, 112],
  ["computes boughtTogether for a home recommendations row 4", "base", 144, 1, 161.4],
  ["applies the boughtTogether fee path for a app recommendations row 5", "fee", 197, 9, 244.46, 9],
  ["clamps boughtTogether for a cart recommendations row 6", "clamp", 26.32, 23, 26.32, 27],
  ["computes boughtTogether for a loyalty recommendations row 7", "base", 79, 21, 105.7],
  ["applies the boughtTogether fee path for a search recommendations row 8", "fee", 140, 2, 170.4, 12],
  ["clamps boughtTogether for a email recommendations row 9", "clamp", 245.35, 241, 245, 245],
  ["computes boughtTogether for a sms recommendations row 10", "base", 30, 12, 39.3],
  ["applies the boughtTogether fee path for a cart recommendations row 11", "fee", 210, 12, 264.1, 7],
  ["clamps boughtTogether for a app recommendations row 12", "clamp", 173.35, 172, 173.35, 176],
  ["computes boughtTogether for a search recommendations row 13", "base", 92, 24, 125.36],
  ["applies the boughtTogether fee path for a loyalty recommendations row 14", "fee", 31, 18, 50.37, 8],
  ["clamps boughtTogether for a sms recommendations row 15", "clamp", 261.8, 258, 261.8, 262],
  ["computes boughtTogether for a email recommendations row 16", "base", 153, 5, 177.42],
  ["applies the boughtTogether fee path for a home recommendations row 17", "fee", 96, 23, 142.72, 13],
  ["clamps boughtTogether for a pdp recommendations row 18", "clamp", 44.1, 45, 45, 49],
  ["computes boughtTogether for a cart recommendations row 19", "base", 218, 10, 262.42],
  ["applies the boughtTogether fee path for a app recommendations row 20", "fee", 157, 4, 194.41, 14],
  ["clamps boughtTogether for a email recommendations row 21", "clamp", 140.52, 137, 140.52, 141],
  ["computes boughtTogether for a sms recommendations row 22", "base", 182, 9, 217.76],
  ["applies the boughtTogether fee path for a pdp recommendations row 23", "fee", 243, 15, 314.32, 10],
  ["clamps boughtTogether for a home recommendations row 24", "clamp", 87.2, 84, 87.2, 88],
  ["computes boughtTogether for a app recommendations row 25", "base", 117, 4, 135.21],
  ["applies the boughtTogether fee path for a cart recommendations row 26", "fee", 178, 10, 219.82, 5],
  ["clamps boughtTogether for a loyalty recommendations row 27", "clamp", 299.75, 300, 300, 304],
  ["computes boughtTogether for a search recommendations row 28", "base", 60, 22, 81.6],
  ["applies the boughtTogether fee path for a email recommendations row 29", "fee", 129, 1, 145.9, 1],
  ["clamps boughtTogether for a sms recommendations row 30", "clamp", 222.4, 221, 222.4, 225],
  ["computes boughtTogether for a home recommendations row 31", "base", 32, 19, 43.96],
  ["applies the boughtTogether fee path for a pdp recommendations row 32", "fee", 211, 13, 268.42, 8],
  ["clamps boughtTogether for a sms recommendations row 33", "clamp", 176, 175, 176, 179],
  ["computes boughtTogether for a email recommendations row 34", "base", 89, 1, 100.9],
  ["applies the boughtTogether fee path for a search recommendations row 35", "fee", 28, 20, 44.12, 5],
  ["clamps boughtTogether for a loyalty recommendations row 36", "clamp", 257.61, 256, 257.61, 260],
  ["computes boughtTogether for a cart recommendations row 37", "base", 146, 8, 173.82],
  ["applies the boughtTogether fee path for a app recommendations row 38", "fee", 85, 2, 99.35, 2],
  ["clamps boughtTogether for a home recommendations row 39", "clamp", 51.4, 51, 51.4, 55],
  ["computes boughtTogether for a pdp recommendations row 40", "base", 219, 11, 265.8],
  ["applies the boughtTogether fee path for a loyalty recommendations row 41", "fee", 175, 17, 225.5, 2],
  ["clamps boughtTogether for a search recommendations row 42", "clamp", 315.52, 313, 315.52, 317],
  ["computes boughtTogether for a app recommendations row 43", "base", 53, 5, 63.42],
  ["applies the boughtTogether fee path for a cart recommendations row 44", "fee", 114, 11, 140.8, 1],
  ["clamps boughtTogether for a pdp recommendations row 45", "clamp", 226.75, 225, 226.75, 229],
  ["computes boughtTogether for a home recommendations row 46", "base", 240, 22, 317.4],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(boughtTogether(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(boughtTogetherWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampBoughtTogether(a, b, extra)).toBe(expected);
    }
  });
}
