// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  emailReco,
  emailRecoWithFee,
  clampEmailReco,
  factorFromBps,
} = require("./emailReco");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes emailReco for a loyalty recommendations row 1", "base", 151, 18, 226.95],
  ["applies the emailReco fee path for a search recommendations row 2", "fee", 212, 24, 337.12, 9],
  ["clamps emailReco for a app recommendations row 3", "clamp", 45.57, 45, 45.57, 49],
  ["computes emailReco for a cart recommendations row 4", "base", 90, 12, 133.1],
  ["applies the emailReco fee path for a pdp recommendations row 5", "fee", 155, 17, 243.2, 12],
  ["clamps emailReco for a home recommendations row 6", "clamp", 331, 330, 331, 334],
  ["computes emailReco for a email recommendations row 7", "base", 33, 5, 51.56],
  ["applies the emailReco fee path for a sms recommendations row 8", "fee", 94, 11, 148.72, 11],
  ["clamps emailReco for a loyalty recommendations row 9", "clamp", 219.21, 216, 219.21, 220],
  ["computes emailReco for a search recommendations row 10", "base", 204, 1, 269.12],
  ["applies the emailReco fee path for a search recommendations row 11", "fee", 172, 19, 273.12, 14],
  ["clamps emailReco for a loyalty recommendations row 12", "clamp", 163.4, 161, 163.4, 165],
  ["computes emailReco for a cart recommendations row 13", "base", 50, 7, 75],
  ["applies the emailReco fee path for a app recommendations row 14", "fee", 229, 1, 312.12, 11],
  ["clamps emailReco for a home recommendations row 15", "clamp", 266.2, 261, 265, 265],
  ["computes emailReco for a pdp recommendations row 16", "base", 115, 12, 167.85],
  ["applies the emailReco fee path for a sms recommendations row 17", "fee", 54, 6, 80.82, 1],
  ["clamps emailReco for a email recommendations row 18", "clamp", 300.91, 302, 302, 306],
  ["computes emailReco for a search recommendations row 19", "base", 180, 17, 267.2],
  ["applies the emailReco fee path for a loyalty recommendations row 20", "fee", 119, 11, 178.22, 6],
  ["clamps emailReco for a loyalty recommendations row 21", "clamp", 162.41, 157, 161, 161],
  ["computes emailReco for a search recommendations row 22", "base", 164, 1, 217.92],
  ["applies the emailReco fee path for a app recommendations row 23", "fee", 221, 8, 309.35, 3],
  ["clamps emailReco for a cart recommendations row 24", "clamp", 68.22, 65, 68.22, 69],
  ["computes emailReco for a pdp recommendations row 25", "base", 107, 19, 164.22],
  ["applies the emailReco fee path for a home recommendations row 26", "fee", 168, 0, 231.36, 10],
  ["clamps emailReco for a email recommendations row 27", "clamp", 309.5, 308, 309.5, 312],
  ["computes emailReco for a sms recommendations row 28", "base", 46, 13, 72.4],
  ["applies the emailReco fee path for a loyalty recommendations row 29", "fee", 95, 22, 161.55, 12],
  ["clamps emailReco for a search recommendations row 30", "clamp", 213.8, 209, 213, 213],
  ["computes emailReco for a sms recommendations row 31", "base", 14, 11, 27.32],
  ["applies the emailReco fee path for a email recommendations row 32", "fee", 193, 5, 267.76, 5],
  ["clamps emailReco for a home recommendations row 33", "clamp", 213, 210, 213, 214],
  ["computes emailReco for a pdp recommendations row 34", "base", 75, 17, 116],
  ["applies the emailReco fee path for a cart recommendations row 35", "fee", 10, 12, 23.9, 2],
  ["clamps emailReco for a app recommendations row 36", "clamp", 260.37, 257, 260.37, 261],
  ["computes emailReco for a search recommendations row 37", "base", 132, 24, 207.32],
  ["applies the emailReco fee path for a loyalty recommendations row 38", "fee", 71, 18, 113.95, 3],
  ["clamps emailReco for a sms recommendations row 39", "clamp", 354.4, 350, 354, 354],
  ["computes emailReco for a email recommendations row 40", "base", 185, 7, 255.9],
  ["applies the emailReco fee path for a email recommendations row 41", "fee", 49, 6, 84.17, 11],
  ["clamps emailReco for a sms recommendations row 42", "clamp", 161.9, 159, 161.9, 163],
  ["computes emailReco for a pdp recommendations row 43", "base", 171, 18, 255.95],
  ["applies the emailReco fee path for a home recommendations row 44", "fee", 232, 24, 372.32, 14],
  ["clamps emailReco for a app recommendations row 45", "clamp", 66.3, 66, 66.3, 70],
  ["computes emailReco for a cart recommendations row 46", "base", 106, 13, 156.4],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(emailReco(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(emailRecoWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampEmailReco(a, b, extra)).toBe(expected);
    }
  });
}
