// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  homepageRail,
  homepageRailWithFee,
  clampHomepageRail,
  factorFromBps,
} = require("./homepageRail");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes homepageRail for a cart recommendations row 1", "base", 114, 6, 139.52],
  ["applies the homepageRail fee path for a app recommendations row 2", "fee", 53, 0, 64.36, 0],
  ["clamps homepageRail for a search recommendations row 3", "clamp", 311.8, 310, 311.8, 314],
  ["computes homepageRail for a loyalty recommendations row 4", "base", 175, 12, 222],
  ["applies the homepageRail fee path for a sms recommendations row 5", "fee", 118, 5, 148.06, 5],
  ["clamps homepageRail for a email recommendations row 6", "clamp", 84.52, 81, 84.52, 85],
  ["computes homepageRail for a home recommendations row 7", "base", 240, 17, 314.6],
  ["applies the homepageRail fee path for a pdp recommendations row 8", "fee", 179, 11, 231.17, 6],
  ["clamps homepageRail for a cart recommendations row 9", "clamp", 144.52, 145, 145, 149],
  ["computes homepageRail for a app recommendations row 10", "base", 61, 23, 87.35],
  ["applies the homepageRail fee path for a loyalty recommendations row 11", "fee", 47, 19, 75.57, 9],
  ["clamps homepageRail for a search recommendations row 12", "clamp", 124.96, 124, 124.96, 128],
  ["computes homepageRail for a app recommendations row 13", "base", 165, 7, 201.35],
  ["applies the homepageRail fee path for a cart recommendations row 14", "fee", 226, 13, 295.5, 8],
  ["clamps homepageRail for a pdp recommendations row 15", "clamp", 69.3, 69, 69.3, 73],
  ["computes homepageRail for a home recommendations row 16", "base", 112, 24, 157.32],
  ["applies the homepageRail fee path for a email recommendations row 17", "fee", 169, 6, 215.42, 11],
  ["clamps homepageRail for a sms recommendations row 18", "clamp", 293.2, 288, 292, 292],
  ["computes homepageRail for a loyalty recommendations row 19", "base", 55, 17, 75.95],
  ["applies the homepageRail fee path for a search recommendations row 20", "fee", 116, 23, 164.6, 3],
  ["clamps homepageRail for a search recommendations row 21", "clamp", 30.8, 29, 30.8, 33],
  ["computes homepageRail for a loyalty recommendations row 22", "base", 199, 11, 249.77],
  ["applies the homepageRail fee path for a cart recommendations row 23", "fee", 138, 5, 176.46, 10],
  ["clamps homepageRail for a app recommendations row 24", "clamp", 110.72, 108, 110.72, 112],
  ["computes homepageRail for a home recommendations row 25", "base", 24, 16, 35.72],
  ["applies the homepageRail fee path for a pdp recommendations row 26", "fee", 203, 10, 252.66, 0],
  ["clamps homepageRail for a sms recommendations row 27", "clamp", 166.72, 168, 168, 172],
  ["computes homepageRail for a email recommendations row 28", "base", 81, 23, 114.35],
  ["applies the homepageRail fee path for a search recommendations row 29", "fee", 12, 19, 24.72, 4],
  ["clamps homepageRail for a loyalty recommendations row 30", "clamp", 246.75, 242, 246, 246],
  ["computes homepageRail for a app recommendations row 31", "base", 109, 1, 128.17],
  ["applies the homepageRail fee path for a cart recommendations row 32", "fee", 170, 7, 219.3, 12],
  ["clamps homepageRail for a loyalty recommendations row 33", "clamp", 296.75, 292, 296, 296],
  ["computes homepageRail for a search recommendations row 34", "base", 52, 19, 73.12],
  ["applies the homepageRail fee path for a email recommendations row 35", "fee", 113, 0, 131.56, 0],
  ["clamps homepageRail for a sms recommendations row 36", "clamp", 212.32, 208, 212, 212],
  ["computes homepageRail for a pdp recommendations row 37", "base", 235, 12, 296.4],
  ["applies the homepageRail fee path for a home recommendations row 38", "fee", 56, 18, 80.8, 3],
  ["clamps homepageRail for a app recommendations row 39", "clamp", 118.15, 119, 119, 123],
  ["computes homepageRail for a cart recommendations row 40", "base", 162, 9, 201.02],
  ["applies the homepageRail fee path for a cart recommendations row 41", "fee", 178, 0, 209.36, 5],
  ["clamps homepageRail for a app recommendations row 42", "clamp", 161.27, 156, 160, 160],
  ["computes homepageRail for a search recommendations row 43", "base", 60, 12, 79.4],
  ["applies the homepageRail fee path for a loyalty recommendations row 44", "fee", 239, 6, 293.02, 6],
  ["clamps homepageRail for a sms recommendations row 45", "clamp", 251.52, 251, 251.52, 255],
  ["computes homepageRail for a email recommendations row 46", "base", 121, 18, 162.3],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(homepageRail(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(homepageRailWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampHomepageRail(a, b, extra)).toBe(expected);
    }
  });
}
