// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  personalized,
  personalizedWithFee,
  clampPersonalized,
  factorFromBps,
} = require("./personalized");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes personalized for a search recommendations row 1", "base", 196, 23, 310.72],
  ["applies the personalized fee path for a loyalty recommendations row 2", "fee", 135, 17, 213.85, 7],
  ["clamps personalized for a cart recommendations row 3", "clamp", 112.3, 108, 112, 112],
  ["computes personalized for a app recommendations row 4", "base", 13, 5, 21.07],
  ["applies the personalized fee path for a home recommendations row 5", "fee", 200, 22, 327, 12],
  ["clamps personalized for a pdp recommendations row 6", "clamp", 209.5, 210, 210, 214],
  ["computes personalized for a sms recommendations row 7", "base", 78, 10, 115.32],
  ["applies the personalized fee path for a email recommendations row 8", "fee", 17, 4, 35.46, 9],
  ["clamps personalized for a search recommendations row 9", "clamp", 251.92, 253, 253, 257],
  ["computes personalized for a loyalty recommendations row 10", "base", 127, 19, 197.31],
  ["applies the personalized fee path for a app recommendations row 11", "fee", 117, 4, 168.46, 4],
  ["clamps personalized for a cart recommendations row 12", "clamp", 262.32, 257, 261, 261],
  ["computes personalized for a loyalty recommendations row 13", "base", 239, 16, 361.5],
  ["applies the personalized fee path for a search recommendations row 14", "fee", 60, 22, 103.6, 7],
  ["clamps personalized for a email recommendations row 15", "clamp", 170.77, 167, 170.77, 171],
  ["computes personalized for a sms recommendations row 16", "base", 182, 9, 263.26],
  ["applies the personalized fee path for a pdp recommendations row 17", "fee", 243, 15, 375.07, 10],
  ["clamps personalized for a home recommendations row 18", "clamp", 103.2, 100, 103.2, 104],
  ["computes personalized for a app recommendations row 19", "base", 125, 2, 173],
  ["applies the personalized fee path for a cart recommendations row 20", "fee", 186, 8, 280.12, 13],
  ["clamps personalized for a sms recommendations row 21", "clamp", 334.82, 332, 334.82, 336],
  ["computes personalized for a email recommendations row 22", "base", 177, 24, 282.66],
  ["applies the personalized fee path for a home recommendations row 23", "fee", 120, 17, 191.2, 7],
  ["clamps personalized for a pdp recommendations row 24", "clamp", 91.55, 87, 91, 91],
  ["computes personalized for a cart recommendations row 25", "base", 234, 6, 330.6],
  ["applies the personalized fee path for a app recommendations row 26", "fee", 173, 0, 234.82, 0],
  ["clamps personalized for a search recommendations row 27", "clamp", 176.32, 177, 177, 181],
  ["computes personalized for a loyalty recommendations row 28", "base", 55, 12, 83.3],
  ["applies the personalized fee path for a sms recommendations row 29", "fee", 230, 7, 339.3, 12],
  ["clamps personalized for a email recommendations row 30", "clamp", 228.15, 229, 229, 233],
  ["computes personalized for a loyalty recommendations row 31", "base", 87, 14, 131.76],
  ["applies the personalized fee path for a search recommendations row 32", "fee", 148, 20, 235.92, 5],
  ["clamps personalized for a app recommendations row 33", "clamp", 284.8, 280, 284, 284],
  ["computes personalized for a cart recommendations row 34", "base", 26, 8, 39.92],
  ["applies the personalized fee path for a pdp recommendations row 35", "fee", 91, 13, 144.77, 8],
  ["clamps personalized for a home recommendations row 36", "clamp", 238.56, 234, 238, 238],
  ["computes personalized for a email recommendations row 37", "base", 209, 1, 285.15],
  ["applies the personalized fee path for a sms recommendations row 38", "fee", 30, 7, 52.3, 7],
  ["clamps personalized for a loyalty recommendations row 39", "clamp", 119.5, 120, 120, 124],
  ["computes personalized for a search recommendations row 40", "base", 140, 22, 221.4],
  ["applies the personalized fee path for a home recommendations row 41", "fee", 184, 16, 290, 11],
  ["clamps personalized for a pdp recommendations row 42", "clamp", 182.12, 178, 182, 182],
  ["computes personalized for a sms recommendations row 43", "base", 62, 4, 88.56],
  ["applies the personalized fee path for a email recommendations row 44", "fee", 241, 23, 389.37, 8],
  ["clamps personalized for a search recommendations row 45", "clamp", 277.8, 273, 277, 277],
  ["computes personalized for a loyalty recommendations row 46", "base", 119, 11, 175.55],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(personalized(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(personalizedWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPersonalized(a, b, extra)).toBe(expected);
    }
  });
}
