// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 112;

function recentlyViewed(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function recentlyViewedWithFee(amount, factor, fee) {
  return recentlyViewed(amount, factor) + fee;
}

function clampRecentlyViewed(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  recentlyViewed,
  recentlyViewedWithFee,
  clampRecentlyViewed,
  factorFromBps,
};
