// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 101;

function seasonalPick(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function seasonalPickWithFee(amount, factor, fee) {
  return seasonalPick(amount, factor) + fee;
}

function clampSeasonalPick(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  seasonalPick,
  seasonalPickWithFee,
  clampSeasonalPick,
  factorFromBps,
};
