// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  similarItems,
  similarItemsWithFee,
  clampSimilarItems,
  factorFromBps,
} = require("./similarItems");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes similarItems for a loyalty recommendations row 1", "base", 183, 5, 227.92],
  ["applies the similarItems fee path for a search recommendations row 2", "fee", 244, 11, 329.2, 11],
  ["clamps similarItems for a app recommendations row 3", "clamp", 86.57, 83, 86.57, 87],
  ["computes similarItems for a cart recommendations row 4", "base", 122, 24, 175.46],
  ["applies the similarItems fee path for a pdp recommendations row 5", "fee", 187, 4, 245.01, 14],
  ["clamps similarItems for a home recommendations row 6", "clamp", 13.32, 9, 13, 13],
  ["computes similarItems for a email recommendations row 7", "base", 65, 17, 89.4],
  ["applies the similarItems fee path for a sms recommendations row 8", "fee", 126, 23, 192.92, 13],
  ["clamps similarItems for a loyalty recommendations row 9", "clamp", 218.5, 220, 220, 224],
  ["computes similarItems for a search recommendations row 10", "base", 236, 13, 312.52],
  ["applies the similarItems fee path for a search recommendations row 11", "fee", 12, 24, 22.16, 4],
  ["clamps similarItems for a loyalty recommendations row 12", "clamp", 262.67, 261, 262.67, 265],
  ["computes similarItems for a cart recommendations row 13", "base", 130, 12, 171.3],
  ["applies the similarItems fee path for a app recommendations row 14", "fee", 69, 6, 88.25, 1],
  ["clamps similarItems for a home recommendations row 15", "clamp", 26.72, 22, 26, 26],
  ["computes similarItems for a pdp recommendations row 16", "base", 195, 17, 266.2],
  ["applies the similarItems fee path for a sms recommendations row 17", "fee", 134, 11, 181.2, 6],
  ["clamps similarItems for a email recommendations row 18", "clamp", 88.52, 90, 90, 94],
  ["computes similarItems for a search recommendations row 19", "base", 20, 22, 29.2],
  ["applies the similarItems fee path for a loyalty recommendations row 20", "fee", 199, 16, 280.65, 11],
  ["clamps similarItems for a loyalty recommendations row 21", "clamp", 205.41, 204, 205.41, 208],
  ["computes similarItems for a search recommendations row 22", "base", 228, 10, 295.12],
  ["applies the similarItems fee path for a app recommendations row 23", "fee", 45, 17, 69.2, 7],
  ["clamps similarItems for a cart recommendations row 24", "clamp", 148.52, 150, 150, 154],
  ["computes similarItems for a pdp recommendations row 25", "base", 171, 3, 209.62],
  ["applies the similarItems fee path for a home recommendations row 26", "fee", 232, 9, 311.96, 14],
  ["clamps similarItems for a email recommendations row 27", "clamp", 70.15, 65, 69, 69],
  ["computes similarItems for a sms recommendations row 28", "base", 110, 22, 156.1],
  ["applies the similarItems fee path for a loyalty recommendations row 29", "fee", 159, 6, 200.75, 1],
  ["clamps similarItems for a search recommendations row 30", "clamp", 288.2, 287, 288.2, 291],
  ["computes similarItems for a sms recommendations row 31", "base", 78, 20, 109.42],
  ["applies the similarItems fee path for a email recommendations row 32", "fee", 17, 14, 32.61, 9],
  ["clamps similarItems for a home recommendations row 33", "clamp", 250, 251, 251, 255],
  ["computes similarItems for a pdp recommendations row 34", "base", 139, 1, 167.8],
  ["applies the similarItems fee path for a cart recommendations row 35", "fee", 74, 21, 110.6, 6],
  ["clamps similarItems for a app recommendations row 36", "clamp", 15.420000000000002, 16, 16, 20],
  ["computes similarItems for a search recommendations row 37", "base", 196, 8, 249.92],
  ["applies the similarItems fee path for a loyalty recommendations row 38", "fee", 135, 2, 171.35, 7],
  ["clamps similarItems for a sms recommendations row 39", "clamp", 97.7, 98, 98, 102],
  ["computes similarItems for a email recommendations row 40", "base", 9, 16, 13.15],
  ["applies the similarItems fee path for a email recommendations row 41", "fee", 113, 15, 152.42, 0],
  ["clamps similarItems for a sms recommendations row 42", "clamp", 241.6, 243, 243, 247],
  ["computes similarItems for a pdp recommendations row 43", "base", 235, 2, 285.35],
  ["applies the similarItems fee path for a home recommendations row 44", "fee", 56, 8, 75.12, 3],
  ["clamps similarItems for a app recommendations row 45", "clamp", 149.15, 146, 149.15, 150],
  ["computes similarItems for a cart recommendations row 46", "base", 170, 22, 240.7],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(similarItems(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(similarItemsWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampSimilarItems(a, b, extra)).toBe(expected);
    }
  });
}
