// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 139;

function staffPick(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function staffPickWithFee(amount, factor, fee) {
  return staffPick(amount, factor) + fee;
}

function clampStaffPick(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  staffPick,
  staffPickWithFee,
  clampStaffPick,
  factorFromBps,
};
