// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  staffPick,
  staffPickWithFee,
  clampStaffPick,
  factorFromBps,
} = require("./staffPick");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes staffPick for a pdp recommendations row 1", "base", 235, 12, 357.85],
  ["applies the staffPick fee path for a home recommendations row 2", "fee", 56, 18, 93.92, 3],
  ["clamps staffPick for a email recommendations row 3", "clamp", 161.07, 158, 161.07, 162],
  ["computes staffPick for a sms recommendations row 4", "base", 174, 6, 255.3],
  ["applies the staffPick fee path for a loyalty recommendations row 5", "fee", 231, 13, 367.12, 13],
  ["clamps staffPick for a search recommendations row 6", "clamp", 84.16, 83, 84.16, 87],
  ["computes staffPick for a app recommendations row 7", "base", 109, 1, 155.6],
  ["applies the staffPick fee path for a cart recommendations row 8", "fee", 170, 7, 263.2, 12],
  ["clamps staffPick for a pdp recommendations row 9", "clamp", 353.31, 348, 352, 352],
  ["computes staffPick for a home recommendations row 10", "base", 48, 20, 79.32],
  ["applies the staffPick fee path for a home recommendations row 11", "fee", 72, 24, 124.36, 4],
  ["clamps staffPick for a pdp recommendations row 12", "clamp", 19.27, 18, 19.27, 22],
  ["computes staffPick for a sms recommendations row 13", "base", 190, 12, 289.9],
  ["applies the staffPick fee path for a email recommendations row 14", "fee", 129, 6, 191.05, 1],
  ["clamps staffPick for a search recommendations row 15", "clamp", 97.52, 96, 97.52, 100],
  ["computes staffPick for a loyalty recommendations row 16", "base", 247, 19, 393.26],
  ["applies the staffPick fee path for a cart recommendations row 17", "fee", 186, 13, 298.72, 13],
  ["clamps staffPick for a app recommendations row 18", "clamp", 186.5, 184, 186.5, 188],
  ["computes staffPick for a home recommendations row 19", "base", 64, 1, 92.6],
  ["applies the staffPick fee path for a pdp recommendations row 20", "fee", 243, 20, 399.37, 10],
  ["clamps staffPick for a pdp recommendations row 21", "clamp", 294.45, 295, 295, 299],
  ["computes staffPick for a home recommendations row 22", "base", 16, 18, 28.12],
  ["applies the staffPick fee path for a email recommendations row 23", "fee", 73, 0, 109.47, 5],
  ["clamps staffPick for a sms recommendations row 24", "clamp", 199.3, 195, 199, 199],
  ["computes staffPick for a loyalty recommendations row 25", "base", 191, 13, 293.32],
  ["applies the staffPick fee path for a search recommendations row 26", "fee", 12, 19, 25.96, 4],
  ["clamps staffPick for a app recommendations row 27", "clamp", 98.6, 98, 98.6, 102],
  ["computes staffPick for a cart recommendations row 28", "base", 130, 7, 192.8],
  ["applies the staffPick fee path for a pdp recommendations row 29", "fee", 203, 10, 305.47, 0],
  ["clamps staffPick for a home recommendations row 30", "clamp", 41.2, 38, 41.2, 42],
  ["computes staffPick for a cart recommendations row 31", "base", 10, 17, 18.6],
  ["applies the staffPick fee path for a app recommendations row 32", "fee", 189, 11, 287.5, 1],
  ["clamps staffPick for a search recommendations row 33", "clamp", 194.76, 190, 194, 194],
  ["computes staffPick for a loyalty recommendations row 34", "base", 71, 23, 118.02],
  ["applies the staffPick fee path for a sms recommendations row 35", "fee", 14, 16, 30.7, 6],
  ["clamps staffPick for a email recommendations row 36", "clamp", 288.57, 289, 289, 293],
  ["computes staffPick for a home recommendations row 37", "base", 136, 3, 196.12],
  ["applies the staffPick fee path for a pdp recommendations row 38", "fee", 75, 22, 130.75, 7],
  ["clamps staffPick for a cart recommendations row 39", "clamp", 382.36, 383, 383, 387],
  ["computes staffPick for a app recommendations row 40", "base", 181, 13, 278.12],
  ["applies the staffPick fee path for a app recommendations row 41", "fee", 133, 5, 199.52, 5],
  ["clamps staffPick for a cart recommendations row 42", "clamp", 291, 292, 292, 296],
  ["computes staffPick for a loyalty recommendations row 43", "base", 15, 17, 26.4],
  ["applies the staffPick fee path for a search recommendations row 44", "fee", 76, 23, 134.12, 8],
  ["clamps staffPick for a email recommendations row 45", "clamp", 201.91, 197, 201, 201],
  ["computes staffPick for a sms recommendations row 46", "base", 198, 10, 298.02],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(staffPick(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(staffPickWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampStaffPick(a, b, extra)).toBe(expected);
    }
  });
}
