// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 138;

function wishlistNudge(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function wishlistNudgeWithFee(amount, factor, fee) {
  return wishlistNudge(amount, factor) + fee;
}

function clampWishlistNudge(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  wishlistNudge,
  wishlistNudgeWithFee,
  clampWishlistNudge,
  factorFromBps,
};
