// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 126;

function catalogCache(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function catalogCacheWithFee(amount, factor, fee) {
  return catalogCache(amount, factor) + fee;
}

function clampCatalogCache(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  catalogCache,
  catalogCacheWithFee,
  clampCatalogCache,
  factorFromBps,
};
