// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  categoryTree,
  categoryTreeWithFee,
  clampCategoryTree,
  factorFromBps,
} = require("./categoryTree");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes categoryTree for a ceramic catalog row 1", "base", 225, 17, 326.5],
  ["applies the categoryTree fee path for a canvas catalog row 2", "fee", 46, 23, 83.08, 8],
  ["clamps categoryTree for a linen catalog row 3", "clamp", 142.03, 143, 143, 147],
  ["computes categoryTree for a denim catalog row 4", "base", 168, 10, 233.8],
  ["applies the categoryTree fee path for a wool catalog row 5", "fee", 221, 18, 326.03, 3],
  ["clamps categoryTree for a oak catalog row 6", "clamp", 70.58, 68, 70.58, 72],
  ["computes categoryTree for a silk catalog row 7", "base", 103, 5, 140.9],
  ["applies the categoryTree fee path for a brass catalog row 8", "fee", 164, 11, 236.04, 6],
  ["clamps categoryTree for a ceramic catalog row 9", "clamp", 317.48, 317, 317.48, 321],
  ["computes categoryTree for a canvas catalog row 10", "base", 38, 0, 54.5],
  ["applies the categoryTree fee path for a oak catalog row 11", "fee", 74, 16, 117.34, 6],
  ["clamps categoryTree for a wool catalog row 12", "clamp", 22.55, 23, 23, 27],
  ["computes categoryTree for a brass catalog row 13", "base", 196, 3, 257.88],
  ["applies the categoryTree fee path for a silk catalog row 14", "fee", 135, 22, 212.45, 7],
  ["clamps categoryTree for a canvas catalog row 15", "clamp", 117.2, 114, 117.2, 118],
  ["computes categoryTree for a ceramic catalog row 16", "base", 17, 9, 29.78],
  ["applies the categoryTree fee path for a denim catalog row 17", "fee", 200, 2, 273, 12],
  ["clamps categoryTree for a linen catalog row 18", "clamp", 212.94, 208, 212, 212],
  ["computes categoryTree for a oak catalog row 19", "base", 66, 18, 101.38],
  ["applies the categoryTree fee path for a wool catalog row 20", "fee", 245, 12, 354.65, 12],
  ["clamps categoryTree for a ceramic catalog row 21", "clamp", 305, 302, 305, 306],
  ["computes categoryTree for a canvas catalog row 22", "base", 46, 13, 70.48],
  ["applies the categoryTree fee path for a linen catalog row 23", "fee", 107, 19, 170.08, 9],
  ["clamps categoryTree for a denim catalog row 24", "clamp", 217, 215, 217, 219],
  ["computes categoryTree for a wool catalog row 25", "base", 221, 8, 300.93],
  ["applies the categoryTree fee path for a oak catalog row 26", "fee", 42, 14, 69.38, 4],
  ["clamps categoryTree for a silk catalog row 27", "clamp", 153.35, 154, 154, 158],
  ["computes categoryTree for a brass catalog row 28", "base", 164, 1, 213.64],
  ["applies the categoryTree fee path for a ceramic catalog row 29", "fee", 217, 9, 311.78, 14],
  ["clamps categoryTree for a canvas catalog row 30", "clamp", 61.2, 58, 61.2, 62],
  ["computes categoryTree for a denim catalog row 31", "base", 136, 23, 208.28],
  ["applies the categoryTree fee path for a linen catalog row 32", "fee", 75, 17, 120.5, 7],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(categoryTree(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(categoryTreeWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCategoryTree(a, b, extra)).toBe(expected);
    }
  });
}
