// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 110;

function facetFilter(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function facetFilterWithFee(amount, factor, fee) {
  return facetFilter(amount, factor) + fee;
}

function clampFacetFilter(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  facetFilter,
  facetFilterWithFee,
  clampFacetFilter,
  factorFromBps,
};
