// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 115;

function productSlug(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function productSlugWithFee(amount, factor, fee) {
  return productSlug(amount, factor) + fee;
}

function clampProductSlug(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  productSlug,
  productSlugWithFee,
  clampProductSlug,
  factorFromBps,
};
