// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 130;

function relatedSkus(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function relatedSkusWithFee(amount, factor, fee) {
  return relatedSkus(amount, factor) + fee;
}

function clampRelatedSkus(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  relatedSkus,
  relatedSkusWithFee,
  clampRelatedSkus,
  factorFromBps,
};
