// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  relatedSkus,
  relatedSkusWithFee,
  clampRelatedSkus,
  factorFromBps,
} = require("./relatedSkus");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes relatedSkus for a denim catalog row 1", "base", 160, 2, 214.2],
  ["applies the relatedSkus fee path for a linen catalog row 2", "fee", 99, 21, 153.49, 1],
  ["clamps relatedSkus for a canvas catalog row 3", "clamp", 57.1, 56, 57.1, 60],
  ["computes relatedSkus for a ceramic catalog row 4", "base", 217, 9, 304.63],
  ["applies the relatedSkus fee path for a brass catalog row 5", "fee", 156, 3, 223.48, 13],
  ["clamps relatedSkus for a silk catalog row 6", "clamp", 147.4, 145, 147.4, 149],
  ["computes relatedSkus for a oak catalog row 7", "base", 34, 16, 52.64],
  ["applies the relatedSkus fee path for a wool catalog row 8", "fee", 213, 10, 311.2, 10],
  ["clamps relatedSkus for a denim catalog row 9", "clamp", 219.4, 219, 219.4, 223],
  ["computes relatedSkus for a linen catalog row 10", "base", 107, 19, 162.43],
  ["applies the relatedSkus fee path for a ceramic catalog row 11", "fee", 73, 15, 113.85, 5],
  ["clamps relatedSkus for a canvas catalog row 12", "clamp", 202.34, 203, 203, 207],
  ["computes relatedSkus for a linen catalog row 13", "base", 195, 2, 260.4],
  ["applies the relatedSkus fee path for a denim catalog row 14", "fee", 16, 8, 33.08, 8],
  ["clamps relatedSkus for a wool catalog row 15", "clamp", 104.74, 102, 104.74, 106],
  ["computes relatedSkus for a oak catalog row 16", "base", 130, 22, 200.6],
  ["applies the relatedSkus fee path for a silk catalog row 17", "fee", 191, 3, 260.03, 3],
  ["clamps relatedSkus for a brass catalog row 18", "clamp", 19.68, 18, 19.68, 22],
  ["computes relatedSkus for a ceramic catalog row 19", "base", 81, 13, 118.83],
  ["applies the relatedSkus fee path for a canvas catalog row 20", "fee", 142, 19, 228.58, 14],
  ["clamps relatedSkus for a oak catalog row 21", "clamp", 253.48, 250, 253.48, 254],
  ["computes relatedSkus for a wool catalog row 22", "base", 101, 18, 152.48],
  ["applies the relatedSkus fee path for a brass catalog row 23", "fee", 44, 11, 71.04, 6],
  ["clamps relatedSkus for a silk catalog row 24", "clamp", 307.05, 302, 306, 306],
  ["computes relatedSkus for a canvas catalog row 25", "base", 166, 23, 256.98],
  ["applies the relatedSkus fee path for a ceramic catalog row 26", "fee", 105, 17, 164.35, 7],
  ["clamps relatedSkus for a denim catalog row 27", "clamp", 69.2, 68, 69.2, 72],
  ["computes relatedSkus for a linen catalog row 28", "base", 227, 4, 307.18],
  ["applies the relatedSkus fee path for a oak catalog row 29", "fee", 170, 22, 273.4, 12],
  ["clamps relatedSkus for a wool catalog row 30", "clamp", 163.14, 160, 163.14, 164],
  ["computes relatedSkus for a linen catalog row 31", "base", 43, 0, 58.9],
  ["applies the relatedSkus fee path for a denim catalog row 32", "fee", 104, 6, 150.44, 6],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(relatedSkus(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(relatedSkusWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampRelatedSkus(a, b, extra)).toBe(expected);
    }
  });
}
