// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 103;

function variantSku(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function variantSkuWithFee(amount, factor, fee) {
  return variantSku(amount, factor) + fee;
}

function clampVariantSku(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  variantSku,
  variantSkuWithFee,
  clampVariantSku,
  factorFromBps,
};
