// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  accountLock,
  accountLockWithFee,
  clampAccountLock,
  factorFromBps,
} = require("./accountLock");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes accountLock for a guest users row 1", "base", 34, 11, 43.82],
  ["applies the accountLock fee path for a buyer users row 2", "fee", 213, 5, 261.21000000000004, 10],
  ["clamps accountLock for a support users row 3", "clamp", 214.6, 211, 214.6, 215],
  ["computes accountLock for a auditor users row 4", "base", 95, 17, 124.55],
  ["applies the accountLock fee path for a owner users row 5", "fee", 38, 10, 48.36, 0],
  ["clamps accountLock for a admin users row 6", "clamp", 250.72, 252, 252, 256],
  ["computes accountLock for a shopper users row 7", "base", 160, 22, 216.4],
  ["applies the accountLock fee path for a reseller users row 8", "fee", 99, 16, 129.72, 1],
  ["clamps accountLock for a guest users row 9", "clamp", 52.82, 51, 52.82, 55],
  ["computes accountLock for a buyer users row 10", "base", 221, 3, 256.15],
  ["applies the accountLock fee path for a auditor users row 11", "fee", 127, 19, 182.37, 14],
  ["clamps accountLock for a support users row 12", "clamp", 211.56, 211, 211.56, 215],
  ["computes accountLock for a buyer users row 13", "base", 245, 7, 293.55],
  ["applies the accountLock fee path for a guest users row 14", "fee", 66, 13, 97.5, 13],
  ["clamps accountLock for a reseller users row 15", "clamp", 170.3, 170, 170.3, 174],
  ["computes accountLock for a shopper users row 16", "base", 192, 24, 263.12],
  ["applies the accountLock fee path for a admin users row 17", "fee", 9, 6, 13.62, 1],
  ["clamps accountLock for a owner users row 18", "clamp", 91.8, 87, 91, 91],
  ["computes accountLock for a auditor users row 19", "base", 135, 17, 176.15],
  ["applies the accountLock fee path for a support users row 20", "fee", 196, 23, 274.6, 8],
  ["clamps accountLock for a support users row 21", "clamp", 290.92, 288, 290.92, 292],
  ["computes accountLock for a auditor users row 22", "base", 183, 0, 206.96],
  ["applies the accountLock fee path for a guest users row 23", "fee", 122, 19, 170.82, 9],
  ["clamps accountLock for a buyer users row 24", "clamp", 80.25, 76, 80, 80],
  ["computes accountLock for a shopper users row 25", "base", 8, 5, 11.36],
  ["applies the accountLock fee path for a reseller users row 26", "fee", 187, 24, 270.32, 14],
  ["clamps accountLock for a owner users row 27", "clamp", 163.8, 164, 164, 168],
  ["computes accountLock for a admin users row 28", "base", 65, 12, 82.6],
  ["applies the accountLock fee path for a support users row 29", "fee", 236, 8, 288.2, 3],
  ["clamps accountLock for a auditor users row 30", "clamp", 198.5, 200, 200, 204],
  ["computes accountLock for a buyer users row 31", "base", 93, 15, 120.11],
  ["applies the accountLock fee path for a guest users row 32", "fee", 154, 21, 217.82, 11],
  ["clamps accountLock for a auditor users row 33", "clamp", 244.1, 245, 245, 249],
  ["computes accountLock for a support users row 34", "base", 36, 8, 45.2],
  ["applies the accountLock fee path for a admin users row 35", "fee", 97, 14, 138.22, 14],
  ["clamps accountLock for a owner users row 36", "clamp", 213.56, 209, 213, 213],
  ["computes accountLock for a reseller users row 37", "base", 219, 1, 249.47],
  ["applies the accountLock fee path for a shopper users row 38", "fee", 40, 7, 51.6, 2],
  ["clamps accountLock for a buyer users row 39", "clamp", 109.65, 110, 110, 114],
  ["computes accountLock for a guest users row 40", "base", 146, 23, 199.1],
  ["applies the accountLock fee path for a guest users row 41", "fee", 162, 14, 210.12, 4],
  ["clamps accountLock for a buyer users row 42", "clamp", 120.2, 121, 121, 125],
  ["computes accountLock for a support users row 43", "base", 44, 1, 51.72],
  ["applies the accountLock fee path for a auditor users row 44", "fee", 223, 20, 301.36, 5],
  ["clamps accountLock for a owner users row 45", "clamp", 209.5, 208, 209.5, 212],
  ["computes accountLock for a admin users row 46", "base", 105, 7, 126.95],
  ["applies the accountLock fee path for a shopper users row 47", "fee", 48, 0, 65.75999999999999, 10],
  ["clamps accountLock for a reseller users row 48", "clamp", 301.37, 297, 301, 301],
  ["computes accountLock for a guest users row 49", "base", 170, 12, 212.8],
  ["applies the accountLock fee path for a buyer users row 50", "fee", 109, 6, 141.62, 11],
  ["clamps accountLock for a reseller users row 51", "clamp", 211.7, 208, 211.7, 212],
  ["computes accountLock for a shopper users row 52", "base", 216, 3, 250.4],
  ["applies the accountLock fee path for a admin users row 53", "fee", 33, 10, 52.26, 10],
  ["clamps accountLock for a owner users row 54", "clamp", 122.32, 120, 122.32, 124],
  ["computes accountLock for a auditor users row 55", "base", 151, 23, 205.85],
  ["applies the accountLock fee path for a support users row 56", "fee", 212, 4, 256.91999999999996, 9],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(accountLock(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(accountLockWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampAccountLock(a, b, extra)).toBe(expected);
    }
  });
}
