// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 125;

function addressBook(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function addressBookWithFee(amount, factor, fee) {
  return addressBook(amount, factor) + fee;
}

function clampAddressBook(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  addressBook,
  addressBookWithFee,
  clampAddressBook,
  factorFromBps,
};
