// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  addressBook,
  addressBookWithFee,
  clampAddressBook,
  factorFromBps,
} = require("./addressBook");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes addressBook for a admin users row 1", "base", 33, 10, 50.55],
  ["applies the addressBook fee path for a owner users row 2", "fee", 94, 16, 149.54, 11],
  ["clamps addressBook for a reseller users row 3", "clamp", 236.85, 232, 236, 236],
  ["computes addressBook for a shopper users row 4", "base", 216, 3, 282.48],
  ["applies the addressBook fee path for a buyer users row 5", "fee", 29, 11, 51.44, 6],
  ["clamps addressBook for a guest users row 6", "clamp", 133.8, 132, 133.8, 136],
  ["computes addressBook for a auditor users row 7", "base", 151, 23, 229.48],
  ["applies the addressBook fee path for a support users row 8", "fee", 212, 4, 288.48, 9],
  ["clamps addressBook for a admin users row 9", "clamp", 37.25, 38, 38, 42],
  ["computes addressBook for a owner users row 10", "base", 86, 18, 128.98],
  ["applies the addressBook fee path for a guest users row 11", "fee", 42, 24, 72.58, 4],
  ["clamps addressBook for a buyer users row 12", "clamp", 325.03, 320, 324, 324],
  ["computes addressBook for a support users row 13", "base", 164, 11, 229.04],
  ["applies the addressBook fee path for a auditor users row 14", "fee", 103, 5, 144.9, 5],
  ["clamps addressBook for a owner users row 15", "clamp", 73.08, 72, 73.08, 76],
  ["computes addressBook for a admin users row 16", "base", 225, 17, 325.5],
  ["applies the addressBook fee path for a shopper users row 17", "fee", 168, 10, 242.8, 10],
  ["clamps addressBook for a reseller users row 18", "clamp", 145.03, 142, 145.03, 146],
  ["computes addressBook for a guest users row 19", "base", 34, 1, 48.84],
  ["applies the addressBook fee path for a buyer users row 20", "fee", 213, 20, 324.85, 10],
  ["clamps addressBook for a admin users row 21", "clamp", 116.73, 112, 116, 116],
  ["computes addressBook for a owner users row 22", "base", 142, 14, 203.38],
  ["applies the addressBook fee path for a reseller users row 23", "fee", 203, 20, 300.35, 0],
  ["clamps addressBook for a shopper users row 24", "clamp", 38.24, 34, 38, 38],
  ["computes addressBook for a buyer users row 25", "base", 77, 9, 109.18],
  ["applies the addressBook fee path for a guest users row 26", "fee", 138, 15, 209.2, 10],
  ["clamps addressBook for a auditor users row 27", "clamp", 295.54, 295, 295.54, 299],
  ["computes addressBook for a support users row 28", "base", 20, 2, 31.4],
  ["applies the addressBook fee path for a admin users row 29", "fee", 73, 10, 109.55, 5],
  ["clamps addressBook for a owner users row 30", "clamp", 197.94, 193, 197, 197],
  ["computes addressBook for a shopper users row 31", "base", 232, 24, 351.68],
  ["applies the addressBook fee path for a reseller users row 32", "fee", 171, 18, 263.53, 13],
  ["clamps addressBook for a owner users row 33", "clamp", 156.7, 155, 156.7, 159],
  ["computes addressBook for a admin users row 34", "base", 49, 6, 70.19],
  ["applies the addressBook fee path for a support users row 35", "fee", 228, 0, 301, 10],
  ["clamps addressBook for a auditor users row 36", "clamp", 247.48, 244, 247.48, 248],
  ["computes addressBook for a guest users row 37", "base", 106, 13, 152.28],
  ["applies the addressBook fee path for a buyer users row 38", "fee", 45, 7, 72.4, 7],
  ["clamps addressBook for a shopper users row 39", "clamp", 290.24, 286, 290, 290],
  ["computes addressBook for a reseller users row 40", "base", 163, 20, 242.35],
  ["applies the addressBook fee path for a auditor users row 41", "fee", 135, 22, 211.45, 7],
  ["clamps addressBook for a support users row 42", "clamp", 258.88, 255, 258.88, 259],
  ["computes addressBook for a buyer users row 43", "base", 13, 10, 23.55],
  ["applies the addressBook fee path for a guest users row 44", "fee", 74, 16, 116.34, 6],
  ["clamps addressBook for a reseller users row 45", "clamp", 209.94, 207, 209.94, 211],
  ["computes addressBook for a shopper users row 46", "base", 200, 2, 260],
  ["applies the addressBook fee path for a admin users row 47", "fee", 17, 9, 37.78, 9],
  ["clamps addressBook for a owner users row 48", "clamp", 114.2, 113, 114.2, 117],
  ["computes addressBook for a auditor users row 49", "base", 127, 24, 195.23],
  ["applies the addressBook fee path for a support users row 50", "fee", 188, 5, 250.4, 0],
  ["clamps addressBook for a owner users row 51", "clamp", 70.48, 67, 70.48, 71],
  ["computes addressBook for a admin users row 52", "base", 225, 7, 303],
  ["applies the addressBook fee path for a shopper users row 53", "fee", 168, 0, 226, 10],
  ["clamps addressBook for a reseller users row 54", "clamp", 163.08, 158, 162, 162],
  ["computes addressBook for a guest users row 55", "base", 42, 14, 64.38],
  ["applies the addressBook fee path for a buyer users row 56", "fee", 221, 8, 302.93, 3],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(addressBook(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(addressBookWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampAddressBook(a, b, extra)).toBe(expected);
    }
  });
}
