// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  avatarUpload,
  avatarUploadWithFee,
  clampAvatarUpload,
  factorFromBps,
} = require("./avatarUpload");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes avatarUpload for a guest users row 1", "base", 210, 7, 308.3],
  ["applies the avatarUpload fee path for a buyer users row 2", "fee", 149, 1, 218.13, 6],
  ["clamps avatarUpload for a support users row 3", "clamp", 153.6, 149, 153, 153],
  ["computes avatarUpload for a auditor users row 4", "base", 31, 13, 54.19],
  ["applies the avatarUpload fee path for a owner users row 5", "fee", 214, 6, 322.88, 11],
  ["clamps avatarUpload for a admin users row 6", "clamp", 214.08, 214, 214.08, 218],
  ["computes avatarUpload for a shopper users row 7", "base", 96, 18, 155.84],
  ["applies the avatarUpload fee path for a reseller users row 8", "fee", 35, 12, 71.8, 12],
  ["clamps avatarUpload for a guest users row 9", "clamp", 316.38, 313, 316.38, 317],
  ["computes avatarUpload for a buyer users row 10", "base", 157, 24, 259.2],
  ["applies the avatarUpload fee path for a auditor users row 11", "fee", 175, 22, 286.5, 2],
  ["clamps avatarUpload for a support users row 12", "clamp", 337.04, 334, 337.04, 338],
  ["computes avatarUpload for a buyer users row 13", "base", 53, 10, 85.38],
  ["applies the avatarUpload fee path for a guest users row 14", "fee", 114, 16, 182.28, 1],
  ["clamps avatarUpload for a reseller users row 15", "clamp", 289.03, 287, 289.03, 291],
  ["computes avatarUpload for a shopper users row 16", "base", 240, 2, 339.2],
  ["applies the avatarUpload fee path for a admin users row 17", "fee", 57, 9, 94.65, 4],
  ["clamps avatarUpload for a owner users row 18", "clamp", 184.18, 184, 184.18, 188],
  ["computes avatarUpload for a auditor users row 19", "base", 183, 20, 293.48],
  ["applies the avatarUpload fee path for a support users row 20", "fee", 244, 1, 353.28, 11],
  ["clamps avatarUpload for a support users row 21", "clamp", 86.4, 81, 85, 85],
  ["computes avatarUpload for a auditor users row 22", "base", 231, 3, 329.09],
  ["applies the avatarUpload fee path for a guest users row 23", "fee", 170, 22, 288.6, 12],
  ["clamps avatarUpload for a buyer users row 24", "clamp", 170.68, 172, 172, 176],
  ["computes avatarUpload for a shopper users row 25", "base", 56, 8, 88.64],
  ["applies the avatarUpload fee path for a reseller users row 26", "fee", 235, 2, 334.3, 2],
  ["clamps avatarUpload for a owner users row 27", "clamp", 281.18, 279, 281.18, 283],
  ["computes avatarUpload for a admin users row 28", "base", 113, 15, 178.63],
  ["applies the avatarUpload fee path for a support users row 29", "fee", 44, 11, 78.68, 6],
  ["clamps avatarUpload for a auditor users row 30", "clamp", 321.43, 320, 321.43, 324],
  ["computes avatarUpload for a buyer users row 31", "base", 141, 18, 225.14],
  ["applies the avatarUpload fee path for a guest users row 32", "fee", 202, 24, 345.2, 14],
  ["clamps avatarUpload for a auditor users row 33", "clamp", 39.43, 38, 39.43, 42],
  ["computes avatarUpload for a support users row 34", "base", 84, 11, 131.48],
  ["applies the avatarUpload fee path for a admin users row 35", "fee", 145, 17, 231.85, 2],
  ["clamps avatarUpload for a owner users row 36", "clamp", 333.54, 334, 334, 338],
  ["computes avatarUpload for a reseller users row 37", "base", 27, 4, 45.8],
  ["applies the avatarUpload fee path for a shopper users row 38", "fee", 88, 10, 141.48, 5],
  ["clamps avatarUpload for a buyer users row 39", "clamp", 215.48, 213, 215.48, 217],
  ["computes avatarUpload for a guest users row 40", "base", 194, 1, 273.78],
  ["applies the avatarUpload fee path for a guest users row 41", "fee", 210, 17, 336.3, 7],
  ["clamps avatarUpload for a buyer users row 42", "clamp", 226.03, 225, 226.03, 229],
  ["computes avatarUpload for a support users row 43", "base", 92, 4, 136.8],
  ["applies the avatarUpload fee path for a auditor users row 44", "fee", 31, 23, 65.28999999999999, 8],
  ["clamps avatarUpload for a owner users row 45", "clamp", 335.28, 331, 335, 335],
  ["computes avatarUpload for a admin users row 46", "base", 153, 10, 231.38],
  ["applies the avatarUpload fee path for a shopper users row 47", "fee", 96, 3, 154.44, 13],
  ["clamps avatarUpload for a reseller users row 48", "clamp", 60.3, 61, 61, 65],
  ["computes avatarUpload for a guest users row 49", "base", 218, 15, 337.18],
  ["applies the avatarUpload fee path for a buyer users row 50", "fee", 157, 9, 249.65, 14],
  ["clamps avatarUpload for a reseller users row 51", "clamp", 281.08, 282, 282, 286],
  ["computes avatarUpload for a shopper users row 52", "base", 24, 6, 42.08],
  ["applies the avatarUpload fee path for a admin users row 53", "fee", 81, 13, 141.69, 13],
  ["clamps avatarUpload for a owner users row 54", "clamp", 230.1, 226, 230, 230],
  ["computes avatarUpload for a auditor users row 55", "base", 199, 1, 280.63],
  ["applies the avatarUpload fee path for a support users row 56", "fee", 20, 7, 48.6, 12],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(avatarUpload(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(avatarUploadWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampAvatarUpload(a, b, extra)).toBe(expected);
    }
  });
}
