// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 139;

function closeAccount(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function closeAccountWithFee(amount, factor, fee) {
  return closeAccount(amount, factor) + fee;
}

function clampCloseAccount(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  closeAccount,
  closeAccountWithFee,
  clampCloseAccount,
  factorFromBps,
};
