// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  consentFlag,
  consentFlagWithFee,
  clampConsentFlag,
  factorFromBps,
} = require("./consentFlag");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes consentFlag for a owner users row 1", "base", 142, 9, 192.86],
  ["applies the consentFlag fee path for a admin users row 2", "fee", 81, 3, 119.87, 13],
  ["clamps consentFlag for a shopper users row 3", "clamp", 38.8, 37, 38.8, 41],
  ["computes consentFlag for a reseller users row 4", "base", 203, 15, 286.17],
  ["applies the consentFlag fee path for a guest users row 5", "fee", 138, 10, 198.92, 10],
  ["clamps consentFlag for a buyer users row 6", "clamp", 102.56, 101, 102.56, 105],
  ["computes consentFlag for a support users row 7", "base", 20, 22, 33.2],
  ["applies the consentFlag fee path for a auditor users row 8", "fee", 199, 16, 293.6, 11],
  ["clamps consentFlag for a owner users row 9", "clamp", 185.9, 183, 185.9, 187],
  ["computes consentFlag for a admin users row 10", "base", 73, 5, 98.17],
  ["applies the consentFlag fee path for a reseller users row 11", "fee", 195, 22, 295.7, 7],
  ["clamps consentFlag for a shopper users row 12", "clamp", 21.32, 22, 22, 26],
  ["computes consentFlag for a admin users row 13", "base", 73, 10, 101.82],
  ["applies the consentFlag fee path for a owner users row 14", "fee", 134, 16, 197.6, 6],
  ["clamps consentFlag for a auditor users row 15", "clamp", 285.77, 283, 285.77, 287],
  ["computes consentFlag for a support users row 16", "base", 12, 4, 19.36],
  ["applies the consentFlag fee path for a buyer users row 17", "fee", 69, 11, 98.15, 1],
  ["clamps consentFlag for a guest users row 18", "clamp", 186.3, 185, 186.3, 189],
  ["computes consentFlag for a reseller users row 19", "base", 203, 20, 296.32],
  ["applies the consentFlag fee path for a shopper users row 20", "fee", 24, 1, 35, 1],
  ["clamps consentFlag for a shopper users row 21", "clamp", 82.72, 79, 82.72, 83],
  ["computes consentFlag for a reseller users row 22", "base", 235, 7, 311.85],
  ["applies the consentFlag fee path for a owner users row 23", "fee", 174, 1, 222.5, 1],
  ["clamps consentFlag for a admin users row 24", "clamp", 169.72, 165, 169, 169],
  ["computes consentFlag for a support users row 25", "base", 52, 14, 75.76],
  ["applies the consentFlag fee path for a auditor users row 26", "fee", 231, 8, 321.92, 13],
  ["clamps consentFlag for a guest users row 27", "clamp", 215.2, 216, 216, 220],
  ["computes consentFlag for a buyer users row 28", "base", 109, 21, 162.05],
  ["applies the consentFlag fee path for a shopper users row 29", "fee", 48, 15, 80.72, 10],
  ["clamps consentFlag for a reseller users row 30", "clamp", 303.91, 304, 304, 308],
  ["computes consentFlag for a admin users row 31", "base", 145, 22, 215.7],
  ["applies the consentFlag fee path for a owner users row 32", "fee", 206, 3, 268.62, 3],
  ["clamps consentFlag for a reseller users row 33", "clamp", 37.91, 38, 38, 42],
  ["computes consentFlag for a shopper users row 34", "base", 88, 15, 126.32],
  ["applies the consentFlag fee path for a buyer users row 35", "fee", 141, 23, 224.27, 13],
  ["clamps consentFlag for a guest users row 36", "clamp", 264.56, 261, 264.56, 265],
  ["computes consentFlag for a auditor users row 37", "base", 23, 10, 34.82],
  ["applies the consentFlag fee path for a support users row 38", "fee", 84, 16, 122.6, 1],
  ["clamps consentFlag for a admin users row 39", "clamp", 205.76, 205, 205.76, 209],
  ["computes consentFlag for a owner users row 40", "base", 198, 5, 259.42],
  ["applies the consentFlag fee path for a owner users row 41", "fee", 110, 2, 154.6, 12],
  ["clamps consentFlag for a admin users row 42", "clamp", 72.05, 73, 73, 77],
  ["computes consentFlag for a shopper users row 43", "base", 232, 14, 324.16],
  ["applies the consentFlag fee path for a reseller users row 44", "fee", 171, 8, 242.72, 13],
  ["clamps consentFlag for a guest users row 45", "clamp", 136.62, 137, 137, 141],
  ["computes consentFlag for a buyer users row 46", "base", 45, 22, 69.7],
  ["applies the consentFlag fee path for a support users row 47", "fee", 228, 15, 330.92, 10],
  ["clamps consentFlag for a auditor users row 48", "clamp", 226.11, 224, 226.11, 228],
  ["computes consentFlag for a owner users row 49", "base", 102, 4, 134.56],
  ["applies the consentFlag fee path for a admin users row 50", "fee", 41, 23, 67.27, 3],
  ["clamps consentFlag for a auditor users row 51", "clamp", 270.65, 271, 271, 275],
  ["computes consentFlag for a support users row 52", "base", 20, 17, 32.2],
  ["applies the consentFlag fee path for a buyer users row 53", "fee", 77, 24, 126.96, 9],
  ["clamps consentFlag for a guest users row 54", "clamp", 185.02, 180, 184, 184],
  ["computes consentFlag for a reseller users row 55", "base", 203, 10, 276.02],
  ["applies the consentFlag fee path for a shopper users row 56", "fee", 24, 16, 38.6, 1],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(consentFlag(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(consentFlagWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampConsentFlag(a, b, extra)).toBe(expected);
    }
  });
}
