// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 124;

function consentFlag(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function consentFlagWithFee(amount, factor, fee) {
  return consentFlag(amount, factor) + fee;
}

function clampConsentFlag(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  consentFlag,
  consentFlagWithFee,
  clampConsentFlag,
  factorFromBps,
};
