// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  gdprExport,
  gdprExportWithFee,
  clampGdprExport,
  factorFromBps,
} = require("./gdprExport");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes gdprExport for a auditor users row 1", "base", 55, 22, 93.35],
  ["applies the gdprExport fee path for a support users row 2", "fee", 116, 3, 170.08, 3],
  ["clamps gdprExport for a buyer users row 3", "clamp", 259.85, 256, 259.85, 260],
  ["computes gdprExport for a guest users row 4", "base", 234, 16, 360.34],
  ["applies the gdprExport fee path for a reseller users row 5", "fee", 59, 21, 105.04, 6],
  ["clamps gdprExport for a shopper users row 6", "clamp", 173.4, 169, 173, 173],
  ["computes gdprExport for a admin users row 7", "base", 177, 9, 261.88],
  ["applies the gdprExport fee path for a owner users row 8", "fee", 238, 15, 369, 5],
  ["clamps gdprExport for a auditor users row 9", "clamp", 78.73, 80, 80, 84],
  ["computes gdprExport for a support users row 10", "base", 108, 5, 158.2],
  ["applies the gdprExport fee path for a support users row 11", "fee", 188, 10, 279.6, 0],
  ["clamps gdprExport for a auditor users row 12", "clamp", 183.53, 182, 183.53, 186],
  ["computes gdprExport for a guest users row 13", "base", 66, 23, 111.28],
  ["applies the gdprExport fee path for a buyer users row 14", "fee", 245, 17, 391.4, 12],
  ["clamps gdprExport for a shopper users row 15", "clamp", 286.48, 281, 285, 285],
  ["computes gdprExport for a reseller users row 16", "base", 131, 3, 187.78],
  ["applies the gdprExport fee path for a owner users row 17", "fee", 70, 22, 118.9, 2],
  ["clamps gdprExport for a admin users row 18", "clamp", 17.59, 19, 19, 23],
  ["computes gdprExport for a support users row 19", "base", 196, 8, 287.28],
  ["applies the gdprExport fee path for a auditor users row 20", "fee", 135, 2, 198.95, 7],
  ["clamps gdprExport for a auditor users row 21", "clamp", 183.74, 179, 183, 183],
  ["computes gdprExport for a support users row 22", "base", 180, 17, 280.6],
  ["applies the gdprExport fee path for a buyer users row 23", "fee", 237, 24, 387.83, 4],
  ["clamps gdprExport for a guest users row 24", "clamp", 89.2, 86, 89.2, 90],
  ["computes gdprExport for a reseller users row 25", "base", 123, 10, 185.35],
  ["applies the gdprExport fee path for a shopper users row 26", "fee", 184, 16, 295.84, 11],
  ["clamps gdprExport for a admin users row 27", "clamp", 387.78, 386, 387.78, 390],
  ["computes gdprExport for a owner users row 28", "base", 62, 4, 93.18],
  ["applies the gdprExport fee path for a auditor users row 29", "fee", 111, 13, 184.28, 13],
  ["clamps gdprExport for a support users row 30", "clamp", 274.88, 270, 274, 274],
  ["computes gdprExport for a owner users row 31", "base", 158, 20, 251.9],
  ["applies the gdprExport fee path for a admin users row 32", "fee", 97, 14, 165.53, 14],
  ["clamps gdprExport for a shopper users row 33", "clamp", 61.8, 62, 62, 66],
  ["computes gdprExport for a reseller users row 34", "base", 219, 1, 304.84],
  ["applies the gdprExport fee path for a guest users row 35", "fee", 154, 21, 258.24, 11],
  ["clamps gdprExport for a buyer users row 36", "clamp", 144.5, 145, 145, 149],
  ["computes gdprExport for a support users row 37", "base", 36, 8, 58.48],
  ["applies the gdprExport fee path for a auditor users row 38", "fee", 215, 2, 313.55, 12],
  ["clamps gdprExport for a owner users row 39", "clamp", 241.5, 241, 241.5, 245],
  ["computes gdprExport for a admin users row 40", "base", 89, 16, 141.39],
  ["applies the gdprExport fee path for a admin users row 41", "fee", 65, 22, 121.05, 12],
  ["clamps gdprExport for a owner users row 42", "clamp", 181.88, 179, 181.88, 183],
  ["computes gdprExport for a reseller users row 43", "base", 187, 9, 276.28],
  ["applies the gdprExport fee path for a shopper users row 44", "fee", 8, 15, 19, 0],
  ["clamps gdprExport for a buyer users row 45", "clamp", 101.38, 101, 101.38, 105],
  ["computes gdprExport for a guest users row 46", "base", 122, 4, 176.58],
  ["applies the gdprExport fee path for a auditor users row 47", "fee", 183, 10, 282.35, 10],
  ["clamps gdprExport for a support users row 48", "clamp", 372.44, 373, 373, 377],
  ["computes gdprExport for a admin users row 49", "base", 57, 24, 97.63],
  ["applies the gdprExport fee path for a owner users row 50", "fee", 118, 5, 177.2, 5],
  ["clamps gdprExport for a shopper users row 51", "clamp", 326.68, 325, 326.68, 329],
  ["computes gdprExport for a reseller users row 52", "base", 155, 7, 227.1],
  ["applies the gdprExport fee path for a owner users row 53", "fee", 94, 1, 145.84, 11],
  ["clamps gdprExport for a admin users row 54", "clamp", 59.15, 56, 59.15, 60],
  ["computes gdprExport for a support users row 55", "base", 212, 14, 322.88],
  ["applies the gdprExport fee path for a auditor users row 56", "fee", 151, 8, 230.93, 8],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(gdprExport(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(gdprExportWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampGdprExport(a, b, extra)).toBe(expected);
    }
  });
}
