// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 126;

function loyaltyTier(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function loyaltyTierWithFee(amount, factor, fee) {
  return loyaltyTier(amount, factor) + fee;
}

function clampLoyaltyTier(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  loyaltyTier,
  loyaltyTierWithFee,
  clampLoyaltyTier,
  factorFromBps,
};
