// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 130;

function notificationPref(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function notificationPrefWithFee(amount, factor, fee) {
  return notificationPref(amount, factor) + fee;
}

function clampNotificationPref(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  notificationPref,
  notificationPrefWithFee,
  clampNotificationPref,
  factorFromBps,
};
