// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  orgMember,
  orgMemberWithFee,
  clampOrgMember,
  factorFromBps,
} = require("./orgMember");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes orgMember for a guest users row 1", "base", 34, 6, 38.4],
  ["applies the orgMember fee path for a buyer users row 2", "fee", 213, 0, 232.52, 10],
  ["clamps orgMember for a support users row 3", "clamp", 190.32, 189, 190.32, 193],
  ["computes orgMember for a auditor users row 4", "base", 95, 12, 111.2],
  ["applies the orgMember fee path for a owner users row 5", "fee", 38, 5, 42.42, 0],
  ["clamps orgMember for a admin users row 6", "clamp", 279.76, 277, 279.76, 281],
  ["computes orgMember for a shopper users row 7", "base", 160, 17, 194.6],
  ["applies the orgMember fee path for a reseller users row 8", "fee", 99, 11, 115.85, 1],
  ["clamps orgMember for a guest users row 9", "clamp", 43.36, 44, 44, 48],
  ["computes orgMember for a buyer users row 10", "base", 221, 23, 281.67],
  ["applies the orgMember fee path for a auditor users row 11", "fee", 159, 6, 176.9, 1],
  ["clamps orgMember for a support users row 12", "clamp", 256.2, 254, 256.2, 258],
  ["computes orgMember for a buyer users row 13", "base", 37, 19, 46.51],
  ["applies the orgMember fee path for a guest users row 14", "fee", 98, 0, 102.92, 0],
  ["clamps orgMember for a reseller users row 15", "clamp", 177.67, 177, 177.67, 181],
  ["computes orgMember for a shopper users row 16", "base", 224, 11, 258.6],
  ["applies the orgMember fee path for a admin users row 17", "fee", 41, 18, 54.02, 3],
  ["clamps orgMember for a owner users row 18", "clamp", 128.56, 130, 130, 134],
  ["computes orgMember for a auditor users row 19", "base", 167, 4, 181.36],
  ["applies the orgMember fee path for a support users row 20", "fee", 228, 10, 270.92, 10],
  ["clamps orgMember for a support users row 21", "clamp", 46.92, 43, 46.92, 47],
  ["computes orgMember for a auditor users row 22", "base", 215, 12, 250.4],
  ["applies the orgMember fee path for a guest users row 23", "fee", 154, 6, 181.4, 11],
  ["clamps orgMember for a buyer users row 24", "clamp", 100.72, 96, 100, 100],
  ["computes orgMember for a shopper users row 25", "base", 40, 17, 49.4],
  ["applies the orgMember fee path for a reseller users row 26", "fee", 219, 11, 253.85, 1],
  ["clamps orgMember for a owner users row 27", "clamp", 172.22, 171, 172.22, 175],
  ["computes orgMember for a admin users row 28", "base", 97, 24, 125.16],
  ["applies the orgMember fee path for a support users row 29", "fee", 28, 20, 40.72, 5],
  ["clamps orgMember for a auditor users row 30", "clamp", 243.26, 243, 243.26, 247],
  ["computes orgMember for a buyer users row 31", "base", 125, 2, 133.5],
  ["applies the orgMember fee path for a guest users row 32", "fee", 186, 8, 222.32, 13],
  ["clamps orgMember for a auditor users row 33", "clamp", 290.46, 290, 290.46, 294],
  ["computes orgMember for a support users row 34", "base", 68, 20, 85.32],
  ["applies the orgMember fee path for a admin users row 35", "fee", 129, 1, 137.45, 1],
  ["clamps orgMember for a owner users row 36", "clamp", 208.9, 210, 210, 214],
  ["computes orgMember for a reseller users row 37", "base", 11, 13, 13.87],
  ["applies the orgMember fee path for a shopper users row 38", "fee", 72, 19, 93.56, 4],
  ["clamps orgMember for a buyer users row 39", "clamp", 126.36, 125, 126.36, 129],
  ["computes orgMember for a guest users row 40", "base", 178, 10, 203.92],
  ["applies the orgMember fee path for a guest users row 41", "fee", 194, 1, 210.7, 6],
  ["clamps orgMember for a buyer users row 42", "clamp", 163.92, 164, 164, 168],
  ["computes orgMember for a support users row 43", "base", 76, 13, 89.92],
  ["applies the orgMember fee path for a auditor users row 44", "fee", 15, 7, 24.65, 7],
  ["clamps orgMember for a owner users row 45", "clamp", 207.92, 205, 207.92, 209],
  ["computes orgMember for a admin users row 46", "base", 137, 19, 169.51],
  ["applies the orgMember fee path for a shopper users row 47", "fee", 80, 12, 105.8, 12],
  ["clamps orgMember for a reseller users row 48", "clamp", 24.9, 20, 24, 24],
  ["computes orgMember for a guest users row 49", "base", 202, 24, 259.56],
  ["applies the orgMember fee path for a buyer users row 50", "fee", 141, 18, 186.02, 13],
  ["clamps orgMember for a reseller users row 51", "clamp", 215.31, 210, 214, 214],
  ["computes orgMember for a shopper users row 52", "base", 8, 15, 10.52],
  ["applies the orgMember fee path for a admin users row 53", "fee", 65, 22, 94.9, 12],
  ["clamps orgMember for a owner users row 54", "clamp", 136.82, 134, 136.82, 138],
  ["computes orgMember for a auditor users row 55", "base", 183, 10, 209.62],
  ["applies the orgMember fee path for a support users row 56", "fee", 244, 16, 304.8, 11],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(orgMember(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(orgMemberWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampOrgMember(a, b, extra)).toBe(expected);
    }
  });
}
