// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  passwordReset,
  passwordResetWithFee,
  clampPasswordReset,
  factorFromBps,
} = require("./passwordReset");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes passwordReset for a owner users row 1", "base", 206, 18, 260.56],
  ["applies the passwordReset fee path for a admin users row 2", "fee", 145, 12, 177, 2],
  ["clamps passwordReset for a shopper users row 3", "clamp", 100.44, 98, 100.44, 102],
  ["computes passwordReset for a reseller users row 4", "base", 27, 24, 36.64],
  ["applies the passwordReset fee path for a guest users row 5", "fee", 202, 19, 271.54, 14],
  ["clamps passwordReset for a buyer users row 6", "clamp", 171.61, 170, 171.61, 174],
  ["computes passwordReset for a support users row 7", "base", 84, 6, 96.76],
  ["applies the passwordReset fee path for a auditor users row 8", "fee", 23, 0, 25.84, 0],
  ["clamps passwordReset for a owner users row 9", "clamp", 255.44, 252, 255.44, 256],
  ["computes passwordReset for a admin users row 10", "base", 137, 14, 168.14],
  ["applies the passwordReset fee path for a reseller users row 11", "fee", 243, 0, 273.44, 10],
  ["clamps passwordReset for a shopper users row 12", "clamp", 74.96, 72, 74.96, 76],
  ["computes passwordReset for a admin users row 13", "base", 121, 13, 147.41],
  ["applies the passwordReset fee path for a owner users row 14", "fee", 182, 19, 241.14, 9],
  ["clamps passwordReset for a auditor users row 15", "clamp", 259.51, 260, 260, 264],
  ["computes passwordReset for a support users row 16", "base", 60, 7, 70],
  ["applies the passwordReset fee path for a buyer users row 17", "fee", 117, 14, 147.74, 4],
  ["clamps passwordReset for a guest users row 18", "clamp", 231.84, 227, 231, 231],
  ["computes passwordReset for a reseller users row 19", "base", 11, 23, 15.41],
  ["applies the passwordReset fee path for a shopper users row 20", "fee", 72, 4, 85.64, 4],
  ["clamps passwordReset for a shopper users row 21", "clamp", 128.96, 128, 128.96, 132],
  ["computes passwordReset for a reseller users row 22", "base", 43, 10, 51.74],
  ["applies the passwordReset fee path for a owner users row 23", "fee", 222, 4, 253.64, 4],
  ["clamps passwordReset for a admin users row 24", "clamp", 211.91, 210, 211.91, 214],
  ["computes passwordReset for a support users row 25", "base", 100, 17, 126],
  ["applies the passwordReset fee path for a auditor users row 26", "fee", 39, 11, 48.41, 1],
  ["clamps passwordReset for a guest users row 27", "clamp", 248.34, 245, 248.34, 249],
  ["computes passwordReset for a buyer users row 28", "base", 157, 24, 208.24],
  ["applies the passwordReset fee path for a shopper users row 29", "fee", 96, 18, 134.95999999999998, 13],
  ["clamps passwordReset for a reseller users row 30", "clamp", 45, 41, 45, 45],
  ["computes passwordReset for a admin users row 31", "base", 193, 0, 209.44],
  ["applies the passwordReset fee path for a owner users row 32", "fee", 14, 6, 22.96, 6],
  ["clamps passwordReset for a reseller users row 33", "clamp", 93, 89, 93, 93],
  ["computes passwordReset for a shopper users row 34", "base", 136, 18, 172.36],
  ["applies the passwordReset fee path for a buyer users row 35", "fee", 189, 1, 208.01, 1],
  ["clamps passwordReset for a guest users row 36", "clamp", 11.5, 11, 11.5, 15],
  ["computes passwordReset for a auditor users row 37", "base", 71, 13, 86.91],
  ["applies the passwordReset fee path for a support users row 38", "fee", 132, 19, 172.64, 4],
  ["clamps passwordReset for a admin users row 39", "clamp", 207.5, 203, 207, 207],
  ["computes passwordReset for a owner users row 40", "base", 246, 8, 286.36],
  ["applies the passwordReset fee path for a owner users row 41", "fee", 158, 5, 179.54, 0],
  ["clamps passwordReset for a admin users row 42", "clamp", 130.04, 127, 130.04, 131],
  ["computes passwordReset for a shopper users row 43", "base", 40, 17, 51],
  ["applies the passwordReset fee path for a reseller users row 44", "fee", 219, 11, 262.61, 1],
  ["clamps passwordReset for a guest users row 45", "clamp", 178.56, 175, 178.56, 179],
  ["computes passwordReset for a buyer users row 46", "base", 93, 0, 101.44],
  ["applies the passwordReset fee path for a support users row 47", "fee", 36, 18, 59.36, 13],
  ["clamps passwordReset for a auditor users row 48", "clamp", 256, 257, 257, 261],
  ["computes passwordReset for a owner users row 49", "base", 150, 7, 173.5],
  ["applies the passwordReset fee path for a admin users row 50", "fee", 89, 1, 104.01, 6],
  ["clamps passwordReset for a auditor users row 51", "clamp", 304.34, 300, 304, 304],
  ["computes passwordReset for a support users row 52", "base", 68, 20, 88.04],
  ["applies the passwordReset fee path for a buyer users row 53", "fee", 125, 2, 150.5, 12],
  ["clamps passwordReset for a guest users row 54", "clamp", 216.76, 215, 216.76, 219],
  ["computes passwordReset for a reseller users row 55", "base", 11, 13, 14.31],
  ["applies the passwordReset fee path for a shopper users row 56", "fee", 72, 19, 96.44, 4],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(passwordReset(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(passwordResetWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPasswordReset(a, b, extra)).toBe(expected);
    }
  });
}
