// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 108;

function passwordReset(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function passwordResetWithFee(amount, factor, fee) {
  return passwordReset(amount, factor) + fee;
}

function clampPasswordReset(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  passwordReset,
  passwordResetWithFee,
  clampPasswordReset,
  factorFromBps,
};
