// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 101;

function roleGuard(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function roleGuardWithFee(amount, factor, fee) {
  return roleGuard(amount, factor) + fee;
}

function clampRoleGuard(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  roleGuard,
  roleGuardWithFee,
  clampRoleGuard,
  factorFromBps,
};
