// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  roleGuard,
  roleGuardWithFee,
  clampRoleGuard,
  factorFromBps,
} = require("./roleGuard");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes roleGuard for a admin users row 1", "base", 185, 12, 213.05],
  ["applies the roleGuard fee path for a owner users row 2", "fee", 246, 18, 309.74, 13],
  ["clamps roleGuard for a reseller users row 3", "clamp", 85.75, 86, 86, 90],
  ["computes roleGuard for a shopper users row 4", "base", 128, 5, 139.68],
  ["applies the roleGuard fee path for a buyer users row 5", "fee", 181, 13, 218.34, 8],
  ["clamps roleGuard for a guest users row 6", "clamp", 296.4, 292, 296, 296],
  ["computes roleGuard for a auditor users row 7", "base", 63, 0, 67.63],
  ["applies the roleGuard fee path for a support users row 8", "fee", 124, 6, 147.68, 11],
  ["clamps roleGuard for a admin users row 9", "clamp", 221.23, 216, 220, 220],
  ["computes roleGuard for a owner users row 10", "base", 14, 16, 20.38],
  ["applies the roleGuard fee path for a guest users row 11", "fee", 18, 15, 34.879999999999995, 10],
  ["clamps roleGuard for a buyer users row 12", "clamp", 221.7, 219, 221.7, 223],
  ["computes roleGuard for a support users row 13", "base", 140, 2, 148.2],
  ["applies the roleGuard fee path for a auditor users row 14", "fee", 79, 21, 111.38, 11],
  ["clamps roleGuard for a owner users row 15", "clamp", 26.3, 27, 27, 31],
  ["computes roleGuard for a admin users row 16", "base", 201, 8, 223.09],
  ["applies the roleGuard fee path for a shopper users row 17", "fee", 144, 1, 151.88, 1],
  ["clamps roleGuard for a reseller users row 18", "clamp", 103.43, 102, 103.43, 106],
  ["computes roleGuard for a guest users row 19", "base", 26, 13, 33.64],
  ["applies the roleGuard fee path for a buyer users row 20", "fee", 205, 7, 227.4, 2],
  ["clamps roleGuard for a admin users row 21", "clamp", 181.83, 183, 183, 187],
  ["computes roleGuard for a owner users row 22", "base", 230, 12, 263.9],
  ["applies the roleGuard fee path for a reseller users row 23", "fee", 51, 18, 77.69, 13],
  ["clamps roleGuard for a shopper users row 24", "clamp", 147, 142, 146, 146],
  ["computes roleGuard for a buyer users row 25", "base", 165, 7, 182.2],
  ["applies the roleGuard fee path for a guest users row 26", "fee", 226, 13, 269.64, 8],
  ["clamps roleGuard for a auditor users row 27", "clamp", 60.4, 58, 60.4, 62],
  ["computes roleGuard for a support users row 28", "base", 108, 0, 113.08],
  ["applies the roleGuard fee path for a admin users row 29", "fee", 177, 4, 193.85, 4],
  ["clamps roleGuard for a owner users row 30", "clamp", 269.18, 266, 269.18, 270],
  ["computes roleGuard for a shopper users row 31", "base", 80, 22, 102.4],
  ["applies the roleGuard fee path for a reseller users row 32", "fee", 19, 16, 37.230000000000004, 11],
  ["clamps roleGuard for a owner users row 33", "clamp", 224.78, 222, 224.78, 226],
  ["computes roleGuard for a admin users row 34", "base", 137, 4, 147.85],
  ["applies the roleGuard fee path for a support users row 35", "fee", 76, 23, 106.24, 8],
  ["clamps roleGuard for a auditor users row 36", "clamp", 23.7, 20, 23.7, 24],
  ["computes roleGuard for a guest users row 37", "base", 194, 11, 221.28],
  ["applies the roleGuard fee path for a buyer users row 38", "fee", 133, 5, 149.98, 5],
  ["clamps roleGuard for a shopper users row 39", "clamp", 110.48, 108, 110.48, 112],
  ["computes roleGuard for a reseller users row 40", "base", 27, 14, 35.05],
  ["applies the roleGuard fee path for a auditor users row 41", "fee", 223, 20, 278.83, 5],
  ["clamps roleGuard for a support users row 42", "clamp", 51.88, 47, 51, 51],
  ["computes roleGuard for a buyer users row 43", "base", 101, 8, 114.09],
  ["applies the roleGuard fee path for a guest users row 44", "fee", 162, 14, 194.3, 4],
  ["clamps roleGuard for a reseller users row 45", "clamp", 278.4, 274, 278, 278],
  ["computes roleGuard for a shopper users row 46", "base", 48, 0, 52.48],
  ["applies the roleGuard fee path for a admin users row 47", "fee", 105, 7, 124.4, 7],
  ["clamps roleGuard for a owner users row 48", "clamp", 193.24, 191, 193.24, 195],
  ["computes roleGuard for a auditor users row 49", "base", 231, 18, 278.89],
  ["applies the roleGuard fee path for a support users row 50", "fee", 52, 24, 83, 14],
  ["clamps roleGuard for a owner users row 51", "clamp", 26.1, 25, 26.1, 29],
  ["computes roleGuard for a admin users row 52", "base", 201, 23, 253.24],
  ["applies the roleGuard fee path for a shopper users row 53", "fee", 144, 16, 173.48, 1],
  ["clamps roleGuard for a reseller users row 54", "clamp", 97.13, 94, 97.13, 98],
  ["computes roleGuard for a guest users row 55", "base", 18, 5, 23.08],
  ["applies the roleGuard fee path for a buyer users row 56", "fee", 197, 24, 259.25, 9],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(roleGuard(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(roleGuardWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampRoleGuard(a, b, extra)).toBe(expected);
    }
  });
}
