// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  userMerge,
  userMergeWithFee,
  clampUserMerge,
  factorFromBps,
} = require("./userMerge");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes userMerge for a buyer users row 1", "base", 197, 9, 226.58],
  ["applies the userMerge fee path for a guest users row 2", "fee", 18, 15, 33.6, 10],
  ["clamps userMerge for a auditor users row 3", "clamp", 98.54, 100, 100, 104],
  ["computes userMerge for a support users row 4", "base", 140, 2, 151.8],
  ["applies the userMerge fee path for a admin users row 5", "fee", 201, 8, 242.13, 13],
  ["clamps userMerge for a owner users row 6", "clamp", 31.18, 26, 30, 30],
  ["computes userMerge for a reseller users row 7", "base", 83, 20, 105.75],
  ["applies the userMerge fee path for a shopper users row 8", "fee", 144, 1, 155.64, 1],
  ["clamps userMerge for a buyer users row 9", "clamp", 233.6, 230, 233.6, 234],
  ["computes userMerge for a guest users row 10", "base", 26, 13, 32.68],
  ["applies the userMerge fee path for a owner users row 11", "fee", 166, 8, 197.58, 8],
  ["clamps userMerge for a admin users row 12", "clamp", 113.35, 112, 113.35, 116],
  ["computes userMerge for a shopper users row 13", "base", 48, 20, 62],
  ["applies the userMerge fee path for a reseller users row 14", "fee", 227, 14, 281.13, 9],
  ["clamps userMerge for a guest users row 15", "clamp", 186.68, 185, 186.68, 189],
  ["computes userMerge for a buyer users row 16", "base", 101, 3, 111.08],
  ["applies the userMerge fee path for a support users row 17", "fee", 44, 21, 63.44, 6],
  ["clamps userMerge for a auditor users row 18", "clamp", 271.6, 268, 271.6, 272],
  ["computes userMerge for a owner users row 19", "base", 174, 6, 195.14],
  ["applies the userMerge fee path for a admin users row 20", "fee", 113, 0, 120.65, 0],
  ["clamps userMerge for a buyer users row 21", "clamp", 103.33, 99, 103, 103],
  ["computes userMerge for a guest users row 22", "base", 138, 5, 153.8],
  ["applies the userMerge fee path for a auditor users row 23", "fee", 199, 11, 243.84, 11],
  ["clamps userMerge for a support users row 24", "clamp", 27.4, 24, 27.4, 28],
  ["computes userMerge for a admin users row 25", "base", 81, 23, 105.68],
  ["applies the userMerge fee path for a owner users row 26", "fee", 142, 4, 170.78, 14],
  ["clamps userMerge for a reseller users row 27", "clamp", 235.45, 233, 235.45, 237],
  ["computes userMerge for a shopper users row 28", "base", 24, 16, 31.04],
  ["applies the userMerge fee path for a buyer users row 29", "fee", 69, 1, 76.14, 1],
  ["clamps userMerge for a guest users row 30", "clamp", 149.6, 146, 149.6, 150],
  ["computes userMerge for a support users row 31", "base", 228, 15, 275.6],
  ["applies the userMerge fee path for a auditor users row 32", "fee", 167, 9, 201.38, 9],
  ["clamps userMerge for a guest users row 33", "clamp", 115.48, 114, 115.48, 118],
  ["computes userMerge for a buyer users row 34", "base", 45, 22, 59.15],
  ["applies the userMerge fee path for a shopper users row 35", "fee", 232, 14, 292.08, 14],
  ["clamps userMerge for a reseller users row 36", "clamp", 197.23, 193, 197, 197],
  ["computes userMerge for a owner users row 37", "base", 110, 2, 119.7],
  ["applies the userMerge fee path for a admin users row 38", "fee", 49, 21, 74.74000000000001, 11],
  ["clamps userMerge for a support users row 39", "clamp", 271.4, 268, 271.4, 272],
  ["computes userMerge for a auditor users row 40", "base", 159, 11, 186.44],
  ["applies the userMerge fee path for a reseller users row 41", "fee", 43, 20, 60.75, 5],
  ["clamps userMerge for a shopper users row 42", "clamp", 112.24, 110, 112.24, 114],
  ["computes userMerge for a admin users row 43", "base", 161, 8, 183.93],
  ["applies the userMerge fee path for a owner users row 44", "fee", 222, 14, 270.18, 4],
  ["clamps userMerge for a auditor users row 45", "clamp", 48.14, 49, 49, 53],
  ["computes userMerge for a support users row 46", "base", 100, 2, 109],
  ["applies the userMerge fee path for a buyer users row 47", "fee", 157, 9, 194.98, 14],
  ["clamps userMerge for a guest users row 48", "clamp", 265.6, 262, 265.6, 266],
  ["computes userMerge for a reseller users row 49", "base", 35, 22, 46.45],
  ["applies the userMerge fee path for a shopper users row 50", "fee", 96, 3, 118.68, 13],
  ["clamps userMerge for a guest users row 51", "clamp", 200.88, 201, 201, 205],
  ["computes userMerge for a buyer users row 52", "base", 101, 13, 121.18],
  ["applies the userMerge fee path for a support users row 53", "fee", 44, 6, 56.84, 6],
  ["clamps userMerge for a auditor users row 54", "clamp", 236.15, 234, 236.15, 238],
  ["computes userMerge for a owner users row 55", "base", 166, 18, 206.18],
  ["applies the userMerge fee path for a admin users row 56", "fee", 105, 12, 131.85, 7],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(userMerge(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(userMergeWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampUserMerge(a, b, extra)).toBe(expected);
    }
  });
}
