// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 101;

function userLocale(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function userLocaleWithFee(amount, factor, fee) {
  return userLocale(amount, factor) + fee;
}

function clampUserLocale(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  userLocale,
  userLocaleWithFee,
  clampUserLocale,
  factorFromBps,
};
