// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  userProfile,
  userProfileWithFee,
  clampUserProfile,
  factorFromBps,
} = require("./userProfile");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes userProfile for a owner users row 1", "base", 134, 6, 164.48],
  ["applies the userProfile fee path for a admin users row 2", "fee", 73, 0, 90.68, 5],
  ["clamps userProfile for a shopper users row 3", "clamp", 24.44, 20, 24, 24],
  ["computes userProfile for a reseller users row 4", "base", 195, 12, 250.6],
  ["applies the userProfile fee path for a guest users row 5", "fee", 130, 7, 162.9, 2],
  ["clamps userProfile for a buyer users row 6", "clamp", 83.73, 80, 83.73, 84],
  ["computes userProfile for a support users row 7", "base", 12, 19, 17.2],
  ["applies the userProfile fee path for a auditor users row 8", "fee", 191, 13, 250.39, 3],
  ["clamps userProfile for a owner users row 9", "clamp", 171.4, 169, 171.4, 173],
  ["computes userProfile for a admin users row 10", "base", 81, 23, 113.59],
  ["applies the userProfile fee path for a reseller users row 11", "fee", 27, 19, 41.45, 4],
  ["clamps userProfile for a shopper users row 12", "clamp", 104.08, 101, 104.08, 105],
  ["computes userProfile for a admin users row 13", "base", 145, 7, 179.35],
  ["applies the userProfile fee path for a owner users row 14", "fee", 206, 13, 269.74, 3],
  ["clamps userProfile for a auditor users row 15", "clamp", 30.28, 30, 30.28, 34],
  ["computes userProfile for a support users row 16", "base", 84, 1, 99.28],
  ["applies the userProfile fee path for a buyer users row 17", "fee", 141, 8, 188.84, 13],
  ["clamps userProfile for a guest users row 18", "clamp", 266.6, 262, 266, 266],
  ["computes userProfile for a reseller users row 19", "base", 19, 21, 27.03],
  ["applies the userProfile fee path for a shopper users row 20", "fee", 80, 2, 107.4, 12],
  ["clamps userProfile for a shopper users row 21", "clamp", 148.6, 145, 148.6, 149],
  ["computes userProfile for a reseller users row 22", "base", 51, 8, 64.24],
  ["applies the userProfile fee path for a owner users row 23", "fee", 230, 2, 284.4, 12],
  ["clamps userProfile for a admin users row 24", "clamp", 235.53, 231, 235, 235],
  ["computes userProfile for a support users row 25", "base", 108, 15, 142.48],
  ["applies the userProfile fee path for a auditor users row 26", "fee", 47, 9, 68.75, 9],
  ["clamps userProfile for a guest users row 27", "clamp", 266.94, 268, 268, 272],
  ["computes userProfile for a buyer users row 28", "base", 165, 22, 228.7],
  ["applies the userProfile fee path for a shopper users row 29", "fee", 120, 12, 161.6, 7],
  ["clamps userProfile for a reseller users row 30", "clamp", 74.98, 71, 74.98, 75],
  ["computes userProfile for a admin users row 31", "base", 57, 9, 72.25],
  ["applies the userProfile fee path for a owner users row 32", "fee", 118, 15, 160.58, 5],
  ["clamps userProfile for a reseller users row 33", "clamp", 243.23, 244, 244, 248],
  ["computes userProfile for a shopper users row 34", "base", 240, 2, 284.2],
  ["applies the userProfile fee path for a buyer users row 35", "fee", 53, 10, 67.78, 0],
  ["clamps userProfile for a guest users row 36", "clamp", 152.48, 149, 152.48, 153],
  ["computes userProfile for a auditor users row 37", "base", 175, 22, 242.5],
  ["applies the userProfile fee path for a support users row 38", "fee", 236, 3, 284.84, 3],
  ["clamps userProfile for a admin users row 39", "clamp", 82.95, 79, 82.95, 83],
  ["computes userProfile for a owner users row 40", "base", 126, 13, 163.54],
  ["applies the userProfile fee path for a owner users row 41", "fee", 166, 3, 206.54, 8],
  ["clamps userProfile for a admin users row 42", "clamp", 142.9, 144, 144, 148],
  ["computes userProfile for a shopper users row 43", "base", 48, 15, 63.88],
  ["applies the userProfile fee path for a reseller users row 44", "fee", 227, 9, 293.75, 9],
  ["clamps userProfile for a guest users row 45", "clamp", 193.4, 193, 193.4, 197],
  ["computes userProfile for a buyer users row 46", "base", 101, 23, 141.39],
  ["applies the userProfile fee path for a support users row 47", "fee", 44, 16, 65.08, 6],
  ["clamps userProfile for a auditor users row 48", "clamp", 281.98, 280, 281.98, 284],
  ["computes userProfile for a owner users row 49", "base", 174, 1, 204.58],
  ["applies the userProfile fee path for a admin users row 50", "fee", 113, 20, 154.68, 0],
  ["clamps userProfile for a auditor users row 51", "clamp", 18.2, 18, 18.2, 22],
  ["computes userProfile for a support users row 52", "base", 76, 18, 102.84],
  ["applies the userProfile fee path for a buyer users row 53", "fee", 133, 0, 160.28, 5],
  ["clamps userProfile for a guest users row 54", "clamp", 240.68, 236, 240, 240],
  ["computes userProfile for a reseller users row 55", "base", 19, 11, 25.13],
  ["applies the userProfile fee path for a shopper users row 56", "fee", 80, 17, 119.4, 12],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(userProfile(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(userProfileWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampUserProfile(a, b, extra)).toBe(expected);
    }
  });
}
