// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 2;
const FACTOR_BASE = 105;

function userMerge(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function userMergeWithFee(amount, factor, fee) {
  return userMerge(amount, factor) + fee;
}

function clampUserMerge(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  userMerge,
  userMergeWithFee,
  clampUserMerge,
  factorFromBps,
};
