// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 116;

function userProfile(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function userProfileWithFee(amount, factor, fee) {
  return userProfile(amount, factor) + fee;
}

function clampUserProfile(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  userProfile,
  userProfileWithFee,
  clampUserProfile,
  factorFromBps,
};
