// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  amountOff,
  amountOffWithFee,
  clampAmountOff,
  factorFromBps,
} = require("./amountOff");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes amountOff for a welcome coupons row 1", "base", 200, 7, 298],
  ["applies the amountOff fee path for a referral coupons row 2", "fee", 139, 1, 212.21, 11],
  ["clamps amountOff for a app coupons row 3", "clamp", 130.24, 129, 130.24, 133],
  ["computes amountOff for a flash coupons row 4", "base", 17, 14, 33.84],
  ["applies the amountOff fee path for a clearance coupons row 5", "fee", 196, 8, 302.16, 8],
  ["clamps amountOff for a vip coupons row 6", "clamp", 197, 195, 197, 199],
  ["computes amountOff for a loyalty coupons row 7", "base", 74, 21, 125.66],
  ["applies the amountOff fee path for a holiday coupons row 8", "fee", 13, 15, 32.89, 5],
  ["clamps amountOff for a welcome coupons row 9", "clamp", 291.24, 288, 291.24, 292],
  ["computes amountOff for a referral coupons row 10", "base", 131, 3, 192.71],
  ["applies the amountOff fee path for a flash coupons row 11", "fee", 49, 1, 87.11, 11],
  ["clamps amountOff for a app coupons row 12", "clamp", 164.5, 166, 166, 170],
  ["computes amountOff for a referral coupons row 13", "base", 171, 13, 266.21],
  ["applies the amountOff fee path for a welcome coupons row 14", "fee", 232, 19, 386.24, 14],
  ["clamps amountOff for a holiday coupons row 15", "clamp", 72, 69, 72, 73],
  ["computes amountOff for a loyalty coupons row 16", "base", 106, 8, 162.76],
  ["applies the amountOff fee path for a vip coupons row 17", "fee", 167, 14, 270.84, 9],
  ["clamps amountOff for a clearance coupons row 18", "clamp", 368.24, 366, 368.24, 370],
  ["computes amountOff for a flash coupons row 19", "base", 41, 3, 65.81],
  ["applies the amountOff fee path for a app coupons row 20", "fee", 102, 9, 161.94, 4],
  ["clamps amountOff for a loyalty coupons row 21", "clamp", 213.24, 210, 213.24, 214],
  ["computes amountOff for a holiday coupons row 22", "base", 77, 4, 117.34],
  ["applies the amountOff fee path for a clearance coupons row 23", "fee", 20, 22, 52, 12],
  ["clamps amountOff for a vip coupons row 24", "clamp", 317.46, 312, 316, 316],
  ["computes amountOff for a app coupons row 25", "base", 142, 9, 216.74],
  ["applies the amountOff fee path for a flash coupons row 26", "fee", 81, 3, 135.20999999999998, 13],
  ["clamps amountOff for a welcome coupons row 27", "clamp", 45.16, 44, 45.16, 48],
  ["computes amountOff for a referral coupons row 28", "base", 203, 15, 318.59],
  ["applies the amountOff fee path for a loyalty coupons row 29", "fee", 130, 12, 205, 2],
  ["clamps amountOff for a holiday coupons row 30", "clamp", 104.36, 105, 105, 109],
  ["computes amountOff for a referral coupons row 31", "base", 99, 1, 145.61],
  ["applies the amountOff fee path for a welcome coupons row 32", "fee", 160, 7, 242, 2],
  ["clamps amountOff for a flash coupons row 33", "clamp", 336.84, 336, 336.84, 340],
  ["computes amountOff for a app coupons row 34", "base", 38, 20, 68.04],
  ["applies the amountOff fee path for a vip coupons row 35", "fee", 95, 2, 153, 12],
  ["clamps amountOff for a clearance coupons row 36", "clamp", 232.76, 234, 234, 238],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(amountOff(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(amountOffWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampAmountOff(a, b, extra)).toBe(expected);
    }
  });
}
