// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  couponFraud,
  couponFraudWithFee,
  clampCouponFraud,
  factorFromBps,
} = require("./couponFraud");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes couponFraud for a vip coupons row 1", "base", 31, 3, 46.3],
  ["applies the couponFraud fee path for a clearance coupons row 2", "fee", 92, 9, 140.12, 9],
  ["clamps couponFraud for a holiday coupons row 3", "clamp", 222.07, 217, 221, 221],
  ["computes couponFraud for a loyalty coupons row 4", "base", 210, 22, 318.9],
  ["applies the couponFraud fee path for a referral coupons row 5", "fee", 35, 2, 63.15, 12],
  ["clamps couponFraud for a welcome coupons row 6", "clamp", 138.6, 134, 138, 138],
  ["computes couponFraud for a flash coupons row 7", "base", 153, 15, 223.26],
  ["applies the couponFraud fee path for a app coupons row 8", "fee", 214, 21, 333.72, 11],
  ["clamps couponFraud for a vip coupons row 9", "clamp", 57.92, 54, 57.92, 58],
  ["computes couponFraud for a clearance coupons row 10", "base", 100, 7, 140],
  ["applies the couponFraud fee path for a clearance coupons row 11", "fee", 244, 21, 378.12, 11],
  ["clamps couponFraud for a vip coupons row 12", "clamp", 264.86, 264, 264.86, 268],
  ["computes couponFraud for a loyalty coupons row 13", "base", 122, 9, 171.92],
  ["applies the couponFraud fee path for a holiday coupons row 14", "fee", 61, 3, 93.3, 8],
  ["clamps couponFraud for a welcome coupons row 15", "clamp", 19.76, 16, 19.76, 20],
  ["computes couponFraud for a referral coupons row 16", "base", 187, 14, 269.67],
  ["applies the couponFraud fee path for a app coupons row 17", "fee", 126, 8, 189.1, 13],
  ["clamps couponFraud for a flash coupons row 18", "clamp", 92.85, 88, 92, 92],
  ["computes couponFraud for a clearance coupons row 19", "base", 236, 23, 360],
  ["applies the couponFraud fee path for a vip coupons row 20", "fee", 175, 17, 260, 2],
  ["clamps couponFraud for a vip coupons row 21", "clamp", 175.72, 177, 177, 181],
  ["computes couponFraud for a clearance coupons row 22", "base", 188, 15, 272.96],
  ["applies the couponFraud fee path for a holiday coupons row 23", "fee", 245, 22, 383.05, 12],
  ["clamps couponFraud for a loyalty coupons row 24", "clamp", 93.8, 90, 93.8, 94],
  ["computes couponFraud for a referral coupons row 25", "base", 131, 8, 182.85],
  ["applies the couponFraud fee path for a welcome coupons row 26", "fee", 192, 14, 280.72, 4],
  ["clamps couponFraud for a flash coupons row 27", "clamp", 20.32, 17, 20.32, 21],
  ["computes couponFraud for a app coupons row 28", "base", 70, 2, 96.3],
  ["applies the couponFraud fee path for a vip coupons row 29", "fee", 135, 7, 193.9, 7],
  ["clamps couponFraud for a clearance coupons row 30", "clamp", 281.4, 278, 281.4, 282],
  ["computes couponFraud for a app coupons row 31", "base", 38, 0, 54.26],
  ["applies the couponFraud fee path for a flash coupons row 32", "fee", 217, 19, 336.82, 14],
  ["clamps couponFraud for a welcome coupons row 33", "clamp", 230.4, 226, 230, 230],
  ["computes couponFraud for a referral coupons row 34", "base", 99, 6, 137.67],
  ["applies the couponFraud fee path for a loyalty coupons row 35", "fee", 34, 1, 60.52, 11],
  ["clamps couponFraud for a holiday coupons row 36", "clamp", 321.11, 317, 321, 321],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(couponFraud(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(couponFraudWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCouponFraud(a, b, extra)).toBe(expected);
    }
  });
}
