// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  couponBudget,
  couponBudgetWithFee,
  clampCouponBudget,
  factorFromBps,
} = require("./couponBudget");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes couponBudget for a welcome coupons row 1", "base", 96, 8, 149.16],
  ["applies the couponBudget fee path for a referral coupons row 2", "fee", 35, 2, 70, 12],
  ["clamps couponBudget for a app coupons row 3", "clamp", 350.26, 347, 350.26, 351],
  ["computes couponBudget for a flash coupons row 4", "base", 153, 15, 243.09],
  ["applies the couponBudget fee path for a clearance coupons row 5", "fee", 92, 9, 153.24, 9],
  ["clamps couponBudget for a vip coupons row 6", "clamp", 54.71, 51, 54.71, 55],
  ["computes couponBudget for a loyalty coupons row 7", "base", 210, 22, 345],
  ["applies the couponBudget fee path for a holiday coupons row 8", "fee", 149, 16, 244.46, 6],
  ["clamps couponBudget for a welcome coupons row 9", "clamp", 158.76, 157, 158.76, 161],
  ["computes couponBudget for a referral coupons row 10", "base", 43, 0, 68.34],
  ["applies the couponBudget fee path for a flash coupons row 11", "fee", 217, 24, 374.54, 14],
  ["clamps couponBudget for a app coupons row 12", "clamp", 63.34, 61, 63.34, 65],
  ["computes couponBudget for a referral coupons row 13", "base", 99, 11, 156.51],
  ["applies the couponBudget fee path for a welcome coupons row 14", "fee", 160, 17, 259, 2],
  ["clamps couponBudget for a holiday coupons row 15", "clamp", 299.94, 301, 301, 305],
  ["computes couponBudget for a loyalty coupons row 16", "base", 34, 6, 57.96],
  ["applies the couponBudget fee path for a vip coupons row 17", "fee", 95, 12, 163.5, 12],
  ["clamps couponBudget for a clearance coupons row 18", "clamp", 255.36, 250, 254, 254],
  ["computes couponBudget for a flash coupons row 19", "base", 225, 22, 369],
  ["applies the couponBudget fee path for a app coupons row 20", "fee", 46, 3, 81.86, 8],
  ["clamps couponBudget for a loyalty coupons row 21", "clamp", 281.34, 279, 281.34, 283],
  ["computes couponBudget for a holiday coupons row 22", "base", 117, 9, 180.99],
  ["applies the couponBudget fee path for a clearance coupons row 23", "fee", 60, 2, 100, 7],
  ["clamps couponBudget for a vip coupons row 24", "clamp", 391.01, 387, 391, 391],
  ["computes couponBudget for a app coupons row 25", "base", 182, 14, 285.64],
  ["applies the couponBudget fee path for a flash coupons row 26", "fee", 121, 8, 193.66, 8],
  ["clamps couponBudget for a welcome coupons row 27", "clamp", 95.96, 96, 96, 100],
  ["computes couponBudget for a referral coupons row 28", "base", 243, 20, 392.94],
  ["applies the couponBudget fee path for a loyalty coupons row 29", "fee", 186, 13, 302.86, 13],
  ["clamps couponBudget for a holiday coupons row 30", "clamp", 190.25, 188, 190.25, 192],
  ["computes couponBudget for a referral coupons row 31", "base", 59, 16, 99.86],
  ["applies the couponBudget fee path for a welcome coupons row 32", "fee", 120, 22, 208, 7],
  ["clamps couponBudget for a flash coupons row 33", "clamp", 263.34, 258, 262, 262],
  ["computes couponBudget for a app coupons row 34", "base", 238, 10, 361.24],
  ["applies the couponBudget fee path for a vip coupons row 35", "fee", 55, 17, 96.25, 2],
  ["clamps couponBudget for a clearance coupons row 36", "clamp", 196.76, 194, 196.76, 198],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(couponBudget(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(couponBudgetWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCouponBudget(a, b, extra)).toBe(expected);
    }
  });
}
