// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 138;

function couponBudget(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function couponBudgetWithFee(amount, factor, fee) {
  return couponBudget(amount, factor) + fee;
}

function clampCouponBudget(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  couponBudget,
  couponBudgetWithFee,
  clampCouponBudget,
  factorFromBps,
};
