// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  couponLocale,
  couponLocaleWithFee,
  clampCouponLocale,
  factorFromBps,
} = require("./couponLocale");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes couponLocale for a holiday coupons row 1", "base", 117, 19, 184.52],
  ["applies the couponLocale fee path for a loyalty coupons row 2", "fee", 178, 0, 250.86, 5],
  ["clamps couponLocale for a vip coupons row 3", "clamp", 340.77, 342, 342, 346],
  ["computes couponLocale for a clearance coupons row 4", "base", 60, 12, 91.4],
  ["applies the couponLocale fee path for a flash coupons row 5", "fee", 121, 18, 197.55, 8],
  ["clamps couponLocale for a app coupons row 6", "clamp", 298.02, 293, 297, 297],
  ["computes couponLocale for a referral coupons row 7", "base", 243, 5, 347.06],
  ["applies the couponLocale fee path for a welcome coupons row 8", "fee", 64, 11, 107.72, 11],
  ["clamps couponLocale for a holiday coupons row 9", "clamp", 196.5, 193, 196.5, 197],
  ["computes couponLocale for a loyalty coupons row 10", "base", 186, 23, 299.6],
  ["applies the couponLocale fee path for a app coupons row 11", "fee", 22, 24, 51.42, 14],
  ["clamps couponLocale for a flash coupons row 12", "clamp", 315.55, 312, 315.55, 316],
  ["computes couponLocale for a welcome coupons row 13", "base", 144, 11, 215.12],
  ["applies the couponLocale fee path for a referral coupons row 14", "fee", 83, 5, 119.86, 0],
  ["clamps couponLocale for a loyalty coupons row 15", "clamp", 29.66, 25, 29, 29],
  ["computes couponLocale for a holiday coupons row 16", "base", 197, 19, 309.32],
  ["applies the couponLocale fee path for a clearance coupons row 17", "fee", 140, 12, 222.6, 12],
  ["clamps couponLocale for a vip coupons row 18", "clamp", 112.97, 113, 113, 117],
  ["computes couponLocale for a app coupons row 19", "base", 46, 18, 73.3],
  ["applies the couponLocale fee path for a flash coupons row 20", "fee", 225, 12, 344.25, 7],
  ["clamps couponLocale for a holiday coupons row 21", "clamp", 283.72, 280, 283.72, 284],
  ["computes couponLocale for a loyalty coupons row 22", "base", 10, 17, 17.4],
  ["applies the couponLocale fee path for a vip coupons row 23", "fee", 71, 23, 118.6, 3],
  ["clamps couponLocale for a clearance coupons row 24", "clamp", 189.12, 186, 189.12, 190],
  ["computes couponLocale for a flash coupons row 25", "base", 193, 10, 285.71],
  ["applies the couponLocale fee path for a app coupons row 26", "fee", 14, 16, 29.42, 6],
  ["clamps couponLocale for a referral coupons row 27", "clamp", 121.25, 119, 121.25, 123],
  ["computes couponLocale for a welcome coupons row 28", "base", 136, 3, 192.4],
  ["applies the couponLocale fee path for a holiday coupons row 29", "fee", 165, 17, 263.1, 7],
  ["clamps couponLocale for a loyalty coupons row 30", "clamp", 361.6, 362, 362, 366],
  ["computes couponLocale for a clearance coupons row 31", "base", 100, 2, 141],
  ["applies the couponLocale fee path for a vip coupons row 32", "fee", 39, 21, 64.62, 1],
  ["clamps couponLocale for a loyalty coupons row 33", "clamp", 332.36, 331, 332.36, 335],
  ["computes couponLocale for a holiday coupons row 34", "base", 157, 9, 231.22],
  ["applies the couponLocale fee path for a welcome coupons row 35", "fee", 104, 1, 151.52, 6],
  ["clamps couponLocale for a referral coupons row 36", "clamp", 71.51, 68, 71.51, 72],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(couponLocale(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(couponLocaleWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCouponLocale(a, b, extra)).toBe(expected);
    }
  });
}
