// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  expiryWindow,
  expiryWindowWithFee,
  clampExpiryWindow,
  factorFromBps,
} = require("./expiryWindow");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes expiryWindow for a clearance coupons row 1", "base", 156, 3, 165.8],
  ["applies the expiryWindow fee path for a vip coupons row 2", "fee", 95, 22, 131.8, 12],
  ["clamps expiryWindow for a loyalty coupons row 3", "clamp", 45.12, 40, 44, 44],
  ["computes expiryWindow for a holiday coupons row 4", "base", 213, 10, 240.56],
  ["applies the expiryWindow fee path for a welcome coupons row 5", "fee", 160, 2, 170.4, 2],
  ["clamps expiryWindow for a referral coupons row 6", "clamp", 122.77, 122, 122.77, 126],
  ["computes expiryWindow for a app coupons row 7", "base", 38, 15, 46.46],
  ["applies the expiryWindow fee path for a flash coupons row 8", "fee", 217, 9, 256.87, 14],
  ["clamps expiryWindow for a clearance coupons row 9", "clamp", 172.92, 169, 172.92, 173],
  ["computes expiryWindow for a vip coupons row 10", "base", 103, 20, 127.66],
  ["applies the expiryWindow fee path for a holiday coupons row 11", "fee", 125, 17, 162.75, 12],
  ["clamps expiryWindow for a loyalty coupons row 12", "clamp", 231.5, 233, 233, 237],
  ["computes expiryWindow for a vip coupons row 13", "base", 247, 4, 263.82],
  ["applies the expiryWindow fee path for a clearance coupons row 14", "fee", 68, 10, 78.16, 0],
  ["clamps expiryWindow for a flash coupons row 15", "clamp", 157.22, 152, 156, 156],
  ["computes expiryWindow for a app coupons row 16", "base", 190, 22, 237.6],
  ["applies the expiryWindow fee path for a referral coupons row 17", "fee", 11, 3, 16.55, 3],
  ["clamps expiryWindow for a welcome coupons row 18", "clamp", 83.92, 80, 83.92, 84],
  ["computes expiryWindow for a holiday coupons row 19", "base", 117, 19, 143.57],
  ["applies the expiryWindow fee path for a loyalty coupons row 20", "fee", 178, 0, 188.56, 5],
  ["clamps expiryWindow for a app coupons row 21", "clamp", 93.6, 95, 95, 99],
  ["computes expiryWindow for a flash coupons row 22", "base", 25, 2, 28],
  ["applies the expiryWindow fee path for a welcome coupons row 23", "fee", 208, 20, 260.76, 5],
  ["clamps expiryWindow for a referral coupons row 24", "clamp", 171.52, 171, 171.52, 175],
  ["computes expiryWindow for a loyalty coupons row 25", "base", 82, 9, 93.02],
  ["applies the expiryWindow fee path for a holiday coupons row 26", "fee", 21, 3, 37.05, 13],
  ["clamps expiryWindow for a clearance coupons row 27", "clamp", 252.92, 251, 252.92, 255],
  ["computes expiryWindow for a vip coupons row 28", "base", 143, 15, 169.31],
  ["applies the expiryWindow fee path for a app coupons row 29", "fee", 94, 6, 114.52, 11],
  ["clamps expiryWindow for a flash coupons row 30", "clamp", 32.66, 34, 34, 38],
  ["computes expiryWindow for a vip coupons row 31", "base", 175, 17, 210.25],
  ["applies the expiryWindow fee path for a clearance coupons row 32", "fee", 236, 23, 300, 3],
  ["clamps expiryWindow for a holiday coupons row 33", "clamp", 57.71, 57, 57.71, 61],
  ["computes expiryWindow for a loyalty coupons row 34", "base", 114, 11, 130.82],
  ["applies the expiryWindow fee path for a referral coupons row 35", "fee", 179, 16, 219.22, 6],
  ["clamps expiryWindow for a welcome coupons row 36", "clamp", 298.6, 298, 298.6, 302],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(expiryWindow(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(expiryWindowWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampExpiryWindow(a, b, extra)).toBe(expected);
    }
  });
}
