// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 2;
const FACTOR_BASE = 102;

function expiryWindow(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function expiryWindowWithFee(amount, factor, fee) {
  return expiryWindow(amount, factor) + fee;
}

function clampExpiryWindow(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  expiryWindow,
  expiryWindowWithFee,
  clampExpiryWindow,
  factorFromBps,
};
