// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 8;
const FACTOR_BASE = 111;

function firstOrder(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function firstOrderWithFee(amount, factor, fee) {
  return firstOrder(amount, factor) + fee;
}

function clampFirstOrder(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  firstOrder,
  firstOrderWithFee,
  clampFirstOrder,
  factorFromBps,
};
