// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 108;

function flashCode(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function flashCodeWithFee(amount, factor, fee) {
  return flashCode(amount, factor) + fee;
}

function clampFlashCode(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  flashCode,
  flashCodeWithFee,
  clampFlashCode,
  factorFromBps,
};
