// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 101;

function minSpend(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function minSpendWithFee(amount, factor, fee) {
  return minSpend(amount, factor) + fee;
}

function clampMinSpend(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  minSpend,
  minSpendWithFee,
  clampMinSpend,
  factorFromBps,
};
