// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 105;

function referralCredit(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function referralCreditWithFee(amount, factor, fee) {
  return referralCredit(amount, factor) + fee;
}

function clampReferralCredit(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  referralCredit,
  referralCreditWithFee,
  clampReferralCredit,
  factorFromBps,
};
