// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  skuRestrict,
  skuRestrictWithFee,
  clampSkuRestrict,
  factorFromBps,
} = require("./skuRestrict");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes skuRestrict for a clearance coupons row 1", "base", 28, 5, 43.44],
  ["applies the skuRestrict fee path for a vip coupons row 2", "fee", 207, 24, 306.94, 4],
  ["clamps skuRestrict for a loyalty coupons row 3", "clamp", 206.56, 206, 206.56, 210],
  ["computes skuRestrict for a holiday coupons row 4", "base", 85, 12, 119.5],
  ["applies the skuRestrict fee path for a welcome coupons row 5", "fee", 32, 4, 57.04, 9],
  ["clamps skuRestrict for a referral coupons row 6", "clamp", 308.51, 305, 308.51, 309],
  ["computes skuRestrict for a app coupons row 7", "base", 150, 17, 211.5],
  ["applies the skuRestrict fee path for a flash coupons row 8", "fee", 89, 11, 129.81, 6],
  ["clamps skuRestrict for a clearance coupons row 9", "clamp", 50.56, 51, 51, 55],
  ["computes skuRestrict for a vip coupons row 10", "base", 215, 22, 310],
  ["applies the skuRestrict fee path for a holiday coupons row 11", "fee", 77, 24, 127.34, 9],
  ["clamps skuRestrict for a loyalty coupons row 12", "clamp", 179.74, 177, 179.74, 181],
  ["computes skuRestrict for a vip coupons row 13", "base", 199, 11, 265.71],
  ["applies the skuRestrict fee path for a clearance coupons row 14", "fee", 20, 17, 48, 12],
  ["clamps skuRestrict for a flash coupons row 15", "clamp", 123.21, 121, 123.21, 125],
  ["computes skuRestrict for a app coupons row 16", "base", 142, 4, 182.24],
  ["applies the skuRestrict fee path for a referral coupons row 17", "fee", 203, 10, 268.84, 0],
  ["clamps skuRestrict for a welcome coupons row 18", "clamp", 40.16, 39, 40.16, 43],
  ["computes skuRestrict for a holiday coupons row 19", "base", 69, 1, 91.11],
  ["applies the skuRestrict fee path for a loyalty coupons row 20", "fee", 130, 7, 173.5, 2],
  ["clamps skuRestrict for a app coupons row 21", "clamp", 36.14, 37, 37, 41],
  ["computes skuRestrict for a flash coupons row 22", "base", 201, 13, 272.31],
  ["applies the skuRestrict fee path for a welcome coupons row 23", "fee", 144, 6, 188.56, 1],
  ["clamps skuRestrict for a referral coupons row 24", "clamp", 105.94, 105, 105.94, 109],
  ["computes skuRestrict for a loyalty coupons row 25", "base", 18, 20, 33.84],
  ["applies the skuRestrict fee path for a holiday coupons row 26", "fee", 197, 14, 278.04, 9],
  ["clamps skuRestrict for a clearance coupons row 27", "clamp", 184, 182, 184, 186],
  ["computes skuRestrict for a vip coupons row 28", "base", 79, 1, 103.01],
  ["applies the skuRestrict fee path for a app coupons row 29", "fee", 30, 17, 56.5, 7],
  ["clamps skuRestrict for a flash coupons row 30", "clamp", 275.61, 277, 277, 281],
  ["computes skuRestrict for a vip coupons row 31", "base", 111, 3, 143.31],
  ["applies the skuRestrict fee path for a clearance coupons row 32", "fee", 172, 9, 241.44, 14],
  ["clamps skuRestrict for a holiday coupons row 33", "clamp", 314.86, 314, 314.86, 318],
  ["computes skuRestrict for a loyalty coupons row 34", "base", 50, 22, 79],
  ["applies the skuRestrict fee path for a referral coupons row 35", "fee", 115, 2, 149, 2],
  ["clamps skuRestrict for a welcome coupons row 36", "clamp", 229.76, 229, 229.76, 233],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(skuRestrict(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(skuRestrictWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampSkuRestrict(a, b, extra)).toBe(expected);
    }
  });
}
