// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 106;

function stackRules(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function stackRulesWithFee(amount, factor, fee) {
  return stackRules(amount, factor) + fee;
}

function clampStackRules(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  stackRules,
  stackRulesWithFee,
  clampStackRules,
  factorFromBps,
};
