// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  stackRules,
  stackRulesWithFee,
  clampStackRules,
  factorFromBps,
} = require("./stackRules");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes stackRules for a welcome coupons row 1", "base", 64, 1, 73.48],
  ["applies the stackRules fee path for a referral coupons row 2", "fee", 243, 20, 321.18, 10],
  ["clamps stackRules for a app coupons row 3", "clamp", 220.4, 221, 221, 225],
  ["computes stackRules for a flash coupons row 4", "base", 121, 8, 142.94],
  ["applies the stackRules fee path for a clearance coupons row 5", "fee", 60, 2, 76.8, 7],
  ["clamps stackRules for a vip coupons row 6", "clamp", 306.53, 307, 307, 311],
  ["computes stackRules for a loyalty coupons row 7", "base", 178, 15, 220.38],
  ["applies the stackRules fee path for a holiday coupons row 8", "fee", 117, 9, 143.55, 4],
  ["clamps stackRules for a welcome coupons row 9", "clamp", 101.6, 97, 101, 101],
  ["computes stackRules for a referral coupons row 10", "base", 11, 18, 18.64],
  ["applies the stackRules fee path for a flash coupons row 11", "fee", 105, 2, 125.4, 7],
  ["clamps stackRules for a app coupons row 12", "clamp", 193.24, 192, 193.24, 196],
  ["computes stackRules for a referral coupons row 13", "base", 227, 14, 277.4],
  ["applies the stackRules fee path for a welcome coupons row 14", "fee", 48, 20, 75.48, 10],
  ["clamps stackRules for a holiday coupons row 15", "clamp", 100.05, 99, 100.05, 103],
  ["computes stackRules for a loyalty coupons row 16", "base", 146, 13, 178.74],
  ["applies the stackRules fee path for a vip coupons row 17", "fee", 207, 19, 267.75, 4],
  ["clamps stackRules for a clearance coupons row 18", "clamp", 62.88, 59, 62.88, 63],
  ["computes stackRules for a flash coupons row 19", "base", 113, 0, 124.78],
  ["applies the stackRules fee path for a app coupons row 20", "fee", 174, 6, 200.88, 1],
  ["clamps stackRules for a loyalty coupons row 21", "clamp", 219.38, 218, 219.38, 222],
  ["computes stackRules for a holiday coupons row 22", "base", 117, 9, 139.55],
  ["applies the stackRules fee path for a clearance coupons row 23", "fee", 60, 2, 76.8, 7],
  ["clamps stackRules for a vip coupons row 24", "clamp", 309.53, 307, 309.53, 311],
  ["computes stackRules for a app coupons row 25", "base", 182, 14, 223.4],
  ["applies the stackRules fee path for a flash coupons row 26", "fee", 121, 8, 150.94, 8],
  ["clamps stackRules for a welcome coupons row 27", "clamp", 108.4, 105, 108.4, 109],
  ["computes stackRules for a referral coupons row 28", "base", 19, 16, 28.18],
  ["applies the stackRules fee path for a loyalty coupons row 29", "fee", 202, 9, 251.3, 14],
  ["clamps stackRules for a holiday coupons row 30", "clamp", 161.69, 157, 161, 161],
  ["computes stackRules for a referral coupons row 31", "base", 171, 23, 225.59],
  ["applies the stackRules fee path for a welcome coupons row 32", "fee", 232, 4, 274.2, 14],
  ["clamps stackRules for a flash coupons row 33", "clamp", 60.33, 60, 60.33, 64],
  ["computes stackRules for a app coupons row 34", "base", 110, 17, 140.3],
  ["applies the stackRules fee path for a vip coupons row 35", "fee", 167, 24, 231.1, 9],
  ["clamps stackRules for a clearance coupons row 36", "clamp", 261.08, 256, 260, 260],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(stackRules(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(stackRulesWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampStackRules(a, b, extra)).toBe(expected);
    }
  });
}
