// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  cartExpiry,
  cartExpiryWithFee,
  clampCartExpiry,
  factorFromBps,
} = require("./cartExpiry");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes cartExpiry for a tote cart row 1", "base", 173, 5, 221.98],
  ["applies the cartExpiry fee path for a hoodie cart row 2", "fee", 234, 11, 313.88, 1],
  ["clamps cartExpiry for a socks cart row 3", "clamp", 77.9, 78, 78, 82],
  ["computes cartExpiry for a bottle cart row 4", "base", 116, 23, 171.04],
  ["applies the cartExpiry fee path for a tee cart row 5", "fee", 177, 4, 229.25, 4],
  ["clamps cartExpiry for a cap cart row 6", "clamp", 312.78, 314, 314, 318],
  ["computes cartExpiry for a sticker cart row 7", "base", 59, 16, 84.83],
  ["applies the cartExpiry fee path for a mug cart row 8", "fee", 120, 22, 182.6, 7],
  ["clamps cartExpiry for a tote cart row 9", "clamp", 214.2, 213, 214.2, 217],
  ["computes cartExpiry for a hoodie cart row 10", "base", 226, 13, 306.84],
  ["applies the cartExpiry fee path for a cap cart row 11", "fee", 238, 10, 320.78, 5],
  ["clamps cartExpiry for a tee cart row 12", "clamp", 228.25, 223, 227, 227],
  ["computes cartExpiry for a mug cart row 13", "base", 120, 22, 175.6],
  ["applies the cartExpiry fee path for a sticker cart row 14", "fee", 59, 16, 90.83, 6],
  ["clamps cartExpiry for a hoodie cart row 15", "clamp", 309.88, 311, 311, 315],
  ["computes cartExpiry for a tote cart row 16", "base", 173, 5, 221.98],
  ["applies the cartExpiry fee path for a bottle cart row 17", "fee", 116, 23, 174.04, 3],
  ["clamps cartExpiry for a socks cart row 18", "clamp", 78.9, 78, 78.9, 82],
  ["computes cartExpiry for a cap cart row 19", "base", 230, 12, 309.9],
  ["applies the cartExpiry fee path for a tee cart row 20", "fee", 169, 6, 229.63, 11],
  ["clamps cartExpiry for a tote cart row 21", "clamp", 33.24, 32, 33.24, 36],
  ["computes cartExpiry for a hoodie cart row 22", "base", 82, 4, 106.5],
  ["applies the cartExpiry fee path for a socks cart row 23", "fee", 143, 10, 191.33, 0],
  ["clamps cartExpiry for a bottle cart row 24", "clamp", 281.48, 281, 281.48, 285],
  ["computes cartExpiry for a tee cart row 25", "base", 25, 22, 39.75],
  ["applies the cartExpiry fee path for a cap cart row 26", "fee", 86, 3, 113.64, 3],
  ["clamps cartExpiry for a sticker cart row 27", "clamp", 192.1, 193, 193, 197],
  ["computes cartExpiry for a mug cart row 28", "base", 208, 15, 286.88],
  ["applies the cartExpiry fee path for a tote cart row 29", "fee", 29, 21, 51.18, 6],
  ["clamps cartExpiry for a hoodie cart row 30", "clamp", 117.7, 113, 117, 117],
  ["computes cartExpiry for a bottle cart row 31", "base", 172, 14, 236.2],
  ["applies the cartExpiry fee path for a socks cart row 32", "fee", 111, 8, 160.19, 13],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(cartExpiry(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(cartExpiryWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCartExpiry(a, b, extra)).toBe(expected);
    }
  });
}
