// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 138;

function cartWeight(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function cartWeightWithFee(amount, factor, fee) {
  return cartWeight(amount, factor) + fee;
}

function clampCartWeight(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  cartWeight,
  cartWeightWithFee,
  clampCartWeight,
  factorFromBps,
};
