// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 121;

function cartExpiry(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function cartExpiryWithFee(amount, factor, fee) {
  return cartExpiry(amount, factor) + fee;
}

function clampCartExpiry(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  cartExpiry,
  cartExpiryWithFee,
  clampCartExpiry,
  factorFromBps,
};
