// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  cartSubtotal,
  cartSubtotalWithFee,
  clampCartSubtotal,
  factorFromBps,
} = require("./cartSubtotal");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes cartSubtotal for a mug cart row 1", "base", 8, 15, 14.6],
  ["applies the cartSubtotal fee path for a sticker cart row 2", "fee", 187, 9, 276.93, 14],
  ["clamps cartSubtotal for a cap cart row 3", "clamp", 172.58, 169, 172.58, 173],
  ["computes cartSubtotal for a tee cart row 4", "base", 65, 22, 101.8],
  ["applies the cartSubtotal fee path for a bottle cart row 5", "fee", 244, 16, 370.24, 11],
  ["clamps cartSubtotal for a socks cart row 6", "clamp", 262.2, 257, 261, 261],
  ["computes cartSubtotal for a hoodie cart row 7", "base", 122, 4, 166.48],
  ["applies the cartSubtotal fee path for a tote cart row 8", "fee", 61, 23, 104.33, 8],
  ["clamps cartSubtotal for a mug cart row 9", "clamp", 352.8, 354, 354, 358],
  ["computes cartSubtotal for a sticker cart row 10", "base", 179, 11, 255.39],
  ["applies the cartSubtotal fee path for a tee cart row 11", "fee", 17, 19, 37.33, 9],
  ["clamps cartSubtotal for a cap cart row 12", "clamp", 104.4, 102, 104.4, 106],
  ["computes cartSubtotal for a sticker cart row 13", "base", 139, 6, 192.04],
  ["applies the cartSubtotal fee path for a mug cart row 14", "fee", 200, 12, 299, 12],
  ["clamps cartSubtotal for a tote cart row 15", "clamp", 19.5, 21, 21, 25],
  ["computes cartSubtotal for a hoodie cart row 16", "base", 74, 1, 99.94],
  ["applies the cartSubtotal fee path for a socks cart row 17", "fee", 135, 7, 194.95, 7],
  ["clamps cartSubtotal for a bottle cart row 18", "clamp", 286.28, 281, 285, 285],
  ["computes cartSubtotal for a tee cart row 19", "base", 9, 21, 16.59],
  ["applies the cartSubtotal fee path for a cap cart row 20", "fee", 70, 2, 97.4, 2],
  ["clamps cartSubtotal for a hoodie cart row 21", "clamp", 140.98, 142, 142, 146],
  ["computes cartSubtotal for a tote cart row 22", "base", 45, 22, 71.4],
  ["applies the cartSubtotal fee path for a bottle cart row 23", "fee", 228, 15, 343.6, 10],
  ["clamps cartSubtotal for a socks cart row 24", "clamp", 234.13, 233, 234.13, 237],
  ["computes cartSubtotal for a cap cart row 25", "base", 110, 2, 148.2],
  ["applies the cartSubtotal fee path for a tee cart row 26", "fee", 49, 21, 87.99, 11],
  ["clamps cartSubtotal for a mug cart row 27", "clamp", 339.08, 335, 339, 339],
  ["computes cartSubtotal for a sticker cart row 28", "base", 171, 8, 238.98],
  ["applies the cartSubtotal fee path for a hoodie cart row 29", "fee", 98, 5, 135.3, 0],
  ["clamps cartSubtotal for a tote cart row 30", "clamp", 59.98, 58, 59.98, 62],
  ["computes cartSubtotal for a sticker cart row 31", "base", 195, 12, 279.9],
  ["applies the cartSubtotal fee path for a mug cart row 32", "fee", 16, 18, 34.68, 8],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(cartSubtotal(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(cartSubtotalWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCartSubtotal(a, b, extra)).toBe(expected);
    }
  });
}
