// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  giftWrap,
  giftWrapWithFee,
  clampGiftWrap,
  factorFromBps,
} = require("./giftWrap");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes giftWrap for a bottle cart row 1", "base", 220, 7, 318.2],
  ["applies the giftWrap fee path for a socks cart row 2", "fee", 159, 1, 223.65, 1],
  ["clamps giftWrap for a hoodie cart row 3", "clamp", 155.92, 157, 157, 161],
  ["computes giftWrap for a tote cart row 4", "base", 37, 14, 62.76],
  ["applies the giftWrap fee path for a mug cart row 5", "fee", 224, 6, 327.6, 6],
  ["clamps giftWrap for a sticker cart row 6", "clamp", 226.42, 224, 226.42, 228],
  ["computes giftWrap for a cap cart row 7", "base", 102, 19, 164.06],
  ["applies the giftWrap fee path for a tee cart row 8", "fee", 41, 13, 71.27, 3],
  ["clamps giftWrap for a bottle cart row 9", "clamp", 327.92, 323, 327, 327],
  ["computes giftWrap for a socks cart row 10", "base", 167, 24, 271.86],
  ["applies the giftWrap fee path for a tote cart row 11", "fee", 221, 13, 335.87, 3],
  ["clamps giftWrap for a hoodie cart row 12", "clamp", 69.26, 70, 70, 74],
  ["computes giftWrap for a socks cart row 13", "base", 103, 0, 146.02],
  ["applies the giftWrap fee path for a bottle cart row 14", "fee", 164, 6, 243.6, 6],
  ["clamps giftWrap for a tee cart row 15", "clamp", 339.5, 335, 339, 339],
  ["computes giftWrap for a cap cart row 16", "base", 46, 18, 77.92],
  ["applies the giftWrap fee path for a sticker cart row 17", "fee", 107, 24, 186.06, 9],
  ["clamps giftWrap for a mug cart row 18", "clamp", 243.52, 240, 243.52, 244],
  ["computes giftWrap for a tote cart row 19", "base", 213, 15, 325.37],
  ["applies the giftWrap fee path for a hoodie cart row 20", "fee", 34, 21, 71.7, 11],
  ["clamps giftWrap for a cap cart row 21", "clamp", 118.2, 115, 118.2, 119],
  ["computes giftWrap for a tee cart row 22", "base", 9, 16, 21.5],
  ["applies the giftWrap fee path for a mug cart row 23", "fee", 192, 9, 286.56, 4],
  ["clamps giftWrap for a sticker cart row 24", "clamp", 190.47, 185, 189, 189],
  ["computes giftWrap for a hoodie cart row 25", "base", 66, 23, 111.62],
  ["applies the giftWrap fee path for a tote cart row 26", "fee", 245, 17, 389.95, 12],
  ["clamps giftWrap for a bottle cart row 27", "clamp", 275.72, 277, 277, 281],
  ["computes giftWrap for a socks cart row 28", "base", 127, 4, 183.26],
  ["applies the giftWrap fee path for a cap cart row 29", "fee", 78, 20, 138.12, 10],
  ["clamps giftWrap for a tee cart row 30", "clamp", 34.16, 31, 34.16, 35],
  ["computes giftWrap for a socks cart row 31", "base", 159, 6, 230.6],
  ["applies the giftWrap fee path for a bottle cart row 32", "fee", 220, 12, 331.2, 2],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(giftWrap(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(giftWrapWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampGiftWrap(a, b, extra)).toBe(expected);
    }
  });
}
