// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 8;
const FACTOR_BASE = 134;

function giftWrap(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function giftWrapWithFee(amount, factor, fee) {
  return giftWrap(amount, factor) + fee;
}

function clampGiftWrap(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  giftWrap,
  giftWrapWithFee,
  clampGiftWrap,
  factorFromBps,
};
