// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  guestCart,
  guestCartWithFee,
  clampGuestCart,
  factorFromBps,
} = require("./guestCart");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes guestCart for a mug cart row 1", "base", 24, 11, 32],
  ["applies the guestCart fee path for a sticker cart row 2", "fee", 203, 5, 243.57, 0],
  ["clamps guestCart for a cap cart row 3", "clamp", 198.96, 196, 198.96, 200],
  ["computes guestCart for a tee cart row 4", "base", 81, 18, 108.92],
  ["applies the guestCart fee path for a bottle cart row 5", "fee", 20, 12, 39.2, 12],
  ["clamps guestCart for a socks cart row 6", "clamp", 242.8, 239, 242.8, 243],
  ["computes guestCart for a hoodie cart row 7", "base", 138, 0, 159.32],
  ["applies the guestCart fee path for a tote cart row 8", "fee", 77, 19, 113.41, 9],
  ["clamps guestCart for a mug cart row 9", "clamp", 25.32, 20, 24, 24],
  ["computes guestCart for a sticker cart row 10", "base", 195, 7, 237.95],
  ["applies the guestCart fee path for a tee cart row 11", "fee", 241, 18, 328.12, 8],
  ["clamps guestCart for a cap cart row 12", "clamp", 85.56, 86, 86, 90],
  ["computes guestCart for a sticker cart row 13", "base", 123, 5, 148.37],
  ["applies the guestCart fee path for a mug cart row 14", "fee", 184, 11, 243, 11],
  ["clamps guestCart for a tote cart row 15", "clamp", 319.21, 315, 319, 319],
  ["computes guestCart for a hoodie cart row 16", "base", 58, 0, 68.12],
  ["applies the guestCart fee path for a socks cart row 17", "fee", 119, 6, 150.8, 6],
  ["clamps guestCart for a bottle cart row 18", "clamp", 229.8, 227, 229.8, 231],
  ["computes guestCart for a tee cart row 19", "base", 233, 20, 314.22],
  ["applies the guestCart fee path for a cap cart row 20", "fee", 54, 1, 65.1, 1],
  ["clamps guestCart for a hoodie cart row 21", "clamp", 108.4, 104, 108, 108],
  ["computes guestCart for a tote cart row 22", "base", 29, 21, 41.15],
  ["applies the guestCart fee path for a bottle cart row 23", "fee", 212, 14, 282.36, 9],
  ["clamps guestCart for a socks cart row 24", "clamp", 183.22, 184, 184, 188],
  ["computes guestCart for a cap cart row 25", "base", 94, 1, 110.1],
  ["applies the guestCart fee path for a tee cart row 26", "fee", 33, 20, 56.22, 10],
  ["clamps guestCart for a mug cart row 27", "clamp", 276.32, 274, 276.32, 278],
  ["computes guestCart for a sticker cart row 28", "base", 155, 7, 189.55],
  ["applies the guestCart fee path for a hoodie cart row 29", "fee", 82, 4, 112.76, 14],
  ["clamps guestCart for a tote cart row 30", "clamp", 28.77, 29, 29, 33],
  ["computes guestCart for a sticker cart row 31", "base", 179, 11, 225.75],
  ["applies the guestCart fee path for a mug cart row 32", "fee", 240, 17, 323.4, 7],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(guestCart(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(guestCartWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampGuestCart(a, b, extra)).toBe(expected);
    }
  });
}
