// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 101;

function lineItem(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function lineItemWithFee(amount, factor, fee) {
  return lineItem(amount, factor) + fee;
}

function clampLineItem(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  lineItem,
  lineItemWithFee,
  clampLineItem,
  factorFromBps,
};
