// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  mergeCarts,
  mergeCartsWithFee,
  clampMergeCarts,
  factorFromBps,
} = require("./mergeCarts");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes mergeCarts for a socks cart row 1", "base", 183, 15, 251.22],
  ["applies the mergeCarts fee path for a bottle cart row 2", "fee", 244, 21, 358.6, 11],
  ["clamps mergeCarts for a tote cart row 3", "clamp", 81.42, 78, 81.42, 82],
  ["computes mergeCarts for a hoodie cart row 4", "base", 122, 9, 162.16],
  ["applies the mergeCarts fee path for a sticker cart row 5", "fee", 187, 14, 268.71000000000004, 14],
  ["clamps mergeCarts for a mug cart row 6", "clamp", 18.12, 15, 18.12, 19],
  ["computes mergeCarts for a tee cart row 7", "base", 65, 2, 84.65],
  ["applies the mergeCarts fee path for a cap cart row 8", "fee", 126, 8, 179.02, 13],
  ["clamps mergeCarts for a socks cart row 9", "clamp", 247, 242, 246, 246],
  ["computes mergeCarts for a bottle cart row 10", "base", 236, 23, 341.12],
  ["applies the mergeCarts fee path for a bottle cart row 11", "fee", 92, 19, 141.96, 9],
  ["clamps mergeCarts for a socks cart row 12", "clamp", 47.92, 45, 47.92, 49],
  ["computes mergeCarts for a hoodie cart row 13", "base", 210, 7, 270.6],
  ["applies the mergeCarts fee path for a tote cart row 14", "fee", 149, 1, 190.8, 6],
  ["clamps mergeCarts for a mug cart row 15", "clamp", 134.52, 136, 136, 140],
  ["computes mergeCarts for a sticker cart row 16", "base", 35, 12, 51.85],
  ["applies the mergeCarts fee path for a cap cart row 17", "fee", 214, 6, 284.5, 11],
  ["clamps mergeCarts for a tee cart row 18", "clamp", 186.07, 186, 186.07, 190],
  ["computes mergeCarts for a bottle cart row 19", "base", 100, 17, 142],
  ["applies the mergeCarts fee path for a socks cart row 20", "fee", 39, 11, 57.7, 1],
  ["clamps mergeCarts for a socks cart row 21", "clamp", 359.21, 357, 359.21, 361],
  ["computes mergeCarts for a bottle cart row 22", "base", 68, 5, 90.32],
  ["applies the mergeCarts fee path for a tote cart row 23", "fee", 125, 12, 181.75, 12],
  ["clamps mergeCarts for a hoodie cart row 24", "clamp", 258.82, 259, 259, 263],
  ["computes mergeCarts for a sticker cart row 25", "base", 11, 23, 21.62],
  ["applies the mergeCarts fee path for a mug cart row 26", "fee", 72, 4, 98.56, 4],
  ["clamps mergeCarts for a tee cart row 27", "clamp", 170.7, 172, 172, 176],
  ["computes mergeCarts for a cap cart row 28", "base", 190, 17, 264.4],
  ["applies the mergeCarts fee path for a socks cart row 29", "fee", 239, 1, 298.8, 6],
  ["clamps mergeCarts for a bottle cart row 30", "clamp", 81.6, 80, 81.6, 84],
  ["computes mergeCarts for a cap cart row 31", "base", 62, 4, 82.26],
  ["applies the mergeCarts fee path for a tee cart row 32", "fee", 241, 23, 356.22, 8],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(mergeCarts(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(mergeCartsWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampMergeCarts(a, b, extra)).toBe(expected);
    }
  });
}
