// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  quantityGuard,
  quantityGuardWithFee,
  clampQuantityGuard,
  factorFromBps,
} = require("./quantityGuard");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes quantityGuard for a mug cart row 1", "base", 152, 24, 236.08],
  ["applies the quantityGuard fee path for a sticker cart row 2", "fee", 91, 18, 144.68, 8],
  ["clamps quantityGuard for a cap cart row 3", "clamp", 46.6, 43, 46.6, 47],
  ["computes quantityGuard for a tee cart row 4", "base", 209, 6, 286.24],
  ["applies the quantityGuard fee path for a bottle cart row 5", "fee", 148, 0, 199.4, 5],
  ["clamps quantityGuard for a socks cart row 6", "clamp", 134.63, 130, 134, 134],
  ["computes quantityGuard for a hoodie cart row 7", "base", 26, 13, 39.18],
  ["applies the quantityGuard fee path for a tote cart row 8", "fee", 205, 7, 284.85, 2],
  ["clamps quantityGuard for a mug cart row 9", "clamp", 187.64, 189, 189, 193],
  ["computes quantityGuard for a sticker cart row 10", "base", 83, 20, 126.5],
  ["applies the quantityGuard fee path for a tee cart row 11", "fee", 81, 8, 126.78, 13],
  ["clamps quantityGuard for a cap cart row 12", "clamp", 204.48, 204, 204.48, 208],
  ["computes quantityGuard for a sticker cart row 13", "base", 203, 20, 306.5],
  ["applies the quantityGuard fee path for a mug cart row 14", "fee", 24, 1, 34.44, 1],
  ["clamps quantityGuard for a tote cart row 15", "clamp", 111.03, 107, 111, 111],
  ["computes quantityGuard for a hoodie cart row 16", "base", 138, 15, 202.1],
  ["applies the quantityGuard fee path for a socks cart row 17", "fee", 199, 21, 313.49, 11],
  ["clamps quantityGuard for a bottle cart row 18", "clamp", 29.4, 26, 29.4, 30],
  ["computes quantityGuard for a tee cart row 19", "base", 73, 10, 104.2],
  ["applies the quantityGuard fee path for a cap cart row 20", "fee", 134, 16, 203.64, 6],
  ["clamps quantityGuard for a hoodie cart row 21", "clamp", 253.9, 250, 253.9, 254],
  ["computes quantityGuard for a tote cart row 22", "base", 109, 11, 155.69],
  ["applies the quantityGuard fee path for a bottle cart row 23", "fee", 52, 4, 85.68, 14],
  ["clamps quantityGuard for a socks cart row 24", "clamp", 352.43, 353, 353, 357],
  ["computes quantityGuard for a cap cart row 25", "base", 174, 16, 256.04],
  ["applies the quantityGuard fee path for a tee cart row 26", "fee", 113, 10, 160.2, 0],
  ["clamps quantityGuard for a mug cart row 27", "clamp", 76.48, 74, 76.48, 78],
  ["computes quantityGuard for a sticker cart row 28", "base", 235, 22, 359.2],
  ["applies the quantityGuard fee path for a hoodie cart row 29", "fee", 162, 19, 247.38, 4],
  ["clamps quantityGuard for a tote cart row 30", "clamp", 144.43, 144, 144.43, 148],
  ["computes quantityGuard for a sticker cart row 31", "base", 19, 1, 26.89],
  ["applies the quantityGuard fee path for a mug cart row 32", "fee", 80, 7, 123.6, 12],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(quantityGuard(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(quantityGuardWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampQuantityGuard(a, b, extra)).toBe(expected);
    }
  });
}
