// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 115;

function removeItem(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function removeItemWithFee(amount, factor, fee) {
  return removeItem(amount, factor) + fee;
}

function clampRemoveItem(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  removeItem,
  removeItemWithFee,
  clampRemoveItem,
  factorFromBps,
};
