// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  saveForLater,
  saveForLaterWithFee,
  clampSaveForLater,
  factorFromBps,
} = require("./saveForLater");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes saveForLater for a bottle cart row 1", "base", 12, 19, 24.4],
  ["applies the saveForLater fee path for a socks cart row 2", "fee", 191, 13, 275.49, 3],
  ["clamps saveForLater for a hoodie cart row 3", "clamp", 179.9, 178, 179.9, 182],
  ["computes saveForLater for a tote cart row 4", "base", 69, 1, 94.63],
  ["applies the saveForLater fee path for a mug cart row 5", "fee", 16, 18, 38.04, 8],
  ["clamps saveForLater for a sticker cart row 6", "clamp", 279.1, 274, 278, 278],
  ["computes saveForLater for a cap cart row 7", "base", 134, 6, 183.88],
  ["applies the saveForLater fee path for a tee cart row 8", "fee", 73, 0, 103.98, 5],
  ["clamps saveForLater for a bottle cart row 9", "clamp", 34.6, 34, 34.6, 38],
  ["computes saveForLater for a socks cart row 10", "base", 199, 11, 279.63],
  ["applies the saveForLater fee path for a tote cart row 11", "fee", 13, 5, 29.03, 5],
  ["clamps saveForLater for a hoodie cart row 12", "clamp", 109.38, 106, 109.38, 110],
  ["computes saveForLater for a socks cart row 13", "base", 135, 17, 200.05],
  ["applies the saveForLater fee path for a bottle cart row 14", "fee", 196, 23, 307.04, 8],
  ["clamps saveForLater for a tee cart row 15", "clamp", 29.1, 27, 29.1, 31],
  ["computes saveForLater for a cap cart row 16", "base", 78, 10, 113.08],
  ["applies the saveForLater fee path for a sticker cart row 17", "fee", 139, 16, 215.38, 11],
  ["clamps saveForLater for a mug cart row 18", "clamp", 302, 301, 302, 305],
  ["computes saveForLater for a tote cart row 19", "base", 229, 11, 320.73],
  ["applies the saveForLater fee path for a hoodie cart row 20", "fee", 50, 17, 90.5, 12],
  ["clamps saveForLater for a cap cart row 21", "clamp", 131.84, 129, 131.84, 133],
  ["computes saveForLater for a tee cart row 22", "base", 25, 12, 41.5],
  ["applies the saveForLater fee path for a mug cart row 23", "fee", 224, 1, 297.48, 6],
  ["clamps saveForLater for a sticker cart row 24", "clamp", 230.5, 226, 230, 230],
  ["computes saveForLater for a hoodie cart row 25", "base", 82, 19, 125.9],
  ["applies the saveForLater fee path for a tote cart row 26", "fee", 21, 13, 49.19, 13],
  ["clamps saveForLater for a bottle cart row 27", "clamp", 273.28, 274, 274, 278],
  ["computes saveForLater for a socks cart row 28", "base", 143, 0, 187.18],
  ["applies the saveForLater fee path for a cap cart row 29", "fee", 110, 12, 170.8, 12],
  ["clamps saveForLater for a tee cart row 30", "clamp", 69.68, 70, 70, 74],
  ["computes saveForLater for a socks cart row 31", "base", 175, 2, 231],
  ["applies the saveForLater fee path for a bottle cart row 32", "fee", 236, 8, 326.24, 3],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(saveForLater(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(saveForLaterWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampSaveForLater(a, b, extra)).toBe(expected);
    }
  });
}
