// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  backorder,
  backorderWithFee,
  clampBackorder,
  factorFromBps,
} = require("./backorder");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes backorder for a overflow inventory row 1", "base", 229, 11, 284.96],
  ["applies the backorder fee path for a bulk inventory row 2", "fee", 50, 17, 78, 12],
  ["clamps backorder for a hazmat inventory row 3", "clamp", 154.96, 150, 154, 154],
  ["computes backorder for a returns inventory row 4", "base", 172, 4, 202.24],
  ["applies the backorder fee path for a west inventory row 5", "fee", 233, 10, 287.59, 0],
  ["clamps backorder for a cold inventory row 6", "clamp", 72.66, 69, 72.66, 73],
  ["computes backorder for a retail inventory row 7", "base", 115, 22, 156.25],
  ["applies the backorder fee path for a east inventory row 8", "fee", 176, 3, 208.16, 3],
  ["clamps backorder for a overflow inventory row 9", "clamp", 291.14, 288, 291.14, 292],
  ["computes backorder for a bulk inventory row 10", "base", 58, 15, 75.24],
  ["applies the backorder fee path for a cold inventory row 11", "fee", 102, 9, 129.44, 4],
  ["clamps backorder for a west inventory row 12", "clamp", 45.56, 47, 47, 51],
  ["computes backorder for a east inventory row 13", "base", 224, 21, 301.16],
  ["applies the backorder fee path for a retail inventory row 14", "fee", 163, 15, 214.64, 5],
  ["clamps backorder for a bulk inventory row 15", "clamp", 119.54, 120, 120, 124],
  ["computes backorder for a overflow inventory row 16", "base", 37, 4, 44.29],
  ["applies the backorder fee path for a returns inventory row 17", "fee", 220, 22, 300, 2],
  ["clamps backorder for a hazmat inventory row 18", "clamp", 206.11, 204, 206.11, 208],
  ["computes backorder for a cold inventory row 19", "base", 110, 7, 133],
  ["applies the backorder fee path for a west inventory row 20", "fee", 49, 1, 67.86, 11],
  ["clamps backorder for a overflow inventory row 21", "clamp", 15.69, 14, 15.69, 18],
  ["computes backorder for a bulk inventory row 22", "base", 74, 6, 89.06],
  ["applies the backorder fee path for a hazmat inventory row 23", "fee", 135, 12, 176.75, 7],
  ["clamps backorder for a returns inventory row 24", "clamp", 256.76, 256, 256.76, 260],
  ["computes backorder for a west inventory row 25", "base", 17, 24, 24.29],
  ["applies the backorder fee path for a cold inventory row 26", "fee", 78, 5, 103.04, 10],
  ["clamps backorder for a retail inventory row 27", "clamp", 171.36, 171, 171.36, 175],
  ["computes backorder for a east inventory row 28", "base", 200, 17, 261],
  ["applies the backorder fee path for a overflow inventory row 29", "fee", 245, 2, 294.75, 12],
  ["clamps backorder for a bulk inventory row 30", "clamp", 80.86, 79, 80.86, 83],
  ["computes backorder for a returns inventory row 31", "base", 164, 16, 212.56],
  ["applies the backorder fee path for a hazmat inventory row 32", "fee", 103, 10, 132.69, 5],
  ["clamps backorder for a bulk inventory row 33", "clamp", 47.14, 48, 48, 52],
  ["computes backorder for a overflow inventory row 34", "base", 221, 23, 301.56],
  ["applies the backorder fee path for a east inventory row 35", "fee", 168, 15, 226.04, 10],
  ["clamps backorder for a retail inventory row 36", "clamp", 131.54, 130, 131.54, 134],
  ["computes backorder for a cold inventory row 37", "base", 46, 3, 54.36],
  ["applies the backorder fee path for a west inventory row 38", "fee", 225, 22, 311.75, 7],
  ["clamps backorder for a returns inventory row 39", "clamp", 204.36, 203, 204.36, 207],
  ["computes backorder for a hazmat inventory row 40", "base", 95, 12, 119.75],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(backorder(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(backorderWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampBackorder(a, b, extra)).toBe(expected);
    }
  });
}
