// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  inboundAsn,
  inboundAsnWithFee,
  clampInboundAsn,
  factorFromBps,
} = require("./inboundAsn");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes inboundAsn for a west inventory row 1", "base", 201, 8, 271.33],
  ["applies the inboundAsn fee path for a cold inventory row 2", "fee", 22, 14, 48.58, 14],
  ["clamps inboundAsn for a retail inventory row 3", "clamp", 125.35, 122, 125.35, 126],
  ["computes inboundAsn for a east inventory row 4", "base", 144, 1, 185.44],
  ["applies the inboundAsn fee path for a overflow inventory row 5", "fee", 197, 9, 276.98, 9],
  ["clamps inboundAsn for a bulk inventory row 6", "clamp", 27.2, 27, 27.2, 31],
  ["computes inboundAsn for a hazmat inventory row 7", "base", 79, 21, 119.34],
  ["applies the inboundAsn fee path for a returns inventory row 8", "fee", 140, 2, 193.8, 12],
  ["clamps inboundAsn for a west inventory row 9", "clamp", 276.79, 276, 276.79, 280],
  ["computes inboundAsn for a cold inventory row 10", "base", 30, 12, 45.1],
  ["applies the inboundAsn fee path for a bulk inventory row 11", "fee", 162, 14, 233.18, 4],
  ["clamps inboundAsn for a overflow inventory row 12", "clamp", 137.33, 136, 137.33, 140],
  ["computes inboundAsn for a returns inventory row 13", "base", 44, 1, 59.44],
  ["applies the inboundAsn fee path for a hazmat inventory row 14", "fee", 223, 20, 332.35, 5],
  ["clamps inboundAsn for a cold inventory row 15", "clamp", 235.08, 231, 235, 235],
  ["computes inboundAsn for a west inventory row 16", "base", 105, 7, 142.6],
  ["applies the inboundAsn fee path for a east inventory row 17", "fee", 48, 0, 74, 10],
  ["clamps inboundAsn for a retail inventory row 18", "clamp", 327.88, 329, 329, 333],
  ["computes inboundAsn for a bulk inventory row 19", "base", 170, 12, 236.9],
  ["applies the inboundAsn fee path for a overflow inventory row 20", "fee", 109, 6, 157.79, 11],
  ["clamps inboundAsn for a west inventory row 21", "clamp", 319.48, 314, 318, 318],
  ["computes inboundAsn for a cold inventory row 22", "base", 38, 0, 51.5],
  ["applies the inboundAsn fee path for a retail inventory row 23", "fee", 99, 6, 134.69, 1],
  ["clamps inboundAsn for a east inventory row 24", "clamp", 225.2, 221, 225, 225],
  ["computes inboundAsn for a overflow inventory row 25", "base", 213, 20, 312.85],
  ["applies the inboundAsn fee path for a bulk inventory row 26", "fee", 34, 1, 57.84, 11],
  ["clamps inboundAsn for a hazmat inventory row 27", "clamp", 128.4, 127, 128.4, 131],
  ["computes inboundAsn for a returns inventory row 28", "base", 156, 13, 219.28],
  ["applies the inboundAsn fee path for a west inventory row 29", "fee", 225, 17, 330.5, 7],
  ["clamps inboundAsn for a cold inventory row 30", "clamp", 72.08, 70, 72.08, 74],
  ["computes inboundAsn for a east inventory row 31", "base", 128, 10, 176.8],
  ["applies the inboundAsn fee path for a retail inventory row 32", "fee", 67, 4, 104.43, 14],
  ["clamps inboundAsn for a cold inventory row 33", "clamp", 368.08, 366, 368.08, 370],
  ["computes inboundAsn for a west inventory row 34", "base", 185, 17, 266.7],
  ["applies the inboundAsn fee path for a returns inventory row 35", "fee", 124, 11, 183.64, 11],
  ["clamps inboundAsn for a hazmat inventory row 36", "clamp", 86.9, 84, 86.9, 88],
  ["computes inboundAsn for a bulk inventory row 37", "base", 242, 24, 364.58],
  ["applies the inboundAsn fee path for a overflow inventory row 38", "fee", 181, 18, 270.83, 8],
  ["clamps inboundAsn for a east inventory row 39", "clamp", 183.88, 183, 183.88, 187],
  ["computes inboundAsn for a retail inventory row 40", "base", 75, 2, 99.25],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(inboundAsn(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(inboundAsnWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampInboundAsn(a, b, extra)).toBe(expected);
    }
  });
}
