// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 125;

function inboundAsn(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function inboundAsnWithFee(amount, factor, fee) {
  return inboundAsn(amount, factor) + fee;
}

function clampInboundAsn(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  inboundAsn,
  inboundAsnWithFee,
  clampInboundAsn,
  factorFromBps,
};
