// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  inventorySync,
  inventorySyncWithFee,
  clampInventorySync,
  factorFromBps,
} = require("./inventorySync");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes inventorySync for a retail inventory row 1", "base", 75, 22, 126.75],
  ["applies the inventorySync fee path for a east inventory row 2", "fee", 136, 3, 207.12, 8],
  ["clamps inventorySync for a west inventory row 3", "clamp", 293.57, 292, 293.57, 296],
  ["computes inventorySync for a cold inventory row 4", "base", 14, 16, 27.7],
  ["applies the inventorySync fee path for a hazmat inventory row 5", "fee", 71, 23, 124.02, 3],
  ["clamps inventorySync for a returns inventory row 6", "clamp", 192.76, 193, 193, 197],
  ["computes inventorySync for a overflow inventory row 7", "base", 189, 11, 289.5],
  ["applies the inventorySync fee path for a bulk inventory row 8", "fee", 10, 17, 23.6, 2],
  ["clamps inventorySync for a retail inventory row 9", "clamp", 117.21, 113, 117, 117],
  ["computes inventorySync for a east inventory row 10", "base", 128, 5, 190.32],
  ["applies the inventorySync fee path for a east inventory row 11", "fee", 216, 3, 325.72, 13],
  ["clamps inventorySync for a retail inventory row 12", "clamp", 258.55, 254, 258, 258],
  ["computes inventorySync for a cold inventory row 13", "base", 94, 16, 151.7],
  ["applies the inventorySync fee path for a west inventory row 14", "fee", 33, 10, 65.17, 10],
  ["clamps inventorySync for a returns inventory row 15", "clamp", 306.16, 307, 307, 311],
  ["computes inventorySync for a hazmat inventory row 16", "base", 151, 23, 250.62],
  ["applies the inventorySync fee path for a bulk inventory row 17", "fee", 90, 17, 153.4, 7],
  ["clamps inventorySync for a overflow inventory row 18", "clamp", 47.5, 48, 48, 52],
  ["computes inventorySync for a east inventory row 19", "base", 208, 5, 305.52],
  ["applies the inventorySync fee path for a retail inventory row 20", "fee", 147, 24, 249.61, 4],
  ["clamps inventorySync for a retail inventory row 21", "clamp", 177.65, 178, 178, 182],
  ["computes inventorySync for a east inventory row 22", "base", 176, 18, 282.32],
  ["applies the inventorySync fee path for a west inventory row 23", "fee", 233, 0, 329.87, 0],
  ["clamps inventorySync for a cold inventory row 24", "clamp", 87.3, 82, 86, 86],
  ["computes inventorySync for a hazmat inventory row 25", "base", 111, 13, 174.72],
  ["applies the inventorySync fee path for a returns inventory row 26", "fee", 172, 19, 291.76, 14],
  ["clamps inventorySync for a overflow inventory row 27", "clamp", 326.6, 325, 326.6, 329],
  ["computes inventorySync for a bulk inventory row 28", "base", 50, 7, 79],
  ["applies the inventorySync fee path for a retail inventory row 29", "fee", 123, 10, 199.27, 10],
  ["clamps inventorySync for a east inventory row 30", "clamp", 293.2, 289, 293, 293],
  ["computes inventorySync for a bulk inventory row 31", "base", 154, 21, 252.4],
  ["applies the inventorySync fee path for a overflow inventory row 32", "fee", 93, 15, 159.22, 10],
  ["clamps inventorySync for a returns inventory row 33", "clamp", 58.92, 57, 58.92, 61],
  ["computes inventorySync for a hazmat inventory row 34", "base", 215, 2, 309.15],
  ["applies the inventorySync fee path for a cold inventory row 35", "fee", 158, 20, 257.22, 0],
  ["clamps inventorySync for a west inventory row 36", "clamp", 156.41, 152, 156, 156],
  ["computes inventorySync for a east inventory row 37", "base", 40, 7, 64.4],
  ["applies the inventorySync fee path for a retail inventory row 38", "fee", 219, 1, 313.6, 1],
  ["clamps inventorySync for a bulk inventory row 39", "clamp", 243.52, 241, 243.52, 245],
  ["computes inventorySync for a overflow inventory row 40", "base", 85, 17, 138.6],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(inventorySync(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(inventorySyncWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampInventorySync(a, b, extra)).toBe(expected);
    }
  });
}
