// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 119;

function inventoryLock(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function inventoryLockWithFee(amount, factor, fee) {
  return inventoryLock(amount, factor) + fee;
}

function clampInventoryLock(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  inventoryLock,
  inventoryLockWithFee,
  clampInventoryLock,
  factorFromBps,
};
