// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  lotNumber,
  lotNumberWithFee,
  clampLotNumber,
  factorFromBps,
} = require("./lotNumber");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes lotNumber for a east inventory row 1", "base", 72, 19, 102.76],
  ["applies the lotNumber fee path for a retail inventory row 2", "fee", 11, 13, 23.97, 3],
  ["clamps lotNumber for a cold inventory row 3", "clamp", 234.9, 235, 235, 239],
  ["computes lotNumber for a west inventory row 4", "base", 129, 1, 155.35],
  ["applies the lotNumber fee path for a returns inventory row 5", "fee", 68, 20, 98.12, 0],
  ["clamps lotNumber for a hazmat inventory row 6", "clamp", 313.92, 310, 313.92, 314],
  ["computes lotNumber for a bulk inventory row 7", "base", 170, 12, 221.2],
  ["applies the lotNumber fee path for a overflow inventory row 8", "fee", 109, 6, 148.8, 11],
  ["clamps lotNumber for a east inventory row 9", "clamp", 64.72, 60, 64, 64],
  ["computes lotNumber for a retail inventory row 10", "base", 227, 19, 308.91],
  ["applies the lotNumber fee path for a west inventory row 11", "fee", 33, 10, 57.92, 10],
  ["clamps lotNumber for a cold inventory row 12", "clamp", 127.19999999999999, 127, 127.19999999999999, 131],
  ["computes lotNumber for a retail inventory row 13", "base", 155, 22, 217.8],
  ["applies the lotNumber fee path for a east inventory row 14", "fee", 216, 3, 272.72, 13],
  ["clamps lotNumber for a overflow inventory row 15", "clamp", 45.25, 41, 45, 45],
  ["computes lotNumber for a bulk inventory row 16", "base", 90, 17, 124.9],
  ["applies the lotNumber fee path for a hazmat inventory row 17", "fee", 151, 23, 221.87, 8],
  ["clamps lotNumber for a returns inventory row 18", "clamp", 258.16, 255, 258.16, 259],
  ["computes lotNumber for a west inventory row 19", "base", 25, 12, 38.5],
  ["applies the lotNumber fee path for a cold inventory row 20", "fee", 86, 18, 123.52, 3],
  ["clamps lotNumber for a bulk inventory row 21", "clamp", 171.26, 167, 171, 171],
  ["computes lotNumber for a overflow inventory row 22", "base", 61, 13, 84.47],
  ["applies the lotNumber fee path for a returns inventory row 23", "fee", 244, 6, 310.8, 11],
  ["clamps lotNumber for a hazmat inventory row 24", "clamp", 212.62, 214, 214, 218],
  ["computes lotNumber for a cold inventory row 25", "base", 126, 18, 173.32],
  ["applies the lotNumber fee path for a west inventory row 26", "fee", 65, 12, 100.9, 12],
  ["clamps lotNumber for a east inventory row 27", "clamp", 16.52, 15, 16.52, 19],
  ["computes lotNumber for a retail inventory row 28", "base", 187, 24, 265.06],
  ["applies the lotNumber fee path for a bulk inventory row 29", "fee", 114, 21, 161.9, 1],
  ["clamps lotNumber for a overflow inventory row 30", "clamp", 73.37, 73, 73.37, 77],
  ["computes lotNumber for a retail inventory row 31", "base", 211, 3, 253.87],
  ["applies the lotNumber fee path for a east inventory row 32", "fee", 32, 9, 55.36, 9],
  ["clamps lotNumber for a west inventory row 33", "clamp", 119.7, 121, 121, 125],
  ["computes lotNumber for a cold inventory row 34", "base", 150, 22, 211],
  ["applies the lotNumber fee path for a hazmat inventory row 35", "fee", 207, 4, 255.26, 4],
  ["clamps lotNumber for a returns inventory row 36", "clamp", 43.72, 40, 43.72, 44],
  ["computes lotNumber for a overflow inventory row 37", "base", 85, 17, 118.35],
  ["applies the lotNumber fee path for a bulk inventory row 38", "fee", 146, 23, 210.02, 3],
  ["clamps lotNumber for a retail inventory row 39", "clamp", 261.85, 257, 261, 261],
  ["computes lotNumber for a east inventory row 40", "base", 40, 7, 55.4],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(lotNumber(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(lotNumberWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampLotNumber(a, b, extra)).toBe(expected);
    }
  });
}
