// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  releaseHold,
  releaseHoldWithFee,
  clampReleaseHold,
  factorFromBps,
} = require("./releaseHold");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes releaseHold for a cold inventory row 1", "base", 190, 22, 253],
  ["applies the releaseHold fee path for a west inventory row 2", "fee", 129, 16, 166.96, 1],
  ["clamps releaseHold for a east inventory row 3", "clamp", 93.24, 88, 92, 92],
  ["computes releaseHold for a retail inventory row 4", "base", 11, 3, 18.21],
  ["applies the releaseHold fee path for a bulk inventory row 5", "fee", 186, 23, 262.65999999999997, 13],
  ["clamps releaseHold for a overflow inventory row 6", "clamp", 165.25, 160, 164, 164],
  ["computes releaseHold for a returns inventory row 7", "base", 68, 10, 86.24],
  ["applies the releaseHold fee path for a hazmat inventory row 8", "fee", 247, 4, 296.64, 14],
  ["clamps releaseHold for a cold inventory row 9", "clamp", 243.24, 244, 244, 248],
  ["computes releaseHold for a west inventory row 10", "base", 121, 18, 158.46],
  ["applies the releaseHold fee path for a retail inventory row 11", "fee", 115, 12, 146, 2],
  ["clamps releaseHold for a east inventory row 12", "clamp", 226.76, 226, 226.76, 230],
  ["computes releaseHold for a west inventory row 13", "base", 233, 0, 257.64],
  ["applies the releaseHold fee path for a cold inventory row 14", "fee", 54, 6, 68.56, 1],
  ["clamps releaseHold for a hazmat inventory row 15", "clamp", 143.31, 138, 142, 142],
  ["computes releaseHold for a returns inventory row 16", "base", 172, 19, 224.44],
  ["applies the releaseHold fee path for a overflow inventory row 17", "fee", 229, 1, 266.61, 11],
  ["clamps releaseHold for a bulk inventory row 18", "clamp", 64.5, 62, 64.5, 66],
  ["computes releaseHold for a retail inventory row 19", "base", 123, 10, 151.14],
  ["applies the releaseHold fee path for a east inventory row 20", "fee", 184, 16, 245.16, 11],
  ["clamps releaseHold for a east inventory row 21", "clamp", 242.76, 244, 244, 248],
  ["computes releaseHold for a retail inventory row 22", "base", 155, 22, 207.5],
  ["applies the releaseHold fee path for a cold inventory row 23", "fee", 94, 16, 133.56, 11],
  ["clamps releaseHold for a west inventory row 24", "clamp", 42.94, 43, 43, 47],
  ["computes releaseHold for a returns inventory row 25", "base", 212, 4, 243.44],
  ["applies the releaseHold fee path for a hazmat inventory row 26", "fee", 151, 23, 211.81, 8],
  ["clamps releaseHold for a bulk inventory row 27", "clamp", 117.5, 117, 117.5, 121],
  ["computes releaseHold for a overflow inventory row 28", "base", 29, 11, 40.51],
  ["applies the releaseHold fee path for a east inventory row 29", "fee", 208, 5, 246.04, 5],
  ["clamps releaseHold for a retail inventory row 30", "clamp", 200.04, 198, 200.04, 202],
  ["computes releaseHold for a west inventory row 31", "base", 65, 12, 84],
  ["applies the releaseHold fee path for a cold inventory row 32", "fee", 126, 18, 177.76, 13],
  ["clamps releaseHold for a retail inventory row 33", "clamp", 252.84, 251, 252.84, 255],
  ["computes releaseHold for a east inventory row 34", "base", 8, 5, 15.04],
  ["applies the releaseHold fee path for a overflow inventory row 35", "fee", 61, 13, 87.81, 8],
  ["clamps releaseHold for a bulk inventory row 36", "clamp", 157.94, 159, 159, 163],
  ["computes releaseHold for a hazmat inventory row 37", "base", 183, 0, 203.64],
  ["applies the releaseHold fee path for a returns inventory row 38", "fee", 244, 6, 295.16, 11],
  ["clamps releaseHold for a west inventory row 39", "clamp", 76.54, 74, 76.54, 78],
  ["computes releaseHold for a cold inventory row 40", "base", 118, 20, 157.04],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(releaseHold(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(releaseHoldWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampReleaseHold(a, b, extra)).toBe(expected);
    }
  });
}
