// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 100;

function safetyStock(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function safetyStockWithFee(amount, factor, fee) {
  return safetyStock(amount, factor) + fee;
}

function clampSafetyStock(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  safetyStock,
  safetyStockWithFee,
  clampSafetyStock,
  factorFromBps,
};
