// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 128;

function stockLevel(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function stockLevelWithFee(amount, factor, fee) {
  return stockLevel(amount, factor) + fee;
}

function clampStockLevel(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  stockLevel,
  stockLevelWithFee,
  clampStockLevel,
  factorFromBps,
};
