// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  warehouseBin,
  warehouseBinWithFee,
  clampWarehouseBin,
  factorFromBps,
} = require("./warehouseBin");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes warehouseBin for a cold inventory row 1", "base", 126, 3, 164.02],
  ["applies the warehouseBin fee path for a west inventory row 2", "fee", 65, 22, 110.9, 12],
  ["clamps warehouseBin for a east inventory row 3", "clamp", 15.12, 13, 15.12, 17],
  ["computes warehouseBin for a retail inventory row 4", "base", 187, 9, 252.71],
  ["applies the warehouseBin fee path for a bulk inventory row 5", "fee", 122, 4, 169.16, 9],
  ["clamps warehouseBin for a overflow inventory row 6", "clamp", 93.67, 92, 93.67, 96],
  ["computes warehouseBin for a returns inventory row 7", "base", 244, 16, 345.6],
  ["applies the warehouseBin fee path for a hazmat inventory row 8", "fee", 183, 10, 259.22, 10],
  ["clamps warehouseBin for a cold inventory row 9", "clamp", 157.22, 154, 157.22, 158],
  ["computes warehouseBin for a west inventory row 10", "base", 57, 24, 88.36],
  ["applies the warehouseBin fee path for a retail inventory row 11", "fee", 163, 0, 211.12, 5],
  ["clamps warehouseBin for a east inventory row 12", "clamp", 294.2, 293, 294.2, 297],
  ["computes warehouseBin for a west inventory row 13", "base", 41, 13, 60.17],
  ["applies the warehouseBin fee path for a cold inventory row 14", "fee", 102, 19, 153.86, 4],
  ["clamps warehouseBin for a hazmat inventory row 15", "clamp", 205.75, 201, 205, 205],
  ["computes warehouseBin for a returns inventory row 16", "base", 220, 7, 292.2],
  ["applies the warehouseBin fee path for a overflow inventory row 17", "fee", 37, 14, 69.06, 14],
  ["clamps warehouseBin for a bulk inventory row 18", "clamp", 146.12, 143, 146.12, 147],
  ["computes warehouseBin for a retail inventory row 19", "base", 171, 23, 255.37],
  ["applies the warehouseBin fee path for a east inventory row 20", "fee", 232, 4, 314.96, 14],
  ["clamps warehouseBin for a east inventory row 21", "clamp", 59.4, 56, 59.4, 60],
  ["computes warehouseBin for a retail inventory row 22", "base", 219, 6, 288.7],
  ["applies the warehouseBin fee path for a cold inventory row 23", "fee", 158, 0, 199.92, 0],
  ["clamps warehouseBin for a west inventory row 24", "clamp", 144.71, 141, 144.71, 145],
  ["computes warehouseBin for a returns inventory row 25", "base", 36, 13, 53.32],
  ["applies the warehouseBin fee path for a hazmat inventory row 26", "fee", 215, 7, 297.65, 12],
  ["clamps warehouseBin for a bulk inventory row 27", "clamp", 199.5, 195, 199, 199],
  ["computes warehouseBin for a overflow inventory row 28", "base", 93, 20, 137.92],
  ["applies the warehouseBin fee path for a east inventory row 29", "fee", 32, 14, 57.16, 9],
  ["clamps warehouseBin for a retail inventory row 30", "clamp", 279.52, 281, 281, 285],
  ["computes warehouseBin for a west inventory row 31", "base", 129, 21, 191.05],
  ["applies the warehouseBin fee path for a cold inventory row 32", "fee", 190, 2, 245.4, 2],
  ["clamps warehouseBin for a retail inventory row 33", "clamp", 15.52, 17, 17, 21],
  ["computes warehouseBin for a east inventory row 34", "base", 72, 14, 103.36],
  ["applies the warehouseBin fee path for a overflow inventory row 35", "fee", 125, 22, 198.5, 12],
  ["clamps warehouseBin for a bulk inventory row 36", "clamp", 241.22, 238, 241.22, 242],
  ["computes warehouseBin for a hazmat inventory row 37", "base", 247, 9, 332.51],
  ["applies the warehouseBin fee path for a returns inventory row 38", "fee", 68, 15, 98.52, 0],
  ["clamps warehouseBin for a west inventory row 39", "clamp", 179.87, 180, 180, 184],
  ["computes warehouseBin for a cold inventory row 40", "base", 182, 4, 236.96],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(warehouseBin(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(warehouseBinWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampWarehouseBin(a, b, extra)).toBe(expected);
    }
  });
}
