// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 121;

function destination(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function destinationWithFee(amount, factor, fee) {
  return destination(amount, factor) + fee;
}

function clampDestination(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  destination,
  destinationWithFee,
  clampDestination,
  factorFromBps,
};
