// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 136;

function exemptionCert(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function exemptionCertWithFee(amount, factor, fee) {
  return exemptionCert(amount, factor) + fee;
}

function clampExemptionCert(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  exemptionCert,
  exemptionCertWithFee,
  clampExemptionCert,
  factorFromBps,
};
