// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  exemptionCert,
  exemptionCertWithFee,
  clampExemptionCert,
  factorFromBps,
} = require("./exemptionCert");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes exemptionCert for a tx tax row 1", "base", 42, 14, 64],
  ["applies the exemptionCert fee path for a de tax row 2", "fee", 221, 8, 322.24, 3],
  ["clamps exemptionCert for a ie tax row 3", "clamp", 222.68, 224, 224, 228],
  ["computes exemptionCert for a gb tax row 4", "base", 103, 20, 161.68],
  ["applies the exemptionCert fee path for a jp tax row 5", "fee", 46, 13, 77.54, 8],
  ["clamps exemptionCert for a ny tax row 6", "clamp", 321.75, 321, 321.75, 325],
  ["computes exemptionCert for a ca tax row 7", "base", 168, 0, 229.48],
  ["applies the exemptionCert fee path for a wa tax row 8", "fee", 107, 19, 175.85, 9],
  ["clamps exemptionCert for a tx tax row 9", "clamp", 50.68, 51, 51, 55],
  ["computes exemptionCert for a de tax row 10", "base", 213, 10, 311.98],
  ["applies the exemptionCert fee path for a gb tax row 11", "fee", 55, 12, 84.4, 2],
  ["clamps exemptionCert for a ie tax row 12", "clamp", 177.64, 178, 178, 182],
  ["computes exemptionCert for a de tax row 13", "base", 173, 0, 236.28],
  ["applies the exemptionCert fee path for a tx tax row 14", "fee", 234, 6, 334.28, 1],
  ["clamps exemptionCert for a wa tax row 15", "clamp", 84.73, 86, 86, 90],
  ["computes exemptionCert for a ca tax row 16", "base", 120, 17, 184.6],
  ["applies the exemptionCert fee path for a ny tax row 17", "fee", 177, 24, 288.2, 4],
  ["clamps exemptionCert for a jp tax row 18", "clamp", 338.58, 335, 338.58, 339],
  ["computes exemptionCert for a gb tax row 19", "base", 47, 14, 71.5],
  ["applies the exemptionCert fee path for a ie tax row 20", "fee", 108, 20, 179.48, 10],
  ["clamps exemptionCert for a ie tax row 21", "clamp", 200.2, 199, 200.2, 203],
  ["computes exemptionCert for a gb tax row 22", "base", 79, 1, 109.23],
  ["applies the exemptionCert fee path for a tx tax row 23", "fee", 18, 20, 39.08, 10],
  ["clamps exemptionCert for a de tax row 24", "clamp", 296.5, 295, 296.5, 299],
  ["computes exemptionCert for a ca tax row 25", "base", 144, 6, 205.48],
  ["applies the exemptionCert fee path for a wa tax row 26", "fee", 83, 0, 113.88, 0],
  ["clamps exemptionCert for a jp tax row 27", "clamp", 38.1, 33, 37, 37],
  ["computes exemptionCert for a ny tax row 28", "base", 201, 13, 300.49],
  ["applies the exemptionCert fee path for a ie tax row 29", "fee", 148, 5, 214.68, 5],
  ["clamps exemptionCert for a gb tax row 30", "clamp", 139.2, 138, 139.2, 142],
  ["computes exemptionCert for a de tax row 31", "base", 229, 16, 349.08],
  ["applies the exemptionCert fee path for a tx tax row 32", "fee", 50, 22, 92, 12],
  ["clamps exemptionCert for a gb tax row 33", "clamp", 157.29, 153, 157, 157],
  ["computes exemptionCert for a ie tax row 34", "base", 172, 9, 250.4],
  ["applies the exemptionCert fee path for a ny tax row 35", "fee", 233, 15, 352.83, 0],
  ["clamps exemptionCert for a jp tax row 36", "clamp", 86.78, 84, 86.78, 88],
  ["computes exemptionCert for a wa tax row 37", "base", 115, 2, 159.7],
  ["applies the exemptionCert fee path for a ca tax row 38", "fee", 176, 8, 257.44, 3],
  ["clamps exemptionCert for a de tax row 39", "clamp", 356.5, 355, 356.5, 359],
  ["computes exemptionCert for a tx tax row 40", "base", 58, 20, 91.48],
  ["applies the exemptionCert fee path for a tx tax row 41", "fee", 90, 7, 136.7, 7],
  ["clamps exemptionCert for a de tax row 42", "clamp", 43.73, 39, 43, 43],
  ["computes exemptionCert for a ie tax row 43", "base", 212, 19, 329.6],
  ["applies the exemptionCert fee path for a gb tax row 44", "fee", 151, 13, 233.99, 8],
  ["clamps exemptionCert for a jp tax row 45", "clamp", 133.48, 132, 133.48, 136],
  ["computes exemptionCert for a ny tax row 46", "base", 33, 0, 45.88],
  ["applies the exemptionCert fee path for a ca tax row 47", "fee", 216, 18, 346.64, 13],
  ["clamps exemptionCert for a wa tax row 48", "clamp", 231.4, 228, 231.4, 232],
  ["computes exemptionCert for a tx tax row 49", "base", 82, 9, 119.9],
  ["applies the exemptionCert fee path for a de tax row 50", "fee", 21, 3, 43.19, 13],
  ["clamps exemptionCert for a wa tax row 51", "clamp", 270.08, 271, 271, 275],
  ["computes exemptionCert for a ca tax row 52", "base", 240, 22, 380.2],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(exemptionCert(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(exemptionCertWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampExemptionCert(a, b, extra)).toBe(expected);
    }
  });
}
