// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 133;

function marketplaceFacil(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function marketplaceFacilWithFee(amount, factor, fee) {
  return marketplaceFacil(amount, factor) + fee;
}

function clampMarketplaceFacil(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  marketplaceFacil,
  marketplaceFacilWithFee,
  clampMarketplaceFacil,
  factorFromBps,
};
