// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  marketplaceFacil,
  marketplaceFacilWithFee,
  clampMarketplaceFacil,
  factorFromBps,
} = require("./marketplaceFacil");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes marketplaceFacil for a ny tax row 1", "base", 81, 23, 135.36],
  ["applies the marketplaceFacil fee path for a jp tax row 2", "fee", 142, 4, 217.54, 14],
  ["clamps marketplaceFacil for a wa tax row 3", "clamp", 299.29, 297, 299.29, 301],
  ["computes marketplaceFacil for a ca tax row 4", "base", 24, 16, 44.76],
  ["applies the marketplaceFacil fee path for a de tax row 5", "fee", 77, 24, 138.89, 9],
  ["clamps marketplaceFacil for a tx tax row 6", "clamp", 196.44, 197, 197, 201],
  ["computes marketplaceFacil for a gb tax row 7", "base", 199, 11, 295.56],
  ["applies the marketplaceFacil fee path for a ie tax row 8", "fee", 20, 17, 51, 12],
  ["clamps marketplaceFacil for a ny tax row 9", "clamp", 107.09, 104, 107.09, 108],
  ["computes marketplaceFacil for a jp tax row 10", "base", 134, 6, 195.26],
  ["applies the marketplaceFacil fee path for a tx tax row 11", "fee", 202, 19, 330.04, 14],
  ["clamps marketplaceFacil for a de tax row 12", "clamp", 217.86, 213, 217, 217],
  ["computes marketplaceFacil for a ie tax row 13", "base", 84, 6, 125.76],
  ["applies the marketplaceFacil fee path for a gb tax row 14", "fee", 23, 0, 39.59, 0],
  ["clamps marketplaceFacil for a jp tax row 15", "clamp", 319.06, 318, 319.06, 322],
  ["computes marketplaceFacil for a ny tax row 16", "base", 145, 12, 219.25],
  ["applies the marketplaceFacil fee path for a ca tax row 17", "fee", 88, 5, 135.44, 5],
  ["clamps marketplaceFacil for a wa tax row 18", "clamp", 52.39, 49, 52.39, 53],
  ["computes marketplaceFacil for a tx tax row 19", "base", 194, 21, 307.76],
  ["applies the marketplaceFacil fee path for a de tax row 20", "fee", 133, 15, 210.84, 5],
  ["clamps marketplaceFacil for a ny tax row 21", "clamp", 169.59, 169, 169.59, 173],
  ["computes marketplaceFacil for a jp tax row 22", "base", 174, 16, 268.26],
  ["applies the marketplaceFacil fee path for a wa tax row 23", "fee", 235, 22, 375.25, 2],
  ["clamps marketplaceFacil for a ca tax row 24", "clamp", 83.16, 83, 83.16, 87],
  ["computes marketplaceFacil for a de tax row 25", "base", 109, 11, 165.96],
  ["applies the marketplaceFacil fee path for a tx tax row 26", "fee", 170, 17, 276, 12],
  ["clamps marketplaceFacil for a gb tax row 27", "clamp", 371.36, 367, 371, 371],
  ["computes marketplaceFacil for a ie tax row 28", "base", 52, 4, 80.24],
  ["applies the marketplaceFacil fee path for a ny tax row 29", "fee", 105, 12, 168.25, 7],
  ["clamps marketplaceFacil for a jp tax row 30", "clamp", 258.66, 258, 258.66, 262],
  ["computes marketplaceFacil for a ca tax row 31", "base", 152, 19, 240.04],
  ["applies the marketplaceFacil fee path for a wa tax row 32", "fee", 91, 13, 149.86, 8],
  ["clamps marketplaceFacil for a jp tax row 33", "clamp", 51, 49, 51, 53],
  ["computes marketplaceFacil for a ny tax row 34", "base", 209, 1, 289.06],
  ["applies the marketplaceFacil fee path for a ie tax row 35", "fee", 148, 20, 240.44, 5],
  ["clamps marketplaceFacil for a gb tax row 36", "clamp", 137.89, 135, 137.89, 139],
  ["computes marketplaceFacil for a tx tax row 37", "base", 26, 8, 45.66],
  ["applies the marketplaceFacil fee path for a de tax row 38", "fee", 205, 2, 287.75, 2],
  ["clamps marketplaceFacil for a ca tax row 39", "clamp", 232.76, 229, 232.76, 233],
  ["computes marketplaceFacil for a wa tax row 40", "base", 83, 15, 131.84],
  ["applies the marketplaceFacil fee path for a gb tax row 41", "fee", 55, 17, 93.5, 2],
  ["clamps marketplaceFacil for a ie tax row 42", "clamp", 191.96, 188, 191.96, 192],
  ["computes marketplaceFacil for a de tax row 43", "base", 173, 5, 247.74],
  ["applies the marketplaceFacil fee path for a tx tax row 44", "fee", 234, 11, 346.96, 1],
  ["clamps marketplaceFacil for a wa tax row 45", "clamp", 97.91, 95, 97.91, 99],
  ["computes marketplaceFacil for a ca tax row 46", "base", 120, 22, 195],
  ["applies the marketplaceFacil fee path for a ny tax row 47", "fee", 177, 4, 255.49, 4],
  ["clamps marketplaceFacil for a jp tax row 48", "clamp", 348.34, 347, 348.34, 351],
  ["computes marketplaceFacil for a gb tax row 49", "base", 47, 19, 80.44],
  ["applies the marketplaceFacil fee path for a ie tax row 50", "fee", 108, 0, 162.64, 10],
  ["clamps marketplaceFacil for a jp tax row 51", "clamp", 300.46, 297, 300.46, 301],
  ["computes marketplaceFacil for a ny tax row 52", "base", 145, 2, 204.75],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(marketplaceFacil(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(marketplaceFacilWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampMarketplaceFacil(a, b, extra)).toBe(expected);
    }
  });
}
