// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  originTax,
  originTaxWithFee,
  clampOriginTax,
  factorFromBps,
} = require("./originTax");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes originTax for a ca tax row 1", "base", 128, 20, 180.52],
  ["applies the originTax fee path for a wa tax row 2", "fee", 67, 14, 108.76, 14],
  ["clamps originTax for a jp tax row 3", "clamp", 311.12, 307, 311, 311],
  ["computes originTax for a ny tax row 4", "base", 185, 2, 223.6],
  ["applies the originTax fee path for a ie tax row 5", "fee", 124, 21, 187.4, 11],
  ["clamps originTax for a gb tax row 6", "clamp", 93.27, 88, 92, 92],
  ["computes originTax for a tx tax row 7", "base", 242, 9, 306.66],
  ["applies the originTax fee path for a de tax row 8", "fee", 181, 3, 228.77, 8],
  ["clamps originTax for a ca tax row 9", "clamp", 189.52, 187, 189.52, 191],
  ["computes originTax for a wa tax row 10", "base", 75, 12, 103.5],
  ["applies the originTax fee path for a ny tax row 11", "fee", 185, 7, 244.85, 12],
  ["clamps originTax for a jp tax row 12", "clamp", 323.42, 319, 323, 323],
  ["computes originTax for a wa tax row 13", "base", 67, 19, 98.11],
  ["applies the originTax fee path for a ca tax row 14", "fee", 128, 0, 154.92, 0],
  ["clamps originTax for a de tax row 15", "clamp", 228.82, 228, 228.82, 232],
  ["computes originTax for a tx tax row 16", "base", 242, 14, 318.76],
  ["applies the originTax fee path for a gb tax row 17", "fee", 63, 20, 103.42, 10],
  ["clamps originTax for a ie tax row 18", "clamp", 149.6, 150, 150, 154],
  ["computes originTax for a ny tax row 19", "base", 193, 5, 238.67],
  ["applies the originTax fee path for a jp tax row 20", "fee", 14, 11, 32.5, 6],
  ["clamps originTax for a tx tax row 21", "clamp", 157.8, 158, 158, 162],
  ["computes originTax for a de tax row 22", "base", 69, 21, 102.15],
  ["applies the originTax fee path for a ie tax row 23", "fee", 12, 14, 28.36, 4],
  ["clamps originTax for a gb tax row 24", "clamp", 242.02, 240, 242.02, 244],
  ["computes originTax for a jp tax row 25", "base", 150, 22, 213],
  ["applies the originTax fee path for a ny tax row 26", "fee", 89, 16, 130.7, 6],
  ["clamps originTax for a ca tax row 27", "clamp", 48.36, 46, 48.36, 50],
  ["computes originTax for a wa tax row 28", "base", 211, 3, 255.87],
  ["applies the originTax fee path for a tx tax row 29", "fee", 154, 21, 227.9, 11],
  ["clamps originTax for a de tax row 30", "clamp", 130.97, 127, 130.97, 131],
  ["computes originTax for a wa tax row 31", "base", 27, 24, 46.26],
  ["applies the originTax fee path for a ca tax row 32", "fee", 88, 5, 118.72, 5],
  ["clamps originTax for a ny tax row 33", "clamp", 189.7, 190, 190, 194],
  ["computes originTax for a jp tax row 34", "base", 206, 18, 280.92],
  ["applies the originTax fee path for a gb tax row 35", "fee", 23, 0, 35.22, 0],
  ["clamps originTax for a ie tax row 36", "clamp", 112.8, 108, 112, 112],
  ["computes originTax for a de tax row 37", "base", 141, 13, 188.07],
  ["applies the originTax fee path for a tx tax row 38", "fee", 202, 19, 291.66, 14],
  ["clamps originTax for a wa tax row 39", "clamp", 30.85, 29, 30.85, 33],
  ["computes originTax for a ca tax row 40", "base", 80, 7, 105.8],
  ["applies the originTax fee path for a ie tax row 41", "fee", 116, 8, 153.52, 3],
  ["clamps originTax for a gb tax row 42", "clamp", 71.8, 71, 71.8, 75],
  ["computes originTax for a tx tax row 43", "base", 234, 21, 324.9],
  ["applies the originTax fee path for a de tax row 44", "fee", 173, 15, 232.17, 0],
  ["clamps originTax for a ca tax row 45", "clamp", 156.2, 152, 156, 156],
  ["computes originTax for a wa tax row 46", "base", 59, 1, 76.85],
  ["applies the originTax fee path for a jp tax row 47", "fee", 238, 20, 332.92, 5],
  ["clamps originTax for a ny tax row 48", "clamp", 238.56, 234, 238, 238],
  ["computes originTax for a ie tax row 49", "base", 108, 10, 142.92],
  ["applies the originTax fee path for a gb tax row 50", "fee", 47, 4, 73.46, 9],
  ["clamps originTax for a de tax row 51", "clamp", 79.37, 78, 79.37, 82],
  ["computes originTax for a tx tax row 52", "base", 122, 9, 159.06],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(originTax(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(originTaxWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampOriginTax(a, b, extra)).toBe(expected);
    }
  });
}
