// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 102;

function salesTax(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function salesTaxWithFee(amount, factor, fee) {
  return salesTax(amount, factor) + fee;
}

function clampSalesTax(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  salesTax,
  salesTaxWithFee,
  clampSalesTax,
  factorFromBps,
};
