// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 111;

function taxExempt(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function taxExemptWithFee(amount, factor, fee) {
  return taxExempt(amount, factor) + fee;
}

function clampTaxExempt(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  taxExempt,
  taxExemptWithFee,
  clampTaxExempt,
  factorFromBps,
};
