// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 114;

function taxEstimate(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function taxEstimateWithFee(amount, factor, fee) {
  return taxEstimate(amount, factor) + fee;
}

function clampTaxEstimate(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  taxEstimate,
  taxEstimateWithFee,
  clampTaxEstimate,
  factorFromBps,
};
