// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  taxHoliday,
  taxHolidayWithFee,
  clampTaxHoliday,
  factorFromBps,
} = require("./taxHoliday");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes taxHoliday for a tx tax row 1", "base", 106, 18, 143.8],
  ["applies the taxHoliday fee path for a de tax row 2", "fee", 45, 12, 68.8, 7],
  ["clamps taxHoliday for a ie tax row 3", "clamp", 271.76, 271, 271.76, 275],
  ["computes taxHoliday for a gb tax row 4", "base", 167, 24, 233.12],
  ["applies the taxHoliday fee path for a jp tax row 5", "fee", 110, 17, 159.9, 12],
  ["clamps taxHoliday for a ny tax row 6", "clamp", 67.27, 64, 67.27, 68],
  ["computes taxHoliday for a ca tax row 7", "base", 232, 4, 275.12],
  ["applies the taxHoliday fee path for a wa tax row 8", "fee", 171, 23, 249.85, 13],
  ["clamps taxHoliday for a tx tax row 9", "clamp", 135.36, 133, 135.36, 137],
  ["computes taxHoliday for a de tax row 10", "base", 37, 14, 52.62],
  ["applies the taxHoliday fee path for a gb tax row 11", "fee", 151, 8, 195.2, 8],
  ["clamps taxHoliday for a ie tax row 12", "clamp", 276.12, 271, 275, 275],
  ["computes taxHoliday for a de tax row 13", "base", 29, 21, 44.57],
  ["applies the taxHoliday fee path for a tx tax row 14", "fee", 90, 2, 115.6, 7],
  ["clamps taxHoliday for a wa tax row 15", "clamp", 192.45, 188, 192, 192],
  ["computes taxHoliday for a ca tax row 16", "base", 216, 13, 276],
  ["applies the taxHoliday fee path for a ny tax row 17", "fee", 33, 20, 59.56, 10],
  ["clamps taxHoliday for a jp tax row 18", "clamp", 112.22, 110, 112.22, 114],
  ["computes taxHoliday for a gb tax row 19", "base", 143, 10, 180.46],
  ["applies the taxHoliday fee path for a ie tax row 20", "fee", 204, 16, 268.12, 1],
  ["clamps taxHoliday for a ie tax row 21", "clamp", 274.4, 275, 275, 279],
  ["computes taxHoliday for a gb tax row 22", "base", 175, 22, 240.5],
  ["applies the taxHoliday fee path for a tx tax row 23", "fee", 114, 16, 152.92, 1],
  ["clamps taxHoliday for a de tax row 24", "clamp", 68.66, 69, 69, 73],
  ["computes taxHoliday for a ca tax row 25", "base", 240, 2, 279.6],
  ["applies the taxHoliday fee path for a wa tax row 26", "fee", 179, 21, 250.07, 6],
  ["clamps taxHoliday for a jp tax row 27", "clamp", 156.86, 154, 156.86, 158],
  ["computes taxHoliday for a ny tax row 28", "base", 57, 9, 74.97],
  ["applies the taxHoliday fee path for a ie tax row 29", "fee", 244, 1, 292.72, 11],
  ["clamps taxHoliday for a gb tax row 30", "clamp", 244.56, 246, 246, 250],
  ["computes taxHoliday for a de tax row 31", "base", 85, 12, 111.4],
  ["applies the taxHoliday fee path for a tx tax row 32", "fee", 146, 18, 198.8, 3],
  ["clamps taxHoliday for a gb tax row 33", "clamp", 287.52, 286, 287.52, 290],
  ["computes taxHoliday for a ie tax row 34", "base", 28, 5, 38.76],
  ["applies the taxHoliday fee path for a ny tax row 35", "fee", 89, 11, 121.47, 6],
  ["clamps taxHoliday for a jp tax row 36", "clamp", 198.5, 198, 198.5, 202],
  ["computes taxHoliday for a wa tax row 37", "base", 211, 23, 290.85],
  ["applies the taxHoliday fee path for a ca tax row 38", "fee", 32, 4, 52.12, 9],
  ["clamps taxHoliday for a de tax row 39", "clamp", 117.46, 117, 117.46, 121],
  ["computes taxHoliday for a tx tax row 40", "base", 154, 16, 203.12],
  ["applies the taxHoliday fee path for a tx tax row 41", "fee", 186, 3, 232.9, 13],
  ["clamps taxHoliday for a de tax row 42", "clamp", 174.5, 172, 174.5, 176],
  ["computes taxHoliday for a ie tax row 43", "base", 68, 15, 92.36],
  ["applies the taxHoliday fee path for a gb tax row 44", "fee", 247, 9, 318.87, 14],
  ["clamps taxHoliday for a jp tax row 45", "clamp", 219.6, 221, 221, 225],
  ["computes taxHoliday for a ny tax row 46", "base", 129, 21, 177.57],
  ["applies the taxHoliday fee path for a ca tax row 47", "fee", 72, 14, 100.72, 4],
  ["clamps taxHoliday for a wa tax row 48", "clamp", 18.2, 17, 18.2, 21],
  ["computes taxHoliday for a tx tax row 49", "base", 178, 5, 214.26],
  ["applies the taxHoliday fee path for a de tax row 50", "fee", 117, 24, 169.12, 4],
  ["clamps taxHoliday for a wa tax row 51", "clamp", 51.4, 47, 51, 51],
  ["computes taxHoliday for a ca tax row 52", "base", 96, 18, 130.8],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(taxHoliday(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(taxHolidayWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampTaxHoliday(a, b, extra)).toBe(expected);
    }
  });
}
