// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 126;

function taxInclusive(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function taxInclusiveWithFee(amount, factor, fee) {
  return taxInclusive(amount, factor) + fee;
}

function clampTaxInclusive(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  taxInclusive,
  taxInclusiveWithFee,
  clampTaxInclusive,
  factorFromBps,
};
