// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 105;

function taxJurisdiction(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function taxJurisdictionWithFee(amount, factor, fee) {
  return taxJurisdiction(amount, factor) + fee;
}

function clampTaxJurisdiction(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  taxJurisdiction,
  taxJurisdictionWithFee,
  clampTaxJurisdiction,
  factorFromBps,
};
