// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 134;

function taxReport(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function taxReportWithFee(amount, factor, fee) {
  return taxReport(amount, factor) + fee;
}

function clampTaxReport(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  taxReport,
  taxReportWithFee,
  clampTaxReport,
  factorFromBps,
};
