// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  taxRounding,
  taxRoundingWithFee,
  clampTaxRounding,
  factorFromBps,
} = require("./taxRounding");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes taxRounding for a jp tax row 1", "base", 246, 8, 292.36],
  ["applies the taxRounding fee path for a ny tax row 2", "fee", 185, 2, 222.5, 12],
  ["clamps taxRounding for a ca tax row 3", "clamp", 173.84, 169, 173, 173],
  ["computes taxRounding for a wa tax row 4", "base", 67, 14, 88.74],
  ["applies the taxRounding fee path for a tx tax row 5", "fee", 242, 9, 299.14, 9],
  ["clamps taxRounding for a de tax row 6", "clamp", 210.91, 206, 210, 210],
  ["computes taxRounding for a ie tax row 7", "base", 124, 21, 166.96],
  ["applies the taxRounding fee path for a gb tax row 8", "fee", 63, 15, 94.49, 10],
  ["clamps taxRounding for a jp tax row 9", "clamp", 23.96, 21, 23.96, 25],
  ["computes taxRounding for a ny tax row 10", "base", 193, 0, 215.44],
  ["applies the taxRounding fee path for a wa tax row 11", "fee", 203, 20, 266.84, 0],
  ["clamps taxRounding for a ca tax row 12", "clamp", 34.16, 31, 34.16, 35],
  ["computes taxRounding for a ny tax row 13", "base", 81, 8, 100.96],
  ["applies the taxRounding fee path for a jp tax row 14", "fee", 142, 14, 194.24, 14],
  ["clamps taxRounding for a gb tax row 15", "clamp", 261.71, 262, 262, 266],
  ["computes taxRounding for a ie tax row 16", "base", 20, 2, 29],
  ["applies the taxRounding fee path for a de tax row 17", "fee", 77, 9, 106.09, 9],
  ["clamps taxRounding for a tx tax row 18", "clamp", 179.74, 175, 179, 179],
  ["computes taxRounding for a wa tax row 19", "base", 195, 22, 260.5],
  ["applies the taxRounding fee path for a ca tax row 20", "fee", 16, 3, 32.760000000000005, 8],
  ["clamps taxRounding for a ca tax row 21", "clamp", 45.64, 46, 46, 50],
  ["computes taxRounding for a wa tax row 22", "base", 211, 13, 262.31],
  ["applies the taxRounding fee path for a jp tax row 23", "fee", 150, 7, 186.5, 7],
  ["clamps taxRounding for a ny tax row 24", "clamp", 103.01, 102, 103.01, 106],
  ["computes taxRounding for a ie tax row 25", "base", 28, 20, 42.84],
  ["applies the taxRounding fee path for a gb tax row 26", "fee", 207, 14, 263.54, 4],
  ["clamps taxRounding for a tx tax row 27", "clamp", 176.36, 174, 176.36, 178],
  ["computes taxRounding for a de tax row 28", "base", 85, 2, 100.5],
  ["applies the taxRounding fee path for a ca tax row 29", "fee", 40, 17, 59, 2],
  ["clamps taxRounding for a wa tax row 30", "clamp", 265.61, 266, 266, 270],
  ["computes taxRounding for a ny tax row 31", "base", 121, 3, 141.31],
  ["applies the taxRounding fee path for a jp tax row 32", "fee", 182, 9, 228.94, 9],
  ["clamps taxRounding for a wa tax row 33", "clamp", 306.89, 304, 306.89, 308],
  ["computes taxRounding for a ca tax row 34", "base", 64, 21, 89.56],
  ["applies the taxRounding fee path for a de tax row 35", "fee", 117, 4, 142.04, 4],
  ["clamps taxRounding for a tx tax row 36", "clamp", 215.04, 215, 215.04, 219],
  ["computes taxRounding for a gb tax row 37", "base", 239, 16, 303.36],
  ["applies the taxRounding fee path for a ie tax row 38", "fee", 60, 22, 92, 7],
  ["clamps taxRounding for a ny tax row 39", "clamp", 146.61, 146, 146.61, 150],
  ["computes taxRounding for a jp tax row 40", "base", 190, 7, 225.5],
  ["applies the taxRounding fee path for a jp tax row 41", "fee", 230, 22, 318, 12],
  ["clamps taxRounding for a ny tax row 42", "clamp", 217.56, 215, 217.56, 219],
  ["computes taxRounding for a ca tax row 43", "base", 112, 9, 138.04],
  ["applies the taxRounding fee path for a wa tax row 44", "fee", 51, 3, 76.61, 13],
  ["clamps taxRounding for a tx tax row 45", "clamp", 305.06, 301, 305, 305],
  ["computes taxRounding for a de tax row 46", "base", 149, 21, 199.21],
  ["applies the taxRounding fee path for a ie tax row 47", "fee", 108, 10, 144.44, 10],
  ["clamps taxRounding for a gb tax row 48", "clamp", 56.64, 58, 58, 62],
  ["computes taxRounding for a jp tax row 49", "base", 238, 20, 311.64],
  ["applies the taxRounding fee path for a ny tax row 50", "fee", 177, 14, 226.94, 4],
  ["clamps taxRounding for a gb tax row 51", "clamp", 226.75, 224, 226.75, 228],
  ["computes taxRounding for a ie tax row 52", "base", 236, 23, 316.16],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(taxRounding(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(taxRoundingWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampTaxRounding(a, b, extra)).toBe(expected);
    }
  });
}
