// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 107;

function useTax(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function useTaxWithFee(amount, factor, fee) {
  return useTax(amount, factor) + fee;
}

function clampUseTax(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  useTax,
  useTaxWithFee,
  clampUseTax,
  factorFromBps,
};
