// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 136;

function vatRate(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function vatRateWithFee(amount, factor, fee) {
  return vatRate(amount, factor) + fee;
}

function clampVatRate(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  vatRate,
  vatRateWithFee,
  clampVatRate,
  factorFromBps,
};
