// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  clearance,
  clearanceWithFee,
  clampClearance,
  factorFromBps,
} = require("./clearance");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes clearance for a map pricing row 1", "base", 126, 3, 133.78],
  ["applies the clearance fee path for a promo pricing row 2", "fee", 65, 22, 95.3, 12],
  ["clamps clearance for a list pricing row 3", "clamp", 11.2, 11, 11.2, 15],
  ["computes clearance for a clearance pricing row 4", "base", 187, 9, 207.83],
  ["applies the clearance fee path for a member pricing row 5", "fee", 122, 4, 139.88, 9],
  ["clamps clearance for a contract pricing row 6", "clamp", 77.03, 77, 77.03, 81],
  ["computes clearance for a bundle pricing row 7", "base", 244, 16, 287.04],
  ["applies the clearance fee path for a surge pricing row 8", "fee", 183, 10, 215.3, 10],
  ["clamps clearance for a map pricing row 9", "clamp", 126.9, 126, 126.9, 130],
  ["computes clearance for a promo pricing row 10", "base", 57, 24, 74.68],
  ["applies the clearance fee path for a clearance pricing row 11", "fee", 163, 15, 196.45, 5],
  ["clamps clearance for a list pricing row 12", "clamp", 272.04, 273, 273, 277],
  ["computes clearance for a promo pricing row 13", "base", 41, 3, 46.23],
  ["applies the clearance fee path for a map pricing row 14", "fee", 102, 9, 119.18, 4],
  ["clamps clearance for a surge pricing row 15", "clamp", 189.44, 186, 189.44, 190],
  ["computes clearance for a bundle pricing row 16", "base", 220, 22, 272.4],
  ["applies the clearance fee path for a contract pricing row 17", "fee", 37, 4, 56.48, 14],
  ["clamps clearance for a member pricing row 18", "clamp", 110.8, 110, 110.8, 114],
  ["computes clearance for a clearance pricing row 19", "base", 171, 13, 197.23],
  ["applies the clearance fee path for a list pricing row 20", "fee", 232, 19, 294.08, 14],
  ["clamps clearance for a list pricing row 21", "clamp", 171.68, 168, 171.68, 172],
  ["computes clearance for a clearance pricing row 22", "base", 91, 3, 97.73],
  ["applies the clearance fee path for a map pricing row 23", "fee", 30, 22, 47.6, 7],
  ["clamps clearance for a promo pricing row 24", "clamp", 249.44, 244, 248, 248],
  ["computes clearance for a bundle pricing row 25", "base", 148, 10, 166.8],
  ["applies the clearance fee path for a surge pricing row 26", "fee", 87, 4, 98.48, 4],
  ["clamps clearance for a member pricing row 27", "clamp", 32.98, 34, 34, 38],
  ["computes clearance for a contract pricing row 28", "base", 205, 17, 243.85],
  ["applies the clearance fee path for a list pricing row 29", "fee", 128, 15, 151.2, 0],
  ["clamps clearance for a clearance pricing row 30", "clamp", 78.03, 75, 78.03, 79],
  ["computes clearance for a promo pricing row 31", "base", 241, 18, 288.38],
  ["applies the clearance fee path for a map pricing row 32", "fee", 62, 24, 89.88, 9],
  ["clamps clearance for a clearance pricing row 33", "clamp", 131.15, 131, 131.15, 135],
  ["computes clearance for a list pricing row 34", "base", 184, 11, 208.24],
  ["applies the clearance fee path for a contract pricing row 35", "fee", 221, 23, 278.83, 3],
  ["clamps clearance for a member pricing row 36", "clamp", 45.68, 46, 46, 50],
  ["computes clearance for a surge pricing row 37", "base", 103, 10, 117.3],
  ["applies the clearance fee path for a bundle pricing row 38", "fee", 180, 12, 212.6, 7],
  ["clamps clearance for a promo pricing row 39", "clamp", 275.08, 271, 275, 275],
  ["computes clearance for a map pricing row 40", "base", 38, 5, 43.9],
  ["applies the clearance fee path for a map pricing row 41", "fee", 94, 16, 124.04, 11],
  ["clamps clearance for a promo pricing row 42", "clamp", 41.3, 38, 41.3, 42],
  ["computes clearance for a list pricing row 43", "base", 216, 3, 226.48],
  ["applies the clearance fee path for a clearance pricing row 44", "fee", 155, 22, 205.1, 12],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(clearance(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(clearanceWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampClearance(a, b, extra)).toBe(expected);
    }
  });
}
