// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  competitorMatch,
  competitorMatchWithFee,
  clampCompetitorMatch,
  factorFromBps,
} = require("./competitorMatch");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes competitorMatch for a promo pricing row 1", "base", 81, 3, 90.24],
  ["applies the competitorMatch fee path for a map pricing row 2", "fee", 142, 9, 176.2, 14],
  ["clamps competitorMatch for a clearance pricing row 3", "clamp", 238.48, 239, 239, 243],
  ["computes competitorMatch for a list pricing row 4", "base", 24, 21, 35.28],
  ["applies the competitorMatch fee path for a contract pricing row 5", "fee", 77, 4, 95.85, 9],
  ["clamps competitorMatch for a member pricing row 6", "clamp", 160.18, 157, 160.18, 161],
  ["computes competitorMatch for a surge pricing row 7", "base", 199, 16, 238.83],
  ["applies the competitorMatch fee path for a bundle pricing row 8", "fee", 20, 22, 42.6, 12],
  ["clamps competitorMatch for a promo pricing row 9", "clamp", 81.38, 81, 81.38, 85],
  ["computes competitorMatch for a map pricing row 10", "base", 134, 11, 156.08],
  ["applies the competitorMatch fee path for a member pricing row 11", "fee", 202, 19, 262.4, 14],
  ["clamps competitorMatch for a contract pricing row 12", "clamp", 169.74, 165, 169, 169],
  ["computes competitorMatch for a bundle pricing row 13", "base", 84, 6, 95.88],
  ["applies the competitorMatch fee path for a surge pricing row 14", "fee", 23, 0, 29.23, 0],
  ["clamps competitorMatch for a map pricing row 15", "clamp", 250.14, 249, 250.14, 253],
  ["computes competitorMatch for a promo pricing row 16", "base", 145, 12, 169.85],
  ["applies the competitorMatch fee path for a list pricing row 17", "fee", 88, 5, 104.28, 5],
  ["clamps competitorMatch for a clearance pricing row 18", "clamp", 40.75, 38, 40.75, 42],
  ["computes competitorMatch for a member pricing row 19", "base", 194, 21, 242.68],
  ["applies the competitorMatch fee path for a contract pricing row 20", "fee", 133, 15, 165.28, 5],
  ["clamps competitorMatch for a promo pricing row 21", "clamp", 130.43, 129, 130.43, 133],
  ["computes competitorMatch for a map pricing row 22", "base", 174, 16, 209.58],
  ["applies the competitorMatch fee path for a clearance pricing row 23", "fee", 235, 22, 297.05, 2],
  ["clamps competitorMatch for a list pricing row 24", "clamp", 62.239999999999995, 62, 62.239999999999995, 66],
  ["computes competitorMatch for a contract pricing row 25", "base", 109, 11, 128.08],
  ["applies the competitorMatch fee path for a member pricing row 26", "fee", 170, 17, 218.6, 12],
  ["clamps competitorMatch for a surge pricing row 27", "clamp", 294.44, 290, 294, 294],
  ["computes competitorMatch for a bundle pricing row 28", "base", 52, 4, 60.6],
  ["applies the competitorMatch fee path for a promo pricing row 29", "fee", 105, 12, 131.65, 7],
  ["clamps competitorMatch for a map pricing row 30", "clamp", 202.54, 202, 202.54, 206],
  ["computes competitorMatch for a list pricing row 31", "base", 24, 1, 30.48],
  ["applies the competitorMatch fee path for a clearance pricing row 32", "fee", 203, 20, 251.63, 0],
  ["clamps competitorMatch for a map pricing row 33", "clamp", 172.3, 167, 171, 171],
  ["computes competitorMatch for a promo pricing row 34", "base", 81, 8, 94.29],
  ["applies the competitorMatch fee path for a bundle pricing row 35", "fee", 20, 2, 38.6, 12],
  ["clamps competitorMatch for a surge pricing row 36", "clamp", 245.78, 247, 247, 251],
  ["computes competitorMatch for a member pricing row 37", "base", 138, 15, 166.08],
  ["applies the competitorMatch fee path for a contract pricing row 38", "fee", 77, 9, 99.7, 9],
  ["clamps competitorMatch for a list pricing row 39", "clamp", 20.64, 21, 21, 25],
  ["computes competitorMatch for a clearance pricing row 40", "base", 195, 22, 245.85],
  ["applies the competitorMatch fee path for a surge pricing row 41", "fee", 167, 24, 223.75, 9],
  ["clamps competitorMatch for a bundle pricing row 42", "clamp", 245.68, 246, 246, 250],
  ["computes competitorMatch for a contract pricing row 43", "base", 45, 12, 56.85],
  ["applies the competitorMatch fee path for a member pricing row 44", "fee", 106, 18, 140.14, 8],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(competitorMatch(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(competitorMatchWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCompetitorMatch(a, b, extra)).toBe(expected);
    }
  });
}
