// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  currencyConvert,
  currencyConvertWithFee,
  clampCurrencyConvert,
  factorFromBps,
} = require("./currencyConvert");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes currencyConvert for a map pricing row 1", "base", 206, 8, 272.92],
  ["applies the currencyConvert fee path for a promo pricing row 2", "fee", 145, 2, 185.7, 2],
  ["clamps currencyConvert for a list pricing row 3", "clamp", 127.72, 126, 127.72, 130],
  ["computes currencyConvert for a clearance pricing row 4", "base", 27, 14, 38.26],
  ["applies the currencyConvert fee path for a member pricing row 5", "fee", 202, 9, 283.66, 14],
  ["clamps currencyConvert for a contract pricing row 6", "clamp", 180.07, 178, 180.07, 182],
  ["computes currencyConvert for a bundle pricing row 7", "base", 84, 21, 122.8],
  ["applies the currencyConvert fee path for a surge pricing row 8", "fee", 23, 15, 32.97, 0],
  ["clamps currencyConvert for a map pricing row 9", "clamp", 267.32, 264, 267.32, 268],
  ["computes currencyConvert for a promo pricing row 10", "base", 137, 4, 176.36],
  ["applies the currencyConvert fee path for a clearance pricing row 11", "fee", 243, 5, 324.47, 10],
  ["clamps currencyConvert for a list pricing row 12", "clamp", 89.4, 85, 89, 89],
  ["computes currencyConvert for a promo pricing row 13", "base", 121, 18, 172.82],
  ["applies the currencyConvert fee path for a map pricing row 14", "fee", 182, 24, 279.36, 9],
  ["clamps currencyConvert for a surge pricing row 15", "clamp", 310.7, 310, 310.7, 314],
  ["computes currencyConvert for a bundle pricing row 16", "base", 60, 12, 82.6],
  ["applies the currencyConvert fee path for a contract pricing row 17", "fee", 117, 19, 172.31, 4],
  ["clamps currencyConvert for a member pricing row 18", "clamp", 218.72, 220, 220, 224],
  ["computes currencyConvert for a clearance pricing row 19", "base", 11, 3, 14.97],
  ["applies the currencyConvert fee path for a list pricing row 20", "fee", 72, 9, 100.76, 4],
  ["clamps currencyConvert for a list pricing row 21", "clamp", 167.2, 168, 168, 172],
  ["computes currencyConvert for a clearance pricing row 22", "base", 59, 11, 80.65],
  ["applies the currencyConvert fee path for a map pricing row 23", "fee", 238, 5, 313.02, 5],
  ["clamps currencyConvert for a promo pricing row 24", "clamp", 260.96, 261, 261, 265],
  ["computes currencyConvert for a bundle pricing row 25", "base", 116, 18, 165.72],
  ["applies the currencyConvert fee path for a surge pricing row 26", "fee", 55, 12, 77.8, 2],
  ["clamps currencyConvert for a member pricing row 27", "clamp", 304.2, 303, 304.2, 307],
  ["computes currencyConvert for a contract pricing row 28", "base", 173, 0, 215.52],
  ["applies the currencyConvert fee path for a list pricing row 29", "fee", 112, 19, 175.16, 14],
  ["clamps currencyConvert for a clearance pricing row 30", "clamp", 70.87, 69, 70.87, 73],
  ["computes currencyConvert for a promo pricing row 31", "base", 209, 1, 262.25],
  ["applies the currencyConvert fee path for a map pricing row 32", "fee", 30, 7, 47.3, 7],
  ["clamps currencyConvert for a clearance pricing row 33", "clamp", 125.67, 124, 125.67, 128],
  ["computes currencyConvert for a list pricing row 34", "base", 152, 19, 218.36],
  ["applies the currencyConvert fee path for a contract pricing row 35", "fee", 205, 2, 261.3, 2],
  ["clamps currencyConvert for a member pricing row 36", "clamp", 32.32, 33, 33, 37],
  ["computes currencyConvert for a surge pricing row 37", "base", 87, 14, 121.06],
  ["applies the currencyConvert fee path for a bundle pricing row 38", "fee", 148, 20, 219.12, 5],
  ["clamps currencyConvert for a promo pricing row 39", "clamp", 257.27, 254, 257.27, 258],
  ["computes currencyConvert for a map pricing row 40", "base", 22, 9, 30.26],
  ["applies the currencyConvert fee path for a map pricing row 41", "fee", 174, 6, 228.2, 1],
  ["clamps currencyConvert for a promo pricing row 42", "clamp", 140.12, 139, 140.12, 143],
  ["computes currencyConvert for a list pricing row 43", "base", 56, 18, 80.52],
  ["applies the currencyConvert fee path for a clearance pricing row 44", "fee", 235, 12, 322.6, 2],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(currencyConvert(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(currencyConvertWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCurrencyConvert(a, b, extra)).toBe(expected);
    }
  });
}
