// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  listPrice,
  listPriceWithFee,
  clampListPrice,
  factorFromBps,
} = require("./listPrice");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes listPrice for a surge pricing row 1", "base", 215, 2, 300.55],
  ["applies the listPrice fee path for a bundle pricing row 2", "fee", 36, 8, 70.47999999999999, 13],
  ["clamps listPrice for a contract pricing row 3", "clamp", 148.5, 144, 148, 148],
  ["computes listPrice for a member pricing row 4", "base", 154, 21, 246.24],
  ["applies the listPrice fee path for a clearance pricing row 5", "fee", 219, 1, 304.84, 1],
  ["clamps listPrice for a list pricing row 6", "clamp", 65.8, 61, 65, 65],
  ["computes listPrice for a promo pricing row 7", "base", 97, 14, 150.53],
  ["applies the listPrice fee path for a map pricing row 8", "fee", 158, 20, 250.9, 0],
  ["clamps listPrice for a surge pricing row 9", "clamp", 291.73, 292, 292, 296],
  ["computes listPrice for a bundle pricing row 10", "base", 28, 10, 46.6],
  ["applies the listPrice fee path for a bundle pricing row 11", "fee", 156, 23, 265.48, 13],
  ["clamps listPrice for a surge pricing row 12", "clamp", 153.4, 148, 152, 152],
  ["computes listPrice for a member pricing row 13", "base", 34, 11, 55.64],
  ["applies the listPrice fee path for a contract pricing row 14", "fee", 213, 5, 314.2, 10],
  ["clamps listPrice for a list pricing row 15", "clamp", 256.2, 255, 256.2, 259],
  ["computes listPrice for a clearance pricing row 16", "base", 99, 16, 155.49],
  ["applies the listPrice fee path for a map pricing row 17", "fee", 38, 10, 61.1, 0],
  ["clamps listPrice for a promo pricing row 18", "clamp", 307.63, 306, 307.63, 310],
  ["computes listPrice for a bundle pricing row 19", "base", 164, 21, 261.84],
  ["applies the listPrice fee path for a surge pricing row 20", "fee", 103, 15, 165.5, 5],
  ["clamps listPrice for a surge pricing row 21", "clamp", 143.33, 142, 143.33, 146],
  ["computes listPrice for a bundle pricing row 22", "base", 148, 5, 213.2],
  ["applies the listPrice fee path for a contract pricing row 23", "fee", 205, 12, 309.35, 2],
  ["clamps listPrice for a member pricing row 24", "clamp", 42.78, 44, 44, 48],
  ["computes listPrice for a clearance pricing row 25", "base", 91, 23, 149.78],
  ["applies the listPrice fee path for a list pricing row 26", "fee", 152, 4, 226.28, 9],
  ["clamps listPrice for a promo pricing row 27", "clamp", 314.14, 309, 313, 313],
  ["computes listPrice for a map pricing row 28", "base", 30, 17, 51.6],
  ["applies the listPrice fee path for a surge pricing row 29", "fee", 79, 1, 124.44, 11],
  ["clamps listPrice for a bundle pricing row 30", "clamp", 203.8, 203, 203.8, 207],
  ["computes listPrice for a map pricing row 31", "base", 238, 15, 363],
  ["applies the listPrice fee path for a promo pricing row 32", "fee", 177, 9, 264.88, 4],
  ["clamps listPrice for a list pricing row 33", "clamp", 167.4, 168, 168, 172],
  ["computes listPrice for a clearance pricing row 34", "base", 59, 21, 98.04],
  ["applies the listPrice fee path for a member pricing row 35", "fee", 234, 16, 360.34, 1],
  ["clamps listPrice for a contract pricing row 36", "clamp", 253.85000000000002, 255, 255, 259],
  ["computes listPrice for a bundle pricing row 37", "base", 116, 3, 166.08],
  ["applies the listPrice fee path for a surge pricing row 38", "fee", 55, 22, 94.35, 2],
  ["clamps listPrice for a map pricing row 39", "clamp", 353.6, 354, 354, 358],
  ["computes listPrice for a promo pricing row 40", "base", 169, 11, 252.74],
  ["applies the listPrice fee path for a promo pricing row 41", "fee", 129, 21, 208.24, 1],
  ["clamps listPrice for a map pricing row 42", "clamp", 269.3, 264, 268, 268],
  ["computes listPrice for a clearance pricing row 43", "base", 11, 8, 21.73],
  ["applies the listPrice fee path for a list pricing row 44", "fee", 72, 14, 117.28, 4],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(listPrice(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(listPriceWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampListPrice(a, b, extra)).toBe(expected);
    }
  });
}
