// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  mapPrice,
  mapPriceWithFee,
  clampMapPrice,
  factorFromBps,
} = require("./mapPrice");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes mapPrice for a contract pricing row 1", "base", 245, 2, 304.35],
  ["applies the mapPrice fee path for a member pricing row 2", "fee", 66, 8, 101.14, 13],
  ["clamps mapPrice for a surge pricing row 3", "clamp", 176.45, 172, 176, 176],
  ["computes mapPrice for a bundle pricing row 4", "base", 188, 20, 268.08],
  ["applies the mapPrice fee path for a promo pricing row 5", "fee", 9, 1, 14.98, 1],
  ["clamps mapPrice for a map pricing row 6", "clamp", 93.6, 91, 93.6, 95],
  ["computes mapPrice for a clearance pricing row 7", "base", 131, 13, 178.54],
  ["applies the mapPrice fee path for a list pricing row 8", "fee", 192, 19, 275.8, 4],
  ["clamps mapPrice for a contract pricing row 9", "clamp", 18.73, 17, 18.73, 21],
  ["computes mapPrice for a member pricing row 10", "base", 74, 6, 96.98],
  ["applies the mapPrice fee path for a map pricing row 11", "fee", 86, 18, 125.54, 3],
  ["clamps mapPrice for a promo pricing row 12", "clamp", 33.25, 34, 34, 38],
  ["computes mapPrice for a list pricing row 13", "base", 208, 5, 265.08],
  ["applies the mapPrice fee path for a clearance pricing row 14", "fee", 147, 24, 220.15, 4],
  ["clamps mapPrice for a member pricing row 15", "clamp", 115.8, 116, 116, 120],
  ["computes mapPrice for a contract pricing row 16", "base", 21, 13, 31.14],
  ["applies the mapPrice fee path for a bundle pricing row 17", "fee", 204, 6, 263.08, 1],
  ["clamps mapPrice for a surge pricing row 18", "clamp", 176.03, 174, 176.03, 178],
  ["computes mapPrice for a map pricing row 19", "base", 94, 16, 131.78],
  ["applies the mapPrice fee path for a promo pricing row 20", "fee", 33, 10, 56.23, 10],
  ["clamps mapPrice for a contract pricing row 21", "clamp", 311.1, 309, 311.1, 313],
  ["computes mapPrice for a member pricing row 22", "base", 58, 15, 81.88],
  ["applies the mapPrice fee path for a surge pricing row 23", "fee", 119, 21, 177.98, 6],
  ["clamps mapPrice for a bundle pricing row 24", "clamp", 223.4, 222, 223.4, 226],
  ["computes mapPrice for a promo pricing row 25", "base", 241, 8, 313.89],
  ["applies the mapPrice fee path for a map pricing row 26", "fee", 62, 14, 95.7, 9],
  ["clamps mapPrice for a clearance pricing row 27", "clamp", 174.43, 174, 174.43, 178],
  ["computes mapPrice for a list pricing row 28", "base", 184, 1, 227.48],
  ["applies the mapPrice fee path for a contract pricing row 29", "fee", 229, 11, 316.28, 11],
  ["clamps mapPrice for a member pricing row 30", "clamp", 72, 70, 72, 74],
  ["computes mapPrice for a bundle pricing row 31", "base", 148, 0, 182.08],
  ["applies the mapPrice fee path for a surge pricing row 32", "fee", 87, 19, 128.8, 4],
  ["clamps mapPrice for a member pricing row 33", "clamp", 34.84, 36, 36, 40],
  ["computes mapPrice for a contract pricing row 34", "base", 205, 7, 265.4],
  ["applies the mapPrice fee path for a list pricing row 35", "fee", 152, 24, 232.4, 9],
  ["clamps mapPrice for a clearance pricing row 36", "clamp", 129.49, 127, 129.49, 131],
  ["computes mapPrice for a map pricing row 37", "base", 30, 12, 42.9],
  ["applies the mapPrice fee path for a promo pricing row 38", "fee", 209, 6, 274.43, 6],
  ["clamps mapPrice for a bundle pricing row 39", "clamp", 174.2, 173, 174.2, 177],
  ["computes mapPrice for a surge pricing row 40", "base", 79, 21, 115.18],
  ["applies the mapPrice fee path for a clearance pricing row 41", "fee", 187, 9, 260.1, 14],
  ["clamps mapPrice for a list pricing row 42", "clamp", 14.88, 12, 14.88, 16],
  ["computes mapPrice for a promo pricing row 43", "base", 65, 22, 95.95],
  ["applies the mapPrice fee path for a map pricing row 44", "fee", 126, 3, 172.24, 13],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(mapPrice(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(mapPriceWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampMapPrice(a, b, extra)).toBe(expected);
    }
  });
}
