// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  markdown,
  markdownWithFee,
  clampMarkdown,
  factorFromBps,
} = require("./markdown");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes markdown for a surge pricing row 1", "base", 183, 0, 252.05],
  ["applies the markdown fee path for a bundle pricing row 2", "fee", 244, 6, 360.04, 11],
  ["clamps markdown for a contract pricing row 3", "clamp", 94.28, 93, 94.28, 97],
  ["computes markdown for a member pricing row 4", "base", 122, 19, 192.88],
  ["applies the markdown fee path for a clearance pricing row 5", "fee", 187, 24, 316.33, 14],
  ["clamps markdown for a list pricing row 6", "clamp", 15.2, 14, 15.2, 18],
  ["computes markdown for a promo pricing row 7", "base", 65, 12, 100.55],
  ["applies the markdown fee path for a map pricing row 8", "fee", 126, 18, 210.78, 13],
  ["clamps markdown for a surge pricing row 9", "clamp", 245.75, 243, 245.75, 247],
  ["computes markdown for a bundle pricing row 10", "base", 236, 8, 342.48],
  ["applies the markdown fee path for a bundle pricing row 11", "fee", 140, 7, 215.8, 12],
  ["clamps markdown for a surge pricing row 12", "clamp", 112.44, 110, 112.44, 114],
  ["computes markdown for a member pricing row 13", "base", 18, 20, 32.9],
  ["applies the markdown fee path for a contract pricing row 14", "fee", 197, 14, 307.53, 9],
  ["clamps markdown for a list pricing row 15", "clamp", 211.04, 206, 210, 210],
  ["computes markdown for a clearance pricing row 16", "base", 83, 0, 117.05],
  ["applies the markdown fee path for a map pricing row 17", "fee", 22, 19, 52.88, 14],
  ["clamps markdown for a promo pricing row 18", "clamp", 299.48, 300, 300, 304],
  ["computes markdown for a bundle pricing row 19", "base", 148, 5, 212.2],
  ["applies the markdown fee path for a surge pricing row 20", "fee", 87, 24, 147.33, 4],
  ["clamps markdown for a surge pricing row 21", "clamp", 84.85, 84, 84.85, 88],
  ["computes markdown for a bundle pricing row 22", "base", 116, 18, 182.48],
  ["applies the markdown fee path for a contract pricing row 23", "fee", 173, 0, 238.55, 0],
  ["clamps markdown for a member pricing row 24", "clamp", 331.94, 333, 333, 337],
  ["computes markdown for a clearance pricing row 25", "base", 59, 11, 91.14],
  ["applies the markdown fee path for a list pricing row 26", "fee", 120, 17, 194.4, 7],
  ["clamps markdown for a promo pricing row 27", "clamp", 289.43, 284, 288, 288],
  ["computes markdown for a map pricing row 28", "base", 238, 5, 338.2],
  ["applies the markdown fee path for a surge pricing row 29", "fee", 47, 14, 84.03, 9],
  ["clamps markdown for a bundle pricing row 30", "clamp", 171.4, 170, 171.4, 174],
  ["computes markdown for a map pricing row 31", "base", 110, 17, 172.2],
  ["applies the markdown fee path for a promo pricing row 32", "fee", 49, 11, 87.54, 11],
  ["clamps markdown for a list pricing row 33", "clamp", 325.48, 325, 325.48, 329],
  ["computes markdown for a clearance pricing row 34", "base", 171, 23, 275.18],
  ["applies the markdown fee path for a member pricing row 35", "fee", 106, 18, 175.18, 8],
  ["clamps markdown for a contract pricing row 36", "clamp", 69.15, 69, 69.15, 73],
  ["computes markdown for a bundle pricing row 37", "base", 228, 5, 324.2],
  ["applies the markdown fee path for a surge pricing row 38", "fee", 167, 24, 279.53, 9],
  ["clamps markdown for a map pricing row 39", "clamp", 161.08, 160, 161.08, 164],
  ["computes markdown for a promo pricing row 40", "base", 41, 13, 65.68],
  ["applies the markdown fee path for a promo pricing row 41", "fee", 241, 23, 393.78, 8],
  ["clamps markdown for a map pricing row 42", "clamp", 88.18, 89, 89, 93],
  ["computes markdown for a clearance pricing row 43", "base", 123, 10, 183.35],
  ["applies the markdown fee path for a list pricing row 44", "fee", 184, 16, 293.84, 11],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(markdown(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(markdownWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampMarkdown(a, b, extra)).toBe(expected);
    }
  });
}
