// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 113;

function memberPrice(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function memberPriceWithFee(amount, factor, fee) {
  return memberPrice(amount, factor) + fee;
}

function clampMemberPrice(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  memberPrice,
  memberPriceWithFee,
  clampMemberPrice,
  factorFromBps,
};
