// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  memberPrice,
  memberPriceWithFee,
  clampMemberPrice,
  factorFromBps,
} = require("./memberPrice");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes memberPrice for a contract pricing row 1", "base", 197, 4, 233.49],
  ["applies the memberPrice fee path for a member pricing row 2", "fee", 18, 10, 35.14, 10],
  ["clamps memberPrice for a surge pricing row 3", "clamp", 101.91, 103, 103, 107],
  ["computes memberPrice for a bundle pricing row 4", "base", 140, 22, 192],
  ["applies the memberPrice fee path for a promo pricing row 5", "fee", 201, 3, 249.16, 13],
  ["clamps memberPrice for a map pricing row 6", "clamp", 32.84, 28, 32, 32],
  ["computes memberPrice for a clearance pricing row 7", "base", 83, 15, 109.24],
  ["applies the memberPrice fee path for a list pricing row 8", "fee", 144, 21, 196.96, 1],
  ["clamps memberPrice for a contract pricing row 9", "clamp", 240.75, 237, 240.75, 241],
  ["computes memberPrice for a member pricing row 10", "base", 26, 8, 34.46],
  ["applies the memberPrice fee path for a map pricing row 11", "fee", 118, 20, 164.94, 5],
  ["clamps memberPrice for a promo pricing row 12", "clamp", 77.39, 73, 77, 77],
  ["computes memberPrice for a list pricing row 13", "base", 240, 7, 291],
  ["applies the memberPrice fee path for a clearance pricing row 14", "fee", 179, 1, 213.06, 6],
  ["clamps memberPrice for a member pricing row 15", "clamp", 158.76, 154, 158, 158],
  ["computes memberPrice for a contract pricing row 16", "base", 53, 15, 70.84],
  ["applies the memberPrice fee path for a bundle pricing row 17", "fee", 236, 8, 291.56, 3],
  ["clamps memberPrice for a surge pricing row 18", "clamp", 202.25, 202, 202.25, 206],
  ["computes memberPrice for a map pricing row 19", "base", 126, 18, 168.06],
  ["applies the memberPrice fee path for a promo pricing row 20", "fee", 65, 12, 96.25, 12],
  ["clamps memberPrice for a contract pricing row 21", "clamp", 36.96, 37, 37, 41],
  ["computes memberPrice for a member pricing row 22", "base", 90, 17, 120],
  ["applies the memberPrice fee path for a surge pricing row 23", "fee", 151, 23, 216.36, 8],
  ["clamps memberPrice for a bundle pricing row 24", "clamp", 248.04, 249, 249, 253],
  ["computes memberPrice for a promo pricing row 25", "base", 49, 6, 61.31],
  ["applies the memberPrice fee path for a map pricing row 26", "fee", 110, 12, 152.5, 12],
  ["clamps memberPrice for a clearance pricing row 27", "clamp", 227.01, 225, 227.01, 229],
  ["computes memberPrice for a list pricing row 28", "base", 232, 24, 320.84],
  ["applies the memberPrice fee path for a contract pricing row 29", "fee", 21, 13, 42.46, 13],
  ["clamps memberPrice for a member pricing row 30", "clamp", 109.24, 109, 109.24, 113],
  ["computes memberPrice for a bundle pricing row 31", "base", 84, 16, 111.36],
  ["applies the memberPrice fee path for a surge pricing row 32", "fee", 23, 10, 31.29, 0],
  ["clamps memberPrice for a member pricing row 33", "clamp", 242.34, 237, 241, 241],
  ["computes memberPrice for a contract pricing row 34", "base", 141, 23, 194.76],
  ["applies the memberPrice fee path for a list pricing row 35", "fee", 88, 15, 120.64, 5],
  ["clamps memberPrice for a clearance pricing row 36", "clamp", 34.94, 34, 34.94, 38],
  ["computes memberPrice for a map pricing row 37", "base", 206, 3, 241.96],
  ["applies the memberPrice fee path for a promo pricing row 38", "fee", 145, 22, 200.75, 2],
  ["clamps memberPrice for a bundle pricing row 39", "clamp", 100.56, 101, 101, 105],
  ["computes memberPrice for a surge pricing row 40", "base", 15, 12, 21.75],
  ["applies the memberPrice fee path for a clearance pricing row 41", "fee", 235, 7, 287, 2],
  ["clamps memberPrice for a list pricing row 42", "clamp", 76.56, 72, 76, 76],
  ["computes memberPrice for a promo pricing row 43", "base", 113, 20, 153.29],
  ["applies the memberPrice fee path for a map pricing row 44", "fee", 174, 1, 202.36, 1],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(memberPrice(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(memberPriceWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampMemberPrice(a, b, extra)).toBe(expected);
    }
  });
}
