// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 115;

function priceList(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function priceListWithFee(amount, factor, fee) {
  return priceList(amount, factor) + fee;
}

function clampPriceList(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  priceList,
  priceListWithFee,
  clampPriceList,
  factorFromBps,
};
