// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 104;

function priceGuard(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function priceGuardWithFee(amount, factor, fee) {
  return priceGuard(amount, factor) + fee;
}

function clampPriceGuard(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  priceGuard,
  priceGuardWithFee,
  clampPriceGuard,
  factorFromBps,
};
