// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  promoPrice,
  promoPriceWithFee,
  clampPromoPrice,
  factorFromBps,
} = require("./promoPrice");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes promoPrice for a bundle pricing row 1", "base", 188, 10, 257.68],
  ["applies the promoPrice fee path for a surge pricing row 2", "fee", 127, 4, 181.1, 14],
  ["clamps promoPrice for a member pricing row 3", "clamp", 99.34, 98, 99.34, 102],
  ["computes promoPrice for a contract pricing row 4", "base", 245, 17, 352.35],
  ["applies the promoPrice fee path for a list pricing row 5", "fee", 192, 9, 265.2, 4],
  ["clamps promoPrice for a clearance pricing row 6", "clamp", 172.99, 169, 172.99, 173],
  ["computes promoPrice for a map pricing row 7", "base", 70, 22, 105.6],
  ["applies the promoPrice fee path for a promo pricing row 8", "fee", 9, 16, 15.78, 1],
  ["clamps promoPrice for a bundle pricing row 9", "clamp", 262.64, 263, 263, 267],
  ["computes promoPrice for a surge pricing row 10", "base", 135, 2, 174.8],
  ["applies the promoPrice fee path for a contract pricing row 11", "fee", 141, 18, 218.04, 13],
  ["clamps promoPrice for a member pricing row 12", "clamp", 304, 303, 304, 307],
  ["computes promoPrice for a surge pricing row 13", "base", 23, 5, 32.13],
  ["applies the promoPrice fee path for a bundle pricing row 14", "fee", 84, 11, 118.08, 1],
  ["clamps promoPrice for a promo pricing row 15", "clamp", 207.35, 207, 207.35, 211],
  ["computes promoPrice for a map pricing row 16", "base", 206, 23, 308.94],
  ["applies the promoPrice fee path for a clearance pricing row 17", "fee", 27, 4, 41.1, 4],
  ["clamps promoPrice for a list pricing row 18", "clamp", 118.68, 120, 120, 124],
  ["computes promoPrice for a contract pricing row 19", "base", 133, 20, 196.18],
  ["applies the promoPrice fee path for a member pricing row 20", "fee", 194, 1, 254.38, 6],
  ["clamps promoPrice for a map pricing row 21", "clamp", 138.7, 138, 138.7, 142],
  ["computes promoPrice for a promo pricing row 22", "base", 41, 3, 54.89],
  ["applies the promoPrice fee path for a list pricing row 23", "fee", 224, 21, 337.28, 6],
  ["clamps promoPrice for a clearance pricing row 24", "clamp", 232.83, 230, 232.83, 234],
  ["computes promoPrice for a member pricing row 25", "base", 98, 10, 135.28],
  ["applies the promoPrice fee path for a contract pricing row 26", "fee", 37, 4, 64.1, 14],
  ["clamps promoPrice for a bundle pricing row 27", "clamp", 329.6, 326, 329.6, 330],
  ["computes promoPrice for a surge pricing row 28", "base", 159, 16, 227.78],
  ["applies the promoPrice fee path for a map pricing row 29", "fee", 110, 7, 160.3, 12],
  ["clamps promoPrice for a promo pricing row 30", "clamp", 63.230000000000004, 62, 63.230000000000004, 66],
  ["computes promoPrice for a surge pricing row 31", "base", 191, 18, 277.04],
  ["applies the promoPrice fee path for a bundle pricing row 32", "fee", 12, 24, 24, 4],
  ["clamps promoPrice for a contract pricing row 33", "clamp", 94.08, 91, 94.08, 95],
  ["computes promoPrice for a member pricing row 34", "base", 130, 12, 181.4],
  ["applies the promoPrice fee path for a clearance pricing row 35", "fee", 195, 17, 287.85, 7],
  ["clamps promoPrice for a list pricing row 36", "clamp", 26.84, 24, 26.84, 28],
  ["computes promoPrice for a promo pricing row 37", "base", 73, 5, 97.63],
  ["applies the promoPrice fee path for a map pricing row 38", "fee", 134, 11, 191.58, 6],
  ["clamps promoPrice for a surge pricing row 39", "clamp", 284.58, 283, 284.58, 287],
  ["computes promoPrice for a bundle pricing row 40", "base", 20, 22, 31.6],
  ["applies the promoPrice fee path for a list pricing row 41", "fee", 48, 20, 82.08, 10],
  ["clamps promoPrice for a clearance pricing row 42", "clamp", 319.8, 318, 319.8, 322],
  ["computes promoPrice for a map pricing row 43", "base", 166, 8, 224.44],
  ["applies the promoPrice fee path for a promo pricing row 44", "fee", 105, 2, 143.4, 7],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(promoPrice(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(promoPriceWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPromoPrice(a, b, extra)).toBe(expected);
    }
  });
}
