// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  quote,
  quoteWithFee,
  clampQuote,
  factorFromBps,
} = require("./quote");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes quote for a bundle pricing row 1", "base", 180, 12, 264.8],
  ["applies the quote fee path for a surge pricing row 2", "fee", 119, 6, 174.6, 6],
  ["clamps quote for a member pricing row 3", "clamp", 76.72, 78, 78, 82],
  ["computes quote for a contract pricing row 4", "base", 237, 19, 364.61],
  ["applies the quote fee path for a list pricing row 5", "fee", 184, 11, 279.8, 11],
  ["clamps quote for a clearance pricing row 6", "clamp", 172.97, 171, 172.97, 175],
  ["computes quote for a map pricing row 7", "base", 62, 24, 99.96],
  ["applies the quote fee path for a promo pricing row 8", "fee", 241, 18, 376.32, 8],
  ["clamps quote for a bundle pricing row 9", "clamp", 255.56, 255, 255.56, 259],
  ["computes quote for a surge pricing row 10", "base", 111, 8, 159.62],
  ["applies the quote fee path for a contract pricing row 11", "fee", 85, 17, 132.35, 2],
  ["clamps quote for a member pricing row 12", "clamp", 234.22, 229, 233, 233],
  ["computes quote for a surge pricing row 13", "base", 207, 4, 287.66],
  ["applies the quote fee path for a bundle pricing row 14", "fee", 28, 10, 47.32, 5],
  ["clamps quote for a promo pricing row 15", "clamp", 137.5, 134, 137.5, 138],
  ["computes quote for a map pricing row 16", "base", 150, 22, 236],
  ["applies the quote fee path for a clearance pricing row 17", "fee", 211, 3, 299.07, 8],
  ["clamps quote for a list pricing row 18", "clamp", 48.76, 46, 48.76, 50],
  ["computes quote for a contract pricing row 19", "base", 93, 15, 140.57],
  ["applies the quote fee path for a member pricing row 20", "fee", 154, 21, 251.7, 11],
  ["clamps quote for a map pricing row 21", "clamp", 87.56, 86, 87.56, 90],
  ["computes quote for a promo pricing row 22", "base", 241, 23, 380.37],
  ["applies the quote fee path for a list pricing row 23", "fee", 184, 16, 289, 11],
  ["clamps quote for a clearance pricing row 24", "clamp", 181.12, 177, 181, 181],
  ["computes quote for a member pricing row 25", "base", 58, 5, 82.62],
  ["applies the quote fee path for a contract pricing row 26", "fee", 237, 24, 380.46, 4],
  ["clamps quote for a bundle pricing row 27", "clamp", 276.8, 272, 276, 276],
  ["computes quote for a surge pricing row 28", "base", 119, 11, 174.55],
  ["applies the quote fee path for a map pricing row 29", "fee", 54, 6, 78.6, 1],
  ["clamps quote for a promo pricing row 30", "clamp", 317.22, 312, 316, 316],
  ["computes quote for a surge pricing row 31", "base", 151, 13, 223.97],
  ["applies the quote fee path for a bundle pricing row 32", "fee", 212, 19, 335.36, 9],
  ["clamps quote for a contract pricing row 33", "clamp", 43.15, 39, 43, 43],
  ["computes quote for a member pricing row 34", "base", 90, 7, 128.9],
  ["applies the quote fee path for a clearance pricing row 35", "fee", 155, 12, 240.3, 12],
  ["clamps quote for a list pricing row 36", "clamp", 332.32, 328, 332, 332],
  ["computes quote for a promo pricing row 37", "base", 33, 0, 46.22],
  ["applies the quote fee path for a map pricing row 38", "fee", 94, 6, 144.6, 11],
  ["clamps quote for a surge pricing row 39", "clamp", 212.07, 213, 213, 217],
  ["computes quote for a bundle pricing row 40", "base", 204, 21, 318.2],
  ["applies the quote fee path for a list pricing row 41", "fee", 8, 15, 13.92, 0],
  ["clamps quote for a clearance pricing row 42", "clamp", 270.41, 267, 270.41, 271],
  ["computes quote for a map pricing row 43", "base", 126, 3, 174.62],
  ["applies the quote fee path for a promo pricing row 44", "fee", 65, 22, 115.4, 12],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(quote(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(quoteWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampQuote(a, b, extra)).toBe(expected);
    }
  });
}
