// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  surgePrice,
  surgePriceWithFee,
  clampSurgePrice,
  factorFromBps,
} = require("./surgePrice");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes surgePrice for a promo pricing row 1", "base", 9, 6, 17.35],
  ["applies the surgePrice fee path for a map pricing row 2", "fee", 70, 12, 93.7, 2],
  ["clamps surgePrice for a clearance pricing row 3", "clamp", 176.37, 171, 175, 175],
  ["computes surgePrice for a list pricing row 4", "base", 192, 24, 262.36],
  ["applies the surgePrice fee path for a contract pricing row 5", "fee", 245, 7, 303.2, 12],
  ["clamps surgePrice for a member pricing row 6", "clamp", 87.52, 86, 87.52, 90],
  ["computes surgePrice for a surge pricing row 7", "base", 127, 19, 169.56],
  ["applies the surgePrice fee path for a bundle pricing row 8", "fee", 188, 0, 211.92, 0],
  ["clamps surgePrice for a promo pricing row 9", "clamp", 27.21, 24, 27.21, 28],
  ["computes surgePrice for a map pricing row 10", "base", 78, 10, 99.82],
  ["applies the surgePrice fee path for a member pricing row 11", "fee", 114, 21, 156.2, 1],
  ["clamps surgePrice for a contract pricing row 12", "clamp", 74.72, 71, 74.72, 75],
  ["computes surgePrice for a bundle pricing row 13", "base", 12, 4, 20.56],
  ["applies the surgePrice fee path for a surge pricing row 14", "fee", 191, 23, 262.12, 3],
  ["clamps surgePrice for a map pricing row 15", "clamp", 176.5, 173, 176.5, 177],
  ["computes surgePrice for a promo pricing row 16", "base", 73, 10, 93.87],
  ["applies the surgePrice fee path for a list pricing row 17", "fee", 16, 3, 32.92, 8],
  ["clamps surgePrice for a clearance pricing row 18", "clamp", 259.45, 260, 260, 264],
  ["computes surgePrice for a member pricing row 19", "base", 138, 15, 178.12],
  ["applies the surgePrice fee path for a contract pricing row 20", "fee", 77, 9, 106.86, 9],
  ["clamps surgePrice for a promo pricing row 21", "clamp", 191.9, 191, 191.9, 195],
  ["computes surgePrice for a map pricing row 22", "base", 230, 7, 273.8],
  ["applies the surgePrice fee path for a clearance pricing row 23", "fee", 51, 13, 82.22, 13],
  ["clamps surgePrice for a list pricing row 24", "clamp", 148.36, 148, 148.36, 152],
  ["computes surgePrice for a contract pricing row 25", "base", 165, 2, 190.15],
  ["applies the surgePrice fee path for a member pricing row 26", "fee", 226, 8, 279.42, 8],
  ["clamps surgePrice for a surge pricing row 27", "clamp", 66.81, 63, 66.81, 67],
  ["computes surgePrice for a bundle pricing row 28", "base", 108, 20, 146.32],
  ["applies the surgePrice fee path for a promo pricing row 29", "fee", 177, 24, 246.41, 4],
  ["clamps surgePrice for a map pricing row 30", "clamp", 281.32, 276, 280, 280],
  ["computes surgePrice for a list pricing row 31", "base", 80, 17, 107.8],
  ["applies the surgePrice fee path for a clearance pricing row 32", "fee", 19, 11, 40.8, 11],
  ["clamps surgePrice for a map pricing row 33", "clamp", 235.72, 231, 235, 235],
  ["computes surgePrice for a promo pricing row 34", "base", 137, 24, 189.21],
  ["applies the surgePrice fee path for a bundle pricing row 35", "fee", 76, 18, 111.52, 8],
  ["clamps surgePrice for a surge pricing row 36", "clamp", 22.15, 23, 23, 27],
  ["computes surgePrice for a member pricing row 37", "base", 194, 6, 230.1],
  ["applies the surgePrice fee path for a contract pricing row 38", "fee", 133, 0, 156.97, 5],
  ["clamps surgePrice for a list pricing row 39", "clamp", 118.12, 114, 118, 118],
  ["computes surgePrice for a clearance pricing row 40", "base", 27, 9, 38.86],
  ["applies the surgePrice fee path for a surge pricing row 41", "fee", 223, 15, 288.52, 5],
  ["clamps surgePrice for a bundle pricing row 42", "clamp", 62.2, 62, 62.2, 66],
  ["computes surgePrice for a contract pricing row 43", "base", 101, 3, 120.12],
  ["applies the surgePrice fee path for a member pricing row 44", "fee", 162, 9, 202.16, 4],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(surgePrice(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(surgePriceWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampSurgePrice(a, b, extra)).toBe(expected);
    }
  });
}
