// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 139;

function tierPrice(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function tierPriceWithFee(amount, factor, fee) {
  return tierPrice(amount, factor) + fee;
}

function clampTierPrice(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  tierPrice,
  tierPriceWithFee,
  clampTierPrice,
  factorFromBps,
};
