// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 137;

function customsHs(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function customsHsWithFee(amount, factor, fee) {
  return customsHs(amount, factor) + fee;
}

function clampCustomsHs(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  customsHs,
  customsHsWithFee,
  clampCustomsHs,
  factorFromBps,
};
