// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 110;

function dimWeight(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function dimWeightWithFee(amount, factor, fee) {
  return dimWeight(amount, factor) + fee;
}

function clampDimWeight(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  dimWeight,
  dimWeightWithFee,
  clampDimWeight,
  factorFromBps,
};
