// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 133;

function freightClass(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function freightClassWithFee(amount, factor, fee) {
  return freightClass(amount, factor) + fee;
}

function clampFreightClass(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  freightClass,
  freightClassWithFee,
  clampFreightClass,
  factorFromBps,
};
