// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  holdAtLocation,
  holdAtLocationWithFee,
  clampHoldAtLocation,
  factorFromBps,
} = require("./holdAtLocation");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes holdAtLocation for a intl shipping row 1", "base", 71, 3, 77.26],
  ["applies the holdAtLocation fee path for a pickup shipping row 2", "fee", 132, 9, 153.84, 4],
  ["clamps holdAtLocation for a locker shipping row 3", "clamp", 228.91, 225, 228.91, 229],
  ["computes holdAtLocation for a overnight shipping row 4", "base", 10, 22, 14.5],
  ["applies the holdAtLocation fee path for a freight shipping row 5", "fee", 75, 2, 87.75, 7],
  ["clamps holdAtLocation for a ground shipping row 6", "clamp", 154.96, 151, 154.96, 155],
  ["computes holdAtLocation for a express shipping row 7", "base", 193, 15, 229.74],
  ["applies the holdAtLocation fee path for a rural shipping row 8", "fee", 14, 21, 25.36, 6],
  ["clamps holdAtLocation for a intl shipping row 9", "clamp", 67.04, 68, 68, 72],
  ["computes holdAtLocation for a pickup shipping row 10", "base", 124, 11, 143.36],
  ["applies the holdAtLocation fee path for a pickup shipping row 11", "fee", 60, 22, 84, 7],
  ["clamps holdAtLocation for a intl shipping row 12", "clamp", 287.41, 284, 287.41, 288],
  ["computes holdAtLocation for a overnight shipping row 13", "base", 178, 10, 203.14],
  ["applies the holdAtLocation fee path for a locker shipping row 14", "fee", 117, 4, 131.19, 4],
  ["clamps holdAtLocation for a ground shipping row 15", "clamp", 78.36, 79, 79, 83],
  ["computes holdAtLocation for a freight shipping row 16", "base", 243, 15, 288.74],
  ["applies the holdAtLocation fee path for a rural shipping row 17", "fee", 182, 9, 214.84, 9],
  ["clamps holdAtLocation for a express shipping row 18", "clamp", 128.26, 128, 128.26, 132],
  ["computes holdAtLocation for a pickup shipping row 19", "base", 68, 20, 85.64],
  ["applies the holdAtLocation fee path for a intl shipping row 20", "fee", 247, 14, 304.99, 14],
  ["clamps holdAtLocation for a intl shipping row 21", "clamp", 227.75, 226, 227.75, 230],
  ["computes holdAtLocation for a pickup shipping row 22", "base", 36, 8, 41.96],
  ["applies the holdAtLocation fee path for a locker shipping row 23", "fee", 93, 15, 121.74, 10],
  ["clamps holdAtLocation for a overnight shipping row 24", "clamp", 190.96, 191, 191, 195],
  ["computes holdAtLocation for a freight shipping row 25", "base", 219, 1, 229.76],
  ["applies the holdAtLocation fee path for a ground shipping row 26", "fee", 40, 7, 48, 2],
  ["clamps holdAtLocation for a express shipping row 27", "clamp", 112.49, 113, 113, 117],
  ["computes holdAtLocation for a rural shipping row 28", "base", 158, 20, 196.34],
  ["applies the holdAtLocation fee path for a intl shipping row 29", "fee", 207, 4, 227.49, 4],
  ["clamps holdAtLocation for a pickup shipping row 30", "clamp", 33.64, 32, 33.64, 36],
  ["computes holdAtLocation for a rural shipping row 31", "base", 126, 18, 154.46],
  ["applies the holdAtLocation fee path for a express shipping row 32", "fee", 65, 12, 88.75, 12],
  ["clamps holdAtLocation for a ground shipping row 33", "clamp", 8.64, 9, 9, 13],
  ["computes holdAtLocation for a freight shipping row 34", "base", 187, 24, 239.49],
  ["applies the holdAtLocation fee path for a overnight shipping row 35", "fee", 122, 19, 159.84, 9],
  ["clamps holdAtLocation for a locker shipping row 36", "clamp", 70.76, 71, 71, 75],
  ["computes holdAtLocation for a pickup shipping row 37", "base", 244, 6, 267.96],
  ["applies the holdAtLocation fee path for a intl shipping row 38", "fee", 183, 0, 200.49, 10],
  ["clamps holdAtLocation for a rural shipping row 39", "clamp", 146.14, 145, 146.14, 149],
  ["computes holdAtLocation for a express shipping row 40", "base", 57, 14, 68.69],
  ["applies the holdAtLocation fee path for a express shipping row 41", "fee", 161, 13, 191.76, 3],
  ["clamps holdAtLocation for a rural shipping row 42", "clamp", 270.84, 271, 271, 275],
  ["computes holdAtLocation for a freight shipping row 43", "base", 43, 0, 46.29],
  ["applies the holdAtLocation fee path for a ground shipping row 44", "fee", 104, 6, 121.36, 6],
  ["clamps holdAtLocation for a locker shipping row 45", "clamp", 187.69, 184, 187.69, 188],
  ["computes holdAtLocation for a overnight shipping row 46", "base", 218, 20, 270.14],
  ["applies the holdAtLocation fee path for a intl shipping row 47", "fee", 39, 1, 43.56, 1],
  ["clamps holdAtLocation for a pickup shipping row 48", "clamp", 113, 110, 113, 114],
  ["computes holdAtLocation for a express shipping row 49", "base", 153, 15, 182.54],
  ["applies the holdAtLocation fee path for a rural shipping row 50", "fee", 214, 21, 278.36, 11],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(holdAtLocation(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(holdAtLocationWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampHoldAtLocation(a, b, extra)).toBe(expected);
    }
  });
}
