// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 2;
const FACTOR_BASE = 103;

function holdAtLocation(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function holdAtLocationWithFee(amount, factor, fee) {
  return holdAtLocation(amount, factor) + fee;
}

function clampHoldAtLocation(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  holdAtLocation,
  holdAtLocationWithFee,
  clampHoldAtLocation,
  factorFromBps,
};
