// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 7;
const FACTOR_BASE = 113;

function labelPrint(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function labelPrintWithFee(amount, factor, fee) {
  return labelPrint(amount, factor) + fee;
}

function clampLabelPrint(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  labelPrint,
  labelPrintWithFee,
  clampLabelPrint,
  factorFromBps,
};
