// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  pickupScan,
  pickupScanWithFee,
  clampPickupScan,
  factorFromBps,
} = require("./pickupScan");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes pickupScan for a express shipping row 1", "base", 137, 9, 189.58],
  ["applies the pickupScan fee path for a rural shipping row 2", "fee", 198, 15, 293.2, 10],
  ["clamps pickupScan for a freight shipping row 3", "clamp", 33.74, 32, 33.74, 36],
  ["computes pickupScan for a ground shipping row 4", "base", 80, 2, 107.6],
  ["applies the pickupScan fee path for a locker shipping row 5", "fee", 133, 10, 190.55, 5],
  ["clamps pickupScan for a overnight shipping row 6", "clamp", 276.54, 278, 278, 282],
  ["computes pickupScan for a intl shipping row 7", "base", 15, 22, 28.05],
  ["applies the pickupScan fee path for a pickup shipping row 8", "fee", 76, 3, 111.28, 8],
  ["clamps pickupScan for a express shipping row 9", "clamp", 195.4, 195, 195.4, 199],
  ["computes pickupScan for a rural shipping row 10", "base", 206, 13, 290.28],
  ["applies the pickupScan fee path for a overnight shipping row 11", "fee", 178, 10, 251.3, 5],
  ["clamps pickupScan for a locker shipping row 12", "clamp", 158.93, 155, 158.93, 159],
  ["computes pickupScan for a pickup shipping row 13", "base", 60, 22, 94.2],
  ["applies the pickupScan fee path for a intl shipping row 14", "fee", 239, 16, 348.99, 6],
  ["clamps pickupScan for a rural shipping row 15", "clamp", 247.88, 248, 248, 252],
  ["computes pickupScan for a express shipping row 16", "base", 121, 3, 160.88],
  ["applies the pickupScan fee path for a ground shipping row 17", "fee", 64, 21, 110.44, 11],
  ["clamps pickupScan for a freight shipping row 18", "clamp", 346.2, 344, 346.2, 348],
  ["computes pickupScan for a overnight shipping row 19", "base", 186, 8, 253.38],
  ["applies the pickupScan fee path for a locker shipping row 20", "fee", 125, 2, 176.75, 12],
  ["clamps pickupScan for a express shipping row 21", "clamp", 116.14, 116, 116.14, 120],
  ["computes pickupScan for a rural shipping row 22", "base", 150, 7, 204],
  ["applies the pickupScan fee path for a freight shipping row 23", "fee", 211, 13, 305.18, 8],
  ["clamps pickupScan for a ground shipping row 24", "clamp", 49.08, 50, 50, 54],
  ["computes pickupScan for a locker shipping row 25", "base", 85, 2, 113.95],
  ["applies the pickupScan fee path for a overnight shipping row 26", "fee", 146, 8, 203.18, 3],
  ["clamps pickupScan for a intl shipping row 27", "clamp", 294.73, 292, 294.73, 296],
  ["computes pickupScan for a pickup shipping row 28", "base", 28, 20, 46.6],
  ["applies the pickupScan fee path for a express shipping row 29", "fee", 97, 24, 164.53, 14],
  ["clamps pickupScan for a rural shipping row 30", "clamp", 213.4, 209, 213, 213],
  ["computes pickupScan for a ground shipping row 31", "base", 240, 17, 346.8],
  ["applies the pickupScan fee path for a freight shipping row 32", "fee", 179, 11, 255.44, 6],
  ["clamps pickupScan for a rural shipping row 33", "clamp", 161.4, 157, 161, 161],
  ["computes pickupScan for a express shipping row 34", "base", 57, 24, 90.93],
  ["applies the pickupScan fee path for a pickup shipping row 35", "fee", 236, 18, 346.48, 3],
  ["clamps pickupScan for a intl shipping row 36", "clamp", 248.75, 244, 248, 248],
  ["computes pickupScan for a overnight shipping row 37", "base", 114, 6, 155.34],
  ["applies the pickupScan fee path for a locker shipping row 38", "fee", 53, 0, 72.25, 0],
  ["clamps pickupScan for a ground shipping row 39", "clamp", 18.2, 15, 18.2, 19],
  ["computes pickupScan for a freight shipping row 40", "base", 187, 9, 256.58],
  ["applies the pickupScan fee path for a intl shipping row 41", "fee", 143, 15, 206.2, 0],
  ["clamps pickupScan for a pickup shipping row 42", "clamp", 300.84, 302, 302, 306],
  ["computes pickupScan for a locker shipping row 43", "base", 21, 3, 32.88],
  ["applies the pickupScan fee path for a overnight shipping row 44", "fee", 82, 9, 129.88, 14],
  ["clamps pickupScan for a freight shipping row 45", "clamp", 213.33, 208, 212, 212],
  ["computes pickupScan for a ground shipping row 46", "base", 208, 20, 307.6],
  ["applies the pickupScan fee path for a express shipping row 47", "fee", 25, 2, 39.75, 2],
  ["clamps pickupScan for a rural shipping row 48", "clamp", 121.38, 118, 121.38, 122],
  ["computes pickupScan for a intl shipping row 49", "base", 151, 13, 214.38],
  ["applies the pickupScan fee path for a pickup shipping row 50", "fee", 212, 19, 320.28, 9],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(pickupScan(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(pickupScanWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPickupScan(a, b, extra)).toBe(expected);
    }
  });
}
