// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 118;

function rateShop(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function rateShopWithFee(amount, factor, fee) {
  return rateShop(amount, factor) + fee;
}

function clampRateShop(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  rateShop,
  rateShopWithFee,
  clampRateShop,
  factorFromBps,
};
