// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  ruralSurcharge,
  ruralSurchargeWithFee,
  clampRuralSurcharge,
  factorFromBps,
} = require("./ruralSurcharge");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes ruralSurcharge for a pickup shipping row 1", "base", 124, 16, 157.24],
  ["applies the ruralSurcharge fee path for a intl shipping row 2", "fee", 63, 10, 86.6, 10],
  ["clamps ruralSurcharge for a overnight shipping row 3", "clamp", 274.88, 275, 275, 279],
  ["computes ruralSurcharge for a locker shipping row 4", "base", 181, 23, 241.73],
  ["applies the ruralSurcharge fee path for a ground shipping row 5", "fee", 128, 15, 161, 0],
  ["clamps ruralSurcharge for a freight shipping row 6", "clamp", 81.73, 79, 81.73, 83],
  ["computes ruralSurcharge for a rural shipping row 7", "base", 246, 3, 278.98],
  ["applies the ruralSurcharge fee path for a express shipping row 8", "fee", 185, 22, 257.2, 12],
  ["clamps ruralSurcharge for a pickup shipping row 9", "clamp", 161.68, 163, 163, 167],
  ["computes ruralSurcharge for a intl shipping row 10", "base", 71, 8, 84.78],
  ["applies the ruralSurcharge fee path for a locker shipping row 11", "fee", 141, 23, 201.53, 13],
  ["clamps ruralSurcharge for a overnight shipping row 12", "clamp", 234.28, 229, 233, 233],
  ["computes ruralSurcharge for a intl shipping row 13", "base", 23, 10, 28.6],
  ["applies the ruralSurcharge fee path for a pickup shipping row 14", "fee", 84, 16, 107.84, 1],
  ["clamps ruralSurcharge for a express shipping row 15", "clamp", 194.4, 190, 194, 194],
  ["computes ruralSurcharge for a rural shipping row 16", "base", 206, 3, 233.78],
  ["applies the ruralSurcharge fee path for a freight shipping row 17", "fee", 27, 9, 37.13, 4],
  ["clamps ruralSurcharge for a ground shipping row 18", "clamp", 112, 109, 112, 113],
  ["computes ruralSurcharge for a locker shipping row 19", "base", 133, 0, 147.3],
  ["applies the ruralSurcharge fee path for a overnight shipping row 20", "fee", 194, 6, 232.04, 6],
  ["clamps ruralSurcharge for a rural shipping row 21", "clamp", 110.08, 109, 110.08, 113],
  ["computes ruralSurcharge for a express shipping row 22", "base", 25, 12, 31.5],
  ["applies the ruralSurcharge fee path for a ground shipping row 23", "fee", 208, 5, 245.2, 5],
  ["clamps ruralSurcharge for a freight shipping row 24", "clamp", 198.98, 196, 198.98, 200],
  ["computes ruralSurcharge for a overnight shipping row 25", "base", 82, 19, 106.78],
  ["applies the ruralSurcharge fee path for a locker shipping row 26", "fee", 21, 13, 39.83, 13],
  ["clamps ruralSurcharge for a pickup shipping row 27", "clamp", 239.64, 236, 239.64, 240],
  ["computes ruralSurcharge for a intl shipping row 28", "base", 143, 0, 158.3],
  ["applies the ruralSurcharge fee path for a rural shipping row 29", "fee", 94, 16, 130.44, 11],
  ["clamps ruralSurcharge for a express shipping row 30", "clamp", 39.6, 39, 39.6, 43],
  ["computes ruralSurcharge for a intl shipping row 31", "base", 175, 2, 197],
  ["applies the ruralSurcharge fee path for a pickup shipping row 32", "fee", 236, 8, 282.48, 3],
  ["clamps ruralSurcharge for a locker shipping row 33", "clamp", 68.25, 65, 68.25, 69],
  ["computes ruralSurcharge for a overnight shipping row 34", "base", 114, 21, 150.34],
  ["applies the ruralSurcharge fee path for a freight shipping row 35", "fee", 179, 1, 205.69, 6],
  ["clamps ruralSurcharge for a ground shipping row 36", "clamp", 282.8, 280, 282.8, 284],
  ["computes ruralSurcharge for a express shipping row 37", "base", 57, 14, 71.68],
  ["applies the ruralSurcharge fee path for a rural shipping row 38", "fee", 118, 20, 159.4, 5],
  ["clamps ruralSurcharge for a intl shipping row 39", "clamp", 202.3, 200, 202.3, 204],
  ["computes ruralSurcharge for a pickup shipping row 40", "base", 244, 6, 284.04],
  ["applies the ruralSurcharge fee path for a ground shipping row 41", "fee", 32, 4, 46.48, 9],
  ["clamps ruralSurcharge for a freight shipping row 42", "clamp", 281.63, 280, 281.63, 284],
  ["computes ruralSurcharge for a rural shipping row 43", "base", 150, 17, 191.5],
  ["applies the ruralSurcharge fee path for a express shipping row 44", "fee", 89, 11, 114.69, 6],
  ["clamps ruralSurcharge for a pickup shipping row 45", "clamp", 34.2, 31, 34.2, 35],
  ["computes ruralSurcharge for a intl shipping row 46", "base", 207, 24, 278.38],
  ["applies the ruralSurcharge fee path for a overnight shipping row 47", "fee", 146, 18, 190.88, 3],
  ["clamps ruralSurcharge for a locker shipping row 48", "clamp", 106.7, 103, 106.7, 107],
  ["computes ruralSurcharge for a ground shipping row 49", "base", 40, 2, 45.8],
  ["applies the ruralSurcharge fee path for a freight shipping row 50", "fee", 219, 21, 288.89, 1],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(ruralSurcharge(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(ruralSurchargeWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampRuralSurcharge(a, b, extra)).toBe(expected);
    }
  });
}
