// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 134;

function shippingQuote(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function shippingQuoteWithFee(amount, factor, fee) {
  return shippingQuote(amount, factor) + fee;
}

function clampShippingQuote(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  shippingQuote,
  shippingQuoteWithFee,
  clampShippingQuote,
  factorFromBps,
};
