// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  shipNotify,
  shipNotifyWithFee,
  clampShipNotify,
  factorFromBps,
} = require("./shipNotify");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes shipNotify for a intl shipping row 1", "base", 31, 23, 46.54],
  ["applies the shipNotify fee path for a pickup shipping row 2", "fee", 92, 4, 119.8, 9],
  ["clamps shipNotify for a locker shipping row 3", "clamp", 183.78, 185, 185, 189],
  ["computes shipNotify for a overnight shipping row 4", "base", 210, 17, 273.8],
  ["applies the shipNotify fee path for a freight shipping row 5", "fee", 35, 22, 63.55, 12],
  ["clamps shipNotify for a ground shipping row 6", "clamp", 111.44, 112, 112, 116],
  ["computes shipNotify for a express shipping row 7", "base", 153, 10, 190.13],
  ["applies the shipNotify fee path for a rural shipping row 8", "fee", 214, 16, 287.78, 11],
  ["clamps shipNotify for a intl shipping row 9", "clamp", 59.48, 54, 58, 58],
  ["computes shipNotify for a pickup shipping row 10", "base", 100, 2, 118],
  ["applies the shipNotify fee path for a pickup shipping row 11", "fee", 180, 17, 242.4, 7],
  ["clamps shipNotify for a intl shipping row 12", "clamp", 148.18, 148, 148.18, 152],
  ["computes shipNotify for a overnight shipping row 13", "base", 58, 5, 72.28],
  ["applies the shipNotify fee path for a locker shipping row 14", "fee", 237, 24, 328.95, 4],
  ["clamps shipNotify for a ground shipping row 15", "clamp", 239.68, 237, 239.68, 241],
  ["computes shipNotify for a freight shipping row 16", "base", 123, 10, 153.83],
  ["applies the shipNotify fee path for a rural shipping row 17", "fee", 62, 4, 85.3, 9],
  ["clamps shipNotify for a express shipping row 18", "clamp", 329.94, 326, 329.94, 330],
  ["computes shipNotify for a pickup shipping row 19", "base", 172, 19, 228.6],
  ["applies the shipNotify fee path for a intl shipping row 20", "fee", 111, 13, 155.64, 13],
  ["clamps shipNotify for a intl shipping row 21", "clamp", 93.48, 91, 93.48, 95],
  ["computes shipNotify for a pickup shipping row 22", "base", 140, 7, 170.2],
  ["applies the shipNotify fee path for a locker shipping row 23", "fee", 197, 14, 260.25, 9],
  ["clamps shipNotify for a overnight shipping row 24", "clamp", 26.58, 27, 27, 31],
  ["computes shipNotify for a freight shipping row 25", "base", 83, 0, 97.13],
  ["applies the shipNotify fee path for a ground shipping row 26", "fee", 144, 6, 174.48, 1],
  ["clamps shipNotify for a express shipping row 27", "clamp", 251.24, 252, 252, 256],
  ["computes shipNotify for a rural shipping row 28", "base", 22, 19, 33.6],
  ["applies the shipNotify fee path for a intl shipping row 29", "fee", 87, 24, 126.45, 4],
  ["clamps shipNotify for a pickup shipping row 30", "clamp", 173.68, 175, 175, 179],
  ["computes shipNotify for a rural shipping row 31", "base", 230, 17, 299.4],
  ["applies the shipNotify fee path for a express shipping row 32", "fee", 169, 11, 222.18, 11],
  ["clamps shipNotify for a ground shipping row 33", "clamp", 131.8, 132, 132, 136],
  ["computes shipNotify for a freight shipping row 34", "base", 51, 23, 73.34],
  ["applies the shipNotify fee path for a overnight shipping row 35", "fee", 226, 18, 304.54, 8],
  ["clamps shipNotify for a locker shipping row 36", "clamp", 205.95, 206, 206, 210],
  ["computes shipNotify for a pickup shipping row 37", "base", 108, 5, 130.28],
  ["applies the shipNotify fee path for a intl shipping row 38", "fee", 47, 24, 77.45, 9],
  ["clamps shipNotify for a rural shipping row 39", "clamp", 307.88, 303, 307, 307],
  ["computes shipNotify for a express shipping row 40", "base", 177, 9, 217.4],
  ["applies the shipNotify fee path for a express shipping row 41", "fee", 25, 12, 37.75, 2],
  ["clamps shipNotify for a rural shipping row 42", "clamp", 113.94, 114, 114, 118],
  ["computes shipNotify for a freight shipping row 43", "base", 147, 24, 203.45],
  ["applies the shipNotify fee path for a ground shipping row 44", "fee", 208, 5, 251.28, 5],
  ["clamps shipNotify for a locker shipping row 45", "clamp", 33.04, 29, 33, 33],
  ["computes shipNotify for a overnight shipping row 46", "base", 82, 19, 111.6],
  ["applies the shipNotify fee path for a intl shipping row 47", "fee", 143, 0, 163.73, 0],
  ["clamps shipNotify for a pickup shipping row 48", "clamp", 244.68, 242, 244.68, 246],
  ["computes shipNotify for a express shipping row 49", "base", 33, 10, 44.93],
  ["applies the shipNotify fee path for a rural shipping row 50", "fee", 94, 16, 135.38, 11],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(shipNotify(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(shipNotifyWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampShipNotify(a, b, extra)).toBe(expected);
    }
  });
}
