// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  transitDays,
  transitDaysWithFee,
  clampTransitDays,
  factorFromBps,
} = require("./transitDays");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes transitDays for a overnight shipping row 1", "base", 138, 20, 216.28],
  ["applies the transitDays fee path for a locker shipping row 2", "fee", 77, 14, 125.5, 9],
  ["clamps transitDays for a pickup shipping row 3", "clamp", 27.6, 28, 28, 32],
  ["computes transitDays for a intl shipping row 4", "base", 199, 1, 273.63],
  ["applies the transitDays fee path for a rural shipping row 5", "fee", 142, 19, 235.1, 14],
  ["clamps transitDays for a express shipping row 6", "clamp", 121.69, 120, 121.69, 124],
  ["computes transitDays for a ground shipping row 7", "base", 24, 6, 35.08],
  ["applies the transitDays fee path for a freight shipping row 8", "fee", 203, 0, 277.08, 0],
  ["clamps transitDays for a overnight shipping row 9", "clamp", 205.4, 204, 205.4, 208],
  ["computes transitDays for a locker shipping row 10", "base", 69, 16, 105.88],
  ["applies the transitDays fee path for a intl shipping row 11", "fee", 167, 9, 252.15, 9],
  ["clamps transitDays for a pickup shipping row 12", "clamp", 348.28, 343, 347, 347],
  ["computes transitDays for a locker shipping row 13", "base", 45, 22, 72.1],
  ["applies the transitDays fee path for a overnight shipping row 14", "fee", 106, 3, 156.34, 8],
  ["clamps transitDays for a freight shipping row 15", "clamp", 249.24, 245, 249, 249],
  ["computes transitDays for a ground shipping row 16", "base", 232, 14, 349],
  ["applies the transitDays fee path for a express shipping row 17", "fee", 49, 21, 88.93, 11],
  ["clamps transitDays for a rural shipping row 18", "clamp", 152.8, 151, 152.8, 155],
  ["computes transitDays for a intl shipping row 19", "base", 159, 11, 234.73],
  ["applies the transitDays fee path for a pickup shipping row 20", "fee", 220, 17, 339.6, 2],
  ["clamps transitDays for a pickup shipping row 21", "clamp", 340.84, 339, 340.84, 343],
  ["computes transitDays for a intl shipping row 22", "base", 175, 2, 242.5],
  ["applies the transitDays fee path for a overnight shipping row 23", "fee", 114, 21, 180.98, 1],
  ["clamps transitDays for a locker shipping row 24", "clamp", 82.03, 79, 82.03, 83],
  ["computes transitDays for a ground shipping row 25", "base", 240, 7, 344.2],
  ["applies the transitDays fee path for a freight shipping row 26", "fee", 179, 1, 252.23, 6],
  ["clamps transitDays for a rural shipping row 27", "clamp", 182.08, 183, 183, 187],
  ["computes transitDays for a express shipping row 28", "base", 57, 14, 86.5],
  ["applies the transitDays fee path for a pickup shipping row 29", "fee", 244, 6, 358.48, 11],
  ["clamps transitDays for a intl shipping row 30", "clamp", 249.88, 248, 249.88, 252],
  ["computes transitDays for a locker shipping row 31", "base", 85, 17, 131.05],
  ["applies the transitDays fee path for a overnight shipping row 32", "fee", 146, 23, 236.14, 3],
  ["clamps transitDays for a intl shipping row 33", "clamp", 293.8, 289, 293, 293],
  ["computes transitDays for a pickup shipping row 34", "base", 28, 10, 41.88],
  ["applies the transitDays fee path for a express shipping row 35", "fee", 89, 16, 142.28, 6],
  ["clamps transitDays for a rural shipping row 36", "clamp", 240, 236, 240, 240],
  ["computes transitDays for a freight shipping row 37", "base", 211, 3, 294.29],
  ["applies the transitDays fee path for a ground shipping row 38", "fee", 32, 9, 56.4, 9],
  ["clamps transitDays for a locker shipping row 39", "clamp", 142.43, 139, 142.43, 143],
  ["computes transitDays for a overnight shipping row 40", "base", 154, 21, 242.78],
  ["applies the transitDays fee path for a overnight shipping row 41", "fee", 202, 4, 297.8, 14],
  ["clamps transitDays for a locker shipping row 42", "clamp", 226.19, 223, 226.19, 227],
  ["computes transitDays for a pickup shipping row 43", "base", 84, 16, 128.68],
  ["applies the transitDays fee path for a intl shipping row 44", "fee", 23, 10, 34.58, 0],
  ["clamps transitDays for a rural shipping row 45", "clamp", 284.34, 285, 285, 289],
  ["computes transitDays for a express shipping row 46", "base", 145, 22, 230.1],
  ["applies the transitDays fee path for a ground shipping row 47", "fee", 88, 15, 138.88, 5],
  ["clamps transitDays for a freight shipping row 48", "clamp", 39.15, 38, 39.15, 42],
  ["computes transitDays for a overnight shipping row 49", "base", 194, 6, 276.48],
  ["applies the transitDays fee path for a locker shipping row 50", "fee", 133, 0, 186.88, 5],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(transitDays(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(transitDaysWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampTransitDays(a, b, extra)).toBe(expected);
    }
  });
}
