// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  weekendCut,
  weekendCutWithFee,
  clampWeekendCut,
  factorFromBps,
} = require("./weekendCut");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes weekendCut for a intl shipping row 1", "base", 47, 4, 53.29],
  ["applies the weekendCut fee path for a pickup shipping row 2", "fee", 108, 10, 135.04000000000002, 10],
  ["clamps weekendCut for a locker shipping row 3", "clamp", 200, 199, 200, 203],
  ["computes weekendCut for a overnight shipping row 4", "base", 226, 23, 287.76],
  ["applies the weekendCut fee path for a freight shipping row 5", "fee", 51, 3, 70.06, 13],
  ["clamps weekendCut for a ground shipping row 6", "clamp", 127.44, 126, 127.44, 130],
  ["computes weekendCut for a express shipping row 7", "base", 169, 16, 204.11],
  ["applies the weekendCut fee path for a rural shipping row 8", "fee", 230, 22, 302.5, 12],
  ["clamps weekendCut for a intl shipping row 9", "clamp", 58.75, 59, 59, 63],
  ["computes weekendCut for a pickup shipping row 10", "base", 116, 8, 131.76],
  ["applies the weekendCut fee path for a pickup shipping row 11", "fee", 228, 20, 293.44, 10],
  ["clamps weekendCut for a intl shipping row 12", "clamp", 196.39, 196, 196.39, 200],
  ["computes weekendCut for a overnight shipping row 13", "base", 106, 8, 120.66],
  ["applies the weekendCut fee path for a locker shipping row 14", "fee", 45, 2, 57.25, 7],
  ["clamps weekendCut for a ground shipping row 15", "clamp", 287.04, 284, 287.04, 288],
  ["computes weekendCut for a freight shipping row 16", "base", 171, 13, 201.36],
  ["applies the weekendCut fee path for a rural shipping row 17", "fee", 110, 7, 136, 12],
  ["clamps weekendCut for a express shipping row 18", "clamp", 55.96, 52, 55.96, 56],
  ["computes weekendCut for a pickup shipping row 19", "base", 220, 22, 278],
  ["applies the weekendCut fee path for a intl shipping row 20", "fee", 159, 16, 193.21, 1],
  ["clamps weekendCut for a intl shipping row 21", "clamp", 138.89, 137, 138.89, 141],
  ["computes weekendCut for a pickup shipping row 22", "base", 188, 10, 215.44],
  ["applies the weekendCut fee path for a locker shipping row 23", "fee", 245, 17, 309, 12],
  ["clamps weekendCut for a overnight shipping row 24", "clamp", 84.16, 84, 84.16, 88],
  ["computes weekendCut for a freight shipping row 25", "base", 131, 3, 141.86],
  ["applies the weekendCut fee path for a ground shipping row 26", "fee", 192, 9, 222.04, 4],
  ["clamps weekendCut for a express shipping row 27", "clamp", 10.71, 12, 12, 16],
  ["computes weekendCut for a rural shipping row 28", "base", 70, 22, 90.5],
  ["applies the weekendCut fee path for a intl shipping row 29", "fee", 135, 2, 151.75, 7],
  ["clamps weekendCut for a pickup shipping row 30", "clamp", 217.56, 219, 219, 223],
  ["computes weekendCut for a rural shipping row 31", "base", 38, 20, 49.74],
  ["applies the weekendCut fee path for a express shipping row 32", "fee", 217, 14, 270.89, 14],
  ["clamps weekendCut for a ground shipping row 33", "clamp", 177, 177, 177, 181],
  ["computes weekendCut for a freight shipping row 34", "base", 99, 1, 105.96],
  ["applies the weekendCut fee path for a overnight shipping row 35", "fee", 34, 21, 56.16, 11],
  ["clamps weekendCut for a locker shipping row 36", "clamp", 252.34, 252, 252.34, 256],
  ["computes weekendCut for a pickup shipping row 37", "base", 156, 8, 176.16],
  ["applies the weekendCut fee path for a intl shipping row 38", "fee", 95, 2, 114.75, 12],
  ["clamps weekendCut for a rural shipping row 39", "clamp", 61.66, 57, 61, 61],
  ["computes weekendCut for a express shipping row 40", "base", 225, 12, 261.75],
  ["applies the weekendCut fee path for a express shipping row 41", "fee", 73, 15, 94.14, 5],
  ["clamps weekendCut for a rural shipping row 42", "clamp", 167.16, 167, 167.16, 171],
  ["computes weekendCut for a freight shipping row 43", "base", 195, 2, 207.75],
  ["applies the weekendCut fee path for a ground shipping row 44", "fee", 16, 8, 28.76, 8],
  ["clamps weekendCut for a locker shipping row 45", "clamp", 87.11, 83, 87, 87],
  ["computes weekendCut for a overnight shipping row 46", "base", 130, 22, 165.5],
  ["applies the weekendCut fee path for a intl shipping row 47", "fee", 191, 3, 208.46, 3],
  ["clamps weekendCut for a pickup shipping row 48", "clamp", 17.44, 14, 17.44, 18],
  ["computes weekendCut for a express shipping row 49", "base", 81, 13, 96.96],
  ["applies the weekendCut fee path for a rural shipping row 50", "fee", 142, 19, 190.24, 14],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(weekendCut(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(weekendCutWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampWeekendCut(a, b, extra)).toBe(expected);
    }
  });
}
