// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 3;
const FACTOR_BASE = 103;

function weekendCut(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function weekendCutWithFee(amount, factor, fee) {
  return weekendCut(amount, factor) + fee;
}

function clampWeekendCut(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  weekendCut,
  weekendCutWithFee,
  clampWeekendCut,
  factorFromBps,
};
