// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  zoneLookup,
  zoneLookupWithFee,
  clampZoneLookup,
  factorFromBps,
} = require("./zoneLookup");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes zoneLookup for a overnight shipping row 1", "base", 242, 24, 356.48],
  ["applies the zoneLookup fee path for a locker shipping row 2", "fee", 181, 18, 265.78, 8],
  ["clamps zoneLookup for a pickup shipping row 3", "clamp", 168.44, 168, 168.44, 172],
  ["computes zoneLookup for a intl shipping row 4", "base", 63, 5, 86.75],
  ["applies the zoneLookup fee path for a rural shipping row 5", "fee", 246, 23, 372.78, 13],
  ["clamps zoneLookup for a express shipping row 6", "clamp", 261.45, 259, 261.45, 263],
  ["computes zoneLookup for a ground shipping row 7", "base", 128, 10, 174.4],
  ["applies the zoneLookup fee path for a freight shipping row 8", "fee", 67, 4, 105.08, 14],
  ["clamps zoneLookup for a overnight shipping row 9", "clamp", 25.2, 20, 24, 24],
  ["computes zoneLookup for a locker shipping row 10", "base", 189, 16, 265.04],
  ["applies the zoneLookup fee path for a intl shipping row 11", "fee", 15, 2, 33.3, 7],
  ["clamps zoneLookup for a pickup shipping row 12", "clamp", 105.28, 103, 105.28, 107],
  ["computes zoneLookup for a locker shipping row 13", "base", 133, 15, 187.55],
  ["applies the zoneLookup fee path for a overnight shipping row 14", "fee", 194, 21, 287.54, 6],
  ["clamps zoneLookup for a freight shipping row 15", "clamp", 29.99, 29, 29.99, 33],
  ["computes zoneLookup for a ground shipping row 16", "base", 80, 7, 109.6],
  ["applies the zoneLookup fee path for a express shipping row 17", "fee", 137, 14, 200.58, 9],
  ["clamps zoneLookup for a rural shipping row 18", "clamp", 282.2, 283, 283, 287],
  ["computes zoneLookup for a intl shipping row 19", "base", 23, 0, 35.6],
  ["applies the zoneLookup fee path for a pickup shipping row 20", "fee", 84, 6, 114.84, 1],
  ["clamps zoneLookup for a pickup shipping row 21", "clamp", 186.88, 183, 186.88, 187],
  ["computes zoneLookup for a intl shipping row 22", "base", 71, 8, 98.88],
  ["applies the zoneLookup fee path for a overnight shipping row 23", "fee", 10, 2, 22.2, 2],
  ["clamps zoneLookup for a locker shipping row 24", "clamp", 277.49, 272, 276, 276],
  ["computes zoneLookup for a ground shipping row 25", "base", 136, 13, 188.88],
  ["applies the zoneLookup fee path for a freight shipping row 26", "fee", 75, 7, 110.25, 7],
  ["clamps zoneLookup for a rural shipping row 27", "clamp", 23.94, 23, 23.94, 27],
  ["computes zoneLookup for a express shipping row 28", "base", 193, 20, 278.2],
  ["applies the zoneLookup fee path for a pickup shipping row 29", "fee", 124, 16, 187.64, 11],
  ["clamps zoneLookup for a intl shipping row 30", "clamp", 87.9, 88, 88, 92],
  ["computes zoneLookup for a locker shipping row 31", "base", 77, 9, 107.33],
  ["applies the zoneLookup fee path for a overnight shipping row 32", "fee", 138, 15, 204.3, 10],
  ["clamps zoneLookup for a intl shipping row 33", "clamp", 285.59, 287, 287, 291],
  ["computes zoneLookup for a pickup shipping row 34", "base", 20, 2, 32.4],
  ["applies the zoneLookup fee path for a express shipping row 35", "fee", 81, 8, 124.68, 13],
  ["clamps zoneLookup for a rural shipping row 36", "clamp", 201.28, 196, 200, 200],
  ["computes zoneLookup for a freight shipping row 37", "base", 203, 20, 292.2],
  ["applies the zoneLookup fee path for a ground shipping row 38", "fee", 24, 1, 38.04, 1],
  ["clamps zoneLookup for a locker shipping row 39", "clamp", 96.39, 96, 96.39, 100],
  ["computes zoneLookup for a overnight shipping row 40", "base", 130, 17, 186.1],
  ["applies the zoneLookup fee path for a overnight shipping row 41", "fee", 146, 8, 197.88, 3],
  ["clamps zoneLookup for a locker shipping row 42", "clamp", 108.7, 110, 110, 114],
  ["computes zoneLookup for a pickup shipping row 43", "base", 44, 16, 67.84],
  ["applies the zoneLookup fee path for a intl shipping row 44", "fee", 223, 10, 302.9, 5],
  ["clamps zoneLookup for a rural shipping row 45", "clamp", 209.18, 210, 210, 214],
  ["computes zoneLookup for a express shipping row 46", "base", 105, 22, 157.1],
  ["applies the zoneLookup fee path for a ground shipping row 47", "fee", 48, 15, 82.8, 10],
  ["clamps zoneLookup for a freight shipping row 48", "clamp", 299.83, 299, 299.83, 303],
  ["computes zoneLookup for a overnight shipping row 49", "base", 170, 2, 215.4],
  ["applies the zoneLookup fee path for a locker shipping row 50", "fee", 109, 21, 172.69, 11],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(zoneLookup(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(zoneLookupWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampZoneLookup(a, b, extra)).toBe(expected);
    }
  });
}
