// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  addressValidate,
  addressValidateWithFee,
  clampAddressValidate,
  factorFromBps,
} = require("./addressValidate");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes addressValidate for a pickup checkout row 1", "base", 194, 1, 225.22],
  ["applies the addressValidate fee path for a hold checkout row 2", "fee", 133, 20, 186.56, 5],
  ["clamps addressValidate for a split checkout row 3", "clamp", 101, 99, 101, 103],
  ["computes addressValidate for a retail checkout row 4", "base", 15, 7, 23.85],
  ["applies the addressValidate fee path for a express checkout row 5", "fee", 198, 0, 237.76, 10],
  ["clamps addressValidate for a member checkout row 6", "clamp", 187.47, 183, 187, 187],
  ["computes addressValidate for a guest checkout row 7", "base", 80, 12, 105.2],
  ["applies the addressValidate fee path for a digital checkout row 8", "fee", 19, 6, 39.42, 11],
  ["clamps addressValidate for a pickup checkout row 9", "clamp", 278.72, 279, 279, 283],
  ["computes addressValidate for a hold checkout row 10", "base", 141, 18, 189.3],
  ["applies the addressValidate fee path for a retail checkout row 11", "fee", 127, 19, 186.37, 14],
  ["clamps addressValidate for a split checkout row 12", "clamp", 217.56, 215, 217.56, 219],
  ["computes addressValidate for a hold checkout row 13", "base", 245, 7, 297.55],
  ["applies the addressValidate fee path for a pickup checkout row 14", "fee", 66, 13, 101.5, 13],
  ["clamps addressValidate for a digital checkout row 15", "clamp", 176.3, 174, 176.3, 178],
  ["computes addressValidate for a guest checkout row 16", "base", 192, 24, 267.12],
  ["applies the addressValidate fee path for a member checkout row 17", "fee", 9, 6, 17.62, 1],
  ["clamps addressValidate for a express checkout row 18", "clamp", 90.8, 91, 91, 95],
  ["computes addressValidate for a retail checkout row 19", "base", 135, 17, 180.15],
  ["applies the addressValidate fee path for a split checkout row 20", "fee", 196, 23, 278.6, 8],
  ["clamps addressValidate for a split checkout row 21", "clamp", 296.92, 292, 296, 296],
  ["computes addressValidate for a retail checkout row 22", "base", 167, 4, 199.72],
  ["applies the addressValidate fee path for a pickup checkout row 23", "fee", 106, 23, 157.1, 8],
  ["clamps addressValidate for a hold checkout row 24", "clamp", 64.05, 62, 64.05, 66],
  ["computes addressValidate for a guest checkout row 25", "base", 8, 5, 15.36],
  ["applies the addressValidate fee path for a digital checkout row 26", "fee", 187, 24, 274.32, 14],
  ["clamps addressValidate for a express checkout row 27", "clamp", 169.8, 168, 169.8, 172],
  ["computes addressValidate for a member checkout row 28", "base", 65, 12, 86.6],
  ["applies the addressValidate fee path for a split checkout row 29", "fee", 220, 12, 280.8, 2],
  ["clamps addressValidate for a retail checkout row 30", "clamp", 195.62, 192, 195.62, 196],
  ["computes addressValidate for a hold checkout row 31", "base", 77, 19, 106.87],
  ["applies the addressValidate fee path for a pickup checkout row 32", "fee", 138, 0, 170.56, 10],
  ["clamps addressValidate for a retail checkout row 33", "clamp", 242.82, 239, 242.82, 243],
  ["computes addressValidate for a split checkout row 34", "base", 20, 12, 30.8],
  ["applies the addressValidate fee path for a member checkout row 35", "fee", 81, 18, 124.3, 13],
  ["clamps addressValidate for a express checkout row 36", "clamp", 200.12, 197, 200.12, 201],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(addressValidate(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(addressValidateWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampAddressValidate(a, b, extra)).toBe(expected);
    }
  });
}
