// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  checkoutHold,
  checkoutHoldWithFee,
  clampCheckoutHold,
  factorFromBps,
} = require("./checkoutHold");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes checkoutHold for a digital checkout row 1", "base", 139, 16, 183.09],
  ["applies the checkoutHold fee path for a guest checkout row 2", "fee", 200, 22, 287, 12],
  ["clamps checkoutHold for a member checkout row 3", "clamp", 23.23, 19, 23, 23],
  ["computes checkoutHold for a express checkout row 4", "base", 78, 10, 98.5],
  ["applies the checkoutHold fee path for a retail checkout row 5", "fee", 135, 17, 186.2, 7],
  ["clamps checkoutHold for a split checkout row 6", "clamp", 271.48, 269, 271.48, 273],
  ["computes checkoutHold for a hold checkout row 7", "base", 13, 5, 16.6],
  ["applies the checkoutHold fee path for a pickup checkout row 8", "fee", 74, 11, 100.24, 6],
  ["clamps checkoutHold for a digital checkout row 9", "clamp", 172.23, 173, 173, 177],
  ["computes checkoutHold for a guest checkout row 10", "base", 192, 24, 267.88],
  ["applies the checkoutHold fee path for a guest checkout row 11", "fee", 40, 12, 53.8, 2],
  ["clamps checkoutHold for a digital checkout row 12", "clamp", 264.99, 264, 264.99, 268],
  ["computes checkoutHold for a express checkout row 13", "base", 158, 0, 182.7],
  ["applies the checkoutHold fee path for a member checkout row 14", "fee", 97, 19, 144.98, 14],
  ["clamps checkoutHold for a split checkout row 15", "clamp", 47.08, 45, 47.08, 49],
  ["computes checkoutHold for a retail checkout row 16", "base", 215, 7, 263.3],
  ["applies the checkoutHold fee path for a pickup checkout row 17", "fee", 154, 1, 190.64, 11],
  ["clamps checkoutHold for a hold checkout row 18", "clamp", 127.55, 125, 127.55, 129],
  ["computes checkoutHold for a guest checkout row 19", "base", 32, 14, 42.28],
  ["applies the checkoutHold fee path for a digital checkout row 20", "fee", 211, 8, 268.53, 8],
  ["clamps checkoutHold for a digital checkout row 21", "clamp", 245.44, 242, 245.44, 246],
  ["computes checkoutHold for a guest checkout row 22", "base", 240, 2, 281.8],
  ["applies the checkoutHold fee path for a member checkout row 23", "fee", 57, 9, 75.68, 4],
  ["clamps checkoutHold for a express checkout row 24", "clamp", 153.4, 152, 153.4, 156],
  ["computes checkoutHold for a retail checkout row 25", "base", 175, 22, 240.75],
  ["applies the checkoutHold fee path for a split checkout row 26", "fee", 236, 3, 282.48, 3],
  ["clamps checkoutHold for a hold checkout row 27", "clamp", 70.25, 65, 69, 69],
  ["computes checkoutHold for a pickup checkout row 28", "base", 114, 16, 150.34],
  ["applies the checkoutHold fee path for a digital checkout row 29", "fee", 187, 19, 265.58000000000004, 14],
  ["clamps checkoutHold for a guest checkout row 30", "clamp", 8.2, 8, 8.2, 12],
  ["computes checkoutHold for a pickup checkout row 31", "base", 90, 12, 115.3],
  ["applies the checkoutHold fee path for a hold checkout row 32", "fee", 29, 6, 42.09, 6],
  ["clamps checkoutHold for a split checkout row 33", "clamp", 294.68, 294, 294.68, 298],
  ["computes checkoutHold for a retail checkout row 34", "base", 151, 18, 201.83],
  ["applies the checkoutHold fee path for a express checkout row 35", "fee", 94, 11, 130.44, 11],
  ["clamps checkoutHold for a member checkout row 36", "clamp", 41.6, 39, 41.6, 43],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(checkoutHold(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(checkoutHoldWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCheckoutHold(a, b, extra)).toBe(expected);
    }
  });
}
