// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  checkoutSession,
  checkoutSessionWithFee,
  clampCheckoutSession,
  factorFromBps,
} = require("./checkoutSession");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes checkoutSession for a split checkout row 1", "base", 196, 3, 275.52],
  ["applies the checkoutSession fee path for a retail checkout row 2", "fee", 135, 22, 224.6, 7],
  ["clamps checkoutSession for a pickup checkout row 3", "clamp", 115, 116, 116, 120],
  ["computes checkoutSession for a hold checkout row 4", "base", 13, 10, 25.72],
  ["applies the checkoutSession fee path for a guest checkout row 5", "fee", 200, 2, 291, 12],
  ["clamps checkoutSession for a digital checkout row 6", "clamp", 222.45, 220, 222.45, 224],
  ["computes checkoutSession for a express checkout row 7", "base", 78, 15, 123.22],
  ["applies the checkoutSession fee path for a member checkout row 8", "fee", 17, 9, 40.31, 9],
  ["clamps checkoutSession for a split checkout row 9", "clamp", 267.32, 266, 267.32, 270],
  ["computes checkoutSession for a retail checkout row 10", "base", 127, 24, 207.66],
  ["applies the checkoutSession fee path for a hold checkout row 11", "fee", 197, 19, 317.41, 9],
  ["clamps checkoutSession for a pickup checkout row 12", "clamp", 31.12, 29, 31.12, 33],
  ["computes checkoutSession for a retail checkout row 13", "base", 79, 6, 117.6],
  ["applies the checkoutSession fee path for a split checkout row 14", "fee", 140, 12, 223.4, 12],
  ["clamps checkoutSession for a member checkout row 15", "clamp", 311.52, 311, 311.52, 315],
  ["computes checkoutSession for a express checkout row 16", "base", 22, 24, 41.76],
  ["applies the checkoutSession fee path for a digital checkout row 17", "fee", 83, 5, 122.37, 0],
  ["clamps checkoutSession for a guest checkout row 18", "clamp", 213.8, 214, 214, 218],
  ["computes checkoutSession for a hold checkout row 19", "base", 205, 17, 316.55],
  ["applies the checkoutSession fee path for a pickup checkout row 20", "fee", 26, 23, 50.82, 3],
  ["clamps checkoutSession for a express checkout row 21", "clamp", 266.4, 263, 266.4, 267],
  ["computes checkoutSession for a member checkout row 22", "base", 129, 21, 206.95],
  ["applies the checkoutSession fee path for a guest checkout row 23", "fee", 72, 14, 117.56, 4],
  ["clamps checkoutSession for a digital checkout row 24", "clamp", 25.62, 21, 25, 25],
  ["computes checkoutSession for a pickup checkout row 25", "base", 186, 3, 261.82],
  ["applies the checkoutSession fee path for a hold checkout row 26", "fee", 125, 22, 214, 12],
  ["clamps checkoutSession for a split checkout row 27", "clamp", 105.32, 106, 106, 110],
  ["computes checkoutSession for a retail checkout row 28", "base", 247, 9, 360.21],
  ["applies the checkoutSession fee path for a express checkout row 29", "fee", 182, 4, 267.16, 9],
  ["clamps checkoutSession for a member checkout row 30", "clamp", 193.97, 195, 195, 199],
  ["computes checkoutSession for a retail checkout row 31", "base", 39, 11, 63.55],
  ["applies the checkoutSession fee path for a split checkout row 32", "fee", 100, 17, 160, 2],
  ["clamps checkoutSession for a hold checkout row 33", "clamp", 258.06, 253, 257, 257],
  ["computes checkoutSession for a pickup checkout row 34", "base", 218, 5, 310.02],
  ["applies the checkoutSession fee path for a digital checkout row 35", "fee", 43, 10, 73.92, 5],
  ["clamps checkoutSession for a guest checkout row 36", "clamp", 166, 161, 165, 165],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(checkoutSession(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(checkoutSessionWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCheckoutSession(a, b, extra)).toBe(expected);
    }
  });
}
