// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 125;

function checkoutAudit(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function checkoutAuditWithFee(amount, factor, fee) {
  return checkoutAudit(amount, factor) + fee;
}

function clampCheckoutAudit(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  checkoutAudit,
  checkoutAuditWithFee,
  clampCheckoutAudit,
  factorFromBps,
};
