// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  checkoutAudit,
  checkoutAuditWithFee,
  clampCheckoutAudit,
  factorFromBps,
} = require("./checkoutAudit");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes checkoutAudit for a member checkout row 1", "base", 9, 6, 15.79],
  ["applies the checkoutAudit fee path for a express checkout row 2", "fee", 70, 12, 101.9, 2],
  ["clamps checkoutAudit for a digital checkout row 3", "clamp", 189.33, 189, 189.33, 193],
  ["computes checkoutAudit for a guest checkout row 4", "base", 192, 24, 290.08],
  ["applies the checkoutAudit fee path for a hold checkout row 5", "fee", 229, 11, 326.44, 11],
  ["clamps checkoutAudit for a pickup checkout row 6", "clamp", 73, 73, 73, 77],
  ["computes checkoutAudit for a retail checkout row 7", "base", 111, 23, 168.28],
  ["applies the checkoutAudit fee path for a split checkout row 8", "fee", 172, 4, 239.88, 14],
  ["clamps checkoutAudit for a member checkout row 9", "clamp", 28.93, 24, 28, 28],
  ["computes checkoutAudit for a express checkout row 10", "base", 78, 10, 109.3],
  ["applies the checkoutAudit fee path for a pickup checkout row 11", "fee", 178, 20, 267.1, 5],
  ["clamps checkoutAudit for a hold checkout row 12", "clamp", 164.63, 165, 165, 169],
  ["computes checkoutAudit for a split checkout row 13", "base", 60, 7, 83.2],
  ["applies the checkoutAudit fee path for a retail checkout row 14", "fee", 239, 1, 311.14, 6],
  ["clamps checkoutAudit for a express checkout row 15", "clamp", 267.08, 264, 267.08, 268],
  ["computes checkoutAudit for a member checkout row 16", "base", 121, 13, 170.98],
  ["applies the checkoutAudit fee path for a guest checkout row 17", "fee", 64, 6, 98.84, 11],
  ["clamps checkoutAudit for a digital checkout row 18", "clamp", 310.75, 306, 310, 310],
  ["computes checkoutAudit for a pickup checkout row 19", "base", 186, 18, 269.98],
  ["applies the checkoutAudit fee path for a hold checkout row 20", "fee", 125, 12, 187.25, 12],
  ["clamps checkoutAudit for a member checkout row 21", "clamp", 281.93, 282, 282, 286],
  ["computes checkoutAudit for a express checkout row 22", "base", 38, 10, 55.3],
  ["applies the checkoutAudit fee path for a digital checkout row 23", "fee", 99, 16, 144.59, 1],
  ["clamps checkoutAudit for a guest checkout row 24", "clamp", 236.2, 237, 237, 241],
  ["computes checkoutAudit for a hold checkout row 25", "base", 213, 5, 280.9],
  ["applies the checkoutAudit fee path for a pickup checkout row 26", "fee", 34, 11, 61.24, 11],
  ["clamps checkoutAudit for a retail checkout row 27", "clamp", 139.9, 137, 139.9, 141],
  ["computes checkoutAudit for a split checkout row 28", "base", 156, 23, 234.88],
  ["applies the checkoutAudit fee path for a member checkout row 29", "fee", 225, 2, 296.75, 7],
  ["clamps checkoutAudit for a express checkout row 30", "clamp", 67.18, 63, 67, 67],
  ["computes checkoutAudit for a guest checkout row 31", "base", 128, 20, 189.6],
  ["applies the checkoutAudit fee path for a digital checkout row 32", "fee", 67, 14, 111.13, 14],
  ["clamps checkoutAudit for a express checkout row 33", "clamp", 333.18, 329, 333, 333],
  ["computes checkoutAudit for a member checkout row 34", "base", 185, 2, 238.95],
  ["applies the checkoutAudit fee path for a split checkout row 35", "fee", 124, 21, 196.04, 11],
  ["clamps checkoutAudit for a retail checkout row 36", "clamp", 95.2, 90, 94, 94],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(checkoutAudit(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(checkoutAuditWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampCheckoutAudit(a, b, extra)).toBe(expected);
    }
  });
}
