// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  giftMessage,
  giftMessageWithFee,
  clampGiftMessage,
  factorFromBps,
} = require("./giftMessage");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes giftMessage for a digital checkout row 1", "base", 195, 2, 246.75],
  ["applies the giftMessage fee path for a guest checkout row 2", "fee", 16, 8, 31.96, 8],
  ["clamps giftMessage for a member checkout row 3", "clamp", 102.74, 102, 102.74, 106],
  ["computes giftMessage for a express checkout row 4", "base", 134, 21, 195.96],
  ["applies the giftMessage fee path for a retail checkout row 5", "fee", 191, 3, 246.66, 3],
  ["clamps giftMessage for a split checkout row 6", "clamp", 15.84, 17, 17, 21],
  ["computes giftMessage for a hold checkout row 7", "base", 69, 16, 98.91],
  ["applies the giftMessage fee path for a pickup checkout row 8", "fee", 130, 22, 193.5, 2],
  ["clamps giftMessage for a digital checkout row 9", "clamp", 250.69, 251, 251, 255],
  ["computes giftMessage for a guest checkout row 10", "base", 24, 6, 33.96],
  ["applies the giftMessage fee path for a guest checkout row 11", "fee", 112, 9, 164.84, 14],
  ["clamps giftMessage for a digital checkout row 12", "clamp", 70.26, 65, 69, 69],
  ["computes giftMessage for a express checkout row 13", "base", 230, 22, 336.5],
  ["applies the giftMessage fee path for a member checkout row 14", "fee", 169, 16, 248.91, 11],
  ["clamps giftMessage for a split checkout row 15", "clamp", 143.64, 145, 145, 149],
  ["computes giftMessage for a retail checkout row 16", "base", 47, 4, 62.69],
  ["applies the giftMessage fee path for a pickup checkout row 17", "fee", 226, 23, 340.96, 8],
  ["clamps giftMessage for a hold checkout row 18", "clamp", 232, 232, 232, 236],
  ["computes giftMessage for a guest checkout row 19", "base", 120, 7, 159],
  ["applies the giftMessage fee path for a digital checkout row 20", "fee", 59, 1, 82.16, 6],
  ["clamps giftMessage for a digital checkout row 21", "clamp", 59.19, 58, 59.19, 62],
  ["computes giftMessage for a guest checkout row 22", "base", 104, 16, 147.56],
  ["applies the giftMessage fee path for a member checkout row 23", "fee", 161, 23, 241.06, 3],
  ["clamps giftMessage for a express checkout row 24", "clamp", 281.94, 283, 283, 287],
  ["computes giftMessage for a retail checkout row 25", "base", 23, 15, 34.74],
  ["applies the giftMessage fee path for a split checkout row 26", "fee", 100, 17, 145, 2],
  ["clamps giftMessage for a hold checkout row 27", "clamp", 177.66, 179, 179, 183],
  ["computes giftMessage for a pickup checkout row 28", "base", 202, 9, 269.64],
  ["applies the giftMessage fee path for a digital checkout row 29", "fee", 19, 16, 40.41, 11],
  ["clamps giftMessage for a guest checkout row 30", "clamp", 121, 117, 121, 121],
  ["computes giftMessage for a pickup checkout row 31", "base", 146, 13, 201.56],
  ["applies the giftMessage fee path for a hold checkout row 32", "fee", 85, 7, 115.5, 2],
  ["clamps giftMessage for a split checkout row 33", "clamp", 36.44, 35, 36.44, 39],
  ["computes giftMessage for a retail checkout row 34", "base", 207, 19, 296.94],
  ["applies the giftMessage fee path for a express checkout row 35", "fee", 150, 12, 212.5, 7],
  ["clamps giftMessage for a member checkout row 36", "clamp", 118.81, 116, 118.81, 120],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(giftMessage(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(giftMessageWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampGiftMessage(a, b, extra)).toBe(expected);
    }
  });
}
