// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 9;
const FACTOR_BASE = 118;

function guestCheckout(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function guestCheckoutWithFee(amount, factor, fee) {
  return guestCheckout(amount, factor) + fee;
}

function clampGuestCheckout(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  guestCheckout,
  guestCheckoutWithFee,
  clampGuestCheckout,
  factorFromBps,
};
