// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  guestCheckout,
  guestCheckoutWithFee,
  clampGuestCheckout,
  factorFromBps,
} = require("./guestCheckout");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes guestCheckout for a split checkout row 1", "base", 212, 4, 267.64],
  ["applies the guestCheckout fee path for a retail checkout row 2", "fee", 151, 23, 229.91, 8],
  ["clamps guestCheckout for a pickup checkout row 3", "clamp", 131.5, 129, 131.5, 133],
  ["computes guestCheckout for a hold checkout row 4", "base", 29, 11, 46.41],
  ["applies the guestCheckout fee path for a guest checkout row 5", "fee", 216, 3, 283.36, 13],
  ["clamps guestCheckout for a digital checkout row 6", "clamp", 223, 224, 224, 228],
  ["computes guestCheckout for a express checkout row 7", "base", 94, 16, 134.96],
  ["applies the guestCheckout fee path for a member checkout row 8", "fee", 33, 10, 61.24, 10],
  ["clamps guestCheckout for a split checkout row 9", "clamp", 264.96, 260, 264, 264],
  ["computes guestCheckout for a retail checkout row 10", "base", 143, 0, 177.74],
  ["applies the guestCheckout fee path for a hold checkout row 11", "fee", 53, 5, 74.19, 0],
  ["clamps guestCheckout for a pickup checkout row 12", "clamp", 159.06, 154, 158, 158],
  ["computes guestCheckout for a retail checkout row 13", "base", 175, 17, 245.25],
  ["applies the guestCheckout fee path for a split checkout row 14", "fee", 236, 23, 344.76, 3],
  ["clamps guestCheckout for a member checkout row 15", "clamp", 80.54, 77, 80.54, 81],
  ["computes guestCheckout for a express checkout row 16", "base", 118, 10, 160.04],
  ["applies the guestCheckout fee path for a digital checkout row 17", "fee", 179, 16, 254.86, 6],
  ["clamps guestCheckout for a guest checkout row 18", "clamp", 346, 343, 346, 347],
  ["computes guestCheckout for a hold checkout row 19", "base", 61, 3, 82.81],
  ["applies the guestCheckout fee path for a pickup checkout row 20", "fee", 122, 9, 172.94, 9],
  ["clamps guestCheckout for a express checkout row 21", "clamp", 66.26, 67, 67, 71],
  ["computes guestCheckout for a member checkout row 22", "base", 225, 7, 290.25],
  ["applies the guestCheckout fee path for a guest checkout row 23", "fee", 168, 0, 217.24, 10],
  ["clamps guestCheckout for a digital checkout row 24", "clamp", 154.59, 154, 154.59, 158],
  ["computes guestCheckout for a pickup checkout row 25", "base", 42, 14, 64.44],
  ["applies the guestCheckout fee path for a hold checkout row 26", "fee", 221, 8, 290.46, 3],
  ["clamps guestCheckout for a split checkout row 27", "clamp", 204.16, 202, 204.16, 206],
  ["computes guestCheckout for a retail checkout row 28", "base", 103, 20, 151.14],
  ["applies the guestCheckout fee path for a express checkout row 29", "fee", 38, 15, 59.54, 0],
  ["clamps guestCheckout for a member checkout row 30", "clamp", 284.59, 283, 284.59, 287],
  ["computes guestCheckout for a retail checkout row 31", "base", 135, 22, 198],
  ["applies the guestCheckout fee path for a split checkout row 32", "fee", 196, 3, 254.16, 8],
  ["clamps guestCheckout for a hold checkout row 33", "clamp", 24.64, 24, 24.64, 28],
  ["computes guestCheckout for a pickup checkout row 34", "base", 74, 16, 108.16],
  ["applies the guestCheckout fee path for a digital checkout row 35", "fee", 139, 21, 213.21, 11],
  ["clamps guestCheckout for a guest checkout row 36", "clamp", 248, 247, 248, 251],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(guestCheckout(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(guestCheckoutWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampGuestCheckout(a, b, extra)).toBe(expected);
    }
  });
}
