// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 1;
const FACTOR_BASE = 123;

function orderNotes(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function orderNotesWithFee(amount, factor, fee) {
  return orderNotes(amount, factor) + fee;
}

function clampOrderNotes(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  orderNotes,
  orderNotesWithFee,
  clampOrderNotes,
  factorFromBps,
};
