// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 4;
const FACTOR_BASE = 129;

function orderChannel(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function orderChannelWithFee(amount, factor, fee) {
  return orderChannel(amount, factor) + fee;
}

function clampOrderChannel(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  orderChannel,
  orderChannelWithFee,
  clampOrderChannel,
  factorFromBps,
};
