// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 6;
const FACTOR_BASE = 118;

function pickupWindow(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function pickupWindowWithFee(amount, factor, fee) {
  return pickupWindow(amount, factor) + fee;
}

function clampPickupWindow(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  pickupWindow,
  pickupWindowWithFee,
  clampPickupWindow,
  factorFromBps,
};
