// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const {
  placeOrder,
  placeOrderWithFee,
  clampPlaceOrder,
  factorFromBps,
} = require("./placeOrder");
const { delay } = require("../testSupport/delay");

const cases = [
  ["computes placeOrder for a digital checkout row 1", "base", 51, 13, 71.28],
  ["applies the placeOrder fee path for a guest checkout row 2", "fee", 112, 19, 170.08, 14],
  ["clamps placeOrder for a member checkout row 3", "clamp", 202.04, 200, 202.04, 204],
  ["computes placeOrder for a express checkout row 4", "base", 230, 7, 286.6],
  ["applies the placeOrder fee path for a retail checkout row 5", "fee", 47, 14, 75.63, 9],
  ["clamps placeOrder for a split checkout row 6", "clamp", 149.8, 150, 150, 154],
  ["computes placeOrder for a hold checkout row 7", "base", 165, 2, 199.05],
  ["applies the placeOrder fee path for a pickup checkout row 8", "fee", 226, 8, 291.98, 8],
  ["clamps placeOrder for a digital checkout row 9", "clamp", 79.34, 78, 79.34, 82],
  ["computes placeOrder for a guest checkout row 10", "base", 120, 17, 164.4],
  ["applies the placeOrder fee path for a guest checkout row 11", "fee", 64, 21, 104.04, 11],
  ["clamps placeOrder for a digital checkout row 12", "clamp", 318.9, 320, 320, 324],
  ["computes placeOrder for a express checkout row 13", "base", 182, 9, 231.68],
  ["applies the placeOrder fee path for a member checkout row 14", "fee", 121, 3, 156.78, 8],
  ["clamps placeOrder for a split checkout row 15", "clamp", 86.2, 86, 86.2, 90],
  ["computes placeOrder for a retail checkout row 16", "base", 239, 16, 319.09],
  ["applies the placeOrder fee path for a pickup checkout row 17", "fee", 178, 10, 233.5, 5],
  ["clamps placeOrder for a hold checkout row 18", "clamp", 144.23, 143, 144.23, 147],
  ["computes placeOrder for a guest checkout row 19", "base", 72, 19, 102.48],
  ["applies the placeOrder fee path for a digital checkout row 20", "fee", 11, 13, 23.08, 3],
  ["clamps placeOrder for a digital checkout row 21", "clamp", 263.04, 258, 262, 262],
  ["computes placeOrder for a guest checkout row 22", "base", 40, 7, 54.8],
  ["applies the placeOrder fee path for a member checkout row 23", "fee", 97, 14, 145.13, 14],
  ["clamps placeOrder for a express checkout row 24", "clamp", 220.3, 217, 220.3, 221],
  ["computes placeOrder for a retail checkout row 25", "base", 215, 2, 257.55],
  ["applies the placeOrder fee path for a split checkout row 26", "fee", 36, 8, 63.28, 13],
  ["clamps placeOrder for a hold checkout row 27", "clamp", 124.9, 125, 125, 129],
  ["computes placeOrder for a pickup checkout row 28", "base", 154, 21, 215.44],
  ["applies the placeOrder fee path for a digital checkout row 29", "fee", 211, 3, 262.98, 8],
  ["clamps placeOrder for a guest checkout row 30", "clamp", 48.68, 44, 48, 48],
  ["computes placeOrder for a pickup checkout row 31", "base", 242, 14, 318.18],
  ["applies the placeOrder fee path for a hold checkout row 32", "fee", 181, 8, 236.63, 8],
  ["clamps placeOrder for a split checkout row 33", "clamp", 150.84, 148, 150.84, 152],
  ["computes placeOrder for a retail checkout row 34", "base", 63, 20, 91.05],
  ["applies the placeOrder fee path for a express checkout row 35", "fee", 246, 13, 333.88, 13],
  ["clamps placeOrder for a member checkout row 36", "clamp", 234.7, 230, 234, 234],
];

for (const [name, kind, a, b, expected, extra] of cases) {
  test(name, async () => {
    await delay();
    if (kind === "base") {
      expect(placeOrder(a, factorFromBps(b))).toBe(expected);
    } else if (kind === "fee") {
      expect(placeOrderWithFee(a, factorFromBps(b), extra)).toBe(expected);
    } else {
      expect(clampPlaceOrder(a, b, extra)).toBe(expected);
    }
  });
}
