// Generated by demo/generate.mjs — do not edit by hand.
"use strict";

const UNIT = 5;
const FACTOR_BASE = 112;

function splitShipment(amount, factor) {
  return Math.round((amount * factor + UNIT) * 100) / 100;
}

function splitShipmentWithFee(amount, factor, fee) {
  return splitShipment(amount, factor) + fee;
}

function clampSplitShipment(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function factorFromBps(bps) {
  return (FACTOR_BASE + bps) / 100;
}

module.exports = {
  UNIT,
  FACTOR_BASE,
  splitShipment,
  splitShipmentWithFee,
  clampSplitShipment,
  factorFromBps,
};
